#!/usr/bin/env python3
"""Grace — registration of the substrate lane's FLOOR row (K1879 §4) on Cal §905's word, with his five amendments WRITTEN INTO the text.
STAGED at Casey's EOD 2026-09-07 10:1x; to run at the next session's first minute after Keeper/Cal glance at the amended paragraph below.
Usage: python3 .grace_register_T2624_substrate_floor_on_cal_word.py --cal-word "§905, 10:13"   (claims T2624 by check-and-set if the counter reads 2624)
Edges from = INPUT -> to = CONSEQUENCE: T2623 (no kinematics) -> T2624; T1136 (the tick, the one live timing sentence) -> T2624. Domain substrate_lane.
"""
import json, sys, os, subprocess, datetime
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here); a = sys.argv[1:]
if '--cal-word' not in a: print('REFUSED: --cal-word required'); sys.exit(1)
calword = a[a.index('--cal-word') + 1]
today = datetime.date.today().isoformat(); stamp = subprocess.run(['date', '+%H:%M'], capture_output=True, text=True).stdout.strip()
cnt = open(os.path.join(here, '.next_theorem')).read().strip()
if cnt != '2624': print('REFUSED: counter reads', cnt, '— claim by hand and edit tid'); sys.exit(1)
tid, tid_s = 2624, 'T2624'
open(os.path.join(here, '.next_theorem'), 'w').write('2625\n')
open(os.path.join(here, '.claims', 'theorem_T2624_Grace.claim'), 'w').write(f'Claimed by: Grace\nDate: {today}\nT_ids: T2624\nStatus: claimed — the substrate lane\'s FLOOR (K1879 §4; Cal §905 amended text)\n')
name = 'FLOOR of the substrate lane (record-space dictionary of D_IV^5, K1860 A–P): a REPRESENTATION of the bound electron\'s winding count and angular content — theorems of Hua/Stein–Weiss/Faraut–Korányi sorted by tier — with NO KINEMATICS (T2623), NO ENERGY BUDGET (K-equivariance of the Szegő projection), and no energy, momentum or count sentence; its one candidate laboratory sentence is TIMING (an N-photon absolute offset in ticks a₀/c), not yet measured'
plain = ('The record-space picture reproduces, exactly, how a bound electron\'s winding and angular numbers branch when it "writes" — those are theorems about the geometry. But it cannot move energy: the projection that does the "push" commutes with every symmetric Hamiltonian, so it changes the size of a state, never its energy; the only energy reading that is not a definition fails against Millikan\'s photoelectric data by a factor of sixty to a hundred; and its counts, restricted to the physical sphere, are ordinary quantum-mechanical dipole weights. What is left that could still fail is one thing: a time offset of about 0.18 attoseconds per photon, below what has been measured.')
# Keeper's §4 paragraph, amended per Cal §905 (1)–(5); the refusal list carried; tier sorted.
registry = (f'| T2624 | THE SUBSTRATE LANE\'S FLOOR — a boundary theorem (K1879 §4, register on Cal §905\'s word with his five amendments in the text; registered {stamp} {today}). '
            '"The record-space dictionary of D_IV⁵ (K1860 A–P) is a REPRESENTATION of the bound electron\'s winding count and angular content. THEOREMS (DERIVED, of Hua / Stein–Weiss / Faraut–Korányi): the Hua branching k/(2k+3) (exact; d-generic k/(2k+d−2)); the frame theorem (a distinct orthonormal triple is harmonic); the exact push costs — 25/63 at the matter word on the Lie ball, the closed family c(1,1)(n) = n(n+5)/(2(n+2)(n+4)) (Elie 5724, blind; Cal §904), the disc limit 1/(m+2) word by word. THEOREM GIVEN THE WORD LENGTH: the three-write word 3/7 = 3/(d+2). DERIVED GIVEN THE DICTIONARY (K1860-J/P), not a theorem of the geometry — an identification\'s consequence: single occupancy (rank 2 = one Jones vector ⟹ one photon = one word = 3). '
            'NO KINEMATICS (T2623: push ≠ recoil; cap ½ vs 0.72). NO ENERGY BUDGET: the Bergman → Hardy (Szegő) projection is K-EQUIVARIANT — it preserves the Hua K-types — so every Hamiltonian acting by scalars on K-types commutes with it, and the push moves norm, never energy; the only energy variable compatible with Einstein\'s law is the circle-quantum count, which is Planck\'s relation as a definition; the only non-empty energy reading is refuted at 60–100× Millikan\'s precision. THE COUNT ROUTE CLOSES WITH THE ENERGY ROUTE: restricted to the physical exterior S² (the top-component map, Cal §898) the branching is d = 3\'s l/(2l+1), (l+1)/(2l+1) — quantum mechanics\' dipole weights verbatim (instrumented §899) — so the dictionary\'s counts are a representation of QM as well, with no laboratory referent for the d = 5 numbers. '
            'REFUSAL LIST (carried in the row): 1/5 is the disc\'s number at one word; 3/7 is BOTH the d = 5 three-write probability and the d = 3, l = 3 dipole weight (two objects); n(n+5) at n = 5 is not T1452\'s k(k+5); ½ for the constant is dimension-blind; 25/63 is n = 5\'s, not a BST fraction; none of these is N_c/g or C₂-anything. '
            'It therefore produces NO ENERGY, MOMENTUM OR COUNT SENTENCE; its ONE candidate laboratory sentence is TIMING — an N-photon absolute offset in units of the tick a₀/c = 0.1765 as (T1136, K1877) — NOT YET MEASURED at the needed ≲ 0.05 as (Ossiander\'s absolute precision 0.97 as = 5.5 ticks), hash owed by Lyra. Its physical content is the identifications it was built on (electron = interior torus; photon = frame + Jones vector; shell unit = Rydberg; tick = a₀/c)." '
            'What Casey\'s "the kinematics are the motion of the electron; the push is the transfer of energy to the boundary" meets on the space as built: to carry energy the dynamics must break K-invariance — the photon\'s direction v is the only non-invariant object in the dictionary, and a Hamiltonian that couples to it is a FIELD EQUATION on D_IV⁵, not a dictionary (the Vol 1 QFT program\'s object). Witnesses: T2623 (Cs-137), Millikan 1916 (Elie R130 pins). Inputs: T2623; T1136. | NEGATIVE (a floor with two data witnesses); the theorems inside it DERIVED; the dictionary IDENTIFIED; Cal ' + calword + ' | graph-node (substrate lane) | 5719–5724 | ' + today + ' |')
reg = os.path.join(root, 'notes', 'BST_AC_Theorem_Registry.md'); gd_p = os.path.join(here, 'ac_graph_data.json'); gt_p = os.path.join(here, 'ac_theorem_graph.json')
gd = json.load(open(gd_p, encoding='utf-8')); gt = json.load(open(gt_p, encoding='utf-8')); ids = {t['tid'] for t in gd['theorems']}
lines = open(reg, encoding='utf-8').read().split('\n'); anchor = max(i for i, l in enumerate(lines) if l.startswith('| T2623 |')); lines.insert(anchor + 1, registry); open(reg, 'w', encoding='utf-8').write('\n'.join(lines))
rec = dict(tid=tid, name=name, domain='substrate_lane', status=f'NEGATIVE floor (two data witnesses: T2623, Millikan); theorems inside DERIVED; dictionary IDENTIFIED; Cal {calword}; K1879 §4 with §905\'s five amendments', depth=0, conflation=0, section='K1879 §4 / Cal §905 (Round 130)', toys=[5719, 5720, 5721, 5722, 5723, 5724], date=today, plain=plain)
gd['theorems'].append(rec); gd['nodes'].append(dict(rec))
for fr, lab in ((2623, 'no kinematics: the first negative'), (1136, 'the tick a₀/c — the one candidate timing sentence, not yet measured')):
    assert fr in ids; gd['edges'].append({'from': fr, 'to': tid, 'source': 'negative', 'label': lab}); gt['edges'].append({'source': f'T{fr}', 'target': tid_s, 'type': 'uses'})
color = next((n.get('color') for n in gt['nodes'] if n.get('domain') == 'substrate_lane'), '#B05A5A')
for t_id in (1136,):
    if not any(n['id'] == f'T{t_id}' for n in gt['nodes']):
        t = [x for x in gd['theorems'] if x['tid'] == t_id][0]; gt['nodes'].append(dict(id=f'T{t_id}', name=t['name'], domain=t['domain'], domain_label=t['domain'], status=str(t['status']).split(' ')[0].lower(), plain=t.get('plain', ''), color=color, proofs=[]))
gt['nodes'].append(dict(id=tid_s, name=name, domain='substrate_lane', domain_label='Substrate lane (record space)', status='negative', plain=plain, color=color, proofs=['K-equivariance of the Szegő projection', 'Millikan 1916 (60–100×)', 'top-component map = dipole weights (Cal §898/§899)']))
gd['metadata'].update(node_count=len(gd['nodes']), edge_count=len(gd['edges']), theorem_count=len(gd['theorems']), synced=f'{today} both lists (Grace R130)'); gd['meta']['max_tid'] = f'T{tid}'; gd['meta']['last_updated'] = today
json.dump(gd, open(gd_p, 'w', encoding='utf-8'), indent=1, ensure_ascii=False); json.dump(gt, open(gt_p, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
open(os.path.join(here, 'THEOREM_LOG.md'), 'a').write(f"| T2624 | Substrate lane FLOOR: representation of winding count + angular content; no kinematics; no energy budget; timing the one live sentence | D0 | K1879 §4; Cal {calword} | 5719–5724 | Grace | {today} | negative (floor) |\n")
ids2 = {t['tid'] for t in gd['theorems']}; gids = {n['id'] for n in gt['nodes']}
print('registered T2624 |', len(gd['theorems']), len(gd['nodes']), len(gd['edges']), '|', len(gt['nodes']), len(gt['edges']))
print('dangling data:', [e for e in gd['edges'] if e['from'] not in ids2 or e['to'] not in ids2], '| curated:', [e for e in gt['edges'] if e['source'] not in gids or e['target'] not in gids])
