#!/usr/bin/env python3
"""SUPERSEDED IN PART 10:27 2026-09-09: the CAL variable's clause "the 5 ... is the DIMENSION" was overturned by Cal §930 (Elie 5743). The registry row was repaired in place; DO NOT RE-RUN this script — it would reintroduce the superseded clause. Kept as the record of what was registered 2026-09-08.

Grace — Round 135 G1 (third): THE CLOCK ROW, T2629 — Lyra R134 L1 (j-blind chain theorem) + L2 (closed-form push cost) + Elie 5736 E3
(blindness to twenty digits) + Cal §923's row sentence with K1883 §4's wording fix ("a Born posit at the PUSH", not "at the write").
Usage: python3 .grace_register_T2629_clock_row_on_cal_923.py --cal-word "§923 (10:39); K1883 §4 wording"    Refuses unless T2627 and T2628 are registered (Cal §922 order).
Edges: T2628 -> T2629 (the survivor is j; this row says what reads it: nothing in the law); T2624 -> T2629 (the push cost is the floor's norm); T2629 -> T1292 ("same write statistics every cycle" DERIVED); T2629 -> T633 (shape only, no map — L3).
"""
import json, sys, os, glob, subprocess, datetime
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here); a = sys.argv[1:]
if '--cal-word' not in a: print('REFUSED: --cal-word required (Cal §923)'); sys.exit(1)
cw = a[a.index('--cal-word') + 1]
if not glob.glob(os.path.join(here, '.claims', 'theorem_T2629_*')): print('REFUSED: no claim file'); sys.exit(1)
today = datetime.date.today().isoformat(); ts = subprocess.run(['date', '+%H:%M'], capture_output=True, text=True).stdout.strip(); tid, tid_s = 2629, 'T2629'
F = sorted(glob.glob(os.path.join(root, 'notes', 'Lyra_R134_L1_j_blind_chain*.md')))[-1]; T = open(F, encoding='utf-8').read().split('\n')
i1 = next(i for i, l in enumerate(T) if l.startswith('## L1')); L1 = ' '.join(l.strip() for l in T[i1 + 1:i1 + 4] if l.strip()).replace('|', '∣')
i2 = next(i for i, l in enumerate(T) if l.startswith('## L2')); L2 = ' '.join(l.strip() for l in T[i2 + 1:i2 + 4] if l.strip()).replace('|', '∣')
E3 = 'BLINDNESS CONTROL (Elie 5736 E3, prereg 55526212; cannot fail, reported as such): at j₀ = 0 and j₀ = 2329, H(Δj) = 4.0161235238880345931 bits both; P(three-write word = (1,1)) = 0.42857142857142857143 both = 3/7 to twenty digits; no transition probability contains j. Five successive m-cap cycles: Σc = 14.81, 3.71, 2.25, 1.62, 1.27, drifts −11.10, −1.46, −0.63, −0.35 (asymptote 0 from above, never reached); the m-cap asymptotic (5/2)·N/j₀ within 2 % at j₀ = 2329; under a k-cap the estimate must use the RUNNING j, not j₀ (Cal §923 wording point). REFUSED SHARED NUMBER: Σc(cycle 2)/Σc(cycle 1) = 0.2505 ≈ ¼ = 1/2^rank — a coincidence of the m-cap\'s 137 writes and E[j] = 58; it moves with the cap; not in this row as a value (Elie, Cal §923).'
CAL = 'CAL §923 (C1 closed as hashed: RELABELING): "a j-dependent norm deficit exists (L2) and no transition in the dictionary depends on it (5736 E3, twenty digits); a payer for the deficit would be a Born posit at the PUSH and would collide with K1860-G" — wording per K1883 §4: the WRITE is isometric (K1860-P) and the PUSH is the projection (K1860-M, K1877), so a Born reading at the push does not touch the write\'s isometry; whether such a reading is the program\'s own Born rule applied (T754, T2401) or a new posit is Round 135\'s question and this row does not pre-decide it. Row text carries (Cal §922): c is a NORM DEFICIT (Bergman → Hardy) with no payer named; the 5 in 5/(2(j+5)) is the DIMENSION — n/(2(j+n)) for D_IV^n, equal to n_C by definition, not by signature; the winding asymptotic 5/(2j) is k-blind; the large-k line 5/(4j+14) is not zero (angular content alone never makes a push free). Keeper\'s Monte Carlo (K1883-PRE) is the positive CONTROL for the exact form; the row cites the exact form, not the control. L3 (Lyra): NO MAP to T633 — three independent reasons; shape only; T633\'s value untouched.'
name = 'THE CLOCK ROW (Round 134, Lyra L1+L2 df543d9c, Elie 5735/5736, Cal §921–§923): the chain law is j-BLIND — write branching depends on the angular degree alone, so write statistics, the three-write word 3/7, the saturation degree and the entropy increment are cycle-invariant (DERIVED) — while the push cost c(j,k) = (5/2)[(k+3)/((2k+3)(j+k+5)) + 2k/((2k+3)(2j+7))] is NOT: it falls with the carried winding at every degree, 5/(2(j+5)) at k = 0, → 5/(2j); a j-dependent norm deficit exists and no transition in the dictionary depends on it; the universe remembers its clock and nothing consults it'
plain = ('Each new universe inherits a count of how many times the old clock wound. Nothing that the universe DOES depends on that count: every write branches the same way, the same words appear with the same odds, to twenty decimal places. What does change is a bookkeeping price: the fraction of a state\'s weight that a commitment has to supply falls like five over twice the count, so on paper commitments get cheaper every cycle and never free. Nothing in the rules pays that price. Whether something physical does is the next question, not this row.')
row = ('| T2629 | THE CLOCK ROW — the j-blind chain theorem and the closed-form push cost (registered ' + ts + ' ' + today + ' on Cal ' + cw + '; third in Cal §922\'s order after T2627, T2628). L1 (Lyra, hashed df543d9c): ' + L1 + ' L2 (Lyra; Elie 5735 E1 the same rational function by Schur + Stein–Weiss, term by term, same minute; 5735 P2: eight unseen Gram cells exact — CLEARED as a theorem, Cal §922): ' + L2 + ' ' + E3 + ' ' + CAL
       + ' Inputs: T2628 (the survivor is j), T2624 (the push is a norm). Consequences: T1292\'s "same write statistics every cycle" DERIVED (record space only; no spacetime observable — T2623, K1879); T633 shape only, no map (L3). | L1, L2 DERIVED (Faraut–Korányi norms + Stein–Weiss; no BST input beyond the domain); E3 MEASURED; the payer sentence a RELABELING (Cal C1), the Born-at-the-push question OPEN (Round 135) | graph-node (substrate lane) | 5735, 5736 | ' + today + ' |')
reg = os.path.join(root, 'notes', 'BST_AC_Theorem_Registry.md'); gd_p = os.path.join(here, 'ac_graph_data.json'); gt_p = os.path.join(here, 'ac_theorem_graph.json')
gd = json.load(open(gd_p, encoding='utf-8')); gt = json.load(open(gt_p, encoding='utf-8')); ids = {t['tid'] for t in gd['theorems']}
if tid in ids: print('already registered'); sys.exit(0)
if not (2627 in ids and 2628 in ids): print('REFUSED: T2627/T2628 must be registered first (Cal §922 order)'); sys.exit(1)
L = open(reg, encoding='utf-8').read().split('\n'); anchor = max(i for i, l in enumerate(L) if l.startswith('| T2628 |')); L.insert(anchor + 1, row); open(reg, 'w', encoding='utf-8').write('\n'.join(L))
rec = dict(tid=tid, name=name, domain='substrate_lane', status='L1/L2 DERIVED (two routes + exact Gram); E3 MEASURED (twenty digits); payer sentence RELABELING (Cal C1 §923); Born-at-the-push OPEN (R135); Cal ' + cw, depth=1, conflation=0, section='Lyra R134 L1–L3; Elie 5735/5736; Cal §921–§923; K1883', toys=[5735, 5736], date=today, plain=plain)
gd['theorems'].append(rec); gd['nodes'].append(dict(rec)); color = next((n.get('color') for n in gt['nodes'] if n.get('domain') == 'substrate_lane'), '#B05A5A')
gt['nodes'].append(dict(id=tid_s, name=name, domain='substrate_lane', domain_label='Substrate lane (record space)', status='derived', plain=plain, color=color, proofs=['(z·z)^j unimodular on Š ⇒ branching in k only (Stein–Weiss)', 'Pochhammer telescoping (Lyra) = Schur + Stein–Weiss (Elie), term by term', 'eight unseen Gram cells exact (5735 P2)', 'blindness to twenty digits (5736 E3)']))
for fr, to, lab in ((2628, tid, 'the survivor is j; nothing in the law reads it'), (2624, tid, 'the push cost is the floor\'s norm deficit'), (tid, 1292, '"same write statistics every cycle" DERIVED on record space'), (tid, 633, 'shape only; no map (Lyra L3, three reasons)')):
    gd['edges'].append({'from': fr, 'to': to, 'source': 'derived', 'label': lab}); gt['edges'].append({'source': f'T{fr}', 'target': f'T{to}', 'type': 'uses'})
    for t_id in (fr, to):
        if not any(n['id'] == f'T{t_id}' for n in gt['nodes']):
            t = [x for x in gd['theorems'] if x['tid'] == t_id][0]; gt['nodes'].append(dict(id=f'T{t_id}', name=t['name'], domain=t['domain'], domain_label=t['domain'], status=str(t['status']).split(' ')[0].lower(), plain=t.get('plain', '') or '', color=color, proofs=[]))
ids.add(tid); gd['metadata'].update(node_count=len(gd['nodes']), edge_count=len(gd['edges']), theorem_count=len(gd['theorems']), synced=f'{today} both lists (Grace R135 G1)'); gd['meta']['max_tid'] = f'T{max(ids)}'; gd['meta']['last_updated'] = today
json.dump(gd, open(gd_p, 'w', encoding='utf-8'), indent=1, ensure_ascii=False); json.dump(gt, open(gt_p, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
open(os.path.join(here, 'THEOREM_LOG.md'), 'a').write(f"| T2629 | The clock row: j-blind chain theorem + closed-form push cost c(j,k); blindness to twenty digits; payer = Born posit at the PUSH (open) | D1 | Lyra R134 L1/L2; Elie 5735/5736; Cal {cw} | 5735,5736 | Lyra+Elie (text) / Grace (registered) | {today} | derived |\n")
for cf in glob.glob(os.path.join(here, '.claims', 'theorem_T2629_*')): open(cf, 'a').write(f'Registered: {today} {ts} on Cal\'s word ({cw})\n')
ids2 = {t['tid'] for t in gd['theorems']}; gids = {n['id'] for n in gt['nodes']}
print('registered T2629 |', len(gd['theorems']), len(gd['edges']), '|', len(gt['nodes']), len(gt['edges']), '| dangling:', [e for e in gd['edges'] if e['from'] not in ids2 or e['to'] not in ids2], [e for e in gt['edges'] if e['source'] not in gids or e['target'] not in gids])
