#!/usr/bin/env python3
"""Grace — Round 139 G2: register the BORN-RESOLUTION ROW as T2630 on Cal §935 C2's word, carrying his ruling and not the triumphant reading.
Usage: python3 .grace_register_T2630_born_resolution_on_cal_935.py --cal-word "§935 C2 (11:24)"
Edges INPUT -> CONSEQUENCE: T2630 -> T2629 (the push cost IS this row's isometry defect at the Bergman weight); T2630 -> T2624 (the floor's push sentences).
"""
import json, sys, os, glob, subprocess, datetime
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here); a = sys.argv[1:]
if '--cal-word' not in a: print('REFUSED: --cal-word required (Cal §935 C2)'); sys.exit(1)
cw = a[a.index('--cal-word') + 1]
if not glob.glob(os.path.join(here, '.claims', 'theorem_T2630_*')): print('REFUSED: no claim file'); sys.exit(1)
today = datetime.date.today().isoformat(); ts = subprocess.run(['date', '+%H:%M'], capture_output=True, text=True).stdout.strip(); tid, tid_s = 2630, 'T2630'
name = ('THE BORN-RESOLUTION ROW: on the Shilov boundary the five write operators sum to the identity (Σ_u M_{|z_u|²} = I on H²(Š)), so the write tuple is a row isometry and its outcome probabilities ARE the Hua branching (k+3)/(2k+3) and k/(2k+3); the three-write word 3/7 is one of those probabilities; and at the Bergman weight the same sum fails to be 1 by exactly the push cost c(j,k), so the cost is the tuple\'s ISOMETRY DEFECT and never was a price — a NAMING, not a derivation (Cal §935 C2)')
plain = ('On the boundary of the domain the five coordinate directions a word can be written in have squared lengths that add to one. So writing is already a measurement: the chances of its outcomes are the branching numbers this project has used since April, including the three-sevenths that shows up in the signature. Nothing had to be chosen or identified to get them. Inside the domain the same five numbers fall short of one, and the shortfall is exactly the "push cost" of the last four rounds — which means that cost was never a price paid by anything. It was the writes failing to be a measurement anywhere except on the boundary.')
row = ('| T2630 | THE BORN-RESOLUTION ROW (Lyra R138 L1 + Elie 5747, 5/5 with 3/3 can-fail, prereg cfd0f5e4; registered ' + ts + ' ' + today + ' on Cal ' + cw + '). '
       '**THE IDENTITY.** On Š every point has |z|² = 1, so for the coordinate write operators W_u = M_{z_u} of an orthonormal frame, Σ_u W_u* W_u = Σ_u M_{|z_u|²} = I on H²(Š): **the write tuple is a row isometry.** Verified exactly (rational S⁴ moments, not machine precision) for k = 0..5 on zonal AND random integer harmonics; the winding factor drops out by unimodularity, so j never enters (Elie 5747 P1). '
       '**THE BRANCHING IS ITS BORN LAW.** Splitting each of the five outcomes by Hua component gives, for k = 0..5, light = 1, 4/5, 5/7, 2/3, 7/11, 8/13 and matter = 0, 1/5, 2/7, 1/3, 4/11, 5/13 — **exactly (k+3)/(2k+3) and k/(2k+3), summing to 1 at every k** — K1860-A\'s branching, arrived at with no table consulted, no effect chosen, no Jones identification, no imported observable (5747 P3). **THE SIGNATURE FRACTION IS ONE OF THESE PROBABILITIES:** chaining only these weights, P(word = (1,1) after three writes) = 1/5 + (4/5)(2/7) = **3/7 exactly** (5747 P5). Lyra verified the construction through degree five and named the load-bearing clause: **the normalisation that makes these probabilities is an identity that holds only at the boundary weight.** '
       '**AND IT CLOSES FOUR ROUNDS BACKWARDS.** At the Bergman weight the same sum FAILS to be 1, by exactly 1/2, 10/21, 25/63, 45/98, 7/22 at (0,0), (0,1), (1,1), (0,2), (2,3) — Elie\'s 5735 closed form entry for entry (5747 P4). **So c(j,k) is the DEFECT of the row isometry: Keeper\'s identity, Cal\'s Hardy-point objection, Elie\'s zero at ν_H and the closed form are one fact seen four ways, and the push cost was never a price.** '
       '**WHAT THIS IS, IN CAL\'S WORDS AND NOT THE TRIUMPHANT ONES (§935 C2, the condition of registration).** It is a **TAUTOLOGY OF THE BOUNDARY CONDITION in two independent senses.** (i) Š lies inside the unit sphere of ℂ⁵, so |z|² = 1 there as on any subset of that sphere: **Σ_u M_{|z_u|²} = I holds for the coordinate tuple of ANY orthonormal frame on ANY subset of the unit sphere, for every bounded symmetric domain whose Shilov boundary lies there. It is not a fact about D_IV⁵, about the dictionary, or about the writes, and IT CANNOT BE WRITTEN AS A SIGNATURE.** (ii) The branching weights were DEFINED as normalised squared norms (R134 L1; T2629\'s own proof), and that ratio is the Born formula, so "these are Born probabilities of the write tuple\'s POVM" restates how they were computed. '
       '**WHAT IT BUYS:** it removes the SEARCH for a commitment effect — if a write\'s outcome IS the measurement outcome there is no separate observable to identify, and Rounds 136–137\'s family problem (Keeper\'s three columns, Lyra\'s two-variable family, Σ_u W_u*W_u, 1 − T) **DISSOLVES rather than being solved.** **WHAT IT DOES NOT BUY: the Born rule.** T754/Gleason answers why probability must be quadratic in the state; this reading uses quadratic norms from the start, so **none of T754, T2401 or the K67 chain becomes redundant — they become unnecessary for THIS STEP, which is a different claim.** A dictionary that assumes the norm-square is a probability has not derived that it is. '
       '**HONEST FORM (Cal §935 C2, verbatim):** *the branching weights are the outcome probabilities of the write tuple\'s own resolution of the identity; this is a naming, not a derivation; what it eliminates is the commitment effect, which existed only because the push was treated as a separate event.* There was no free parameter in the branching to begin with. '
       '**THE WORD "COMMITMENT", AUDITED (§935 C2).** In K1860 it works by CONTRAST — it names the step that is not a write. Remove the contrast and it is a synonym for "write outcome". **Test carried into this row and every consumer: replace "commitment" with "write outcome" and see whether the sentence still says anything; where it does not, the word was carrying the distinction and not a fact.** '
       'Inputs: T2629 (whose cost this explains), T2624 (whose push sentences it corrects). | DERIVED as an identity (two-line, exact rationals, verified to degree five) but **TAUTOLOGICAL of the boundary condition and not a signature**; the branching\'s Born reading is a NAMING, not a derivation (Cal ' + cw + ') | graph-node (substrate lane) | 5747, 5735 | ' + today + ' |')
reg = os.path.join(root, 'notes', 'BST_AC_Theorem_Registry.md'); gd_p = os.path.join(here, 'ac_graph_data.json'); gt_p = os.path.join(here, 'ac_theorem_graph.json')
gd = json.load(open(gd_p, encoding='utf-8')); gt = json.load(open(gt_p, encoding='utf-8')); ids = {t['tid'] for t in gd['theorems']}
if tid in ids: print('already registered'); sys.exit(0)
L = open(reg, encoding='utf-8').read().split('\n'); anchor = max(i for i, l in enumerate(L) if l.startswith('| T2629 |')); L.insert(anchor + 1, row); open(reg, 'w', encoding='utf-8').write('\n'.join(L))
rec = dict(tid=tid, name=name, domain='substrate_lane', status='DERIVED as an identity (exact rationals, degree five) but TAUTOLOGICAL of the boundary condition — holds on any subset of the unit sphere for any orthonormal frame, so it cannot be written as a signature; the Born reading of the branching is a NAMING not a derivation; it does NOT supply the Born rule (T754/Gleason unaffected); Cal ' + cw, depth=1, conflation=0, section='Lyra R138 L1 / Elie 5747 / Cal §935 C2', toys=[5747, 5735], date=today, plain=plain)
gd['theorems'].append(rec); gd['nodes'].append(dict(rec)); color = next((n.get('color') for n in gt['nodes'] if n.get('domain') == 'substrate_lane'), '#B05A5A')
gt['nodes'].append(dict(id=tid_s, name=name, domain='substrate_lane', domain_label='Substrate lane (record space)', status='derived', plain=plain, color=color, proofs=['|z|² = 1 on Š ⟹ Σ_u M_{|z_u|²} = I (two lines)', 'exact rational S⁴ moments, k = 0..5, zonal and random (5747 P1/P3)', '3/7 = 1/5 + (4/5)(2/7) with no table (5747 P5)', 'Bergman-weight defect = c(j,k) entry for entry (5747 P4)']))
for fr, to, lab in ((tid, 2629, 'the push cost IS this row\'s isometry defect at the Bergman weight'), (tid, 2624, 'corrects the floor\'s push sentences: push and write are one event')):
    gd['edges'].append({'from': fr, 'to': to, 'source': 'derived', 'label': lab}); gt['edges'].append({'source': f'T{fr}', 'target': f'T{to}', 'type': 'uses'})
ids.add(tid); gd['metadata'].update(node_count=len(gd['nodes']), edge_count=len(gd['edges']), theorem_count=len(gd['theorems']), synced=f'{today} both lists (Grace R139 G2)'); gd['meta']['max_tid'] = f'T{max(ids)}'; gd['meta']['last_updated'] = today
json.dump(gd, open(gd_p, 'w', encoding='utf-8'), indent=1, ensure_ascii=False); json.dump(gt, open(gt_p, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
open(os.path.join(here, 'THEOREM_LOG.md'), 'a').write(f"| T2630 | Born-resolution: write tuple resolves the identity on Š; branching = its outcome probabilities; 3/7 is one; push cost = the isometry defect at the Bergman weight; a naming, not a derivation | D1 | Lyra R138 L1; Elie 5747; Cal {cw} | 5747,5735 | Lyra+Elie (text) / Grace (registered) | {today} | derived (tautological of the boundary condition) |\n")
for cf in glob.glob(os.path.join(here, '.claims', 'theorem_T2630_*')): open(cf, 'a').write(f'Registered: {today} {ts} on Cal\'s word ({cw})\n')
ids2 = {t['tid'] for t in gd['theorems']}; gids = {n['id'] for n in gt['nodes']}
print('registered T2630 |', len(gd['theorems']), len(gd['edges']), '| dangling:', [e for e in gd['edges'] if e['from'] not in ids2 or e['to'] not in ids2], [e for e in gt['edges'] if e['source'] not in gids or e['target'] not in gids])
