#!/usr/bin/env python3
"""bst_26_tier_generator.py — the register-to-presentation generator (Grace, Round 142 G2, 2026-09-11).

Reads data/bst_26_tier_map_v2.json (one row per SM parameter of the 26, keyed to the register as of
Cal Section 946) and EMITS the markdown tier table plus the counts the presentation layer quotes.
The state block's count must fall out of this file, never be typed.

Modes
  --control   POSITIVE CONTROL: parse Grace ledger v0.30's Section 2 table (the origin of the
              "Sourced-clean total: 8" that v0.31..v0.54 carried verbatim) and reproduce 8 from the
              FILE, not from memory; then map those 8 onto the 26 and print where each stands today.
              The generator refuses to emit until this control passes.
  --emit      write data/bst_26_tier_table_generated.md and print the counts + the state-block sentence.
  --sentence  print only the one-line count sentence (for play/sync_presentation_state.py to splice).
  --check     exit 1 if the state block's count sentence disagrees with the generated one.
"""
import json, os, re, sys, hashlib, datetime
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY = os.path.join(ROOT, 'data', 'bst_26_tier_map_v2.json')
OUT = os.path.join(ROOT, 'data', 'bst_26_tier_table_generated.md')
V030 = os.path.join(ROOT, 'notes', 'Grace_Master_Derived_vs_Assigned_Ledger_v0_30.md')
BLOCK = os.path.join(ROOT, 'notes', 'BST_PRESENTATION_STATE_BLOCK.md')
WORDS = ('derived', 'identified', 'floored', 'open', 'input')

def load():
    d = json.load(open(KEY, encoding='utf-8'))
    rows = d['rows']
    assert len(rows) == 26, 'denominator is 26 by construction; got %d' % len(rows)
    for r in rows:
        assert r['tier_word'] in WORDS, (r['id'], r['tier_word'])
    return d, rows

def control():
    """Parse v0.30 Section 2: numbered rows 1..8 are the sourced-clean banks; '— 9?' and '— 10?' are not."""
    t = open(V030, encoding='utf-8').read()
    sec = t.split('## Section 2')[1].split('## Section 3')[0]
    banks, nots = [], []
    for line in sec.splitlines():
        m = re.match(r'^\|\s*(—\s*)?(\d+)\??\s*\|\s*\*\*(.+?)\*\*', line)
        if not m:
            continue
        dash, num, name = m.group(1), int(m.group(2)), m.group(3)
        (nots if dash else banks).append((num, name))
    literal = re.search(r'\*\*Sourced-clean total: (\d+)\*\*', sec)
    n_file = int(literal.group(1)) if literal else None
    print('v0.30 Section 2 parsed: %d numbered bank rows, %d "— n?" rows; the file\'s own literal says %s'
          % (len(banks), len(nots), n_file))
    for num, name in banks:
        print('   bank %d: %s' % (num, name))
    ok = (len(banks) == 8 and n_file == 8)
    print('POSITIVE CONTROL: %s (parsed %d == literal %s == 8)' % ('PASS' if ok else 'FAIL', len(banks), n_file))
    return ok, banks

def map_v030(rows, banks):
    print('\nWhere v0.30\'s eight stand on the 26 today (key: v030_slot):')
    on, off = 0, 0
    for num, name in banks:
        hit = [r for r in rows if r.get('v030_slot') and r['v030_slot'].startswith('%d ' % num)]
        if hit:
            on += 1
            print('   v0.30 #%d %-28s -> row %2d %-16s %s' % (num, name[:28], hit[0]['n'], hit[0]['id'], hit[0]['tier_word'].upper()))
        else:
            off += 1
            print('   v0.30 #%d %-28s -> NOT A ROW OF THE 26 (cross-family ratio; see v030_rows_not_on_the_denominator)' % (num, name[:28]))
    print('   %d of the eight are rows of the 26; %d are not. "8 of 26" was a numerator and a denominator from two different lists.' % (on, off))

def counts(rows):
    c = {w: [r for r in rows if r['tier_word'] == w] for w in WORDS}
    dep = [r for r in c['derived'] if r.get('flag') == 'dependent row']
    return c, dep

def sentence(rows):
    c, dep = counts(rows)
    nd = len(c['derived']); ni = len(dep)
    nf = len([r for r in c['derived'] if r.get('flag') and 'sibling test' in r['flag']])
    nm = len([r for r in c['derived'] if str(r.get('four_word_standard', '')).startswith('meets')])
    return ('Of the 26 primary Standard-Model parameters: %d derived on the K962 ladder (%d independent, %d riding another row; '
            '%d of the %d meet the four-word standard on their own statement — mechanism proved and inputs named — and the rest await Cal/Keeper\'s re-read; '
            '%d carry the flag "K1809 sibling test not run"), '
            '%d identified, %d floored, %d open, %d input. Generated by play/bst_26_tier_generator.py from '
            'data/bst_26_tier_map_v2.json (keyed to the register as of Cal Section 946); the July count '
            '"8 of 26 sourced clean" (ledger v0.30, carried to v0.54) is retired — its numerator and denominator '
            'came from two different lists (positive control in the generator).'
            % (nd, nd - ni, ni, nm, nd, nf, len(c['identified']), len(c['floored']), len(c['open']), len(c['input'])))

def emit(d, rows):
    c, dep = counts(rows)
    keyhash = hashlib.sha256(open(KEY, 'rb').read()).hexdigest()[:16]
    L = []
    L.append('# BST 26 — tier table, GENERATED (do not edit; edit `data/bst_26_tier_map_v2.json` and re-run `python3 play/bst_26_tier_generator.py --emit`)')
    L.append('')
    L.append('*Generated %s by `play/bst_26_tier_generator.py` from `data/bst_26_tier_map_v2.json` (sha256 %s…), keyed to %s. Tier words are the four of `BST_VOICE_AND_STYLE_GUIDE.md` plus "input". A "flag" is a doubt the generator carries but does not adjudicate.*'
             % (datetime.date.today().isoformat(), keyhash, d['keyed_to']))
    L.append('')
    L.append('**' + sentence(rows) + '**')
    L.append('')
    L.append('| # | parameter | sector | form as registered | **tier** | four-word standard (derived rows only) | basis (rows / rulings) | last re-tier | flag |')
    L.append('|---|---|---|---|---|---|---|---|---|')
    for r in rows:
        L.append('| %d | %s | %s | %s | **%s** | %s | %s | %s | %s |' % (
            r['n'], r['id'], r['sector'], r['form'].replace('|', '\\|'), r['tier_word'], r.get('four_word_standard', '—').replace('|', '\\|'),
            ', '.join(r['rows']), r['last_retier'], (r.get('flag') or '')))
    L.append('')
    L.append('## Counts')
    for w in WORDS:
        L.append('- **%s**: %d — %s' % (w, len(c[w]), ', '.join(r['id'] for r in c[w]) or '—'))
    L.append('')
    L.append('## Why this is not "8 of 26"')
    L.append('The July count (ledger v0.30, 2026-07-02; carried verbatim through v0.54) certified eight banks: θ_QCD, α, m_μ/m_e, m_d/m_e, m_s/m_μ, m_b/m_τ, m_t, θ₁₃. Three of the eight (the K582 cross-family ratios) are not rows of the 26-parameter denominator at all; of the five that are, three are derived today (θ_QCD, m_t, θ₁₃) and two are identified (α after K1813/K1816/K1826; the muon after K1814). The honest count above replaces it. Run `--control` to see the eight parsed from the v0.30 file.')
    L.append('')
    L.append('## Not parameters, but rows of the 07-17 map that the presentation quotes')
    for s in d['not_parameters_but_in_the_0717_map']:
        L.append('- ' + s)
    L.append('')
    L.append('## v0.30 banks that are not rows of the 26')
    for s in d['v030_rows_not_on_the_denominator']:
        L.append('- %s — %s' % (s['v030_slot'], s['why']))
    L.append('')
    L.append('— generated; Grace owns the key file.')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('wrote', os.path.relpath(OUT, ROOT))
    print(sentence(rows))

def check(rows):
    s = sentence(rows)
    t = open(BLOCK, encoding='utf-8').read()
    head = s.split(' Generated by')[0]
    ok = head in t
    print('state block carries the generated count sentence:', 'YES' if ok else 'NO')
    return ok

if __name__ == '__main__':
    d, rows = load()
    args = sys.argv[1:]
    if '--sentence' in args:
        print(sentence(rows)); sys.exit(0)
    ok, banks = control()
    if not ok:
        print('control FAILED — refusing to emit'); sys.exit(2)
    if '--control' in args:
        map_v030(rows, banks); sys.exit(0)
    if '--emit' in args:
        map_v030(rows, banks); emit(d, rows); sys.exit(0)
    if '--check' in args:
        sys.exit(0 if check(rows) else 1)
    print(__doc__)
