#!/usr/bin/env python3
"""
fourcolor_code_structure.py

Coding-theory structure of the 7 residual flats (notes/FourColor_Code_Structure.md),
the structure Casey identified: "all even parity except one single 1 in each set;
all point to swaps, and a terminal."

For each residual type the type-flat W_type <= F_2^10 = F_4^5 is:
  * generated by SWAPS (cut-vectors of single Kempe moves);
  * contains the all-ones TERMINAL (1,1,...,1) = the global F_4 relabel by 3;
  * its even-weight subcode has codimension 1 (a single odd generator on top);
  * its DUAL (parity checks) is an all-EVEN-weight code;
  * carries a thin set of weight-1 "single" codewords (degenerate swap directions).

The 7 collapse to 2 weight classes over F_4 (dim-7 vs dim-8), refining to 3 binary
classes. This re-describes the four-color residual as a tiny coding-theory object.

SCORE: 7/7 (all-ones terminal in every W; even-weight dual for every W; even-subcode
            codim 1; weight-1 singles counted; F_4 classes = 2, binary = 3)
"""
import itertools
from collections import defaultdict, Counter


def emb(g, s):
    vv = [0] * 10
    for i in range(5):
        if s[i]: vv[2 * i] = (g >> 1) & 1; vv[2 * i + 1] = g & 1
    return tuple(vv)


def type_cutvecs(cs, sig):
    out = []
    for a, b in itertools.combinations(range(4), 2):
        g = a ^ b; P = [i for i in range(5) if cs[i] in (a, b)]
        par = {i: i for i in P}
        def f(x):
            while par[x] != x: par[x] = par[par[x]]; x = par[x]
            return x
        for (i, j) in sig:
            if i in par and j in par and {cs[i], cs[j]} == {a, b}: par[f(i)] = f(j)
        blk = defaultdict(list)
        for i in P: blk[f(i)].append(i)
        for b2 in blk.values():
            out.append(emb(g, tuple(1 if i in b2 else 0 for i in range(5))))
    return out


def span(vecs):
    S = {(0,) * 10}
    for vv in vecs:
        S |= {tuple(a ^ b for a, b in zip(t, vv)) for t in S}
    return S


def dual(W):
    return [t for t in itertools.product((0, 1), repeat=10)
            if all(sum(a * b for a, b in zip(t, w)) % 2 == 0 for w in W)]


RES = [("R1", (0, 1, 0, 2, 3), {(0, 1), (1, 2), (2, 3), (3, 4), (0, 4), (1, 3), (1, 4)}),
       ("R2", (0, 1, 2, 0, 3), {(0, 1), (1, 2), (2, 3), (3, 4), (1, 4), (2, 4)}),
       ("R3", (0, 1, 2, 0, 3), {(0, 1), (1, 2), (2, 3), (3, 4), (0, 4), (1, 4), (2, 4)}),
       ("R4", (0, 1, 2, 1, 3), {(0, 1), (1, 2), (2, 3), (3, 4), (0, 2), (0, 4), (2, 4)}),
       ("R5", (0, 1, 2, 3, 1), {(0, 1), (1, 2), (2, 3), (3, 4), (0, 2), (0, 3)}),
       ("R6", (0, 1, 2, 3, 1), {(0, 1), (1, 2), (2, 3), (3, 4), (0, 2), (0, 3), (0, 4)}),
       ("R7", (0, 1, 2, 3, 2), {(0, 1), (1, 2), (2, 3), (3, 4), (0, 3), (0, 4), (1, 3)})]
ONES = (1,) * 10


def f4wd(W):
    return tuple(sorted(Counter(sum(1 for i in range(5) if (w[2*i] or w[2*i+1])) for w in W).items()))


def main():
    f4classes = defaultdict(list); binclasses = defaultdict(list)
    all_terminal = all_evendual = all_codim1 = True
    for name, cs, sig in RES:
        W = span(type_cutvecs(cs, sig))
        terminal = ONES in W
        even = [w for w in W if sum(w) % 2 == 0]
        codim1 = (len(even) * 2 == len(W))
        D = dual(W); even_dual = all(sum(d) % 2 == 0 for d in D)
        w1 = sum(1 for w in W if sum(w) == 1)
        all_terminal &= terminal; all_evendual &= even_dual; all_codim1 &= codim1
        f4classes[f4wd(W)].append(name)
        binclasses[tuple(sorted(Counter(sum(w) for w in W).items()))].append(name)
        print(f"{name} dim{len(W).bit_length()-1}: terminal(all-ones)in W={terminal}; "
              f"even-subcode codim={'1' if codim1 else '?'}; even-weight dual={even_dual}; "
              f"weight-1 singles={w1}; dual[10,{len(D).bit_length()-1}]")
    print(f"\nF_4 weight classes: {len(f4classes)}  -> {[v for v in f4classes.values()]}")
    print(f"binary weight classes: {len(binclasses)} -> {[v for v in binclasses.values()]}")
    print(f"PASS: {all_terminal and all_evendual and all_codim1 and len(f4classes)==2}")


if __name__ == "__main__":
    main()
