print("="*92)
print("IS THERE AN IRREDUCIBLE TERNARY BST COMMITMENT?  The candidate is colour, N_c = 3.")
print("="*92)
print("  Corpus (T2527, and the registry's Peirce line): colour IS the Peirce OFF-DIAGONAL V_12 of")
print("  the rank-2 spin factor:  V = R c_1  (+)  R c_2  (+)  V_12,")
print("  with c_1, c_2 the two orthogonal idempotents (the DIAGONAL = the record, 2 seats = the rank)")
print("  and V_12 the off-diagonal block. For the spin factor of dim n:  dim V_12 = n - 2.")
for n in [4,5,6,7]:
    print("      n = %d  ->  dim V_12 = %d%s"%(n,n-2,"   <-- n_C = 5 gives 3 = N_c" if n==5 else ""))
print()
print("="*92)
print("(1) THE CIRCULARITY CHECK KEEPER ASKED FOR -- and it fails, as predicted.")
print("="*92)
print("  The split 'colour is OFF-diagonal, the record is DIAGONAL' comes from the Peirce")
print("  decomposition -- and a Peirce decomposition has exactly TWO diagonal idempotents BECAUSE")
print("  THE RANK IS 2. So the split is a CONSEQUENCE of rank 2, not an independent argument for it.")
print("  ⟹ using it to argue for rank 2 is CIRCULAR. It bottoms at P1, exactly as flagged.")
print()
print("="*92)
print("★★ (2) BUT RUN THE TERNARY CANDIDATE ON ITS OWN TERMS -- and it BACKFIRES.")
print("="*92)
print("  If a commitment were ternary, the algebra is RANK 3: three diagonal idempotents and THREE")
print("  off-diagonal blocks. The simple rank-3 Jordan algebras are Herm_3(A), A a division algebra:")
tot=[]
for A,d in [("R",1),("C",2),("H",4),("O",8)]:
    dim=3+3*d
    tot.append((A,d,dim))
    print("      Herm_3(%s) : dim = 3 (diagonal) + 3 x %d (off-diagonal) = %2d %s"%(
        A,d,dim,"   <-- the ALBERT algebra, E_6" if A=="O" else ""))
print()
print("  ⟹ THE OFF-DIAGONAL BLOCK DIMENSION IN A RANK-3 ALGEBRA IS dim(A) in {1, 2, 4, 8}")
print("     -- by HURWITZ, exactly as in my 5296. NEVER 3.")
print("  ★★★ SO A TERNARY COMMITMENT CANNOT PRODUCE COLOUR-3 AT ALL. The ternary route does not")
print("      merely fail to help -- it is INCOMPATIBLE with N_c = 3. In a rank-3 world the")
print("      off-diagonal would be 1, 2, 4 or 8, and the Albert/E_6 case gives EIGHT.")
print()
print("  and note what 8 is, so nobody reaches for it: 8 = dim SU(3) adjoint = the GLUON count.")
print("  That is a DIFFERENT object from N_c = 3 (fundamental) -- flagging it now, because a")
print("  rank-3 advocate will notice 8 and try to marry it to the gluons. Same failure class as")
print("  today's two elevens.")
print()
print("="*92)
print("(3) THE VERDICT")
print("="*92)
print("  * the ternary candidate is DEAD ON ITS OWN TERMS: rank 3 gives off-diagonal 1/2/4/8, never 3,")
print("    so it cannot deliver the very thing (colour = 3) that motivated it;")
print("  * and the 'off-diagonal vs diagonal' split that would have argued FOR rank 2 is CIRCULAR,")
print("    because the Peirce decomposition presupposes the rank.")
print("  ⟹ BOTH ROADS BOTTOM AT P1. There is no irreducible ternary BST commitment on offer, and no")
print("     non-circular route from colour to the rank. P1 stands as the named axiom -- which is")
print("     exactly where Keeper predicted it would land, and the check is worth having run because")
print("     the ternary route fails for a REASON (Hurwitz), not merely for lack of a candidate.")
