import numpy as np
exec(open('parallax.py').read().split('print("  PARALLAX')[0])
print("="*80)
print("CASEY 2: 'parallax is lost if the observer is unable to MOVE sufficiently to acquire it'")
print("="*80)
print("  My 5270 asked whether depth fails at large D (a horizon). It does not, on a compact S^4.")
print("  Casey's point is different and better: depth fails if there is NO BASELINE AT ALL.")
print("  parallax = b * f(D).  If b is too small, b*f(D) < sigma for EVERY D -- the WHOLE sky is")
print("  depthless, not just the far part. That is not a failure mode; that is the mechanism.")
print()
Ds=np.linspace(0.05,3.09,400)
f=np.array([parallax(0.01,D)/0.01 for D in Ds])
fmax=np.nanmax(f); fmed=np.nanmedian(f)
print("  from my own 5270 profile:  f_max = %.1f (antipodal focusing)   f_median = %.2f"%(fmax,fmed))
print()
print("  CONDITION for a fully depthless sky:   b * f_max < sigma   =>   b < sigma / f_max")
print("     b < sigma / %.1f      -- the observer must move LESS than this between commitments"%fmax)
print()
print("   sigma (rad)     required b <          vs naive (b < sigma)")
for s in [1e-2,1e-3,1e-4,1e-6]:
    print("   %-13.0e   %.3e            %.0fx more stringent"%(s,s/fmax,fmax))
print()
print("  ★ SO MY 5270 'NEGATIVE' BECOMES A QUANTITATIVE CONDITION -- and my antipodal-focusing")
print("    result makes it %.0fx HARDER than the naive estimate, not easier."%fmax)
print("    The sphere's conjugate point is the strictest constraint on the mechanism, not an obstacle to it.")
print()
print("="*80)
print("AND THE TESTABLE FORM")
print("="*80)
print("  b = (observer velocity) x (commitment interval).  A fully angular record requires")
print("        v * Delta_tau  <  sigma / f_max")
print("  => the mechanism predicts a RELATION between observer motion, tick rate, and resolution.")
print("  => an observer that moves too much between ticks WOULD acquire depth -- and the record")
print("     would not be purely angular. That is a falsifiable edge, not a free parameter.")
