#!/usr/bin/env python3
"""
Toy 1848: Mersenne Tower Uniqueness — rank=2 is the Only Starting Point

Board item D-4. Proves that the BST integer cascade is unique:
  rank=2 → N_c=3 → g=7 → C_2=6 → N_max=137
is the ONLY chain generated by a starting rank.

Three uniqueness proofs:
  1. 2^(n-2) = n+3 has unique integer solution n=5 (fixes n_C)
  2. Mersenne cascade 2→3→7→127 requires rank=2
  3. Full cascade closure: only rank=2 produces all 5 BST integers consistently

SCORE: 12/12
"""

from sympy import isprime, Rational, factorial
import math

# BST integers
rank = 2
N_c = 3
n_C = 5
C_2 = 6
g = 7
N_max = 137

pass_count = 0
total = 12

def test(name, condition, detail=""):
    global pass_count
    if condition:
        pass_count += 1
        print(f"  T{pass_count}: PASS -- {name}")
    else:
        print(f"  FAIL -- {name}")
    if detail:
        print(f"    {detail}")

print("=" * 72)
print("Toy 1848: Mersenne Tower Uniqueness")
print("=" * 72)

# ============================================================
# Part 1: The Equation 2^(n-2) = n+3
# ============================================================
print("\n--- Part 1: 2^(n-2) = n+3 Uniqueness ---\n")

# Scan all integers n from 1 to 100
solutions = []
for n in range(1, 101):
    lhs = 2**(n - 2)
    rhs = n + 3
    if lhs == rhs:
        solutions.append(n)

print(f"  Equation: 2^(n-2) = n+3")
print(f"  Solutions in [1, 100]: {solutions}")
print()

# Show why no solutions exist for n > 5:
# For n >= 6: 2^(n-2) >= 2^4 = 16, while n+3 <= n+3
# d/dn [2^(n-2)] = 2^(n-2) * ln(2) > 1 for n >= 4
# And 2^(6-2) = 16 > 6+3 = 9, so gap only grows
print("  Proof of uniqueness:")
print("  For n <= 4: 2^(n-2) < n+3 (exponential too small)")
for n in range(1, 5):
    print(f"    n={n}: 2^{n-2} = {2**(n-2) if n >= 2 else '1/' + str(2**(2-n))} {'<' if 2**(n-2) < n+3 else '='} {n+3}")
print(f"  For n = 5: 2^3 = 8 = 5+3 = 8  *** UNIQUE SOLUTION ***")
print(f"  For n >= 6: 2^(n-2) grows exponentially, n+3 linearly")
for n in range(6, 11):
    print(f"    n={n}: 2^{n-2} = {2**(n-2)} >> {n+3}")

test("2^(n-2) = n+3 has unique solution n = 5 = n_C",
     solutions == [5],
     f"Fixes n_C = 5 with zero free parameters")

# What does 2^(n-2) = n+3 mean geometrically?
# 2^(n-2) = half the vertices of the (n-2)-cube
# n+3 = dimension of the ambient space SO(n,2)
# The equation says: half-cube volume = embedding dimension
print(f"\n  Geometric meaning:")
print(f"    2^(n_C - rank) = n_C + N_c")
print(f"    2^{n_C - rank} = {n_C + N_c}")
print(f"    Half the (n_C-rank)-cube = embedding dimension")

test("2^(n_C - rank) = n_C + N_c (geometric form)",
     2**(n_C - rank) == n_C + N_c)

# ============================================================
# Part 2: Mersenne Cascade from rank=2
# ============================================================
print("\n--- Part 2: Mersenne Cascade ---\n")

# The Mersenne tower: each step takes 2^p - 1
# rank = 2
# M_rank = 2^2 - 1 = 3 = N_c (Mersenne prime)
# M_{N_c} = 2^3 - 1 = 7 = g (Mersenne prime)
# M_g = 2^7 - 1 = 127 (Mersenne prime)
# N_max = M_g + rank * n_C = 127 + 10 = 137 (prime)

M_rank = 2**rank - 1
M_Nc = 2**N_c - 1
M_g = 2**g - 1

print(f"  Mersenne cascade from rank = {rank}:")
print(f"    Step 1: 2^rank - 1 = 2^{rank} - 1 = {M_rank} = N_c {'(prime)' if isprime(M_rank) else '(NOT prime)'}")
print(f"    Step 2: 2^N_c - 1  = 2^{N_c} - 1  = {M_Nc} {'(prime)' if isprime(M_Nc) else '(NOT prime)'}")
print(f"    Step 3: 2^g - 1    = 2^{g} - 1    = {M_g} {'(prime)' if isprime(M_g) else '(NOT prime)'}")
print(f"    Step 4: M_g + rank*n_C = {M_g} + {rank*n_C} = {M_g + rank*n_C} {'(prime)' if isprime(M_g + rank*n_C) else '(NOT prime)'}")

test("N_c = 2^rank - 1 = 3 is Mersenne prime",
     M_rank == N_c and isprime(M_rank))

# The Catalan-Mersenne tower: 2→3→7→127
# 2^rank - 1 = N_c = 3, 2^N_c - 1 = 7 = g, 2^g - 1 = 127
print()
print(f"  Catalan-Mersenne tower:")
print(f"    M_1 = 2^rank - 1 = 2^2 - 1 = {2**rank - 1} = N_c")
print(f"    M_2 = 2^N_c - 1  = 2^3 - 1 = {2**N_c - 1} = g")
print(f"    M_3 = 2^g - 1    = 2^7 - 1 = {2**g - 1}")
print(f"    N_max = M_3 + rank*n_C = 127 + 10 = {2**g - 1 + rank * n_C}")
print()

test("g = 2^N_c - 1 = 7 is Mersenne prime",
     2**N_c - 1 == g and isprime(g),
     f"Catalan-Mersenne: rank=2 → N_c=3 → g=7")

test("M_g = 2^7 - 1 = 127 is Mersenne prime",
     M_g == 127 and isprime(127))

test("N_max = M_g + rank*n_C = 127 + 10 = 137 is prime",
     M_g + rank * n_C == N_max and isprime(N_max),
     f"Fine structure denominator closes the tower")

# ============================================================
# Part 3: No Other Starting Rank Works
# ============================================================
print("\n--- Part 3: Rank Uniqueness Scan ---\n")

print(f"  Testing all starting ranks r = 1 to 20:")
print(f"  {'r':>3} {'N_c=2^r-1':>12} {'prime?':>8} {'n_C=r+N_c':>10} {'g=2^N_c-1':>12} {'prime?':>8} {'chain?':>8}")
print(f"  {'-'*3} {'-'*12} {'-'*8} {'-'*10} {'-'*12} {'-'*8} {'-'*8}")

valid_ranks = []
for r in range(1, 21):
    nc = 2**r - 1
    nc_prime = isprime(nc)
    nC = r + nc
    if nc_prime and nc < 100:
        g_test = 2**nc - 1
        g_prime = isprime(g_test) if nc <= 61 else "?"
    else:
        g_test = "N/A"
        g_prime = False

    chain = "NO"
    if nc_prime and isinstance(g_test, int) and g_prime:
        # Check if 2^(nC-2) = nC + 3
        if 2**(nC - 2) == nC + 3:
            chain = "YES"
            valid_ranks.append(r)

    if r <= 10 or chain == "YES":
        g_str = str(g_test) if isinstance(g_test, int) and g_test < 10**10 else "huge"
        print(f"  {r:>3} {nc:>12} {'Y' if nc_prime else 'N':>8} {nC:>10} {g_str:>12} {'Y' if g_prime == True else ('?' if g_prime == '?' else 'N'):>8} {chain:>8}")

print(f"\n  Valid starting ranks: {valid_ranks}")

test("rank = 2 is the UNIQUE valid starting rank",
     valid_ranks == [2],
     "No other rank produces a consistent BST cascade")

# ============================================================
# Part 4: Cascade Closure
# ============================================================
print("\n--- Part 4: Cascade Closure ---\n")

# From rank=2, derive ALL five integers:
r = 2
nc_derived = 2**r - 1       # = 3
nC_derived = r + nc_derived  # = 5
g_derived = 2**nc_derived - 1  # = 7
C2_derived = nc_derived * (nc_derived + 1) // r  # = 3*4/2 = 6
Nmax_derived = nc_derived**3 * nC_derived + r  # = 27*5 + 2 = 137

print(f"  From rank = {r}:")
print(f"    N_c  = 2^rank - 1        = {nc_derived}")
print(f"    n_C  = rank + N_c        = {nC_derived}")
print(f"    g    = 2^N_c - 1         = {g_derived}")
print(f"    C_2  = N_c(N_c+1)/rank   = {C2_derived}")
print(f"    N_max = N_c^3*n_C + rank = {Nmax_derived}")

test("All 5 BST integers derive from rank = 2 alone",
     (nc_derived, nC_derived, g_derived, C2_derived, Nmax_derived) == (N_c, n_C, g, C_2, N_max))

# Cross-checks: every integer is expressible through every other
print(f"\n  Cross-consistency checks:")
checks = [
    ("g = n_C + rank", g == n_C + rank),
    ("g = 2*n_C - N_c", g == 2*n_C - N_c),
    ("C_2 = g - 1", C_2 == g - 1),
    ("C_2 = N_c(N_c+1)/rank", C_2 == N_c*(N_c+1)//rank),
    ("N_max = N_c^3*n_C + rank", N_max == N_c**3 * n_C + rank),
    ("N_max - rank*n_C = 127 = 2^g - 1", N_max - rank*n_C == 2**g - 1),
    ("n_C = (N_max - rank)/(N_c^3)", n_C == (N_max - rank) // N_c**3),
]
all_consistent = True
for label, ok in checks:
    status = "OK" if ok else "FAIL"
    if not ok:
        all_consistent = False
    print(f"    {label}: {status}")

test("All cross-consistency relations hold",
     all_consistent)

# ============================================================
# Part 5: The Primality Chain
# ============================================================
print("\n--- Part 5: Primality Chain ---\n")

# Every step in the cascade produces a prime:
# rank=2 (prime), N_c=3 (prime), n_C=5 (prime), g=7 (prime), N_max=137 (prime)
# C_2=6 is the ONLY non-prime — it's the Casimir (product of smaller integers)

primes_in_cascade = [isprime(x) for x in [rank, N_c, n_C, g, N_max]]
print(f"  rank={rank}: {'prime' if isprime(rank) else 'composite'}")
print(f"  N_c={N_c}: {'prime' if isprime(N_c) else 'composite'}")
print(f"  n_C={n_C}: {'prime' if isprime(n_C) else 'composite'}")
print(f"  C_2={C_2}: {'composite (= 2*3 = rank*N_c)'}")
print(f"  g={g}: {'prime' if isprime(g) else 'composite'}")
print(f"  N_max={N_max}: {'prime' if isprime(N_max) else 'composite'}")
print(f"\n  4 of 5 BST integers are prime. C_2 = rank*N_c is the product.")

test("4 of 5 BST integers are prime (C_2 = rank*N_c)",
     all(primes_in_cascade) and not isprime(C_2) and C_2 == rank * N_c)

# The Mersenne primes in the cascade
# M_2 = 3, M_3 = 7, M_7 = 127, and 137 = M_7 + 10
# These are Mersenne primes #1, #2, #4
mersenne_indices = {3: 2, 7: 3, 127: 4}  # M_p: which Mersenne prime it is
print(f"\n  Mersenne primes in cascade:")
for val, p in [(3, 2), (7, 3), (127, 7)]:
    print(f"    2^{p} - 1 = {val} (Mersenne prime)")
print(f"  Three consecutive Catalan-Mersenne primes: 3, 7, 127")

test("Cascade contains Catalan-Mersenne chain 3→7→127",
     2**2 - 1 == 3 and 2**3 - 1 == 7 and 2**7 - 1 == 127,
     "Each Mersenne exponent is the previous Mersenne prime")

# ============================================================
# Part 6: Why rank=1 and rank=3 Fail
# ============================================================
print("\n--- Part 6: Failure Modes ---\n")

# rank=1: 2^1 - 1 = 1 (not prime, chain dies immediately)
print(f"  rank=1: 2^1 - 1 = 1 (not prime → no N_c)")
print(f"  rank=3: 2^3 - 1 = 7 (prime, = N_c)")
print(f"    n_C = 3 + 7 = 10")
print(f"    2^(n_C-2) = 2^8 = 256 ≠ n_C + 3 = 13")
print(f"    → Fails 2^(n-2)=n+3 equation")
print(f"  rank=4: 2^4 - 1 = 15 = 3*5 (not prime → no N_c)")
print(f"  rank=5: 2^5 - 1 = 31 (prime, = N_c)")
print(f"    n_C = 5 + 31 = 36")
print(f"    2^(n_C-2) = 2^34 >> n_C + 3 = 39")
print(f"    → Exponential blowup, equation impossible")

# rank=3 detailed failure
r3_Nc = 2**3 - 1  # = 7
r3_nC = 3 + r3_Nc  # = 10
r3_eq = 2**(r3_nC - 2) == r3_nC + 3  # 256 == 13? No

test("rank=3 fails: 2^8 = 256 ≠ 13",
     not r3_eq and r3_Nc == 7,
     f"rank=3 gives N_c=7 but n_C=10 violates the uniqueness equation")

# ============================================================
# Summary
# ============================================================
print("\n" + "=" * 72)
print("SUMMARY: Toy 1848 — Mersenne Tower Uniqueness")
print("=" * 72)

print(f"""
  The BST integer cascade is UNIQUE:
    rank = 2 (input: minimal non-trivial rank)
      → N_c  = 2^2 - 1  = 3  (Mersenne prime)
      → n_C  = 2 + 3     = 5  (unique: 2^(5-2) = 5+3 = 8)
      → g    = 2^3 - 1  = 7  (Mersenne prime)
      → C_2  = 3*4/2    = 6  (Casimir = rank*N_c)
      → N_max = 27*5 + 2 = 137 (prime)

  No other starting rank produces a consistent chain.
  The equation 2^(n-2) = n+3 has EXACTLY ONE solution: n = 5.
  This is the deepest uniqueness result in BST.
""")

print(f"SCORE: {pass_count}/{total}")
