from fractions import Fraction as F
n_C=5; N_c=3
print("="*104)
print("TOY 5344 -- TRACK B: pin the NUMBER-vs-GROUP split from source, and re-state the two mechanisms")
print("  Convention pinned BEFORE the physics (Cal's standing rule). Tables first.")
print("="*104)

print("\nTABLE 1 -- the NUMBER side is solid, and it is banked")
a=n_C-2
print("   Faraut-Koranyi multiplicity for D_IV^n (rank 2):  a = n - 2")
print("   at n = n_C = %d :  a = %d = N_c"%(n_C,a))
print("   same object as the Peirce space:  V = R c_1 (+) R c_2 (+) V_12,  dim V_12 = n - 2 = %d"%a)
print("   ==> *** THE NUMBER 3 IS FORCED GEOMETRY. *** It is the same a that fixes the Wallach point")
print("       a/2 = 3/2 (toy 5324) and the generalized Pochhammer. Load-bearing, uncontested.")

print("\nTABLE 2 -- *** but the GROUP side needs a convention pinned FIRST: is the 3 REAL or COMPLEX? ***")
print("   group    dim   rank   acts naturally on         real dim of that space")
for nm,d,r,sp,rd in [("SO(3)",3,1,"REAL 3-space",3),("SU(3)",8,2,"COMPLEX 3-space",6),("U(3)",9,3,"COMPLEX 3-space",6)]:
    print("   %-8s %-5d %-6d %-25s %d"%(nm,d,r,sp,rd))
print("   ==> *** SU(3) REQUIRES A COMPLEX 3-SPACE, i.e. REAL DIMENSION 6. ***")

print("\nTABLE 3 -- so which is V_12 / the multiplicity space?")
print("   evidence                                              reads as")
print("   FK multiplicity a = n-2 is a RESTRICTED-ROOT           REAL multiplicity")
print("     multiplicity (a count of real root vectors)")
print("   Peirce notation 'V = R c_1 (+) R c_2 (+) V_12'         REAL Jordan algebra")
print("     uses R (real) coefficients on the idempotents")
print("   dim V_12 = n - 2 = 3                                   *** REAL 3, not complex 3 ***")
print("   ==> if that reading is right, the natural group on it is *** SO(3), NOT SU(3) ***.")
print("       SO(3): dim 3, rank 1.   SU(3): dim 8, rank 2.  These are not the same group and")
print("       they are not even the same rank.")

print("\nTABLE 4 -- *** THE PIN TRACK B NEEDS, STATED AS ONE QUESTION ***")
print("   'SU(3) is realized ON the 3-dim multiplicity space' requires that space to be")
print("   COMPLEX 3-dimensional (real dim 6). The corpus's own a = n_C - 2 = 3 and")
print("   dim V_12 = 3 both read as REAL 3.")
print("   ==> *** IS THE 3 A REAL DIMENSION OR A COMPLEX ONE? ***")
print("       real 3  -> SO(3) acts; the SU(3) sentence is WRONG as written and must be re-stated")
print("       complex 3 -> SU(3) acts; but then the REAL multiplicity is 6, not 3, and 'a = N_c = 3'")
print("                    needs re-deriving because a would be 6")
print("   *** EITHER ANSWER COSTS SOMETHING. That is why it must be pinned to FK's book before")
print("       the color piece is assembled, not after. ***")
print("   ** I am NOT resolving this -- @Grace leads Track B and owns the source read. I am")
print("      delivering the question in the form that decides it. **")

print("\nTABLE 5 -- what SURVIVES regardless of how the pin lands")
print("   claim                                                        survives?")
print("   the NUMBER 3 is forced geometry (FK multiplicity a = n_C-2)   *** YES -- untouched ***")
print("   SU(3) is NOT an isometry subgroup of SO(5)                    *** YES -- proved 5332 ***")
print("      (no A_2 in B_2; no real 5-dim irrep of SU(3); centre Z_3 =/= Spin(5)'s Z_2)")
print("   colour thirds come from OUTSIDE the SO(5) factor              *** YES -- C_2 = 6 = 1+N_c+rank")
print("   'SU(3) is realized on the multiplicity space'                 *** PENDING THE PIN ***")

print("\nTABLE 6 -- the two confinement mechanisms, re-stated as instructed (NOT merged)")
print("   mechanism            what it constrains      why it cannot be the other")
print("   W-16 T^2-cycle       GLUON cycles           gluons are ADJOINT -> triality 0")
print("   Z_3 superselection   TRIALITY-charged states  ...so Z_3 is BLIND to gluons")
print("   plus the counting:   |Hom(Z^2, Z_3)| = 9, eight non-trivial; nothing selects one")
print("   ==> *** TWO MECHANISMS, with a POSITIVE reason they cannot merge (toy 5335), not merely")
print("       'unproven'. They constrain disjoint sets of objects. ***")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) THE NUMBER SIDE IS CLEAN AND BANKED: a = n_C - 2 = 3 = N_c is forced geometry (FK")
print("     multiplicity = dim V_12), the same a that gives the Wallach point 3/2. Uncontested.")
print()
print(" (2) *** THE GROUP SIDE HAS A CONVENTION COLLISION THAT MUST BE PINNED BEFORE ASSEMBLY. ***")
print("     'SU(3) realized on the 3-dim multiplicity space' needs a COMPLEX 3-space (real dim 6).")
print("     FK's a is a restricted-root multiplicity (real) and the Peirce notation is over R.")
print("     If the 3 is REAL, the natural group is SO(3) -- dim 3, rank 1 -- and NOT SU(3).")
print("     @Grace: this is the source read that decides the color piece. Either answer costs")
print("     something, which is exactly why it goes before the write-up, not after.")
print()
print(" (3) THE STANDING FIX SURVIVES EITHER WAY, in this exact phrasing: *** the geometry forces")
print("     the NUMBER 3; it does not host the GROUP SU(3) as an isometry. *** What is open is")
print("     only the second clause's positive half -- WHICH group is realized on the 3.")
print()
print(" (4) TWO CONFINEMENT MECHANISMS, re-stated and NOT merged, with the positive reason:")
print("     the adjoint is centre-neutral, so Z_3 is blind to precisely the gluons W-16 is about.")
