#!/usr/bin/env python3
"""
Toy (tower height on the census) — Round 114 §2 corollary (Grace, 2026-09-03): the observer tower's HEIGHT is the
confinement verdict — height 1 ⟺ [c] = 0 ⟺ confined, height 2 otherwise — measured with toy 5653's tower (branched double
cover via 4-triangle subdivision, then the Z3 charge cover) on EVERY fullerene dual C20…C60 (all isomers) and every IPR
isomer C60…C100, generated by fullgen (tools/plantri58/fullgen, code 7 = dual planar_code; Elie 5644's reader), and
compared graph by graph with Elie 5651's sealed class_zero column (.census_5651_sealed.json; join key = (m, index, ipr)).
A THIRD instrument for the class on the whole census; kill = any graph where height and class_zero disagree.
"""
import os, sys, json, time, glob, importlib.util
from collections import Counter
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import importlib
t = importlib.import_module('toy_5627_SEP2_E2_bundle_law_torus_test_completions_per_sign_record_mod_A4_with_sphere_disc_controls')
tw = importlib.import_module('toy_5653_SEP3_R113_observer_tower_built_explicitly_branched_double_cover_then_Z3_charge_cover_worked_cases_claims_i_to_iv')
HERE = os.path.dirname(os.path.abspath(__file__)); T0 = time.time()
def load(name, fname):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, fname)); mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod); return mod
T44 = load('t5644', os.path.basename(glob.glob(os.path.join(HERE, 'toy_5644_*.py'))[0]))

def faces_from_rot(rot):
    rd = {v: list(nb) for v, nb in enumerate(rot)} if isinstance(rot, list) else rot
    faces = t.faces_from_rotation(rd)
    if not all(len(f) == 3 for f in faces): faces = t.faces_from_rotation({v: c[::-1] for v, c in rd.items()})
    assert all(len(f) == 3 for f in faces) and t.check_closed_oriented(faces)
    return faces

def main():
    census = json.load(open(os.path.join(HERE, '.census_5651_sealed.json')))
    key = {(r['m'], r['idx'], r['ipr']): r['class_zero'] for r in census}
    agree = 0; disagree = []; heights = Counter(); done = 0
    pops = [(m, False) for m in range(20, 61, 2)] + [(m, True) for m in range(60, 101, 2)]
    import io, contextlib
    for m, ipr in pops:
        try: gs = T44.fullgen_duals(m, ipr=ipr)
        except Exception as e: print(f"  C{m} {'ipr' if ipr else ''}: generator error {e}"); continue
        for gi, rot in enumerate(gs):
            faces = faces_from_rot(rot)
            with contextlib.redirect_stdout(io.StringIO()):
                r = tw.tower(f"C{m}#{gi}", faces)
            h = r['height']; heights[h] += 1; done += 1
            cz = key.get((m, gi, ipr))
            if cz is None: continue
            if (h == 1) == cz: agree += 1
            else: disagree.append((m, gi, ipr, h, cz))
        print(f"  C{m}{' ipr' if ipr else ''}: {len(gs)} duals; running heights {dict(heights)}; agree {agree}; disagree {len(disagree)}   [{time.time()-T0:.0f}s]", flush=True)
    print(f"\nTOTAL {done} duals: height histogram {dict(heights)}; height-1 ⟺ class_zero agrees on {agree}; DISAGREE {len(disagree)} {disagree[:5]}")
    json.dump(dict(done=done, heights=dict(heights), agree=agree, disagree=disagree), open(os.path.join(HERE, '.out_' + os.path.basename(__file__).split('_')[1] + '.json'), 'w'), indent=1)
    print("SCORE:", "PASS" if not disagree else "FAIL", "— tower height = confinement verdict on the census")
if __name__ == '__main__':
    main()
