import numpy as np
pi=np.pi; n_C=5
print("="*104)
print("TOY 5340 -- the l_B <-> a coefficient reconciliation (gravity thread #94)")
print("  Does the boundary-radius route reproduce F64's -5/pi^5, or is my '12' bare?")
print("  Tables first, verdict after.  *** This audits my OWN 5339 coefficient. ***")
print("="*104)

print("\nTABLE 1 -- the two expressions, side by side")
kappa=-n_C
print("   F64 (KK reduction, banked): G = kappa_Bergman x l_B^2 / pi^{n_C} = %d l_B^2/pi^5"%kappa)
print("   Elie 5339                 : G = 12/R_bdy,  R_bdy = 12/a^2   =>   G = a^2")
print("   *** note what my step actually assumed: G ~ a^2 with COEFFICIENT EXACTLY 1. ***")
print("       That was DIMENSIONAL ANALYSIS, not a derivation. The 12 cancelled against itself.")

print("\nTABLE 2 -- equate them and see what falls out")
val=kappa/pi**n_C
print("   a^2 = (kappa/pi^5) l_B^2 = %.6f l_B^2"%val)
print("   ==> *** NEGATIVE. A squared real radius cannot be negative. THE NAIVE EQUATION FAILS. ***")

print("\nTABLE 3 -- why: the sign is the bulk/boundary curvature difference (my own 5336)")
print("   object          curvature      sign      compact?")
print("   D_IV^5 bulk     R = -n_C = -5  NEGATIVE  no (non-compact)")
print("   boundary S^4    R = +12/a^2    POSITIVE  yes")
print("   ==> kappa_Bergman = -5 is a BULK quantity; my 12 is a BOUNDARY quantity.")
print("       *** THEY ARE TWO DIFFERENT CURVATURES AND CANNOT BE EQUATED AS WRITTEN. ***")
print("       @Keeper was right to hold 'do not cite the unreconciled G = 12/R_bdy'.")

print("\nTABLE 4 -- take magnitudes: what O(1) factor does F64 actually supply?")
r=np.sqrt(abs(val))
print("   |a/l_B| = sqrt(n_C/pi^{n_C}) = sqrt(5/pi^5) = %.6f"%r)
print("   |l_B/a| = sqrt(pi^{n_C}/n_C) = sqrt(pi^5/5)  = %.6f"%(1/r))
print("   ==> the coefficient is NOT 1 and NOT 12: it is sqrt(pi^5/5) ~ %.4f."%(1/r))
print("       *** SO MY '12' WAS BARE -- a placeholder, not a derived number. F64 supplies the real")
print("       coefficient, and it is neither of the ones I wrote. ***")

print("\nTABLE 5 -- *** before anyone banks sqrt(pi^n/n): is IT dimension-generic? ***")
print("   (I just got burned by 25/4 being generic. Running the same sweep first.)")
print("   n     kappa = -n   pi^n        |l_B/a| = sqrt(pi^n/n)")
for n in range(3,9):
    print("   %-5d %-12d %-11.4f %.6f"%(n,-n,pi**n,np.sqrt(pi**n/n)))
print("   ==> the FORM sqrt(pi^n/n) holds identically in n -- *** DIMENSION-GENERIC, like 25/4.")
print("       The VALUE at n=5 is particular, but the FORM selects nothing. NOT a signature. ***")

print("\n--- SECOND QUESTION: can anything fix the boundary radius in ABSOLUTE terms? ---")
print("\nTABLE 6 -- the dimensional-analysis argument, stated as a theorem")
print("   BST's content: 5 INTEGERS (rank, N_c, n_C, C_2, g) + a geometry + dimensionless ratios.")
print("   EVERY one of those is dimensionless.")
print("   *** A dimensionless set cannot determine a LENGTH. *** No combination of pure numbers has")
print("   units of metres. So no amount of BST structure can fix l_B in absolute terms.")
print("   ==> *** THE ANSWER IS PROVABLY NO, AND IT IS NOT A DEFECT. *** It is forced by dimensional")
print("       analysis and applies identically to GR (takes G), the SM (takes v), QCD (takes")
print("       Lambda_QCD). One dimensionful input is the minimum any theory can take, and BST takes")
print("       exactly one.")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) *** THE '12' WAS BARE, AND I AM CORRECTING MY OWN 5339. *** I wrote G = 12/R_bdy")
print("     'literally'. The STRUCTURE (G inversely proportional to a curvature) survives; the")
print("     COEFFICIENT does not. My step assumed G = a^2 with coefficient exactly 1 -- dimensional")
print("     analysis, never derived -- and the 12 simply cancelled against itself. @Keeper's hold on")
print("     citing it was correct.")
print()
print(" (2) *** AND THE NAIVE RECONCILIATION FAILS ON A SIGN. *** kappa_Bergman = -5 is NEGATIVE")
print("     (non-compact BULK); the S^4 boundary curvature is POSITIVE. Setting a^2 = (kappa/pi^5)l_B^2")
print("     demands a negative squared radius. They are two different curvatures -- the same")
print("     bulk/boundary sign split I found in 5336 -- and they do not reconcile as written.")
print()
print(" (3) TAKING MAGNITUDES, F64's coefficient is |l_B/a| = sqrt(pi^{n_C}/n_C) = %.4f -- neither 1"%(1/r))
print("     nor 12. *** AND IT IS DIMENSION-GENERIC (Table 5): sqrt(pi^n/n) holds for every n, so the")
print("     FORM is not a D_IV^5 signature. *** Same category as 25/4. Do not bank it.")
print()
print(" (4) *** NOTHING CAN FIX THE BOUNDARY RADIUS ABSOLUTELY, AND THAT IS A THEOREM, NOT A GAP. ***")
print("     All of BST's content is dimensionless; a dimensionless set cannot determine a length.")
print("     So G's value is NECESSARILY one dimensionful input -- the GR bargain, forced by")
print("     dimensional analysis, identical to what GR/SM/QCD each pay. @Lyra: v1.2's wording")
print("     ('G's value is one dimensionful input, as GR takes G; BST supplies the dimensionless")
print("     structure') is EXACTLY right and is now backed by an impossibility argument, not just")
print("     a comparison. It needs no change.")
