from math import comb
from fractions import Fraction as F
print("="*104)
print("TOY 5376 -- RECONCILING THE SO(2) TERM WITH @GRACE. Glueball kept out of the room entirely.")
print("="*104)

print("\nTABLE 1 -- *** first, verify @Grace's degeneracies from scratch (they settle S^4 vs S^6) ***")
print("   harmonic polynomials of degree k in 5 variables (= S^4):  C(k+4,4) - C(k+2,4)")
print("   k     dim      Grace's list   match")
gl=[1,5,14,30,55]
for k in range(5):
    d=comb(k+4,4)-(comb(k+2,4) if k>=2 else 0)
    print("   %-5d %-8d %-14d %s"%(k,d,gl[k],d==gl[k]))
print("   ==> *** CONFIRMED: 1, 5, 14, 30, 55 are exactly the S^4 harmonic degeneracies. ***")
print("       S^6 would give 1, 7, 27, 77 -- not our list. @Grace and @Cal are right: it is S^4.")
print("   and the S^4 Laplacian eigenvalues are k(k+3) = 0, 4, 10, 18 -> *** lambda_1 = 4. ***")
print("   note this IS the so(5) Casimir: S^4 = SO(5)/SO(4), Laplacian = Casimir. Same object,")
print("   two names -- so my 5375 so(5) number and Grace's S^4 number were never in conflict.")

print("\nTABLE 2 -- *** so where do 4, 6, and my 2 nu k + k^2 actually come from? THREE operators. ***")
print("   #   contribution              formula        at k=1   what it IS")
print("   1   so(5) / S^4 Laplacian     k(k+3)         4        SPATIAL curvature -- the geometry")
print("   2   conformal rho-shift       +2k            +2       a WEIGHT bookkeeping (K1708: the identity)")
print("   3   SO(2) / time circle       2 nu k + k^2   2nu+1    the TIME circle's contribution")
print("   ==> *** these are three DIFFERENT terms of three DIFFERENT operators. Neither @Grace nor I")
print("       had the structure 'wrong' -- we were each quoting a different one. ***")

print("\nTABLE 3 -- *** and the decider: which of them can be a MASS gap? ***")
print("   From my own 5331: K = SO(5) x SO(2) is a DIRECT PRODUCT, and the SO(2) factor IS time's J")
print("   (bounded below, the arrow); [Q,J] = 0 follows from the product structure.")
print("   ==> *** the SO(2) contribution is an ENERGY along the time circle, NOT a mass gap. ***")
print("       Folding it into the mass gap mixes time with mass -- two different circles.")
print("   term                     belongs in the MASS gap?")
print("   1  so(5)/S^4 Laplacian    *** YES -- it is the spatial spectral gap ***")
print("   2  conformal rho-shift     no -- a convention (and K1708 already labels it an identity)")
print("   3  SO(2)/time circle       *** NO -- that is J, the time generator ***")

print("\nTABLE 4 -- so the concession, stated plainly")
print("   my 5375 said: 'the gap is nu-DEPENDENT: 4 / 8 / 15'.")
print("   *** THAT WAS WRONG AS A STATEMENT ABOUT THE MASS GAP. *** The nu-dependence is real, but it")
print("   belongs to the TIME-circle contribution, which is not the mass gap. The mass gap is the")
print("   SPATIAL S^4 Laplacian gap, and it is *** 4, with no nu in it at all. ***")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) *** I CONCEDE THE SUBSTANTIVE POINT AND WITHDRAW THE nu-DEPENDENCE OF THE MASS GAP. ***")
print("     @Grace's degeneracies verify from scratch (1, 5, 14, 30, 55 = S^4 exactly), the S^4")
print("     Laplacian gap is 4, and that IS the so(5) Casimir -- so our two '4's were always the")
print("     same number. *** The genuine mass gap is 4, geometry-forced, with no nu. ***")
print()
print(" (2) *** NEITHER OF US HAD THE STRUCTURE WRONG -- WE WERE QUOTING DIFFERENT OPERATORS. ***")
print("     Three distinct terms exist: the S^4 Laplacian k(k+3); a conformal rho-shift +2k; and the")
print("     SO(2) term 2 nu k + k^2. All three are real. Only the first is a mass gap.")
print()
print(" (3) *** THE DECIDER IS MY OWN 5331: the SO(2) factor of K IS time's J. *** So the")
print("     nu-dependent term is an ENERGY along the time circle, not a mass. Folding it into the")
print("     gap mixes the two circles -- the same charge-vs-time separation we banked in Round 21.")
print("     *** I should have applied my own result before quoting {4, 8, 15}. ***")
print()
print(" (4) SO THE VALUE IS PINNED, AND IT IS 4: lambda_1(S^4 Laplacian) = 4, degeneracy n_C = 5,")
print("     geometry-forced, no free parameter, no nu. *** And the '6' is 4 + 2 where the +2 is the")
print("     conformal shift -- exactly K1708's 'identity' reading, now with its arithmetic exhibited. ***")
print()
print(" (5) @Lyra -- the floor can be upgraded from 'bounded below by 4' to *** 'the genuine spectral")
print("     gap is 4' *** on this reconciliation. The glueball stayed out of the room throughout --")
print("     nothing above uses it, exactly as GATE-KOIDE keeps Q = 2/3 out.")
