from fractions import Fraction as F
d=5; RAC=F(3,2); DI=F(2)
print("="*100)
print("TOY 5328 -- does the VECTOR ROW discriminate singleton-vs-composite?")
print("  Tables first, verdict after.  *** This tests Keeper's FRAMING, not just his question. ***")
print("="*100)

print("\nTABLE 1 -- does the unitarity bound care which reading we adopt?")
print("   Mack's classification is a statement about UNITARY IRREPS of SO(5,2).")
print("   A rep is unitary or not; the bound has no input slot for 'elementary' vs 'composite'.")
print("   reading            spin-1 PRIMARY bound at d=5    is 5/2 allowed?")
for r in ["singleton (elementary)","composite (two-particle)"]:
    print("   %-25s Delta >= %-21s %s"%(r,F(d-2+1),"NO" if F(5,2)<F(d-2+1) else "yes"))
print("   ==> *** THE BOUND DOES NOT DISCRIMINATE. It kills a 5/2 spin-1 PRIMARY under BOTH")
print("       readings, because unitarity is a property of the REPRESENTATION, not of an")
print("       interpretation we lay over it. The proposed discriminator does not discriminate. ***")

print("\nTABLE 2 -- so where COULD a 5/2 vector live?  Enumerate every way to reach it.")
print("   Solve (3/2)n_R + 2 n_D + l + 2n = Delta  over constituents + spin + derivatives:")
for target in [F(5,2),F(4)]:
    sols=[(nR,nD,l,n) for nR in range(4) for nD in range(4) for l in range(4) for n in range(4)
          if RAC*nR+DI*nD+l+2*n==target and nR+nD>0]
    print("\n   Delta = %-4s :"%str(target))
    for nR,nD,l,n in sols[:5]:
        kind="PRIMARY" if (l==0 and n==0) else "DESCENDANT (l=%d, %d deriv)"%(l,n)
        print("      n_Rac=%d n_Di=%d  l=%d  n=%d   -> %s"%(nR,nD,l,n,kind))
print("\n   ==> 5/2 = ONE Rac with l=1 and no extra derivatives = d_mu(Rac).")
print("       *** That is a DESCENDANT INSIDE THE RAC MODULE -- not an independent particle. ***")
print("       Descendants are NOT subject to the primary unitarity bound, which is exactly why")
print("       5/2 'looks possible under the singleton reading': it is possible, as a descendant.")

print("\nTABLE 3 -- *** the REAL discriminator: run our own #Rac identity on each candidate ***")
print("   Delta   #Rac (from Delta parity)   exp(2 pi i J)   rides    photon observed to ride")
for D,nR in [(F(5,2),1),(F(4),2)]:
    ph=(-1)**nR
    print("   %-7s %-26d %-15s %-8s %s"%(str(D),nR,"%+d"%ph,"4 pi" if ph<0 else "2 pi","2 pi (360 deg) -- certain"))
print("\n   A photon is a PHYSICAL bulk particle -- polarization returns after 360 degrees.")
print("   This is not a modelling choice; it is measured, and it is not close.")
print("   ==> Delta = 5/2 forces #Rac = 1 -> rides 4 pi -> CONTRADICTS OBSERVATION.")
print("   ==> Delta = 4   forces #Rac = 2 -> rides 2 pi -> consistent.")

print("\nTABLE 4 -- and the internal consistency check on a 5/2 'vector'")
print("   #Rac = 1 states, by species (from toy 5327):")
print("      bare Rac        -> SCALAR   (not a vector)")
print("      Rac (x) Di      -> FERMION  (not a vector boson)")
print("      d_mu(Rac)       -> vector, but a DESCENDANT of the scalar, i.e. pure gauge / not an")
print("                         independent degree of freedom")
print("   ==> there is NO independent spin-1 BOSON with #Rac odd. A 5/2 vector particle would be a")
print("       boson riding 4 pi, which no odd-#Rac state in the whole enumeration supplies.")

print("\n"+"="*100)
print("VERDICT -- from Tables 1-4 only")
print("="*100)
print(" (1) *** THE ASSIGNED DISCRIMINATOR DOES NOT DISCRIMINATE -- as posed. *** @Keeper: the")
print("     unitarity bound cannot separate the readings, because it is interpretation-independent.")
print("     5/2 is dead as a spin-1 PRIMARY under BOTH the singleton and the composite reading.")
print("     My 5326 kill therefore stands, and it stands more broadly than I claimed there.")
print()
print(" (2) *** BUT THE FRAMING POINTED AT SOMETHING REAL. *** 5/2 IS reachable -- as d_mu(Rac), a")
print("     DESCENDANT inside the Rac module (Table 2). That is the honest content of '5/2 is")
print("     possible under the singleton reading': possible, but as a descendant, NOT as a particle.")
print("     A descendant is not an independent degree of freedom, so it cannot BE the photon row.")
print()
print(" (3) ***** AND THE VECTOR ROW DOES DECIDE -- BY A DIFFERENT ROUTE, FOR COMPOSITE. *****")
print("     Our own #Rac identity fixes the parity: Delta = 5/2 => #Rac = 1 => rides 4 pi.")
print("     A photon's polarization returns after 360 degrees. That is measured and not close.")
print("     Delta = 4 => #Rac = 2 => rides 2 pi => consistent.")
print("     ==> THE PHOTON IS THE Delta = 4 CONSERVED CURRENT IN Rac (x) Rac. COMPOSITE READING.")
print("     ** Note what did the work: the #Rac law (internal) PLUS one measured fact (external).")
print("        Neither alone settles it. I am not dressing the observation up as a derivation. **")
print()
print(" (4) SCOPE, HONESTLY: this decides the VECTOR ROW. It does NOT by itself settle 'are BST's")
print("     singletons particles or constituents' in general -- that is @Lyra/@Grace's corpus audit,")
print("     and the Rac=Higgs vs Rac=muon conflict is untouched by anything I computed here.")
