import numpy as np
from fractions import Fraction as F
print("="*92)
print("THE FORK: PROJECTIVE (states = rays) vs ABSOLUTE (phase physical). Tables first.")
print("="*92)
Di=[F(2)+2*k for k in range(5)]; Rac=[F(3,2)+2*k for k in range(5)]
def phase(T,lam): 
    z=np.exp(1j*float(T)*float(lam)); return complex(round(z.real,12),round(z.imag,12))
print("\nTABLE 1 -- exp(i T J) acting on EACH tower separately, at candidate periods")
for T,lab in [(np.pi,"T = pi"),(2*np.pi,"T = 2pi"),(4*np.pi,"T = 4pi")]:
    dph={phase(T,l) for l in Di}; rph={phase(T,l) for l in Rac}
    print("   %-9s  Di -> %-28s  (scalar? %s)"%(lab,sorted(dph,key=lambda z:(z.real,z.imag)),len(dph)==1))
    print("             Rac-> %-28s  (scalar? %s)"%(sorted(rph,key=lambda z:(z.real,z.imag)),len(rph)==1))
print("\nTABLE 2 -- the overall phase each tower picks up when it IS scalar")
for T,lab in [(np.pi,"pi"),(2*np.pi,"2pi"),(4*np.pi,"4pi")]:
    d=phase(T,Di[0]); r=phase(T,Rac[0])
    print("   T = %-4s  Di phase = %-18s   Rac phase = %s"%(lab,d,r))
print("\nTABLE 3 -- is the phase OBSERVABLE?  (what each reading says)")
print("   PROJECTIVE : an OVERALL phase on a tower is unobservable (states are rays).")
print("                A RELATIVE phase between two towers is observable ONLY if a physical state")
print("                superposes them.")
print("   Rac (scalar sector) vs Di : boson-vs-fermion superposition is FORBIDDEN by the univalence")
print("                superselection rule -> the Rac-Di relative phase is NOT observable.")
print("   ⟹ under PROJECTIVE + superselection, the cross-tower gcd (1/2) is UNMEASURABLE.")
print("\nTABLE 4 -- but does a SINGLE tower ride 4pi on its own?")
for nm,tw in [("Di",Di),("Rac",Rac)]:
    halfodd=all((2*l)%2==1 for l in tw)
    p2=phase(2*np.pi,tw[0])
    print("   %-4s charges %s ... : all half-odd? %-5s   exp(i 2pi J) = %s"%(nm,[str(x) for x in tw[:3]],halfodd,p2))
print()
print("="*92)
print("VERDICT -- from Tables 1-4 only")
print("="*92)
print("  TABLE 4 is decisive. The Rac tower's charges are ALL half-odd-integers (3/2, 7/2, 11/2, ...),")
print("  so exp(i 2pi J) = -1 on the ENTIRE Rac tower. That is the textbook spinor signature, and it")
print("  is observable the way real spinors' 4pi is observable -- by SELF-interference (one tower")
print("  interfering with itself along two paths, as in neutron interferometry), NOT by comparing")
print("  two different towers.")
print()
print("  ⟹ ★★ THE FORK RESOLVES **ABSOLUTE**: A SINGLE TOWER DOES RIDE 4pi.")
print("     The 'projective, no single particle rides it' option is REFUTED -- not because the")
print("     projective reading is wrong about rays, but because a -1 under 2pi is detectable")
print("     WITHIN one tower, where no superselection rule blocks it.")
print()
print("  ⟹ AND THE CROSS-TOWER STORY IS THE ONE THAT DIES: the Rac-Di relative phase IS blocked by")
print("     univalence superselection (Table 3), so the cross-tower gcd = 1/2 is unmeasurable.")
print("     My 5321 computed that gcd over the UNION of the two towers -- correct arithmetic, but it")
print("     is not what carries the physics. The physics is carried by the Rac tower alone.")
print()
print("  ★★★ AND A FLAG THE ROUND NEEDS, because it cuts against the corrected labels:")
print("     THE TOWER THAT BEHAVES SPINORIALLY (2pi -> -1) IS THE **RAC** -- which Cal's correction")
print("     identifies as the SCALAR sector. A scalar-labelled tower with half-odd charges and a")
print("     -1 under 2pi is either a real finding or a sign the (2,2)/(1,1) labels need the")
print("     reconciliation @Keeper already has open. I am NOT calling it either way -- I am flagging")
print("     that the fork's answer lands exactly on the open label question, and the paper must not")
print("     state 'scalar' and 'rides the double cover' in the same sentence until that closes.")
