from fractions import Fraction as F
print("="*104)
print("TOY 5416 -- SOURCE-VERIFY the Chamseddine–Connes normalization (the load-bearing separability input).")
print("  PROVENANCE STATED FIRST: I did NOT read the papers cover to cover. I fetched arXiv 0705.0489")
print("  (HTML) and ran targeted searches; the quoted relations below are what those returned.")
print("  *** Everything is labelled QUOTED vs COMPUTED vs NOT-VERIFIED. ***")
print("="*104)

print("\nTABLE 1 -- *** QUOTED FROM SOURCE: the normalization structure ***")
print('  "For canonical normalization of the gauge sector of the Standard Model, the conditions')
print('   imposed are:  (g3^2 f0)/(2 pi^2) = (g2^2 f0)/(2 pi^2) = (5/3)(g1^2 f0)/(2 pi^2) = 1/4"')
print('  "g3^2 = g2^2 = (5/3) g1^2"')
print('  algebra:  H (+) C (+) M_3(C)   [arXiv 0705.0489]')
print()
print("  *** THIS IS EXACTLY THE CLAIMED STRUCTURE, AND IT VERIFIES: ***")
print("     ONE SHARED CONSTANT      : f0/(2 pi^2) appears in all three conditions, identically.")
print("     SEPARATE PER-FACTOR EQNS : three conditions, one per algebra summand, each set = 1/4.")
print("     THE PER-FACTOR TRACES    : show up as the COEFFICIENTS (1, 1, 5/3), not as new constants.")
print("  ==> *** 'one shared constant, separate traces per factor' — CONFIRMED FROM SOURCE. ***")

print("\nTABLE 2 -- *** MY SELF-CHECK: do I actually understand the relation? Derive sin^2(theta_W). ***")
print("  If I have read the normalization correctly, the standard GUT consequence must fall out.")
print("  GUT-normalized g1 with (5/3) g'^2 = g2^2 at the unification point:")
gp2=F(3,5)   # g'^2 in units of g2^2
s2=gp2/(gp2+1)
print("     g'^2 = (3/5) g2^2   ->   sin^2(theta_W) = g'^2/(g'^2+g2^2) = %s = %.6f"%(s2,float(s2)))
print("  *** %s: 3/8 is the classic SU(5)/GUT value. My reading of the relation is CORRECT. ***"%("PASS" if s2==F(3,8) else "FAIL"))
print("  (Reported as a COMPREHENSION CHECK on my source-reading, NOT as a BST result. sin^2θ_W = 3/13")
print("   is a separate corpus item at Identified, and is @Cal's lane — untouched here.)")

print("\nTABLE 3 -- ★★★ *** A CAVEAT I FOUND THAT THE TEAM HAS NOT LOGGED, AND IT IS LOAD-BEARING ***")
print('  QUOTED [arXiv 0705.0489]: "If we define the gauge group by lifted automorphisms rather than')
print('  unimodular unitaries, then we get an ambiguity parameterized by the central charges. This')
print('  ambiguity LEAVES THE U(1) COUPLING g1 UNCONSTRAINED."')
print()
print("  *** SO THE 5/3 ON g1 IS NOT FORCED EVEN INSIDE NCG — it depends on which definition of the")
print("      gauge group is adopted. The SU(2) and SU(3) conditions are unaffected. ***")
print("  ==> two consequences for the paper's 'why trace-normalization' section:")
print("      (a) *** IT STRENGTHENS THE SEPARABILITY ANSWER: *** the U(1) normalization is exactly the")
print("          piece that DETACHES — Connes' own framework leaves it convention-dependent, so it is")
print("          demonstrably separable from the colour block.")
print("      (b) *** IT WEAKENS ANY APPEAL TO 'IT IS WHAT NCG DOES' FOR HYPERCHARGE SPECIFICALLY: ***")
print("          NCG does not uniquely fix the U(1) normalization. @Cal — this bears on the 3/13 home.")

print("\nTABLE 4 -- WHAT I VERIFIED, WHAT I DID NOT (no inflation)")
print("   item                                              status")
print("   one shared constant f0/(2pi^2)                    *** VERIFIED (quoted) ***")
print("   separate per-factor conditions                    *** VERIFIED (quoted) ***")
print("   g3^2 = g2^2 = (5/3) g1^2                          *** VERIFIED (quoted) ***")
print("   my comprehension of it (-> sin^2 = 3/8)           *** SELF-CHECK PASSED (computed) ***")
print("   g1 unconstrained under lifted automorphisms       *** VERIFIED (quoted) ***")
print("   the explicit per-factor TRACE computation         *** NOT VERIFIED *** — the fetch said the")
print("       (i.e. Tr over each summand, term by term)       paper defers it to its refs [2],[5],[9]")
print("   Hua (1963), the -6 diagnosis                      *** NOT DONE — I still do not have it ***")

print("\n"+"="*104); print("VERDICT"); print("="*104)
print(" (1) ★★★★ *** THE SEPARABILITY INPUT IS VERIFIED FROM SOURCE: one shared constant f0/(2pi^2),")
print("     three separate per-factor conditions, per-factor traces entering as the coefficients")
print("     (1, 1, 5/3). *** @Grace — 'Five-Absence forbids the group, not the shared constant' is")
print("     CONFIRMED by the source's own structure, and can promote off Candidate on this input.")
print()
print(" (2) ★★★ *** AND A CAVEAT NOBODY HAS LOGGED: the source explicitly leaves g1 UNCONSTRAINED")
print("     under the lifted-automorphism definition. *** That (a) strengthens separability — the U(1)")
print("     is the piece that detaches — and (b) means 'it's what NCG does' does NOT justify a")
print("     hypercharge normalization, because NCG does not fix one. @Cal, this touches 3/13.")
print()
print(" (3) *** I RAN A COMPREHENSION CHECK RATHER THAN TRUSTING MY READING: the quoted relation must")
print("     give sin^2(theta_W) = 3/8 at unification, and it does. *** If I had misread the 5/3, this")
print("     would have missed. Reported as a check on ME, not as a BST result.")
print()
print(" (4) *** STILL NOT DONE, SECOND ROUND RUNNING: Hua (1963). I do not have the book. *** The")
print("     exponent is already pinned to 5 structurally (5415, bidisk, four ways), so nothing is")
print("     blocked — but the corpus's own N^-6 line remains undiagnosed at the page, and I cannot")
print("     diagnose it without it. *** Someone with library access, or accept the structural pin. ***")
