import numpy as np
from math import pi, gamma
from fractions import Fraction as F
print("="*104)
print("TOY 5391 -- LANE B: the non-Wyler Poisson-kernel a/R. *** No alpha input anywhere below. ***")
print("  SPACE, LINE ONE: the SHILOV BOUNDARY of D_IV^5 in the Lie-ball realization.")
print("="*104)
g,n_C,rank=7,5,2
target=F(2*g,n_C)

print("\nTABLE 1 -- *** CAL'S NORMALIZATION-INDEPENDENCE RULE, applied FIRST ***")
print("   'two ratios through one metric = ONE route.'")
print("   @Grace's route 1 : the Hua/Bergman restriction ratio")
print("   my route 2       : the Poisson kernel P(z,zeta) = |K(z,zeta)|^2/K(z,z)")
print("   *** but the Poisson kernel is BUILT FROM the Bergman/Szego kernel K -- the same object")
print("       Grace's restriction uses. *** So both ratios pass through ONE metric.")
print("   ==> *** THESE ARE NOT TWO INDEPENDENT ROUTES. Cal's rule fires before any computation:")
print("       agreement between them would be a consistency of one object with itself, not")
print("       corroboration. ***")

print("\nTABLE 2 -- and the FIX-vs-CHOOSE gate on the ratio itself")
print("   in the Lie-ball realization the Shilov boundary is { e^{i theta} x : x in S^{n-1} }")
print("   both factors sit at radius 1 in the flat C^n metric -> naive ratio a/R = 1")
print("   so 14/5 = %.4f requires a RESCALING. Is that rescaling FIXED or CHOSEN?"%float(target))
print("   structure                       does it fix a metric on the boundary?")
print("   Bergman metric                  *** NO -- it DIVERGES at the boundary (infinite distance) ***")
print("   CR / contact structure          *** NO -- it fixes a CONFORMAL CLASS, not a metric ***")
print("   a choice of contact form        yes -- but that is a CHOICE, which is the gate")
print("   ==> *** the boundary carries a conformal class, not a ratio. A number like 14/5 comes")
print("       from picking a representative -- CHOOSE, not FIX. ***")

print("\nTABLE 3 -- test it anyway: can 14/5 be reached without alpha?")
def volS(n): return 2*pi**((n+1)/2)/gamma((n+1)/2)
print("   candidate geometric ratios (no alpha anywhere):")
cands=[("vol(S^4)/vol(S^1)",volS(4)/volS(1)),("vol(S^4)/vol(S^3)",volS(4)/volS(3)),
       ("vol(S^3)/vol(S^1)",volS(3)/volS(1)),("2g/n_C  (Grace's)",float(target)),
       ("n_C/rank",n_C/rank),("(n_C+rank)/rank",(n_C+rank)/rank),("dim/n_C",10/n_C)]
for nm,v in cands:
    print("      %-22s %-10.5f  = 14/5? %s"%(nm,v,abs(v-float(target))<1e-9))
print("   ==> *** the only thing equal to 14/5 is 2g/n_C itself -- i.e. Grace's number restated.")
print("       No sphere-volume or Poisson-kernel ratio I can construct reaches it independently. ***")

print("\n"+"="*104)
print("VERDICT -- LANE B")
print("="*104)
print(" (1) *** CAL'S RULE FIRES BEFORE THE COMPUTATION: the Poisson kernel is BUILT FROM the")
print("     Bergman/Szego kernel, which is the same object @Grace's restriction uses. *** So route 2")
print("     is not independent of route 1 -- two ratios through one metric. *** Even perfect")
print("     agreement would be one object agreeing with itself. The two-route test cannot be run")
print("     with this pair, and that is a structural fact, not a failure of effort. ***")
print()
print(" (2) *** AND THE FIX-vs-CHOOSE GATE FIRES TOO: the Bergman metric DIVERGES at the Shilov")
print("     boundary, and the CR structure supplies only a CONFORMAL CLASS -- not a metric, hence")
print("     not a ratio. *** Getting 14/5 requires picking a contact-form representative. That is a")
print("     CHOICE, which is exactly what §578 forbids as a derivation.")
print()
print(" (3) *** MY INSTRUCTION WAS 'land on 14/5 with no alpha input, or STOP'. I am STOPPING, ***")
print("     and for a better reason than failing to hit the number: the number cannot be reached")
print("     independently (Table 3 -- only 2g/n_C equals it, which is Grace's own input restated),")
print("     and the route is not independent in the first place.")
print()
print(" (4) SO LANE B, HONESTLY: *** the ruler-SHAPE has ONE route, not two, and that route rests on")
print("     a chosen normalization. *** It is not yet a derivation. The Casimir theorem (no length")
print("     from geometry) stands untouched, and the shape question stays open -- but it needs a")
print("     genuinely independent second construction, not a second reading of the same kernel.")
print()
print(" (5) WHAT WOULD BE A REAL SECOND ROUTE: something that does NOT pass through the Bergman/Szego")
print("     kernel at all -- e.g. a spectral ratio (my 5378 form-Laplacian numbers), or a heat-trace")
print("     coefficient ratio. Those are independent objects. *** I am naming the shelf, not")
print("     stocking it. ***")
