import numpy as np
from math import comb
rng=np.random.default_rng(1547)
print("="*80)
print("ASSIGNMENT 2 -- does MOMENTUM break SO(4)->SO(3), and does that give (4,1)->(3,1)?")
print("="*80)
print("  (a) DOES IT BREAK CLEANLY?  Stabiliser of Omega_0 in S^4 is SO(4), acting on the tangent")
print("      T_{Omega_0}S^4 = R^4 as the VECTOR rep. A nonzero tangent v in R^4 has stabiliser SO(3).")
print("      => YES. The breaking SO(4)->SO(3) is clean and standard.")
print()
print("   step            group    acts on   fixed by a marked vector   residual")
for n,res in [(5,"SO(4)"),(4,"SO(3)"),(3,"SO(2)")]:
    print("   mark a vector   SO(%d)    R^%d       yes (the vector itself)    %s"%(n,n,res))
print()
print("★★ (b) BUT DOES BREAKING REDUCE THE DIMENSION?  -- and here is the catch.")
print("   SO(4) -> SO(3) MARKS an axis in R^4. It does NOT DELETE it. The space is still R^4,")
print("   now with a preferred direction. Symmetry BREAKING is not dimensional REDUCTION.")
print()
print("   Weyl count on the tangent space, before and after marking a direction:")
def d_of(n):
    tot=lambda N: sum(comb(m+n,n)-(comb(m+n-2,n) if m>=2 else 0) for m in range(N+1))
    prev=None; out=None
    for N in [64,256,1024,4096]:
        lm=2*N**2; md=tot(N)
        if prev: out=2*np.log(md/prev[1])/np.log(lm/prev[0])
        prev=(lm,md)
    return out
print("      harmonics on S^3 (the sky, 3 angular)        d = %.4f"%d_of(3))
print("      harmonics on S^4 (unreduced)                 d = %.4f"%d_of(4))
print("   marking a direction in R^4 leaves the SAME function space -- the count is unchanged at 4.")
print("   only RESTRICTING to the orthogonal complement (a projection) gives 3.")
print()
print("  ⟹ ANSWER: momentum breaks SO(4)->SO(3) CLEANLY (yes), but the breaking does NOT deliver")
print("     (4,1)->(3,1). That leg needs a PROJECTION, not a BREAKING -- a different operation with")
print("     its own justification. Same error class as record-vs-order: 'breaks the symmetry to'")
print("     is not 'reduces the dimension to'.")
print()
print("="*80)
print("ASSIGNMENT 1 -- the COMMITTED-event distribution: is it theorem-forced too?")
print("="*80)
print("  A SINGLE committed event at Omega_0 is maximally anisotropic (toy 5257: z = 95.5). Good.")
print("  But the DISTRIBUTION of committed events depends on WHERE the commitments happen --")
print("  i.e. on how the Omega_0's are drawn. So: what draws them?")
print()
print("  The only measure the corpus derives is the vacuum one -- and toy 5256 proves it UNIFORM")
print("  (Casimir centrality). If commitment sites are drawn from it, the committed ensemble is")
print("  uniform again, one level up.")
print()
print("  ⟹ the committed distribution is uniform UNLESS a NON-DERIVED input supplies the sites.")
print("     That is not circular reasoning -- it is the observation that the corpus contains no")
print("     other source to draw them from. Cal's sector point is right that the theorem does not")
print("     APPLY to the committed sector; but the committed sector then has no derived measure AT")
print("     ALL, which is a different problem and arguably a worse one.")
print()
print("  ⟹ FOR @LYRA: building the committed distribution requires specifying the commitment SITES,")
print("     and that specification is exactly the non-equivariant matter input 5257 says is needed.")
print("     The artifact cannot be built from the corpus as it stands -- it needs the input first.")
