import numpy as np
print("="*92)
print("IS THE 2*pi*hbar CELL FORCED, OR FITTED?  Decompose the match term by term.")
print("="*92)
print("  N_BK(E,c) = [E log(E/c) - E + c] / (2 pi)")
print("            = (E/2pi)log E - (E/2pi)log c - E/2pi + c/2pi")
print("  N_RvM(T)  = (T/2pi)log T - (T/2pi)log(2pi) - T/2pi + 7/8\n")
print("  TERM BY TERM:")
print("   * E log E coefficient : 1/2pi both sides -- AUTOMATIC. Carries NO information about the cell.")
print("   * LINEAR in E         : -(log c + 1)/2pi  vs  -(log 2pi + 1)/2pi")
print("                           => forces log c = log 2pi  =>  c = 2pi.  ONE condition, ONE parameter.")
print("   * CONSTANT            : c/2pi = 1  vs  7/8   =>  RESIDUAL 1/8, NOT zero.\n")
print("  ⟹ THE CELL IS A ONE-PARAMETER FIT TO THE LINEAR TERM. It is not over-determined: there is")
print("     exactly one condition and exactly one knob. And after fitting, the constant is STILL wrong")
print("     by 1/8.")
print()
print("  ★ I MUST CORRECT MY OWN 5286 PHRASING. I wrote 'reproduces RvM EXACTLY to the constant' and")
print("    'including its subleading term'. The 0.1250 I measured IS the constant MISMATCH (1 - 7/8),")
print("    not agreement. The construction matches the log and the linear term (the latter by fitting")
print("    c) and MISSES the constant by 1/8. Berry-Keating attribute that 1/8 to a Maslov/boundary")
print("    phase. Stated correctly: two terms matched, one of them by fit, one term missed.")
print()
print("  HOW SHARP IS THE FIT? a cell wrong by a factor f shifts N by (T/2pi) log f -- LINEAR in T:")
for f in [1.01,1.1,2.0]:
    for T in [1e4]:
        print("     cell off by x%.2f  =>  error at T=1e4 is %8.1f  against N = %.1f  (%.2f%%)"%(
            f,(T/(2*np.pi))*np.log(f),(T/(2*np.pi))*np.log(T/(2*np.pi))-T/(2*np.pi)+7/8,
            100*(T/(2*np.pi))*np.log(f)/((T/(2*np.pi))*np.log(T/(2*np.pi))-T/(2*np.pi)+7/8)))
print("     => the fit is TIGHT (1% cell error is visible), but it is still a fit: one datum, one knob.")
print()
print("="*92)
print("DOES D_IV^5 FORCE IT?  Two checks.")
print("="*92)
print("  CHECK 1 -- what kind of statement is 'the cell is 2*pi*hbar'?")
print("    It is the UNCERTAINTY PRINCIPLE: one quantum of phase-space area. That is quantum mechanics,")
print("    and it was equally available to Berry-Keating in 1999. It is NOT a BST-specific derivation.")
print("    And BST does not derive hbar: the corpus states l_B = Planck length as an ANCHOR ('every")
print("    theory takes one dimensionful input', CLAUDE.md). An anchor is an input, not a forcing.")
print("    ⟹ BST does NOT force the cell. It anchors it, exactly as everyone else does.")
print()
print("  CHECK 2 -- could the log come from D_IV^5's own spectral theory instead?")
print("    The spherical Plancherel density on a rank-r symmetric space is |c(lambda)|^{-2}, a product")
print("    over positive roots with multiplicity; its total degree is dim(G/K) - rank.")
dimGK, rank = 10, 2
print("    D_IV^5:  dim(G/K) = %d, rank = %d  =>  Plancherel density ~ lambda^%d  -- POLYNOMIAL."%(dimGK,rank,dimGK-rank))
lam=np.array([1e1,1e2,1e3,1e4])
print("      lambda        lambda^8            log(lambda/2pi)/2pi")
for L in lam:
    print("      %7.0e     %12.3e            %.4f"%(L,L**8,np.log(L/(2*np.pi))/(2*np.pi)))
print("    ⟹ SECOND EXCLUSION, same shape as yesterday's: the dilation sector's OWN density is")
print("       polynomial too. The logarithm is NOT a spectral density of D_IV^5 -- at all.")
print()
print("  ★★ SO WHERE DOES THE LOG ACTUALLY COME FROM? The AREA OF THE CUTOFF REGION.")
print("     area{x>=lx, p>=lp, xp<=E} = E log(E/(lx lp)) - E + lx lp. The log is the geometry of a")
print("     HYPERBOLA under two cutoffs -- a BOUNDARY CONDITION, not an operator property.")
print("     ⟹ 'we derive the operator from D_IV^5' does not deliver RH's counting function, because")
print("        the counting function is not coming from the operator. It comes from the REGION.")
print("        The right question is not 'does D_IV^5 force the cell' but 'does D_IV^5 force the")
print("        CUTOFFS' -- and the cell is only the unit in which that area is measured.")
