import numpy as np
from math import log, exp, sqrt, degrees, atan2
from fractions import Fraction as F
print("="*104)
print("TOY 5407 -- LANE B: the equal-norm gate at the banked nu-addresses {5/2, 3/2, 0}.")
print("  *** RECONNECT FIRST: THIS GATE ALREADY RAN AND RETURNED NEGATIVE. ***")
print("    K1221 (2026-08-06): Koide FORCING ruled BREAK -- 'the addresses {5/2,3/2,0} can never be")
print("      B2-symmetric (no Weyl/isotropy mechanism)'.")
print("    Lyra F839: 'the position set is NOT Weyl-symmetric ... my derivation SUPPORTS Elie's")
print("      A^2 = 1.19, not 2.'")
print("  Confirm the number exactly, then close the lane with a MECHANISM rather than a 3rd datapoint.")
print("="*104)

nu=[F(5,2),F(3,2),F(0)]
me,mmu,mtau=0.51099895000,105.6583755,1776.86

def stats(rt):
    rt=np.asarray(rt,dtype=float)
    Q=(rt**2).sum()/rt.sum()**2
    dem=np.full(len(rt),rt.mean()); hier=rt-dem
    th=degrees(atan2(np.linalg.norm(hier),np.linalg.norm(dem)))
    A2=2*np.sum(hier**2)/(len(rt)*rt.mean()**2)
    return Q,th,A2

print("\nTABLE 1 -- *** READING 1 (the direct one): sqrt(m_k) proportional to nu_k ***")
s=sum(nu); s2=sum(x*x for x in nu)
Qex=s2/(s*s)
Q,th,A2=stats([float(x) for x in nu])
print("   addresses nu        = {5/2, 3/2, 0}")
print("   Sum nu = %s , Sum nu^2 = %s  ->  Q = %s = %.6f"%(s,s2,Qex,float(Qex)))
print("   A^2 = 6Q - 2 = %s = %.6f"%(6*Qex-2,float(6*Qex-2)))
print("   tilt theta          = %.4f deg"%th)
print("   *** A^2 = 19/16 = 1.1875 -- EXACTLY the 'Elie's A^2 = 1.19' that F839 cites. CONFIRMED. ***")
print("   *** EQUAL-NORM REQUIRES A^2 = 2 and theta = 45. WE GET 1.1875 and %.2f. THE GATE FAILS. ***"%th)
print("   Not a near miss: A^2 is %.0f%% low, theta is %.1f deg off."%(100*(1-float(6*Qex-2)/2),45-th))

print("\nTABLE 2 -- *** READING 2 (target-innocent forward test): sqrt(m) ~ exp(c*nu) ***")
print("   Fix c from ONE ratio (tau/e), then PREDICT the muon. No Koide input anywhere.")
c=log(mtau/me)/(2*(2.5-0.0))
pred_mu_over_e=exp(2*c*(1.5-0.0))
obs=mmu/me
print("   c fitted on m_tau/m_e only : c = ln(%.1f)/5 = %.6f"%(mtau/me,c))
print("   PREDICT m_mu/m_e           = exp(3c) = %.2f"%pred_mu_over_e)
print("   OBSERVED m_mu/m_e          = %.2f"%obs)
print("   *** MISS = %.1f%%. *** An exponential map on the banked addresses does NOT reproduce the"%(100*abs(pred_mu_over_e-obs)/obs))
print("       lepton hierarchy either. (And its Q would follow from that miss, so nothing is rescued.)")
rt=np.array([exp(c*float(x)) for x in nu]); Q2,th2,A22=stats(rt)
print("   for the record, that map's Q = %.4f, theta = %.2f deg, A^2 = %.4f"%(Q2,th2,A22))

print("\nTABLE 3 -- ★★★ *** THE STRUCTURAL POINT THAT CLOSES THE LANE (not another datapoint) ***")
print("   Suppose sqrt(m_k) = f(nu_k) for SOME map f. There are THREE addresses, so f contributes")
print("   THREE INDEPENDENT VALUES f(5/2), f(3/2), f(0) -- completely unconstrained.")
print("   *** THREE FREE VALUES REPRODUCE ANY THREE MASSES. SO THE ADDRESSES ALONE CARRY NO")
print("       PREDICTIVE CONTENT -- the gate can only bite if the MAP f is FORCED. ***")
print("   Demonstration: solve for the f-values that hit equal-norm exactly, and see they are free:")
tgt=np.array([sqrt(me),sqrt(mmu),sqrt(mtau)])
Qo,tho,A2o=stats(tgt)
print("     observed sqrt-masses      : %s"%np.round(tgt,4))
print("     observed Q = %.8f, theta = %.4f deg, A^2 = %.5f  <- the DATA sits on equal-norm"%(Qo,tho,A2o))
print("     required f-values (up to scale, normalised to Sum = 4 like the addresses):")
print("       %s   vs the addresses  {2.5, 1.5, 0}"%np.round(4*tgt/tgt.sum(),4))
print("   *** The required values are NOT the addresses and are not close to them. And since f is")
print("       unconstrained, NO information flows from {5/2,3/2,0} to the masses at all. ***")

print("\nTABLE 4 -- the second, independent closure (my own 5356, reconnected)")
print("   5356 asked whether a single address->mass MAP exists at all, and found it does not:")
print("     m_mu/m_e = (24/pi^2)^{C_2}  (a volume ratio to a power)")
print("     m_tau/m_e = 49*71           (a product of two primes)")
print("   *** share no structure, and neither extends to the other. *** So 'derive the map'")
print("   presupposes a map. ==> the gate is closed TWICE, on independent grounds:")
print("     (a) K1221/F839 -- the addresses are not Weyl-symmetric, so no isotropy FORCES equal-norm;")
print("     (b) 5356 + Table 3 -- even granting the addresses, no forced MAP exists, and an")
print("         unforced map has exactly enough freedom to fit anything.")

print("\n"+"="*104); print("VERDICT -- Lane B, the equal-norm gate"); print("="*104)
print(" (1) ★★★ *** CLEAN 'NOT YET' -- AND IT IS ALREADY A RECORDED NEGATIVE, NOT A NEW ONE. *** At the")
print("     banked addresses {5/2,3/2,0} the direct reading gives *** A^2 = 19/16 = 1.1875 and")
print("     theta = %.2f deg *** where equal-norm needs 2 and 45. Exactly reproduces the 'A^2 = 1.19'"%th)
print("     Lyra's F839 cites. K1221 ruled this BREAK on 2026-08-06.")
print()
print(" (2) *** THE EXPONENTIAL MAP FAILS TOO, TESTED TARGET-INNOCENTLY: *** fit c on m_tau/m_e alone,")
print("     predict the muon -> %.1f%% miss. Nothing is rescued by changing the map's shape."%(100*abs(pred_mu_over_e-obs)/obs))
print()
print(" (3) ★★★★ *** THE MECHANISM THAT CLOSES THE LANE: three addresses + an unforced map f = THREE")
print("     FREE VALUES = enough to fit any three masses. *** So the addresses carry NO predictive")
print("     content by themselves. The gate can only bite if f is FORCED -- and my 5356 already")
print("     showed no single f exists (the mu and tau forms share no structure).")
print("     ==> *** CLOSED TWICE, INDEPENDENTLY: no isotropy (K1221/F839), and no forced map (5356). ***")
print()
print(" (4) *** KOIDE STAYS WHERE CASEY PUT IT: Conditional-Forced in the MASS sector, displayed")
print("     honestly, leading the negatives. *** The relation Q = 2/3 (0.0009%) stays banked; the")
print("     DERIVATION does not. The rank route died 2026-08-16; the equal-norm route is closed here.")
print()
print(" (5) ★ WHAT WOULD REOPEN IT (so the lane is closed, not abandoned): a FORCED map from address")
print("     to sqrt-mass, derived before looking at any mass. *** Absent that, every address-based")
print("     Koide derivation has exactly as many free values as masses to explain. ***")
print()
print(" (6) MISS OWNED: second assigned target this morning that the corpus had already settled.")
print("     Both cost ~2 minutes of grep instead of a day of derivation.")
