from fractions import Fraction as F
print("="*104)
print("TOY 5382 -- WHAT ELSE IS R^4-VALID FROM THE FIELDED GAUGED OPERATOR?")
print("  *** SPACE, LINE ONE: R^4 -- these are LOCAL invariants, valid on flat non-compact space. ***")
print("="*104)

print("\nTABLE 1 -- *** WHY a_2 spans the fault line, made precise ***")
print("   heat-kernel coefficients are INTEGRALS OF LOCAL CURVATURE INVARIANTS at a point.")
print("   they contain no global data: no topology, no compactness, no boundary conditions.")
print("   quantity                       depends on compactness?   R^4-valid?")
for q,dep,val in [("a_2's F^2 term (the beta-function)","NO -- local","*** YES ***"),
            ("a_2's curvature-squared terms","NO -- local","*** YES ***"),
            ("the KK gap 6/a^2","YES -- dies as a -> inf","no"),
            ("the Polyakov mode at 10","YES -- needs the S^1","no")]:
    print("   %-31s %-24s %s"%(q,dep,val))
print("   ==> *** that IS the fault line: local invariants cross to R^4; spectral gaps on a compact")
print("       space do not. a_2/AF crosses because it is LOCAL, not because we were lucky. ***")

print("\nTABLE 2 -- so what ELSE does the SAME local bracket give?")
print("   a_2 = (1/360)[... + 180 E^2 + 30 Omega^2 + (12 R_;kk + 5R^2 - 2 R_ij^2 + 2 R_ijkl^2) Id]")
print("   I used ONLY the F^2 (Omega^2 + E^2) piece for the beta-function. The CURVATURE-SQUARED")
print("   piece is untouched -- and it is *** the TRACE (conformal) ANOMALY. ***")
print("   local, R^4-valid object        physics it carries")
print("   trace anomaly a, c             central charges; the a-THEOREM (irreversibility of RG flow)")
print("   chiral anomaly                 index theorem, pi^0 -> gamma gamma")
print("   Euler density term             topological, Gauss-Bonnet")

print("\nTABLE 3 -- *** INSTRUMENT CHECK: reproduce the conformal scalar's (a,c) exactly ***")
print("   conformal scalar: E = -R/6, tr(Id) = 1")
r2=F(5)+F(60)*F(-1,6)+F(180)*F(1,36)
print("   R^2 coefficient  : 5 + 60(-1/6) + 180(1/36) = %s"%r2)
print("   R_ij^2 coefficient: -2      R_ijkl^2 coefficient: +2")
print("   now express in the (E_4, W^2) basis:")
print("      E_4 = R_ijkl^2 - 4 R_ij^2 + R^2      W^2 = R_ijkl^2 - 2 R_ij^2 + R^2/3")
# solve alpha E4 + beta W2 = 2 Rijkl^2 - 2 Rij^2 + 0 R^2
import numpy as np
A=np.array([[1,1],[-4,-2],[1,F(1,3)]],dtype=float); b=np.array([2,-2,0],dtype=float)
sol,res,rk,sv=np.linalg.lstsq(A,b,rcond=None)
al,be=sol
print("      solve:  alpha = %.4f, beta = %.4f   (residual %.2e)"%(al,be,np.linalg.norm(A@sol-b)))
print("   ==> a_2 = (1/360)[ %.0f E_4 + %.0f W^2 ]"%(al,be))
print("   ==> *** in <T> = c W^2 - a E_4 :  a : c = 1 : 3, in units of 1/360. ***")
print("       the standard conformal-scalar values are a = 1, c = 3 in exactly those units.")
print("   *** INSTRUMENT VALIDATED on a case with a known answer. ***")

print("\nTABLE 4 -- the targets the same bracket should give (NOT yet computed here)")
print("   field            a (units 1/360)   c (units 1/120)")
for nm,a,c in [("real scalar","1","1"),("Weyl fermion","11/2","3"),("vector","62","12")]:
    print("   %-16s %-17s %s"%(nm,a,c))
print("   *** NOTE the 11 in the Weyl fermion's a-coefficient. It is NOT the beta-function's 11 N_c/3")
print("       -- different construction, different object. FLAGGING, not identifying. ***")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) ***** THE REASON a_2/AF CROSSES TO R^4 IS THAT IT IS *LOCAL*, AND THAT IS THE WHOLE")
print("     FAULT LINE. ***** Heat-kernel coefficients are integrals of pointwise curvature")
print("     invariants -- no topology, no compactness, no boundary conditions. The KK gap 6/a^2 and")
print("     the Polyakov mode at 10 are spectral facts about a COMPACT space and die under")
print("     decompactification; the beta-function does not. *** That is the honest criterion for")
print("     what ships as R^4 physics, and it is checkable per-quantity, not a matter of taste. ***")
print()
print(" (2) *** AND THE SAME BRACKET HAS AN UNTOUCHED HALF: the curvature-squared terms, which are")
print("     the TRACE ANOMALY (a, c). *** I used only the F^2 piece for the beta-function. The")
print("     curvature piece carries the central charges and the a-THEOREM -- irreversibility of RG")
print("     flow, a genuinely deep R^4 result, and it is sitting in machinery we have already")
print("     validated four ways.")
print()
print(" (3) *** INSTRUMENT VALIDATED: I reproduced the conformal scalar's anomaly ratio a : c = 1 : 3")
print("     exactly *** from the same 360-bracket, by solving in the (E_4, W^2) basis. So the route")
print("     is open, not speculative.")
print()
print(" (4) NOT YET COMPUTED, AND I AM NOT CLAIMING IT: the fermion (11/2, 3) and vector (62, 12)")
print("     coefficients. Those are the next blind targets, and they are the natural continuation of")
print("     5369/5371/5372.")
print()
print(" (5) *** SHARED-INTEGER FLAG: the Weyl fermion's a-coefficient contains an 11, and so does the")
print("     beta-function's 11 N_c/3. DIFFERENT CONSTRUCTIONS. I am not identifying them *** -- and")
print("     per 5381, this pair would need a PHYSICS variation to separate, not an n-sweep.")
