#!/usr/bin/env python3
"""
Toy 5421 — LANE B PIVOT: off the Diracs, onto the operator that carries the spectrum.

THE ASK (Round 34): run the reading D^2 can't carry onto the operators that can —
start with the Bergman/Szego kernel (exponent n_C = 5, K1761). Positive-controlled.

WHAT I FOUND, in order of value:

  (1) K671's GATE — open since 2026-07-11 on a result that has since SHIPPED as Derived —
      CLOSES. Keeper: "Lyra used the SCALAR rising factorial; the FK generalized Pochhammer
      for a rank-2 domain is a TWO-FACTOR product. Verify which object is correct for
      rank-2 D_IV^5 — the numbers (and the 20) depend on it. Until verified: F506 is a
      strong candidate, NOT a bank."
      ⟹ On SINGLE-ROW K-types the second factor is (.)_0 = 1, so the two-factor form
        reduces EXACTLY to the scalar one. The 20 was never at risk — for a structural
        reason, not by luck. And the check is NOT vacuous: at two-row lambda they differ.

  (2) THE OPERATOR-LEVEL STATEMENT — why BOTH Diracs failed, in one sentence:
      the ladder operator is NOT in the polynomial algebra generated by the Casimir.
      Kostant D^2 and Parthasarathy D^2 both ARE Casimir polynomials (degree 0 and 1 in
      the Casimir). The FK Pochhammer is not a polynomial in it at all.

  (3) CLASS-WIDE EXCLUSION, generalising toy 5419 from one operator to the whole family:
      for P(k) = k(k+a), ANY a > -1, and ANY positivity-preserving shift c,
             sup b/s = 10/3 = 3.33      required b/s = 42.
      5419 killed the Parthasarathy Dirac; this kills every Casimir-graded operator.

  (4) A LIVE SYMBOL COLLISION flagged, not resolved: K1012 says the down modes sit at
      "Bergman weight nu = 5"; F506/K671 use nu = N_c = 3. These are not interchangeable —
      they give s/d = 42 and s/d = 20. Only 20 matches. Flagging to Keeper.

Exact rationals throughout (Fraction), per the Toy 395 lesson.
"""

from fractions import Fraction as F

N_c, n_C, rank = 3, 5, 2
a_FK = n_C - 2                      # Faraut-Korányi multiplicity a = n_C - 2 = 3
DEGREES = (1, 3, 5)                 # T1929, forced, blind
OBS_SD, OBS_BS = F(934, 10) / F(467, 100), F(4180) / F(934, 10)

def rising(x, k):
    out = F(1)
    for j in range(k):
        out *= (x + j)
    return out

def fk_scalar(nu, lam):
    """The SCALAR rising factorial Lyra used."""
    return rising(F(nu), lam[0]) if len(lam) == 1 or lam[1] == 0 else None

def fk_rank2(nu, lam):
    """The genuine rank-2 FK generalized Pochhammer:
           (nu)_lambda = prod_{j=1..r} ( nu - (j-1)*a/2 )_{lambda_j}
       with r = rank = 2 and a = n_C - 2 = 3."""
    out = F(1)
    for j, lj in enumerate(lam):
        out *= rising(F(nu) - F(j * a_FK, 2), lj)
    return out

def ratios(v):
    return v[1] / v[0], v[2] / v[1]

# ================================================================ (1) K671 GATE
print("=" * 78)
print("SECTION 1 — K671's OPEN GATE: scalar vs rank-2 two-factor FK Pochhammer")
print("=" * 78)
print(f"rank r = {rank},  FK multiplicity a = n_C - 2 = {a_FK},  shift per rank direction = a/2 = {F(a_FK,2)}")
print(f"\n(nu)_lambda = (nu)_(lambda_1) * (nu - {F(a_FK,2)})_(lambda_2)\n")
print(f"{'lambda':>12s} {'scalar form':>14s} {'rank-2 form':>14s} {'agree?':>8s}   note")
print("-" * 78)
single_ok = True
for k in DEGREES:
    lam = (k, 0)
    s, r2 = fk_scalar(N_c, lam), fk_rank2(N_c, lam)
    ok = (s == r2)
    single_ok &= ok
    print(f"{str(lam):>12s} {str(s):>14s} {str(r2):>14s} {'YES' if ok else 'NO':>8s}   "
          f"second factor = (.)_0 = 1")
print()
# NON-VACUITY: the gate was a real question — two-row lambda genuinely differs.
nonvacuous = []
for lam in [(1, 1), (3, 1), (3, 2), (5, 1)]:
    r2 = fk_rank2(N_c, lam)
    s_only = rising(F(N_c), lam[0])                       # what the scalar form would give
    nonvacuous.append(r2 != s_only)
    print(f"{str(lam):>12s} {str(s_only):>14s} {str(r2):>14s} "
          f"{'YES' if r2 == s_only else 'NO':>8s}   two-row: forms DIFFER")
gate_nonvacuous = all(nonvacuous)
print()
print(f"★★★ K671 GATE: on SINGLE-ROW K-types the two forms agree EXACTLY  ->  {single_ok}")
print(f"    and the check is NON-VACUOUS (two-row lambda differ)          ->  {gate_nonvacuous}")
print("⟹ The down modes are single-row (K1012). The second Pochhammer is EMPTY.")
print("⟹ s/d = 20 does NOT depend on the scalar-vs-two-factor choice. GATE CLOSES AFFIRMATIVE.")

# ================================================================ (4) SYMBOL COLLISION
print()
print("=" * 78)
print("SECTION 2 — SYMBOL COLLISION: which nu? (flagging, not resolving)")
print("=" * 78)
print(f"{'source':>34s} {'nu':>4s} {'s/d = (nu+1)(nu+2)':>20s} {'vs obs 20.0':>13s}")
print("-" * 78)
coll = []
for src, nu in [("F506 / K671 (Wallach threshold)", N_c), ("K1012 ('Bergman weight nu=5')", n_C)]:
    lad = [fk_rank2(nu, (k, 0)) for k in DEGREES]
    sd, bs = ratios(lad)
    coll.append((src, nu, sd, bs))
    print(f"{src:>34s} {nu:>4d} {float(sd):>20.4f} {float(sd/OBS_SD):>12.2f}x")
print()
print("★ The two labels give 20 and 42 — the SAME functional form (x+1)(x+2) at different x.")
print("  Only nu = N_c = 3 matches observation. So K1012's 'nu = 5' cannot be the Pochhammer")
print("  parameter; it must be the Bergman genus/exponent (K1761, n_C = 5) — a DIFFERENT")
print("  parameter wearing the same letter.  @Keeper: same-name collision, subscript it.")

# ================================================================ (2) THE OPERATOR
print()
print("=" * 78)
print("SECTION 3 — THE OPERATOR: is the ladder a POLYNOMIAL IN THE CASIMIR?")
print("=" * 78)
print("Casimir eigenvalue on the single-row K-type of degree k:  C(k) = k(k+n_C) = k(k+5)")
print("Ladder eigenvalue (FK Pochhammer at nu=N_c):              L(k) = (3)_k")
print()
print(f"{'k':>3s} {'C(k)':>8s} {'L(k)':>12s}")
print("-" * 78)
KFIT = 7
C = [F(k * (k + n_C)) for k in range(KFIT + 2)]
L = [rising(F(N_c), k) for k in range(KFIT + 2)]
for k in range(KFIT + 2):
    print(f"{k:>3d} {str(C[k]):>8s} {str(L[k]):>12s}")

def interp(xs, ys, x):
    """Exact Lagrange interpolation."""
    tot = F(0)
    for i, xi in enumerate(xs):
        term = ys[i]
        for j, xj in enumerate(xs):
            if i != j:
                term *= (x - xj) / (xi - xj)
        tot += term
    return tot

print()
print("Fit a degree-D polynomial p with p(C(k)) = L(k) on k = 0..D, then TEST it at k = D+1:")
print(f"{'D':>3s} {'p(C(D+1))':>16s} {'L(D+1)':>16s} {'ratio':>10s} {'extrapolates?':>15s}")
print("-" * 78)
poly_fails = True
for D in range(2, KFIT):
    xs, ys = C[:D + 1], L[:D + 1]
    if len(set(xs)) != len(xs):
        continue
    pred = interp(xs, ys, C[D + 1])
    good = (pred == L[D + 1])
    poly_fails &= (not good)
    print(f"{D:>3d} {str(pred):>16s} {str(L[D+1]):>16s} "
          f"{float(pred/L[D+1]):>10.4f} {'YES' if good else 'NO':>15s}")
print()
print("★★★ Every fixed degree fails at the next point. A polynomial of degree D is pinned by")
print("    D+1 values and then MUST extrapolate; the Pochhammer never lets it.")
print("⟹ THE LADDER OPERATOR IS NOT IN THE POLYNOMIAL ALGEBRA GENERATED BY THE CASIMIR.")
print("⟹ And BOTH excluded Diracs ARE Casimir polynomials:")
print("      Kostant cubic D^2      = 25/4                  (degree 0 — flat, toy 5418)")
print("      Parthasarathy D^2      = C(k) - c              (degree 1 — toy 5419)")
print("★★ That is ONE sentence explaining two rounds of negatives, at the operator level.")

# ================================================================ (3) CLASS-WIDE BOUND
print()
print("=" * 78)
print("SECTION 4 — CLASS-WIDE EXCLUSION (generalises toy 5419's bound)")
print("=" * 78)
print("Take ANY Casimir-type grading P(k) = k(k+a) with a > -1, and ANY shift c with")
print("c < P(1) = 1+a (positivity of the lightest mass). Then")
print("      b/s(c) = (P(5)-c)/(P(3)-c)  is increasing in c,  so   sup = (P(5)-P(1))/(P(3)-P(1))")
print("                                                            = (24+4a)/(8+2a) = 2(6+a)/(4+a)")
print("which is DECREASING in a, so the supremum over the whole family is at a -> -1+.")
print()
print(f"{'a':>8s} {'P(1)':>7s} {'P(3)':>7s} {'P(5)':>7s} {'sup b/s':>10s}")
print("-" * 78)
sup_vals = []
for a in [F(-9, 10), F(0), F(1), F(3), F(5), F(10), F(100)]:
    p1, p3, p5 = a + 1, 3 * (3 + a), 5 * (5 + a)
    sup = (p5 - p1) / (p3 - p1)
    sup_vals.append(sup)
    tag = "  <- n_C = 5 : the Parthasarathy case, toy 5419 (22/9)" if a == 5 else ""
    print(f"{float(a):>8.2f} {float(p1):>7.2f} {float(p3):>7.2f} {float(p5):>7.2f} {float(sup):>10.4f}{tag}")
class_sup = F(10, 3)
print()
print(f"★★★ analytic supremum over the ENTIRE two-parameter class:  lim_(a->-1+) 2(6+a)/(4+a) "
      f"= 10/3 = {float(class_sup):.4f}")
print(f"★★★ REQUIRED b/s = 42.   SHORTFALL: a factor of {float(F(42)/class_sup):.1f}, class-wide.")
class_dead = all(s < 42 for s in sup_vals) and class_sup < 42
print("⟹ NO Casimir-graded operator on D_IV^5 can grade the quark ladder — not the two Diracs,")
print("   and not any other. Toy 5419 killed one operator; this kills the class.")

# ================================================================ SHARPNESS OF nu
print()
print("=" * 78)
print("SECTION 5 — LOOK-ELSEWHERE: how sharply is nu = N_c selected?")
print("=" * 78)
print("(This RE-VERIFIES K671/K993 with the sharpness quantified. It is NOT a new hit —")
print(" F506 banked the ladder in July. Reporting it as new would be double-counting.)")
print()
print(f"{'nu':>4s} {'s/d':>10s} {'b/s':>10s} {'s/d within 10%?':>17s} {'b/s within 10%?':>17s}")
print("-" * 78)
sel = []
for nu in range(1, 13):
    lad = [fk_rank2(nu, (k, 0)) for k in DEGREES]
    sd, bs = ratios(lad)
    ok_sd = abs(sd - OBS_SD) / OBS_SD <= F(1, 10)
    ok_bs = abs(bs - OBS_BS) / OBS_BS <= F(1, 10)
    if ok_sd and ok_bs:
        sel.append(nu)
    print(f"{nu:>4d} {float(sd):>10.3f} {float(bs):>10.3f} {str(ok_sd):>17s} {str(ok_bs):>17s}")
print()
print(f"★ integer nu satisfying BOTH ratios at 10%: {sel}   (count = {len(sel)} of 12 swept)")
print(f"★ and nu = N_c = 3 is FORCED independently (Wallach threshold), not selected by the fit.")
nu_sharp = (sel == [N_c])

# ================================================================ SCORE
print()
print("=" * 78)
checks = [
    ("K671 gate: two-factor == scalar on single-row K-types", single_ok),
    ("K671 gate check is NON-VACUOUS (two-row forms differ)", gate_nonvacuous),
    ("nu=3 and nu=5 give different ladders (collision is real)",
     coll[0][2] != coll[1][2]),
    ("only nu = N_c = 3 matches the observed s/d", abs(coll[0][2] - OBS_SD) / OBS_SD < F(1, 10)),
    ("ladder is NOT a polynomial in the Casimir (every degree fails)", poly_fails),
    ("class-wide sup b/s = 10/3 < 42 for every a > -1 and every shift", class_dead),
    ("the a = n_C = 5 row reproduces toy 5419's 22/9", sup_vals[4] == F(22, 9)),
    ("integer nu uniquely selected by both ratios", nu_sharp),
]
for name, ok in checks:
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
score = sum(1 for _, ok in checks if ok)
print(f"\nSCORE: {score}/{len(checks)}")
print()
print("VERDICT — the pivot lands, and it explains the two negatives instead of replacing them:")
print("  The ladder IS an operator statement: the FK Pochhammer is the eigenvalue of a diagonal")
print("  operator on the K-type decomposition of the Bergman space. What makes it able to do")
print("  what the Diracs cannot is not size but ALGEBRA — it is not a polynomial in the Casimir,")
print("  and every Casimir-graded operator is bounded at b/s <= 10/3 against a required 42.")
print("  Kostant (degree 0) and Parthasarathy (degree 1) were two points in a class that was")
print("  excluded whole. And K671's month-old rank-2 gate, on a result already shipped as")
print("  Derived, closes affirmative: on single-row K-types the second Pochhammer is empty.")
