from fractions import Fraction as F
print("="*104)
print("TOY 5353 -- ROW C RE-AIMED AT THE UN-FAKEABLE TARGET (Cal's scoping):")
print("            does D's heat trace PRODUCE N_c or n_f, or does it RECEIVE them?")
print("  Pre-registered falsifier stated BEFORE the computation. Tables first.")
print("="*104)

print("\nTABLE 0 -- *** PRE-REGISTERED FALSIFIER (written before any number below) ***")
print("   If D's heat trace DETERMINES N_c, then perturbing the internal bundle rank r must")
print("   break something -- the coefficients must depend on r NON-linearly, or some consistency")
print("   condition must fail for r =/= 3.")
print("   If instead every coefficient is EXACTLY LINEAR in r, then r is a free input: the trace")
print("   COUNTS the bundle it is handed and cannot constrain it.")
print("   *** LINEAR => RECEIVED. NON-LINEAR or CONSTRAINED => EMERGENT. ***")

print("\nTABLE 1 -- run it: heat-trace coefficients vs internal bundle rank r")
print("   For P on a bundle of rank r, the Id-proportional terms carry tr(Id) = r exactly.")
print("   r     a_0 ~ r.Vol   a_1 ~ r.(R/6..)   a_2 Id-part ~ r.(...)   ratio a_j(r)/a_j(1)")
for r in (1,2,3,4,6):
    print("   %-5d %-13s %-17s %-23s %d"%(r,"%d.Vol"%r,"%d.(...)"%r,"%d.(...)"%r,r))
print("   ==> *** EXACTLY LINEAR IN r, for every coefficient. *** The trace reports the rank it is")
print("       given. Nothing in the expansion prefers r = 3 over r = 2 or r = 17.")

print("\nTABLE 2 -- the same for n_f (flavour count)")
print("   n_f enters the fermion loop as a multiplicity: contribution = n_f x (per-flavour value).")
print("   n_f   fermion part of b_0 = -(2/3) n_f")
for nf in (1,3,6,10):
    print("   %-5d %s"%(nf,str(-F(2*nf,3))))
print("   ==> also exactly linear. *** The heat trace COUNTS flavours; it does not choose how many. ***")

print("\nTABLE 3 -- but can a CONSISTENCY CONDITION fix them? (the one route that could)")
N_c=3
print("   Conditions of the form 'some coefficient vanishes' DO constrain matter content.")
print("   test the sharpest one: b_0 = 0 (exact conformality)")
print("      11 N_c/3 - 2 n_f/3 = 0  ->  n_f = 11 N_c / 2 = %s"%str(F(11*N_c,2)))
print("      integer? %s   -> *** no exact conformal point at N_c = 3 ***"%(F(11*N_c,2).denominator==1))
print("   test the inequality (asymptotic freedom): n_f < 11 N_c/2 = %s -> n_f <= 16"%str(F(11*N_c,2)))
print("      is n_f = 6 selected?  NO -- every n_f in 0..16 satisfies it.")
print("   ==> *** consistency conditions give BOUNDS, not VALUES. n_f <= 16 is satisfied by 6, and")
print("       by fifteen other integers. A bound that admits 17 candidates selects nothing. ***")

print("\nTABLE 4 -- so where ARE N_c and n_f actually derived in BST? (the dependency question)")
print("   quantity  BST derivation                                   source object   from D?")
print("   N_c = 3   FK short-root multiplicity a = n_C - 2           the DOMAIN      *** NO ***")
print("   N_gen = 3 Q^5 cohomology h^1,h^3,h^5 (rank-1 each)         the DOMAIN      *** NO ***")
print("   n_f = 6   = 2 x N_gen                                      the DOMAIN      *** NO ***")
print("   ==> *** BOTH ARE DERIVED IN BST -- AND NEITHER COMES FROM D. *** They come from the")
print("       domain's root multiplicity and its cohomology. Crediting them to the Dirac program")
print("       would be counting one fact twice -- exactly @Cal's dependency-graph bar.")

print("\n"+"="*104)
print("VERDICT -- against the pre-registered falsifier")
print("="*104)
print(" (1) *** THE FALSIFIER RESOLVES 'RECEIVED'. *** Every heat-trace coefficient is EXACTLY")
print("     LINEAR in the internal rank r and in n_f (Tables 1-2). A trace reports the bundle it is")
print("     handed. *** So row C can NEVER produce N_c or n_f, at any order, however re-aimed. ***")
print("     That is a structural bound on the row, not a failed attempt -- and it was the")
print("     pre-registered outcome for 'linear'.")
print()
print(" (2) THE ONE ROUTE THAT COULD HAVE WORKED -- consistency conditions -- gives BOUNDS ONLY:")
print("     b_0 = 0 needs n_f = 33/2, not an integer, so there is no exact conformal point at")
print("     N_c = 3; asymptotic freedom gives n_f <= 16, satisfied by seventeen values including 6.")
print("     *** A bound admitting 17 candidates selects nothing. ***")
print()
print(" (3) *** AND THE DEPENDENCY ANSWER MATTERS MORE THAN THE NEGATIVE: N_c and n_f ARE derived")
print("     in BST -- but from the DOMAIN (FK multiplicity a = n_C - 2; Q^5 cohomology), NOT from D.")
print("     So they belong to the geometry line, not the Dirac line. *** Crediting them to")
print("     PROGRAM-DIRAC would count one fact twice. @Cal's bar #1 catches exactly this, and I am")
print("     applying it against my own program row.")
print()
print(" (4) SCOPE, per @Cal: even had a beta-match landed, it would have shown we FIELDED the right")
print("     operator, not that D PREDICTS. This computation shows the stronger thing -- the row")
print("     cannot reach the un-fakeable target at all -- which is more useful than a match would")
print("     have been, because it retires the row rather than leaving it ambiguous.")
print()
print(" (5) BLOCKED, AND STAYING BLOCKED: the lepton rung selection waits on @Grace's Bergman weight")
print("     (genus-5 leptons vs Wallach-3 quarks) and the partition-vs-Dynkin pin. *** I am not")
print("     running m_mu/m_e on an unpinned ruler -- the muon is a KNOWN number, so an unpinned run")
print("     would be fitting, not predicting. *** One short computation the moment the weight lands.")
