import numpy as np
exec(open('parallax.py').read().split('print("  PARALLAX')[0])
print("SIDE-CHECK 2 -- is f_max ~ 156 corpus-connected, or an artefact? (no-wave-through)")
print()
print("  My 5270/5271 construction fixes an off-axis sky angle phi. If f_max depends on phi,")
print("  it is not a constant of S^4 at all -- let alone a BST number.")
print()
print("   phi      f_max        f_median")
for phi in [0.2,0.4,0.6,0.8,1.0,1.4]:
    Ds=np.linspace(0.02,3.12,3000)
    f=np.array([parallax(0.01,D,phi=phi)/0.01 for D in Ds])
    print("   %.2f     %8.1f     %.3f"%(phi,np.nanmax(f),np.nanmedian(f)))
print()
print("  => f_max varies STRONGLY with phi. It is NOT a geometric constant of S^4 and NOT a number.")
print("     156 was MY construction's value at phi=0.6, nothing more. DO NOT BANK IT, and the")
print("     '156x stricter' phrasing in my 5271 should read 'order 10^2, construction-dependent'.")
print()
print("  ⟹ the ROBUST content is only: f_max is FINITE and >> 1, so the bound b < sigma/f_max")
print("     is achievable but substantially stricter than the naive b < sigma. No BST integer here.")
print()
print("SIDE-CHECK 1 -- is  v*Delta_tau < sigma/f_max  FORCED by the commit tick?")
print("  This needs the dynamics to BOUND observer motion per tick. exp(-tau H_B) generates the")
print("  tick, but nothing in the corpus attaches a VELOCITY to an observer -- and toy 5267 already")
print("  showed #16 does not characterise an observer at all. => NOT FORCED, and not currently")
print("  forceable from what is banked. Same missing premise as Gate 3.")
