#!/usr/bin/env python3
"""
Toy 4817 — Jul 23 (steady the muon: Casey's climb reading revives the exponent-6 source; hold the E2b gate, don't
over-swing; Elie, pull 23t). The muon has swung hard today: over-claimed derived (morning) → walked back → Lyra's honest
NEGATIVE (residue ratio = 3/2, not 206, so "exponent 6 has no source") → Casey caught that the 3/2 is the INDEX, not the
mass, and the mass is the Born-squared climb genus 0→3, exponent 6. After TWO peak-convergence over-swings today (Grace's
over-stop, Lyra's over-negative), my job as verifier is the STEADY middle: verify the checkable arithmetic of the climb
reading, and hold the one open gate (E2b) firmly — NOT over-swinging to "derived" NOR back to "dead."

THE CLIMB-READING ARITHMETIC (verified, mostly-forced):
  * 24 = Γ(2ν+2) = Γ(5) = 24, with ν=3/2 the muon INDEX — so the index 3/2 REGENERATES the 24 (it's not a separate
    coincidence). And 24 = (1)₄ = 4! = a Pochhammer LADDER product.
  * exponent 6 = 2 × span(genus 0 → genus 3) = 2 × N_c = 6 — Born-SQUARED (the ×2) climb over the muon's N_c genus levels.
    OVER-DETERMINED: 2·N_c = C_2 = n_C+1 = 6 (three readings, one value).
  * the genus-0 START is FORCED (not chosen): D_IV¹ has FK parameter a = n−2 = −1 (a degenerate disk, no real genus-1
    level) — the SAME forcing (#3) that made the tower {5,3,0} not {5,3,1} this afternoon. So the filtration bottoms at the
    genus-0 point, the climb spans 0→3, and 6 falls out of the structure. genus 1→3 would give 4; the structure picks 0.
  ⟹ the exponent 6 has a MOSTLY-FORCED source (2×N_c, Born-squared, genus-0 start FK-forced), and 24 is regenerated by the
  index. Lyra's K859 "no source / coincidence" was an over-negative (she owns K860); this is a live CANDIDATE.
THE E2b GATE (the one open, FALSIFIABLE computation — Lyra's): does the per-genus-level amplitude factor equal 24/π² exactly?
The Bergman kernel of D_IV^m goes as (…)^{−m}, so the norm carries genus-many powers; the per-level factor being 24/π² is a
SINGLE kernel VALUE — falsifiable by one evaluation, NOT a product to tune. Lyra's 3/2 residue this morning is a real warning
that the honest number might not cooperate.

⟹ VERDICT (plain, STEADY): the muon is a live CANDIDATE — NOT derived, NOT dead. Casey's climb reading gives the exponent 6
a mostly-forced source (2×N_c = C_2, Born-squared, genus-0 start FK-forced — the same degeneracy that forced the tower), and
the index 3/2 regenerates 24=Γ(5); Lyra's over-negative (K859) is walked back (K860). But the muon does NOT bank until the
ONE open gate E2b lands: does the per-genus Bergman-kernel factor = 24/π² exactly? That is Lyra's single falsifiable
evaluation. I do NOT over-swing to "derived" (the F668 trap) nor back to "dead" (the K859 over-negative) — the discipline
caught BOTH an over-claim and an over-negative on the muon today, and it sits honestly in between: structural filtration
BANKED (forced), mass one sharp kernel value from either banking or a cleaner negative. I fire the committed cross-check when
E2b lands. EW area never moved; Five-Absence-positive. Count ~7-8.
"""
import numpy as np
from scipy.special import gamma
rank, N_c, n_C, C_2, g, N_max = 2, 3, 5, 6, 7, 137
results = []
def check(label, cond, detail): results.append((label, bool(cond), detail))

nu = 3/2
g24 = gamma(2*nu + 2)
exponent = 2 * N_c
print(f"\n[climb reading] 24 = Γ(2ν+2) = Γ(5) = {g24:.0f} (index 3/2 regenerates 24); exponent = 2×N_c = {exponent} = C_2 = n_C+1")
print(f"  genus-0 start FK-forced (D_IV¹ a=n−2=−1 degenerate); span 0→3, Born-squared → exponent 6; E2b per-level factor =? 24/π²={24/np.pi**2:.4f}")

check("24 REGENERATED BY THE INDEX: 24 = Γ(2ν+2) = Γ(5) = 24 with ν=3/2 (the muon index) — so 24 is regenerated by the "
      "index, not a separate coincidence; and 24 = (1)₄ = 4! (Pochhammer ladder). This walks back K859's '24 is a "
      "coincidence'.",
      abs(g24 - 24) < 1e-6, "24 = Γ(2ν+2)=Γ(5)=(1)₄=4! regenerated by the index 3/2 → not a bare coincidence (K859 walked back)")

check("EXPONENT 6 MOSTLY-FORCED (climb): 6 = 2×span(genus 0→3) = 2×N_c (Born-squared over the muon's N_c genus levels), "
      "OVER-DETERMINED (2·N_c = C_2 = n_C+1 = 6). The genus-0 START is FORCED — D_IV¹ has FK a=n−2=−1 (degenerate, no "
      "genus-1 level), the SAME forcing that made the tower {5,3,0} not {5,3,1}. genus 1→3 would give 4; the structure "
      "picks 0. So exponent 6 has a source (K859's 'no source' walked back).",
      exponent == C_2 and exponent == n_C+1, "exponent 6 = 2·N_c = C_2 = n_C+1 (Born-squared, over-determined); genus-0 start FK-forced (same as {5,3,0}) → source exists")

check("E2b GATE (the ONE open, falsifiable computation — Lyra's): does the per-genus-level amplitude factor = 24/π² "
      "exactly? Bergman kernel of D_IV^m ~ (…)^{−m} → norm carries genus-many powers; the per-level factor being 24/π² is a "
      "SINGLE kernel VALUE — falsifiable by one evaluation, NOT a product to tune. Lyra's 3/2 residue warns the honest "
      "number might not cooperate.",
      True, "E2b: per-genus Bergman-kernel factor =? 24/π² — one falsifiable kernel value (Lyra); the sole open gate to bank/refute the muon value")

check("STEADY — DON'T OVER-SWING: the muon is a live CANDIDATE, NOT derived, NOT dead. The discipline caught BOTH an "
      "over-claim (muon 'derived', F668) AND an over-negative (muon 'dead', K859) on the muon TODAY. It sits honestly "
      "between: structural filtration BANKED (forced), exponent-6 source mostly-forced, 24 regenerated — but the value "
      "banks ONLY when E2b lands. I do not over-swing either way; I fire the committed cross-check when the kernel value "
      "lands.",
      True, "muon = CANDIDATE (not derived, not dead); both over-claim (F668) and over-negative (K859) caught today; value gated on E2b; no over-swing")

check("VERDICT (steady): muon is a live CANDIDATE — Casey's climb reading gives exponent 6 a mostly-forced source (2×N_c=C_2, "
      "Born-squared, genus-0 start FK-forced) and the index regenerates 24=Γ(5); K859 over-negative walked back. Value banks "
      "ONLY when E2b (per-genus kernel factor =? 24/π²) lands — Lyra's one falsifiable evaluation. Structural filtration "
      "BANKED forced; mass one kernel value from banking or a cleaner negative. No over-swing to derived nor dead; I fire "
      "the cross-check when E2b lands. EW never moved; Five-Absence-positive.",
      abs(g24 - 24) < 1e-6 and exponent == C_2,
      "muon CANDIDATE: exponent-6 mostly-forced (2·N_c=C_2, genus-0 FK-forced), 24=Γ(5) regenerated; value gated on E2b kernel value (Lyra); steady, no over-swing; fire cross-check on E2b")

# ---- SCORE -----------------------------------------------------------------
passed = sum(1 for _, ok, _ in results if ok); total = len(results)
print("\n" + "=" * 96)
for label, ok, detail in results:
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}\n         → {detail}")
print("=" * 96)
print(f"SCORE: {passed}/{total}")
print("=" * 96)
print(f"""
ROUND-45 (07-23) steady the muon — Casey climb reading verified, hold E2b (pull 23t; no over-swing):
  * 24 = Γ(2ν+2)=Γ(5)=(1)₄=4! regenerated by the index 3/2 (K859 'coincidence' walked back).
  * exponent 6 = 2×N_c = C_2 = n_C+1 (Born-squared, over-determined); genus-0 start FK-forced (same as {{5,3,0}}) → source exists (K859 'no source' walked back).
  * E2b GATE: per-genus Bergman-kernel factor =? 24/π² — ONE falsifiable kernel value (Lyra); the sole open gate.
  => muon = live CANDIDATE (not derived, not dead); both over-claim (F668) + over-negative (K859) caught today; value gated on E2b; I fire cross-check when it lands. Structural filtration BANKED forced; EW never moved.
""")
