import itertools
print("="*92)
print("PRE-REGISTERED (before the break, on the record): antisymmetry will give d_min = 2, NOT 3.")
print("Routed question: can antisymmetry BE an error-DETECTING code (parity/erasure, not repetition)?")
print("="*92)
print()
print("★ FIRST, A CORRECTION TO MY OWN 5302. There I wrote 'one codeword, zero bits' -- treating the")
print("  singlet as a 1-dimensional QUANTUM STATE. That framing was too coarse. As a CLASSICAL CODE")
print("  on the INDEX SET, the support of eps_{abc} is the set of triples where eps is nonzero:")
supp=[p for p in itertools.product(range(1,4),repeat=3) if len(set(p))==3]
print("     support(eps) = %s"%supp)
print("     |C| = %d codewords over alphabet {1,2,3}, length 3  ->  log2(%d) = %.3f bits."%(len(supp),len(supp),__import__('math').log2(len(supp))))
print("  ⟹ IT *IS* A CODE. My 5302's conclusion (the map fails) survives, but its REASON was wrong.")
print()
print("="*92)
print("SO WHAT IS ITS MINIMUM DISTANCE?")
print("="*92)
def ham(a,b): return sum(x!=y for x,y in zip(a,b))
dmin=min(ham(a,b) for a in supp for b in supp if a!=b)
print("   all pairwise Hamming distances among the %d codewords:"%len(supp))
from collections import Counter
dist=Counter(ham(a,b) for a in supp for b in supp if a!=b)
for d,c in sorted(dist.items()): print("      distance %d : %d ordered pairs"%(d,c))
print("   ⟹ d_min = %d"%dmin)
print("   WHY, structurally: two DISTINCT permutations of (1,2,3) cannot differ in exactly one place --")
print("   if they agreed in two positions, the third entry would be forced equal too. So d >= 2.")
print()
print("   capability at d = %d:"%dmin)
print("      errors DETECTED  = d - 1 = %d"%(dmin-1))
print("      errors CORRECTED = floor((d-1)/2) = %d"%((dmin-1)//2))
print("      ERASURES corrected = d - 1 = %d"%(dmin-1))
print()
print("   ★★ PREDICTION CONFIRMED: d_min = 2. Antisymmetry IS a code -- a DETECTION / ERASURE code,")
print("      not an error-CORRECTION code.")
print()
print("   explicit erasure recovery (we know WHERE the loss is):")
print("      given (1, 2, ?) the missing entry is FORCED to 3 -- one candidate:")
for a in supp:
    if a[0]==1 and a[1]==2: print("         %s"%(a,))
print("   explicit error NON-correction (we do NOT know where):")
bad=(1,1,3)
near=[a for a in supp if ham(a,bad)==1]
print("      received %s (illegal). Codewords at distance 1: %s"%(bad,near))
print("      -> %d candidates, AMBIGUOUS. Cannot correct. Detection only."%len(near))
print()
print("="*92)
print("THE VERDICT ON THE PROMOTION")
print("="*92)
print("  * antisymmetry IS a code, and it does erasure/detection -- so the routed question is YES")
print("    in the sense asked. Cal and Lyra were right to ask it; my 5302 answered a coarser question.")
print("  * BUT its minimum distance is 2, not 3. The Shannon route to N_c = 3 needs ERROR correction")
print("    (d >= 2t+1 = 3). Antisymmetry supplies ERASURE correction (d >= e+1 = 2).")
print("  ⟹ N_c = 3 DOES NOT PROMOTE. The antisymmetric structure delivers the integer 2, not 3.")
print()
print("  ★ AND THE SEVENTH #35 OF THE ARC, flagged rather than banked: d_min = 2 here and rank = 2")
print("    (the binary alphabet, our one forced integer) are the SAME INTEGER FROM DIFFERENT OBJECTS")
print("    -- one is an erasure-distance on a 3-letter alphabet, the other is a binary alphabet size.")
print("    Do NOT read this as 'the colour structure re-derives rank'. It does not.")
