"""
Toy 2352 — BST lattice density in ℕ: connect to smooth-number theory.

Owner: Elie
Date: 2026-05-15
Out of: Casey "the BST lattice looks especially interesting and likely
        to fall."

THE HYPOTHESIS
==============
BST atoms: A = {2, 3, 5, 6, 7, 11, 13, 17, 24, 137}
   = {rank, N_c, n_C, C_2, g, c_2, c_3, seesaw, chi, N_max}

The BST lattice L is generated by products and small additive shifts:

  L = {Π a_i^{e_i} · ε  :  a_i ∈ A, e_i ∈ ℕ, ε ∈ {0, ±1, ±rank, ±N_c}}

Question: how dense is L in ℕ at small N? What's the FIRST integer
not in L? How does it compare to:
- 7-smooth numbers (primes ≤ 7)
- 13-smooth numbers (primes ≤ 13)
- π(N) (prime counting)

CONJECTURE: L is denser than 13-smooth-with-shifts because the
BST atoms include 17 (Fermat F_2 = seesaw) and 24 (2³·3 = chi), giving
extra "lattice points" that fill gaps.

This toy:
1. Tabulates BST decomposability up to N = 200
2. Identifies non-BST integers (the "exceptions")
3. Compares density to 7-smooth and 13-smooth
4. Looks for structural pattern in exceptions
"""

rank, N_c, n_C, C_2, g = 2, 3, 5, 6, 7
c_2 = 11
c_3 = 13
seesaw = 17
chi = 24
N_max = 137

BST_ATOMS = {2, 3, 5, 6, 7, 11, 13, 17, 24, 137}
SHIFTS = {0, 1, -1, 2, -2, 3, -3}   # 0 (no shift), ±1, ±rank, ±N_c


def smooth(n, B):
    """Check if n is B-smooth (all prime factors ≤ B)."""
    if n <= 1: return True
    d = 2
    while d * d <= n:
        while n % d == 0:
            if d > B: return False
            n //= d
        d += 1
    if n > 1 and n > B: return False
    return True


def bst_decomposable(target, max_factors=4, max_iterations=2000):
    """Search for BST decomposition of target up to depth max_factors.
    Returns (success, expression) or (False, '').

    Allowed operations:
    - Product of up to max_factors BST atoms
    - Plus or minus a shift from SHIFTS
    """
    if target in BST_ATOMS:
        return True, str(target)
    if target == 0:
        return True, "0"
    if target == 1:
        return True, "1"
    if target < 0:
        ok, expr = bst_decomposable(-target, max_factors)
        return ok, ("-" + expr) if ok else expr

    # Generate products of atoms up to max_factors
    iterations = [0]

    def try_product(remaining, current_factors, base):
        if iterations[0] > max_iterations:
            return None
        iterations[0] += 1
        if remaining == 1 or len(current_factors) == max_factors:
            # Final value is base; check if base ± shift = target
            for s in SHIFTS:
                if base + s == target:
                    if s == 0:
                        return " * ".join(map(str, current_factors)) or "1"
                    sign = "+" if s > 0 else "-"
                    return f"({'·'.join(map(str, current_factors)) or '1'}) {sign} {abs(s)}"
            return None
        for a in BST_ATOMS:
            if a > remaining:
                continue
            if a > target * 2:
                continue
            new_base = base * a
            if new_base > target * 5:
                continue
            result = try_product(remaining // a if remaining % a == 0 else 1,
                                  current_factors + [a], new_base)
            if result is not None:
                return result
        # Also try standalone: factors form product, check if equals target±shift
        for s in SHIFTS:
            if base + s == target:
                if s == 0:
                    return "·".join(map(str, current_factors)) or "1"
                sign = "+" if s > 0 else "-"
                return f"({'·'.join(map(str, current_factors)) or '1'}) {sign} {abs(s)}"
        return None

    # Try all starting atoms
    for a in BST_ATOMS:
        result = try_product(target // a if target % a == 0 else 1, [a], a)
        if result is not None:
            return True, result
    # Also try pure shifts of zero
    for s in SHIFTS:
        if target == s:
            return True, f"{s}"
    return False, ""


# ============================================================
# Density survey up to N = 200
# ============================================================
N_MAX_TEST = 200

bst_count = 0
smooth7_count = 0
smooth13_count = 0
non_bst = []

for n in range(2, N_MAX_TEST + 1):
    ok_bst, expr = bst_decomposable(n)
    ok_7 = smooth(n, 7)
    ok_13 = smooth(n, 13)
    if ok_bst:
        bst_count += 1
    else:
        non_bst.append(n)
    if ok_7:
        smooth7_count += 1
    if ok_13:
        smooth13_count += 1

total = N_MAX_TEST - 1

print("=" * 65)
print(f"Density up to N = {N_MAX_TEST}")
print("=" * 65)
print(f"  BST-decomposable: {bst_count}/{total} = {100*bst_count/total:.1f}%")
print(f"  7-smooth:         {smooth7_count}/{total} = {100*smooth7_count/total:.1f}%")
print(f"  13-smooth:        {smooth13_count}/{total} = {100*smooth13_count/total:.1f}%")
print()
print(f"Non-BST integers in [2, {N_MAX_TEST}]: {len(non_bst)}")
if len(non_bst) > 0:
    print("  First 30 exceptions:", non_bst[:30])

# ============================================================
# Compare to a "null lattice" — random 10 small integers
# ============================================================
print()
print("Null comparison: 10 randomly chosen atoms in [2, 25]")
import random
random.seed(42)
null_atoms = set(random.sample(range(2, 26), 10))
print(f"  Null atoms: {sorted(null_atoms)}")

def null_decomposable(target, max_factors=4):
    """Same as bst_decomposable but with null atoms."""
    if target in null_atoms:
        return True
    if target <= 1:
        return True
    # Quick check: simple product or product+shift
    for a in null_atoms:
        if target % a == 0:
            other = target // a
            if other in null_atoms or other == 1:
                return True
            for b in null_atoms:
                if other % b == 0 and (other // b) in null_atoms:
                    return True
    for a in null_atoms:
        for b in null_atoms:
            for s in SHIFTS:
                if a * b + s == target:
                    return True
                if a + b + s == target:
                    return True
    return False

null_count = sum(1 for n in range(2, N_MAX_TEST + 1) if null_decomposable(n))
print(f"  Null-lattice decomposable: {null_count}/{total} = {100*null_count/total:.1f}%")
print()
print(f"BST advantage over null: {100*(bst_count-null_count)/total:+.1f}%")

# ============================================================
# Pattern in non-BST exceptions
# ============================================================
print()
print("Non-BST primes (first 20):")
non_bst_primes = [n for n in non_bst if all(n % p != 0 for p in range(2, int(n**0.5)+1))][:20]
print(f"  {non_bst_primes}")

# Check: do non-BST exceptions cluster around specific patterns?
# Hypothesis: they're primes near "Mersenne dual" or "Fermat dual" positions

# ============================================================
# INSTINCT — read the geometry
# ============================================================
print()
print("=" * 65)
print("INSTINCT")
print("=" * 65)
print(f"""
The BST lattice density at N=200 is the key statistic. Three regimes:

1. If BST density >> 13-smooth density: BST atoms have ADDED VALUE
   beyond just being small primes (i.e., the shifts {{±1, ±rank, ±N_c}}
   genuinely densify the lattice).

2. If BST density ≈ 13-smooth density: BST is just "small-prime
   smoothness" in disguise.

3. If BST density < 13-smooth density: my decomposer is too strict.

The non-BST exceptions (if any) are the integers that DON'T fit BST's
canonical generators. These are physically interesting: they should
correspond to observables that BST predicts poorly or not at all.

If the first few non-BST exceptions correspond to KNOWN physical
constants that BST gives poorly, we have a STRUCTURAL connection
between the BST lattice and physics's "natural" small-integer set.

The "fall" Casey senses: if the BST lattice IS exactly the
small-integer set physics counts naturally, then physical observables
that don't fit BST (kaon Wolfenstein λ, charm Yukawa, neutrino masses)
should sit at the non-BST exceptions.
""")
