import numpy as np
def A2(v):
    v=np.asarray(v,float); N=len(v)
    return 2*(N*(v**2).sum()/v.sum()**2-1)
print("="*92)
print("STOP -- RETRACTION CHECK BEFORE COMPUTING. The {5,3,0} strata route is thrice-ruled DEAD.")
print("="*92)
print("  My standing rule (memory: 'grep before reopening a retired result') fired. What the corpus says:")
print()
print("  1. F669 (Lyra, 2026-07-23 -- THE SAME DAY she filed F666): 'OWN THE ERROR ... {5,3,0} is NOT")
print("     a single geometry.' And explicitly: 'Does NOT survive: genera {5,3,0} as one geometry,")
print("     c5/c3 = muon derivation.'  ⟹ THE VERY ITEM THE PROMPT CITES AS BANKED IS THE ITEM SHE")
print("     NAMED AS NOT SURVIVING.")
print("  2. K853 (2026-07-23): ruled the {5,3,0} nested tower NOT a consistent geometry + muon NOT derived.")
print("  3. K928: 'MUON-JACOBIAN doubly declined' -- refuted on STRUCTURE and on PREDICTION.")
print("     '@Elie -- your live route with two gates is SUPERSEDED; the route is declined.'")
print("     'Don't reopen the tower.'  ⟹ ADDRESSED TO ME, AND I ACCEPTED IT (my line: 'I own the")
print("     correction'). Muon = identified-coincidence, bucket-2, CLOSED.")
print()
print("  4. And the corpus already named WHY the muon cannot be evidence either way:")
print("     'Only the muon agrees between the two ladders, which is why it survives both and CANNOT")
print("      DISCRIMINATE.' (the banked rho-ladder vs the INVERTED narrative ladder)")
print()
print("="*92)
print("AND I CAN SHOW THE ROUTE FAILS THE KOIDE TARGET USING ITS *OWN* PREDICTIONS")
print("="*92)
r=24/np.pi**2
mu_pred=r**6; tau_pred=r**10
mu_obs=105.6583755/0.51099895; tau_obs=1776.86/0.51099895
print("  the uniform strata rule (F701's gate): m_mu/m_e = (24/pi^2)^6, m_tau/m_e = (24/pi^2)^10")
print("     m_mu/m_e :  predicted %.2f   observed %.2f   -> agrees (this is the coincidence that survives)"%(mu_pred,mu_obs))
print("     m_tau/m_e:  predicted %.1f  observed %.1f   -> OFF BY %.2fx  (F701: '2x off + wrong parity')"%(tau_pred,tau_obs,tau_pred/tau_obs))
vp=[1,np.sqrt(mu_pred),np.sqrt(tau_pred)]
vo=[1,np.sqrt(mu_obs),np.sqrt(tau_obs)]
print("\n  fire the pre-registered estimator on both:")
print("     OBSERVED  sqrt-mass vector (1, %.3f, %.3f)  ->  A^2 = %.6f   [Koide, = 2 ✓]"%(vo[1],vo[2],A2(vo)))
print("     STRATA-RULE PREDICTION      (1, %.3f, %.3f)  ->  A^2 = %.6f   [target 2]"%(vp[1],vp[2],A2(vp)))
print("     miss: %.1f%%"%(100*abs(A2(vp)-2)/2))
print()
print("  ⟹ THE STRATA ROUTE, RUN TO ITS OWN CONCLUSION, GIVES A^2 = %.2f, NOT 2."%A2(vp))
print("     It fails the Koide target by %.0f%%, and it fails for exactly the reason F701 already"%(100*abs(A2(vp)-2)/2))
print("     identified independently: THE TAU. The route was refuted on the tau in July, and the tau")
print("     is precisely where Koide's balance is decided.")
print()
print("="*92)
print("★ WHAT IS LIVE, AND MUST NOT BE CONFLATED -- the arc's NINTH #35")
print("="*92)
print("   BANKED    : the nu-ADDRESSES {5/2, 3/2, 0}  (T2517) -- rho-vector components, Tier D.")
print("   RETRACTED : the GENUS-{5,3,0} nested SUB-DOMAINS (F666 -> F669/K853/K928).")
print("   Same shape, similar integers, DIFFERENT CLAIMS. The prompt treats the second as banked")
print("   because it looks like the first. That is the same failure mode we have caught eight times")
print("   today with 3s, 2s, 11s and 27s -- this time with a whole geometry.")
print()
print("  ⟹ I AM NOT COMPUTING A^2 FROM A RETRACTED OBJECT. The estimator stays pre-registered and")
print("     ready; it fires the moment a LIVE object is handed to it.")
