from fractions import Fraction as F
print("="*104)
print("TOY 5352 -- BLIND: does a_2 from D's heat trace give the QCD beta-function?")
print("  *** STEP 1 writes what a_2 contains, with NO reference to beta. *** Tables first.")
print("="*104)

print("\n"+"-"*104)
print("STEP 1 -- WHAT a_2 CONTAINS (Gilkey), written before opening the beta-function")
print("-"*104)
print("\n  For a Laplace-type P = -(nabla^2 + E) on an n-manifold:")
print("    a_2 = (1/360) Int tr{ 60 E_;kk + 60 R E + 180 E^2 + 30 Omega_ij Omega^ij")
print("                          + (12 R_;kk + 5R^2 - 2 R_ij R^ij + 2 R_ijkl R^ijkl) Id }")
print("\nTABLE 1 -- the gauge-relevant term")
print("   term                 coefficient     what it is")
print("   Omega_ij Omega^ij    30/360 = %-7s the CONNECTION curvature = F_mu_nu"%str(F(30,360)))
print("   E^2 (Dirac: E carries a Clifford-contracted Omega) 180/360 = %s  feeds the same F^2"%str(F(180,360)))
print("   ==> *** a_2 DOES contain an F^2 term. That is the gauge kinetic term, and integrating out")
print("       the field whose operator is P gives THAT FIELD'S one-loop beta contribution. ***")
print("\nTABLE 2 -- so WHOSE loop does D's heat trace compute?")
print("   D is the DIRAC operator -> its heat trace integrates out FERMIONS.")
print("   *** BLIND COMMITMENT, POSTED BEFORE OPENING beta: D's a_2 can supply the FERMION-loop")
print("       contribution to the beta-function and NOTHING ELSE. The gauge-boson + ghost loop is")
print("       a DIFFERENT operator (the gauge-field Laplacian), absent from a fermionic D. ***")

print("\n"+"-"*104)
print("STEP 2 -- NOW open the QCD beta-function")
print("-"*104)
N_c=3
print("   b_0 = (11/3) N_c - (2/3) n_f")
print("     the (11/3) N_c piece  <- GLUON + GHOST loop  (gauge self-interaction)")
print("     the -(2/3) n_f piece  <- FERMION loop")
for nf in (0,3,6):
    print("   n_f = %d :  b_0 = %s - %s = %s"%(nf,F(11*N_c,3),F(2*nf,3),F(11*N_c,3)-F(2*nf,3)))

print("\n"+"-"*104)
print("STEP 3 -- THE COMPARISON")
print("-"*104)
nf=6
gauge=F(11*N_c,3); ferm=-F(2*nf,3); tot=gauge+ferm
print("   piece                     value    does D's heat trace supply it?")
print("   gauge (gluon+ghost) 11N_c/3  %-8s *** NO -- not a fermionic operator ***"%str(gauge))
print("   fermion   -(2/3) n_f         %-8s YES"%str(ferm))
print("   total b_0 (n_f=6)            %-8s D supplies %s of %s"%(str(tot),str(ferm),str(tot)))
print("   ==> *** D's heat trace supplies %s out of %s -- and with the OPPOSITE SIGN. ***"%(str(ferm),str(tot)))
print("       On its own it gives a SCREENING (non-asymptotically-free) contribution.")
print("       Asymptotic freedom IS the 11N_c/3, and that is exactly the piece D does not carry.")

print("\nTABLE 3 -- *** and this is the SAME structural fact as #108's floor ***")
print("   #108 (toy 5350) : the gluon spin-2 generators are NOT in the isometry algebra")
print("   here            : the gluon LOOP is NOT in the fermionic Dirac heat trace")
print("   ==> both say: *** the gauge sector is not present in the geometry/operator as given. ***")
print("       That is a CONSISTENCY between two independent computations, not a new failure --")
print("       and it is what the charter predicted (gluons live in D's FLUCTUATIONS, not the isometry).")

print("\nTABLE 4 -- the clean-number check, run BEFORE anyone gets excited")
print("   b_0 = 7 at n_f = 6, and g = 7. Tempting. Run the family sweep first:")
for nf in range(0,9):
    b=F(11*N_c,3)-F(2*nf,3)
    print("      n_f = %d -> b_0 = %-6s %s"%(nf,str(b)," <-- equals g = 7" if b==7 else ""))
print("   ==> b_0 = 7 happens at n_f = 6 and ONLY there, but n_f = 6 is an INPUT (the observed")
print("       quark count), not something derived here. *** So this is a coincidence of the input,")
print("       not a prediction. NOT banked. *** (Same discipline as 25/4 and sqrt(pi^n/n).)")
print("   ALSO: the 11 in 11N_c/3 is NOT the c_2 = dim K = 11 I flagged earlier -- two different")
print("   elevens, already on the record as a shared-integer trap.")

print("\n"+"="*104)
print("VERDICT -- committed before the comparison")
print("="*104)
print(" (1) *** NO. a_2 FROM D's HEAT TRACE DOES NOT GIVE THE QCD BETA-FUNCTION. *** It contains an")
print("     F^2 term (coefficient 1/12 on Omega^2, plus the E^2 feed), so it computes a one-loop")
print("     beta CONTRIBUTION -- but only the FERMION loop, because D is a fermionic operator.")
print()
print(" (2) *** QUANTITATIVELY: at n_f = 6, D supplies -4 of b_0 = 7, with the OPPOSITE SIGN. *** On")
print("     its own D gives a screening contribution. Asymptotic freedom IS the +11N_c/3 gluon+ghost")
print("     loop, and that is precisely the piece a fermionic Dirac heat trace cannot carry.")
print()
print(" (3) THE HONEST POSITIVE: this is the SAME structural fact as #108's floor, arrived at")
print("     independently -- the gauge sector is not in the geometry/operator AS GIVEN. Two")
print("     computations, one boundary. *** And it is what PROGRAM-DIRAC row C should have expected:")
print("     if the gluons live in D's FLUCTUATIONS, the unfluctuated D cannot show them. ***")
print()
print(" (4) SO THE ROW IS NOT DEAD -- IT IS RE-AIMED. The test that could still land is the")
print("     FLUCTUATED Dirac operator D_A = D + A (the inner fluctuations of the spectral triple),")
print("     whose heat trace DOES contain the gauge-boson loop. *** I did not compute that, and it")
print("     is a strictly larger computation. I am reporting the unfluctuated answer honestly rather")
print("     than presenting the re-aim as a result. ***")
