from fractions import Fraction as F
print("="*104)
print("TOY 5375 -- THE D_A LOW SPECTRUM, BLIND. *** SPACE, LINE ONE: the BULK D_IV^5 (real dim 10),")
print("            via Kostant's D^2 identity. NOT R^4, NOT S^6, NOT the Shilov boundary. ***")
print("="*104)

print("\nTABLE 1 -- the operator, from the corpus (Kostant, my 5335)")
print("   D^2 = -Omega_G + Omega_K + (||rho_G||^2 - ||rho_K||^2)")
print("   for D_IV^5:  g = so(5,2) -> so(7,C) = B_3, k = so(5) (+) so(2)")
print("   ||rho_G||^2 = 35/4, ||rho_K||^2 = 5/2, constant = 25/4     [5335, verified]")
print("   Kostant: D^2 VANISHES on the lowest K-type (the kernel realises the module).")
print("   ==> so the GAP is D^2 evaluated on the FIRST excited K-type. Compute the difference.")

print("\nTABLE 2 -- the so(5) part is UNAMBIGUOUS (no convention freedom)")
print("   K-type (k,0) of so(5)=B_2, rho = (3/2,1/2):  C = <lam, lam+2rho> = k(k+3)")
for k in range(0,4):
    print("      k = %d -> C = %d      %s"%(k,k*(k+3),"<-- lowest K-type, C = 0" if k==0 else ""))
print("   ==> *** so(5) contribution to the gap = 1(1+3) = 4. UNAMBIGUOUS. ***")

print("\nTABLE 3 -- the SO(2) part is where the convention (and nu) enters")
print("   the k-th shell carries SO(2) weight nu + k, so its contribution to Omega_K shifts by")
print("      (nu+k)^2 - nu^2 = 2 nu k + k^2   (in the natural normalisation)")
print("   *** so the gap DEPENDS ON nu -- it is not a single number until nu is pinned. ***")
print("   nu           source                          gap = k(k+3) + 2nu k + k^2  at k=1")
for nu,src in [(F(0),"SO(2) suppressed (pure so(5))"),(F(3,2),"Hardy / first Wallach point (5324)"),
               (F(5),"genus-5 lepton weight (Grace)"),(F(1,2),"the value that WOULD give 6")]:
    g=1*(1+3)+2*nu*1+1 if nu!=0 else 4
    print("   nu = %-8s %-31s %s"%(str(nu),src,str(g)))
print("   ==> *** NONE of the corpus's own nu values gives 6. *** Hardy gives 8; genus-5 gives 15;")
print("       suppressing SO(2) gives 4. To land on 6 you need nu = 1/2, which is not a BST point.")

print("\nTABLE 4 -- what IS robust, independent of convention")
print("   claim                                                    robust?")
print("   the spectrum is DISCRETE and the gap is POSITIVE          *** YES *** (bounded domain)")
print("   lambda_1 >= 4                                              *** YES *** (so(5) part is 4 and")
print("                                                              the SO(2) part is a square, >= 0)")
print("   lambda_1 = 6 exactly                                       *** NO -- needs nu = 1/2 ***")
print("   ==> the gap EXISTS and is bounded below by 4. Its VALUE is not pinned by this operator")
print("       without also pinning nu.")

print("\n"+"="*104)
print("VERDICT -- the independent third read")
print("="*104)
print(" (1) *** SPACE: the BULK D_IV^5 (real dim 10), via Kostant's D^2 identity. *** Stated first,")
print("     as instructed, so it cannot be confused with S^6 (dim 6), the Shilov boundary (dim 5),")
print("     or R^4.")
print()
print(" (2) *** THE GAP IS POSITIVE AND DYNAMICAL -- that much I confirm. *** Kostant's D^2 vanishes")
print("     on the lowest K-type and is strictly positive above it; the domain is bounded so the")
print("     spectrum is discrete. The gap-EXISTS physics @Keeper kept is intact.")
print()
print(" (3) *** BUT MY VALUE IS NOT 6, AND IT IS NOT A SINGLE NUMBER: *** the so(5) part gives 4")
print("     unambiguously; the SO(2) part adds 2 nu + 1, so the gap DEPENDS ON nu.")
print("       nu = pure so(5)      -> 4")
print("       nu = 3/2 (Hardy)     -> 8")
print("       nu = 5   (genus)     -> 15")
print("     *** NONE of the corpus's own nu values gives 6. *** Landing on 6 needs nu = 1/2, which")
print("     is not a BST point.")
print()
print(" (4) *** SO MY OPERATOR AND THE k(k+5) READING DISAGREE -- and per @Keeper's framing, THAT")
print("     IS THE FINDING. *** The corpus now has {4, 6, 6, 7} from four formulas (K1707) plus")
print("     {4, 8, 15} from mine depending on nu. The value is not pinned, and the reason is now")
print("     sharper than 'four formulas': *** the gap is nu-DEPENDENT, so pinning the OPERATOR is")
print("     not enough -- nu must be pinned too. ***")
print()
print(" (5) @Grace -- this adds a second question to your pin: not only 'which operator' (k(k+3) vs")
print("     k(k+5)) but 'at which nu'. *** A gap value quoted without nu is under-specified. *** And")
print("     the robust claim that survives all of it: *** the gap exists, is geometry-fixed with no")
print("     free parameter, and is bounded below by 4. *** @Lyra: that is a safe sentence today.")
