import sympy as sp
print("="*92)
print("THE c_2 = 11 DERIVATION -- corpus-grounded (T1790/T1791) and verified exactly here.")
print("="*92)
print("  T1790: 'the 2-form Laplacian gap on Q^5 is c_2 = 11, the SECOND CHERN CLASS' (Weitzenbock).")
print("  T1791: 'three independent derivations agree; UNIVERSAL IDENTITY c_2 = dim K for all quadrics.'")
print("  So the claim to verify is:  c_2(Q^n) = dim K = dim SO(n) + dim SO(2) = n(n-1)/2 + 1.\n")
h,n=sp.symbols('h n')
print("  Chern class of the quadric Q^n:  c(T Q^n) = (1+h)^{n+2} / (1+2h)")
for N in [3,4,5,6,7,8,10]:
    ser=sp.series((1+h)**(N+2)/(1+2*h),h,0,3).removeO()
    p=sp.Poly(sp.expand(ser),h)
    c1=p.coeff_monomial(h); c2=p.coeff_monomial(h**2)
    dimK=N*(N-1)//2+1
    flag=" <-- D_IV^5, BST" if N==5 else (" <-- n=10 = Herm_2(O), the exclude-list neighbour" if N==10 else "")
    print("    n=%2d :  c_1 = %3d (= n? %s)   c_2 = %3d   dim K = dim SO(%d)+1 = %3d   MATCH: %s%s"%(
        N,c1,c1==N,c2,N,dimK,c2==dimK,flag))
print()
print("  and the closed form, symbolically:")
ser=sp.series((1+h)**(n+2)/(1+2*h),h,0,3).removeO()
c2sym=sp.simplify(sp.expand(ser).coeff(h,2))
print("     c_2(Q^n) = %s  =  %s"%(sp.factor(c2sym),sp.simplify(c2sym - (n*(n-1)/2+1))==0))
print("     c_2(Q^n) - [n(n-1)/2 + 1] = %s   -> IDENTICALLY ZERO"%sp.simplify(sp.expand(c2sym-(n*(n-1)/2+1))))
print()
print("  ⟹ c_2 = 11 IS DERIVED, EXACTLY AND TARGET-INNOCENTLY: it is the coefficient of h^2 in")
print("     (1+h)^7/(1+2h) for the quadric Q^5, and it equals dim K = dim SO(5) + dim SO(2) = 10+1.")
print("     NO gauge group, NO N_c, NO beta function, NO QCD input anywhere. This is the real content")
print("     of the YM claim -- and my 5293 stands: the glueball 0.6%% is a guaranteed grid hit, the")
print("     DERIVATION OF 11 is the result.")
print()
print("="*92)
print("★ AND A #35 TRAP TO BURY IN ADVANCE -- there are TWO ELEVENS and they will get married.")
print("="*92)
print("   (a) c_2 = dim K = dim SO(5) + dim SO(2) = 10 + 1 = 11   [geometry: a Chern class]")
print("   (b) b_0 = 11 N/3 at N = N_c = 3            = 11         [physics: the QCD one-loop beta]")
print("   I used (b) myself in toy 5293 this morning, so the collision is already in today's record.")
print("   THEY ARE DIFFERENT OBJECTS: (a) is n(n-1)/2 + 1 with n = n_C = 5 and has no N_c in it;")
print("   (b) is (11/3)*N_c and has no n_C in it. Same integer, disjoint ingredients.")
print("   TEST that separates them, and it is free: vary n_C. (a) moves, (b) does not.")
for N in [4,5,6,7]:
    print("      n_C = %d :  c_2 = dim K = %2d      b_0(N_c=3) = 11 (unchanged)"%(N,N*(N-1)//2+1))
print("   ⟹ they agree at exactly one point and diverge everywhere else. Not a unification.")
