import numpy as np
print("="*104)
print("TOY 5350 -- #108: WHICH TARGET ALGEBRAS CAN EVEN HOST THE SPIN-3?")
print("  The Schur coefficient vanishes IFF the target contains no spin-3. That is a finite")
print("  representation-theory question -- so answer it exhaustively. Tables first.")
print("="*104)

print("\nTABLE 1 -- the setup, restated exactly")
print("   bracket space  Lambda^2(spin-2) = 10-dim = spin-1 (+) spin-3   (3 + 7)")
print("   the bracket map is SO(3)-EQUIVARIANT, and spin-1, spin-3 are INEQUIVALENT irreps")
print("   ==> by Schur, the map acts as a scalar on each channel")
print("   ==> *** if the TARGET algebra contains no spin-3, that scalar is FORCED to 0. ***")
print("       Not assumed -- forced. This is the non-circular route my 5349 was missing.")

print("\nTABLE 2 -- decompose every candidate target under the colour SO(3). Does spin-3 (dim 7) fit?")
def show(name,dim,pieces):
    tot=sum(d for _,d in pieces)
    has3=any(l==3 for l,_ in pieces)
    print("   %-14s dim %-4d %-36s %s"%(name,dim,
        " (+) ".join("spin-%s(%d)"%(l,d) for l,d in pieces),
        "*** SPIN-3 PRESENT ***" if has3 else "no spin-3 -> scalar FORCED to 0"))
    assert tot==dim,(name,tot,dim)
show("so(3)",3,[(1,3)])
show("u(3)",9,[(0,1),(1,3),(2,5)])
show("su(3)",8,[(1,3),(2,5)])
show("so(6)/u(3)",6,[(1,3),(1,3)])
show("so(6)",15,[(1,3),(1,3),(0,1),(1,3),(2,5)])
show("sp(6,R)",21,[(0,1),(1,3),(2,5),(0,1),(2,5),(0,1),(2,5)])
show("so(5) PRINC",10,[(1,3),(3,7)])
print("\n   derivations: u(3) = i(real symmetric) (+) (real antisym) = [spin-0+spin-2] + [spin-1]")
print("                so(5) under the PRINCIPAL so(3): 10 = 3 + 7 = spin-1 (+) spin-3")

print("\nTABLE 3 -- *** THE FORK, NOW A FINITE LIST ***")
print("   target the bracket lands in     spin-3?   consequence for #108")
print("   u(3)  (J-Hermitian)             NO        *** scalar = 0, spin-3 DIES, #108 PROMOTES ***")
print("   su(3)                           NO        same")
print("   so(6), sp(6,R), the squeeze coset  NO     same -- spin-3 dies even in the leak!")
print("   *** so(5) via the PRINCIPAL so(3) *** YES  *** spin-3 ALIVE, the floor stands ***")
print("   ==> the fork is NOT 'J-Hermitian vs squeeze coset'. *** BOTH of those kill the spin-3. ***")
print("       The ONLY way spin-3 survives is if the bracket reaches the full so(5) with the")
print("       PRINCIPAL so(3) embedding -- i.e. if the colour SO(3) is the principal one.")

print("\nTABLE 4 -- so the real question is WHICH SO(3) c SO(5), and the two differ observably")
print("   embedding      5 branches as            so(5) = 10 branches as       has spin-3?")
print("   REDUCTIVE      3 + 1 + 1 (V_12 + 2)     spin-1 + ... (no spin-3)     NO")
print("   PRINCIPAL      spin-2 (the 5 itself)    spin-1 (+) spin-3            YES")
print("   ==> *** THESE ARE THE TWO SO(3)s @Grace FLAGGED IN ROUND 7 -- 'three scalars vs none'.")
print("       The spin-3 question and the which-SO(3) question ARE THE SAME QUESTION. ***")
print("   and BST's colour SO(3) acts on V_12 = a 3-dim SUBSPACE of the 5 -> that is the")
print("   *** REDUCTIVE *** embedding (5 = 3 + 2), which has NO spin-3.")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) *** THE SCHUR ROUTE IS NON-CIRCULAR, AND IT IS THE FIX MY 5349 WAS MISSING. *** If the")
print("     target algebra contains no spin-3, the Schur scalar is FORCED to zero by equivariance --")
print("     no 3x3 realization assumed. That is a genuine mechanism, not the hunt-if-P shape.")
print()
print(" (2) *** AND THE FORK AS POSED HAS NO LOSING BRANCH. *** I computed every candidate target:")
print("     u(3) = spin-0+1+2, su(3) = spin-1+2, so(6) and sp(6,R) and the squeeze coset -- NONE")
print("     contains a spin-3. *** So 'J-Hermitian -> dies' and 'leaks into the squeeze coset ->")
print("     survives' is not the right dichotomy: the leak kills it too. ***")
print()
print(" (3) *** THE ONLY SURVIVING HOME FOR SPIN-3 IS so(5) UNDER THE PRINCIPAL so(3) *** (10 = 3+7).")
print("     So #108 reduces to ONE question, and it is not about J at all:")
print("       *** IS BST's COLOUR SO(3) THE PRINCIPAL OR THE REDUCTIVE EMBEDDING IN SO(5)? ***")
print("     principal -> spin-3 alive -> floor stands.   reductive -> spin-3 dies -> #108 promotes.")
print()
print(" (4) ** AND THE CORPUS ALREADY LEANS: BST's colour SO(3) acts on V_12, a 3-dim SUBSPACE of")
print("     the 5 (5 = 3 + 2). That is the REDUCTIVE embedding, which has no spin-3. ** If that")
print("     reading holds, #108 promotes. *** I am NOT calling it -- @Grace owns the source read,")
print("     and this is exactly the SO(3)-identification she flagged in Round 7. It must be pinned,")
print("     not inferred from my sentence. ***")
print()
print(" (5) CONVENTION FLAG, because three different J's are live in this session: J = the conformal")
print("     Hamiltonian (time), J = the real structure (JDJ = -D), J = the Kahler complex structure.")
print("     The prompt's 'J-Hermitian' needs pinning to one of them before anyone builds on it --")
print("     though per (2) the spin-3 verdict turns out NOT to depend on which.")
