import numpy as np, mpmath as mp
mp.mp.dps=25
print("="*92)
print("THE CKM SCORECARD -- banking the sector state. Tables first (banked procedure).")
print("="*92)
print("\nTABLE 0 -- GRACE'S CONVENTION PIN CORRECTS MY OWN 5317, IN THE HARDER DIRECTION.")
print("  p_u is a RADIUS, not a radius-squared. My 5317 led with the r^2 readings; the r readings")
print("  are the right comparison. Recomputing both so the record is unambiguous:")
need=0.3713
for nm,r2 in [("b = nu",0.5),("b = 2nu",1/3)]:
    print("     %-9s : r_*^2 = %.4f -> dev %5.1f%%   |   r_* = %.4f -> dev %5.1f%%  <- the right one"%(
        nm,r2,100*abs(r2-need)/need,np.sqrt(r2),100*abs(np.sqrt(r2)-need)/need))
print("  ⟹ the corrected misses are 55%% and 90%%, NOT 10%% and 35%%. THE REFUTATION IS STRONGER")
print("     than I reported. Correction accepted; it goes against my own earlier number.")
print()
obs={"V_us":(0.22431,0.00085),"V_cb":(0.04182,0.00085),"V_ub":(0.003820,0.00012)}
print("TABLE 1 -- what is DERIVED, with numbers")
vus=1/np.sqrt(20); o,e=obs["V_us"]
print("     V_us = 1/sqrt(20) = %.7f   observed %.5f +- %.5f   dev %.2f%%   %.2f sigma   params 0"%(
    vus,o,e,100*abs(vus-o)/o,abs(vus-o)/e))
print("     skeleton: parity selection (even<->odd only via J_W) + one-rung (Delta k = +-1)")
print("               from T1929 degrees + Wigner-Eckart. Structural, 0 params.")
print("\nTABLE 2 -- what is NOT derived, with the routes that failed")
print("     element   status        routes tried (all zero-parameter)          worst miss")
print("     V_cb      Identified    Pochhammer 3.69x ; Clebsch wrong-direction   132 sigma")
print("     V_ub      FREE          Pochhammer 9.03x ; Clebsch wrong-direction   256 sigma")
print("     delta_CP  FREE          none attempted                                --")
print("\nTABLE 3 -- THE PARAMETER COUNT, stated as a count and not an adjective")
print("     the CKM matrix has 4 physical parameters (3 angles + 1 phase).")
print("       derived sharply : 1  (V_us)")
print("       Identified      : 1  (V_cb, coarse, one open identification)")
print("       free inputs     : 2  (V_ub, delta_CP)")
print("     the Standard Model derives 0 of 4.")
print()
print("="*92)
print("VERDICT / SCORECARD -- written from Tables 0-3, and calibrated BOTH ways")
print("="*92)
print("  NOT UNDER-CLAIMED: BST derives 1 of the 4 CKM parameters at 0.83 sigma with ZERO free")
print("  parameters, plus a structural skeleton (which entries are nonzero, and the one-rung")
print("  ordering) that no flavor program derives and the SM does not address at all. That is a")
print("  real, publishable result and I will not soften it.")
print()
print("  NOT OVER-CLAIMED: it is 1 of 4, not 'the CKM'. Two parameters are free inputs and one is")
print("  coarse. The 'one kernel for the whole sector' hope is dead -- THREE independent")
print("  zero-parameter unification routes failed, each for a different structural reason:")
print("     radial-overlap  : rigid and misses (55%%/90%% where 0.49%% was needed)")
print("     Pochhammer      : 1 of 3 (nails V_us, off 3.7x/9.0x on the rest)")
print("     Clebsch weight  : wrong SIGN of dependence (enhances where suppression is needed)")
print("  Three different failure modes is not bad luck -- it is the sector telling us it is a")
print("  PATCHWORK, not one object. I bank that as the finding.")
print()
print("  ⟹ SECTOR CLOSED ON MY SIDE. I stop firing unifications. If a fourth route is proposed it")
print("     needs a NEW pre-registered falsifier before any computation, and it must beat 0.49%% on")
print("     the centre or supply entry-dependent SUPPRESSION -- the two things all three failed.")
