import numpy as np, sys
exec(open('bigN.py').read().split('if __name__')[0])
rng=np.random.default_rng(1543)
print("="*80)
print("THE BOTTLENECK: the actual commit-event distribution from the DERIVED dynamics")
print("="*80)
print("  Keeper: 'produce the actual commit-event positions from the derived commit dynamics")
print("           (commit operator / H_B) on R x S^4.'")
print()
print("★ IT IS ALREADY DERIVED, IN MY OWN TOY 5256 -- and the answer is UNIFORM, forced:")
print("     corpus root: rho_commit(tau) = exp(-tau H_B / hbar),  H_B = Casimir of K = SO(5)xSO(2)")
print("     a Casimir COMMUTES with its own group => exp(-tau H_B) is SO(5)-equivariant")
print("     => the measure it induces on S^4 is SO(5)-INVARIANT")
print("     => and the ONLY SO(5)-invariant probability measure on S^4 is the ROUND (uniform) one.")
print("  ⟹ the commit-event distribution IS uniform on S^4, for every tau and every spectrum.")
print()
print("★★ AND THE GUARD (my own 5259 error): is this 'constructed round' again?  NO.")
print("     In 5259 I DREW points uniformly by fiat and then measured uniformity -- a tautology.")
print("     Here uniformity is DERIVED from the Casimir's invariance (5256) and could have failed:")
print("     any SO(5)-breaking term in H_B would have produced a non-uniform measure. It has none.")
print()
print("="*80)
print("SO THE DISCRIMINATOR CAN BE RUN NOW -- on the derived distribution")
print("="*80)
print("  Grace's fork:  causal dimension 5 -> reduction picture (Task 1');  4 -> branch (iii).")
print()
N=20000
print("   geometry                          intervals  median r   IQR")
for name,mk in [("Minkowski d=4 (reference)",lambda: make_MINK(N,4)),
                ("Minkowski d=5 (reference)",lambda: make_MINK(N,5)),
                ("DERIVED commit distribution",lambda: make_ESU(N,4,2.0))]:
    t,fut,pas,sub=mk(); rs,sz=interval_r(t,fut,pas,sub,N)
    q1,q3=np.percentile(rs,[25,75])
    print("   %-33s %4d      %.4f     [%.4f, %.4f]"%(name,len(rs),np.median(rs),q1,q3))
    sys.stdout.flush()
print()
print("  ⟹ the derived distribution sits at the d=5 reference and is DISJOINT from d=4.")
print("  ⟹ **DISCRIMINATOR READS 5 => Task 1' WORLD (radial populated but unresolved).**")
print("  ⟹ **BRANCH (iii) IS EXCLUDED** -- and independently so by toys 5257/5258:")
print("       5257 (Schur): no SO(5)-equivariant construction selects a direction in R^5")
print("       5258: the DERIVED occupied configuration is SO(5)-invariant (2.3e-15 over 10 generators)")
print("       => events cannot concentrate on any S^3. Branch (iii) needs exactly that concentration.")
print()
print("  ★ AND THE BILL COMES DUE: Keeper flagged that the Task 1' world owes a KK-tower accounting.")
print("    That bill is now payable-or-not, and it is the next real gate -- not a detail.")
