from fractions import Fraction as F
import numpy as np
pi=np.pi
print("="*104)
print("TOY 5337 -- does the banked Szego/Hua regularization make 1/G finite on the bulk?")
print("  Tables first, verdict after.  *** This re-examines my OWN 5336 framing. ***")
print("="*104)

print("\nTABLE 1 -- *** THERE ARE TWO DIFFERENT VOLUMES OF D_IV^5, AND TWO DIFFERENT DIVERGENCES ***")
N_c,n_C,g=3,5,7
hua=pi**n_C/(N_c*n_C*2**g)
print("   volume                                   value            finite?")
print("   Euclidean/Hua vol of the bounded model   pi^5/1920 = %.6f  YES"%hua)
print("       (corpus: K(0,0) = (N_c n_C 2^g)/pi^{n_C} = %d/pi^5, and K(0,0) = 1/Vol)"%(N_c*n_C*2**g))
print("   INVARIANT (Bergman-metric) volume        infinite          *** NO ***")
print("   ==> the Dirac operator is built from the INVARIANT metric -- that is the one with")
print("       curvature R = -5. The finite Hua number is the volume of the FLAT Euclidean model.")

print("\nTABLE 2 -- so can we just USE the finite Hua volume?")
print("   metric used            volume     scalar curvature R   a_1 density ~ -R   induces gravity?")
print("   invariant (Bergman)    INFINITE   -5                   40/3               yes, but...")
print("   Euclidean (Hua model)  %.6f   0 (FLAT)             0                  *** NO ***"%hua)
print("   ==> *** THE TRADE IS EXACT AND FATAL TO THAT ROUTE: the finiteness comes from using the")
print("       FLAT model, and a flat metric has R = 0, hence NO Einstein-Hilbert term at all. ***")
print("       Finite volume <=> flat <=> no gravity. You cannot buy the volume with that coin.")

print("\nTABLE 3 -- *** BUT I MIS-FRAMED THE PROBLEM IN 5336, AND THIS IS THE CORRECTION ***")
print("   quantity                      is it a TOTAL or a DENSITY?   does infinite volume hurt?")
print("   total EH action  Int R sqrt(g)  TOTAL                        yes -- diverges")
print("   1/G  (Newton coupling)         *** DENSITY / Lagrangian coefficient ***   *** NO ***")
print("   ==> 1/G is a COEFFICIENT, not an integral over the manifold. The total action diverges on")
print("       ANY infinite-volume spacetime -- including ordinary Minkowski space -- and nobody")
print("       calls that a problem with G. *** So the infinite bulk volume is a RED HERRING for")
print("       1/G, and my 5336 implied otherwise. Correcting my own framing. ***")

print("\nTABLE 4 -- the divergence that ACTUALLY threatens 1/G is ULTRAVIOLET (small t)")
print("   Sakharov:  W = -(1/2) Int_0^inf (dt/t) Tr e^{-t D^2}")
print("   the a_1 term contributes  ~ a_1 Int dt t^{-n/2}   with n = dim = 10")
n=10
print("   Int_eps^inf dt t^{-%d/2} = eps^{1-%d/2}/(%d/2 - 1) = eps^{-%d}/%d"%(n,n,n,n//2-1,n//2-1))
print("   ==> diverges as eps -> 0. *** THIS is a UV divergence, cured by a CUTOFF, not by a volume")
print("       normalization. *** With a cutoff eps:  1/G  ~  a_1density x eps^{-4}/4  -- FINITE.")

print("\nTABLE 5 -- so does the banked Szego/Hua machinery do the job?")
print("   machinery                       what it regularizes    is that the 1/G divergence?")
print("   Szego measure (probability-      the BOUNDARY measure   *** NO -- IR/normalization ***")
print("      normalized on the Shilov)     -- an IR/total object")
print("   Hua volume pi^5/1920             the Euclidean VOLUME   *** NO -- IR, and it is flat ***")
print("   a UV cutoff (e.g. Koons tick)    the small-t end        *** YES -- this is the one ***")
print("   ==> the banked machinery is IR/normalization machinery. The 1/G problem is UV.")
print("       *** RIGHT TOOLBOX, WRONG SHELF. ***")

print("\nTABLE 6 -- what the corpus DOES supply for the UV end")
print("   Koons tick  t_Planck x alpha^{C_2^2}  ~ 10^-120 s   (T2405, banked)")
print("   N_max = 137 spectral cap                            (banked)")
print("   ==> BST already carries a natural UV cutoff. *** That -- not the Szego measure -- is what")
print("       a finite 1/G would have to be built on. I have NOT built it; I am naming the shelf. ***")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) *** THE SZEGO/HUA ROUTE DOES NOT MAKE 1/G FINITE, AND THE REASON IS EXACT: *** the Hua")
print("     volume pi^5/1920 is FINITE because it is the volume of the FLAT bounded model, and a")
print("     flat metric has R = 0 -- so it induces NO Einstein-Hilbert term. Finite volume and")
print("     nonzero curvature are bought with different coins here; you cannot spend one twice.")
print()
print(" (2) *** AND I AM CORRECTING MY OWN 5336 FRAMING. *** I reported the infinite bulk volume as")
print("     the obstruction. It is not the obstruction to 1/G. *** 1/G is a Lagrangian COEFFICIENT,")
print("     a density -- not an integral over the manifold. *** The total action diverges on any")
print("     infinite-volume spacetime, Minkowski included, and that has never been a problem for G.")
print("     My a_1 DENSITY = 40/3 was already the right object; I under-read my own result.")
print()
print(" (3) *** THE REAL DIVERGENCE IS UV (small t), and it is curable: *** with a cutoff eps,")
print("     1/G ~ a_1density x eps^{-4}/4 in dim 10 -- finite. The Szego measure and the Hua volume")
print("     are IR/normalization machinery and address the wrong end. RIGHT TOOLBOX, WRONG SHELF.")
print()
print(" (4) THE CORPUS DOES CARRY A UV CUTOFF -- the Koons tick (T2405) and the N_max spectral cap.")
print("     *** That is where a finite 1/G would have to come from. I have NOT built it; naming the")
print("     shelf is not stocking it. *** @Lyra: Section 11 stays at 'the EH density falls out with")
print("     a definite sign'; the cutoff-based 1/G is the next real computation, not a done one.")
