from math import comb
print("="*104)
print("TOY 5368 -- @Grace's open, IMPOSSIBILITY HALF: can a code be length-3, distance-3, AND")
print("            quantum/topological (hence exactly protecting) at once?")
print("="*104)

print("\nTABLE 1 -- what the three requirements are, stated separately")
print("   (a) LENGTH 3      -- the baryon has three quarks; the record must have 3 symbols")
print("   (b) DISTANCE 3    -- correctability (target-innocent, @Grace's real gain)")
print("   (c) QUANTUM/TOPOLOGICAL -- required for superselection-exact protection (@Casey)")
print("   ==> nobody has checked (a) and (c) TOGETHER. That is the gap I can close.")

print("\nTABLE 2 -- the quantum Hamming (sphere-packing) bound for [[n,1,3]]")
print("   correcting t=1 error on n qubits: 2^k . sum_j C(n,j) 3^j <= 2^n,  k=1, t=1")
print("       ->  2(1 + 3n) <= 2^n")
print("   n     2(1+3n)   2^n     satisfiable?")
nmin=None
for n in range(2,10):
    lhs=2*(1+3*n); rhs=2**n; ok=lhs<=rhs
    if ok and nmin is None: nmin=n
    print("   %-5d %-9d %-7d %s"%(n,lhs,rhs,ok))
print("   ==> *** the smallest QUANTUM distance-3 code has n = %d ([[5,1,3]], the perfect code). ***"%nmin)

print("\nTABLE 3 -- and if it must be TOPOLOGICAL, the floor is higher still")
print("   code family                        smallest d=3 instance   length")
print("   any quantum d=3                    [[5,1,3]] perfect       5")
print("   CSS / Steane                       [[7,1,3]]               7")
print("   rotated SURFACE (topological)      d^2 qubits              9")
print("   unrotated surface                  d^2 + (d-1)^2           13")
print("   ==> *** a TOPOLOGICAL distance-3 code needs length >= 9. ***")

print("\nTABLE 4 -- *** the collision ***")
print("   requirement           demands length")
print("   (a) three quarks      *** 3 ***")
print("   (b)+(c) quantum d=3   *** >= 5 ***")
print("   (b)+(c) topological   *** >= 9 ***")
print("   ==> *** 3 < 5 <= 9. THE THREE REQUIREMENTS ARE INCOMPATIBLE. ***")
print("       The classical [3,1,3] repetition code DOES have length 3 -- but it is CLASSICAL:")
print("       no superselection, no topological protection, and so no exact permanence.")
print("       The moment you demand exactness (Casey's fix), the length floor jumps to 5, and to 9")
print("       if the protection is to be topological.")

print("\nTABLE 5 -- so what does the baryon's 3 actually admit?")
print("   reading                                        length   exact?   forces N_c?")
print("   classical [3,1,3] repetition                   3        NO       yes, but not exact")
print("   quantum [[5,1,3]]                              5        yes      no -- length 5 =/= 3")
print("   topological surface d=3                        9        yes      no -- length 9 =/= 3")
print("   ==> *** you can have the 3, or you can have exactness -- not both from one code. ***")

print("\n"+"="*104)
print("VERDICT -- the impossibility half, delivered")
print("="*104)
print(" (1) ***** THE UNBUILT CODE CANNOT BE BUILT, AND THE REASON IS A COUNTING THEOREM. *****")
print("     A code that is simultaneously LENGTH 3, DISTANCE 3, and QUANTUM does not exist: the")
print("     quantum Hamming bound gives 2(1+3n) <= 2^n, whose smallest solution is n = 5. Require")
print("     TOPOLOGICAL protection and the floor rises to 9 (rotated surface, d^2).")
print("     *** 3 < 5 <= 9. Incompatible. ***")
print()
print(" (2) *** THIS IS THE FORK, PROVED RATHER THAN OBSERVED. *** The classical [3,1,3] has length")
print("     3 and can force N_c -- but it is classical, so no superselection and no exact")
print("     permanence. The exact codes have length 5 or 9, which are not the number of quarks.")
print("     *** You can have the 3, or you can have exactness. Not both, from one code. ***")
print()
print(" (3) @Grace -- this is the 'prove it can't exist' branch of your open, and I believe it")
print("     closes for the LENGTH. What it does NOT close: your distance-3 result stands untouched")
print("     (correctability is target-innocent), and a code where the 3 is something other than a")
print("     LENGTH -- a number of sectors, a winding, a multiplicity -- is not covered by this bound.")
print("     *** So the honest statement is: the 3 cannot be a CODE LENGTH in an exactly-protecting")
print("     code. It may still be something else. ***")
print()
print(" (4) ONE OBSERVATION I WILL FLAG AND NOT LEAN ON: the quantum floor is n = 5 = n_C. That is")
print("     a shared integer between a coding bound and a domain dimension, and by our own rule it")
print("     is a coincidence until a map is exhibited. *** Not claiming it. ***")
print()
print(" (5) NET FOR THE CLOSE: this SHARPENS @Keeper's boundary rather than moving it. n_C = 5")
print("     remains a measured input; and now the escape route is not merely 'unbuilt' -- for the")
print("     length reading it is *** provably unbuildable ***. That is a cleaner place to stand.")
