import numpy as np
from math import log10
print("="*104)
print("TOY 5364 -- IS THE PROTON STABLE BY ERROR-CORRECTION (prize) OR BY TOPOLOGICAL WINDING")
print("            (circular)?  Are they one object or two?  Decidable -- so decide it.")
print("="*104)

print("\nTABLE 1 -- *** first, confirm @Keeper's circularity charge on the topological route ***")
n=5
print("   topological claim: baryon number = winding count = n - 2")
print("   at n = 5: winding = %d = N_c ."%(n-2))
print("   but n - 2 = a, the FK short-root multiplicity -- the SAME a behind the Wallach point,")
print("   N_c = a, and C_2 = 2a (5362).")
print("   ==> *** so 'baryon number = n-2' says 'baryon number = a', which is a PROPERTY OF THE")
print("       DOMAIN. It describes D_IV^5; it cannot force it. @Keeper's charge is correct. ***")
print("   by contrast the coding route gives 3 from Singleton + [3,1,3] minimality -- no reference")
print("   to the domain at all. *** Target-innocent. ***")

print("\nTABLE 2 -- *** are they the SAME OBJECT? Partly -- and the part that differs is the point ***")
print("   SHARED STRUCTURE: the baryon's 3 quarks ARE the 3 symbols of [3,1,3]. Same three things.")
print("   DIFFERENT CLAIM about what keeps the proton alive:")
print("     topological : B is EXACTLY CONSERVED (a symmetry)         -> tau_p = INFINITE")
print("     coding      : B is MAINTAINED BY ACTIVE CORRECTION        -> tau_p FINITE, set by the")
print("                   (a process, and processes have failure rates)   DOUBLE-error rate")
print("   ==> *** SAME STRUCTURE, DIFFERENT MECHANISM -- and the mechanisms make DIFFERENT")
print("       PREDICTIONS. That is what makes this decidable rather than a matter of taste. ***")

print("\nTABLE 3 -- the coding route's failure mode, computed")
print("   [3,1,3] corrects ONE error per window. It FAILS when >= 2 symbols are hit in one window.")
print("   P(fail per window) = C(3,2) p^2 (1-p) + p^3  ~  3 p^2   for small p")
for p in (1e-10,1e-20,1e-40):
    print("      p = %-8.0e -> P(fail per window) ~ %.2e"%(p,3*p*p))
print("   ==> *** the coding route CANNOT give an exactly stable proton. It gives a finite lifetime. ***")

print("\nTABLE 4 -- so INVERT the observation: what per-symbol error rate does the bound require?")
tau_obs_yr=1e34; s_per_yr=3.156e7; tau_s=tau_obs_yr*s_per_yr
t_tick=6.392e-121                      # Koons tick, T2405
N=tau_s/t_tick
pmax=(1.0/(3*N))**0.5
print("   observed bound      tau_p > 1e34 yr = %.3e s"%tau_s)
print("   correction window   = Koons tick = %.3e s   (T2405)"%t_tick)
print("   windows in that time N = %.2e"%N)
print("   need 3 p^2 N < 1  ->  *** p < %.2e per symbol per tick ***"%pmax)
print("   ==> a HARD CONSTRAINT the coding route must satisfy -- and the topological route does not")
print("       make it at all. *** That asymmetry IS the discriminator. ***")

print("\nTABLE 5 -- what each route owes")
print("   route          forces N_c = 3?              target-innocent?   owes")
print("   topological    no (winding = a = domain)    *** NO ***         nothing -- it is descriptive")
print("   coding         YES ([3,1,3] minimality)     *** YES ***        p < %.0e, underived"%pmax)
print("   ==> the prize is real and it has a price: *** the coding route forces N_c = 3 but buys a")
print("       FINITE proton lifetime and an undelivered bound on the substrate error rate. ***")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) *** THEY ARE THE SAME STRUCTURE BUT DIFFERENT MECHANISMS, and the difference is")
print("     OBSERVABLE. *** The 3 quarks ARE the 3 code symbols -- that part is one object. But")
print("     'B is exactly conserved' (symmetry -> infinite lifetime) and 'B is maintained by active")
print("     correction' (process -> finite lifetime) are DIFFERENT CLAIMS about the same three things.")
print()
print(" (2) *** @Keeper's circularity charge is CONFIRMED: *** baryon-number-as-winding = n-2 = a,")
print("     the same a behind N_c, the Wallach point and C_2 = 2a. It DESCRIBES the domain and")
print("     cannot force it. The coding route uses only Singleton + repetition minimality -- no")
print("     domain reference -- so it is the only target-innocent one. That much is settled.")
print()
print(" (3) *** BUT THE PRIZE HAS A PRICE, AND IT SHOULD BE STATED WITH THE CLAIM: the coding route")
print("     CANNOT give an exactly stable proton. *** Error correction is a process with a failure")
print("     mode (two hits in one window), so it predicts a FINITE lifetime. Anyone claiming")
print("     'the record error-corrects, therefore N_c = 3' is also claiming the proton decays.")
print()
print(" (4) *** AND THAT MAKES IT FALSIFIABLE, WHICH IS THE GOOD NEWS: *** inverting tau_p > 1e34 yr")
print("     with the Koons tick as the correction window requires p < %.0e per symbol per tick."%pmax)
print("     The topological route makes NO such demand. *** The asymmetry is the discriminator, and")
print("     the bound is a real, undelivered obligation on the coding route -- nothing I have derives")
print("     a substrate error rate. ***")
print()
print(" (5) @Lyra -- my read: the coding route is the ONLY one that can force N_c = 3, so it is the")
print("     right route; but it must ship with the finite-lifetime consequence and the error-rate")
print("     bound as OWED, not as a footnote. Claiming the forcing while implying exact stability")
print("     would be taking both mechanisms at once.")
