"""TOY 5717 — T2622 at p = 5: the kernel BY THE CONSTRUCTION RULE (calibration #28). Lyra 2026-09-07.
Prereg .lyra_predictions_p5_kernel_2026-09-07.txt sha256 de24bf05, hashed before this file.
B = (a,b)_Q with a = -2, b = -5: i^2 = a, j^2 = b, k = ij, k^2 = -ab. Elements x + y i + z j + w k.
trd = 2x, nrd = x^2 - a y^2 - b z^2 + a b w^2. Find a maximal order by closure, take its trace-zero
lattice with the reduced norm, test local (an)isotropy exhaustively, count units. Verdicts computed.
"""
from fractions import Fraction as F
import itertools, math
a, b = -2, -5
def mul(p, q):
    x1,y1,z1,w1 = p; x2,y2,z2,w2 = q
    return (x1*x2 + a*y1*y2 + b*z1*z2 - a*b*w1*w2,
            x1*y2 + y1*x2 - b*z1*w2 + b*w1*z2,
            x1*z2 + z1*x2 + a*y1*w2 - a*w1*y2,
            x1*w2 + w1*x2 + y1*z2 - z1*y2)
def trd(p): return 2*p[0]
def nrd(p): x,y,z,w = p; return x*x - a*y*y - b*z*z + a*b*w*w
def integral(p): return trd(p).denominator == 1 and nrd(p).denominator == 1
# ---- Z-module machinery over Q^4 via Hermite normal form on a common denominator
def hnf_basis(vectors):
    """Z-basis (HNF) of the Z-span of rational 4-vectors."""
    if not vectors: return []
    den = 1
    for v in vectors:
        for c in v: den = den*c.denominator//math.gcd(den, c.denominator)
    rows = [[int(c*den) for c in v] for v in vectors]
    # integer HNF by repeated gcd elimination
    m = [r[:] for r in rows]; basis = []
    for col in range(4):
        piv = None
        for r in m:
            if r[col] != 0 and all(r[c]==0 for c in range(col)):
                piv = r if piv is None else piv
        # gather rows with support starting at col
        cand = [r for r in m if any(r[c]!=0 for c in range(4)) and all(r[c]==0 for c in range(col))]
        if not cand: continue
        while True:
            cand = [r for r in cand if r[col] != 0] + [r for r in cand if r[col] == 0]
            nz = [r for r in cand if r[col] != 0]
            if len(nz) <= 1: break
            nz.sort(key=lambda r: abs(r[col]))
            p = nz[0]
            for r in nz[1:]:
                q = r[col] // p[col]
                for c in range(4): r[c] -= q*p[c]
            cand = nz + [r for r in cand if r[col] == 0]
        nz = [r for r in cand if r[col] != 0]
        if nz:
            p = nz[0]
            if p[col] < 0: p = [-c for c in p]
            basis.append(p)
            m = [r for r in m if r is not nz[0]]
            # reduce others by p at col
            for r in m:
                if r[col] != 0:
                    q = r[col] // p[col]
                    for c in range(4): r[c] -= q*p[c]
    return [tuple(F(c, den) for c in r) for r in basis]
def close(gens, maxiter=8):
    """Z-module generated by gens closed under multiplication; returns basis or None if it blows up."""
    B = hnf_basis(gens)
    for _ in range(maxiter):
        prods = [mul(u, v) for u in B for v in B]
        B2 = hnf_basis(B + prods)
        if all(integral(v) for v in B2) is False: return None
        if len(B2) == len(B) and all(any(all(x==y for x,y in zip(u,v)) for v in B2) for u in B):
            return B2
        B = B2
        if len(B) > 4: return None
    return None
def disc(B):
    # |det(trd(b_i b_j))| ; reduced discriminant = sqrt
    M = [[trd(mul(u, v)) for v in B] for u in B]
    from sympy import Matrix
    return abs(Matrix(M).det())
one = (F(1),F(0),F(0),F(0)); I=(F(0),F(1),F(0),F(0)); J=(F(0),F(0),F(1),F(0)); K=(F(0),F(0),F(0),F(1))
O = close([one, I, J, K]); d0 = disc(O); print("start order: disc(trace form) =", d0, " reduced disc =", math.isqrt(int(d0)))
# candidates with denominators 2 or 4
cands = []
for den in (2, 4):
    rng = range(-2*den, 2*den+1)
    for x,y,z,w in itertools.product(rng, repeat=4):
        v = (F(x,den),F(y,den),F(z,den),F(w,den))
        if integral(v) and any(c.denominator > 1 for c in v): cands.append(v)
print("integral candidates with denominators 2/4:", len(cands))
improved = True
while improved:
    improved = False
    for v in cands:
        O2 = close(O + [v])
        if O2 is not None and len(O2) == 4:
            d2 = disc(O2)
            if d2 < disc(O):
                O = O2; improved = True
                print("  adjoined", tuple(str(c) for c in v), "-> disc", d2, " reduced", math.isqrt(int(d2)))
                break
rd = math.isqrt(int(disc(O)))
print("MAXIMAL ORDER basis:", [tuple(str(c) for c in v) for v in O], " reduced disc =", rd)
# trace-zero lattice
from sympy import Matrix, Rational
# solve trd = 0 within O: find Z-basis of kernel of the linear map O -> Z, v -> 2x
coef = [2*v[0] for v in O]  # rational coefficients on the basis
den = 1
for c in coef: den = den*c.denominator//math.gcd(den, c.denominator)
ic = [int(c*den) for c in coef]
# kernel of integer row vector ic in Z^4 via HNF of the lattice {n : sum n_i ic_i = 0}
from sympy import Matrix as SM
M = SM([ic])
ns = M.nullspace()
# integer kernel basis: use smith/ hermite via sympy's method on transposed
import sympy
Kb = []
# brute: small search for kernel vectors then HNF
vecs = []
for n in itertools.product(range(-3,4), repeat=4):
    if sum(x*y for x,y in zip(n, ic)) == 0 and any(n): vecs.append(n)
# lattice spanned in Z^4 -> reduce to rank-3 basis via hnf on integer rows
def ihnf(rows):
    rows = [list(r) for r in rows]; basis=[]
    for col in range(4):
        cand=[r for r in rows if any(r) and all(r[c]==0 for c in range(col))]
        while True:
            nz=[r for r in cand if r[col]!=0]
            if len(nz)<=1: break
            nz.sort(key=lambda r: abs(r[col])); p=nz[0]
            for r in nz[1:]:
                q=r[col]//p[col]
                for c in range(4): r[c]-=q*p[c]
        nz=[r for r in cand if r[col]!=0]
        if nz:
            p=nz[0]
            if p[col]<0: p=[-c for c in p]
            basis.append(p); rows=[r for r in rows if r is not nz[0]]
            for r in rows:
                if r[col]!=0:
                    q=r[col]//p[col]
                    for c in range(4): r[c]-=q*p[c]
    return basis
kb = ihnf(vecs)
K5 = [tuple(sum(F(n[i])*O[i][c] for i in range(4)) for c in range(4)) for n in kb]
assert len(K5) == 3 and all(trd(v) == 0 for v in K5)
def bil(u, v): return (nrd(tuple(x+y for x,y in zip(u,v))) - nrd(u) - nrd(v))/2
G = [[bil(u, v) for v in K5] for u in K5]
print("trace-zero lattice K_5: basis", [tuple(str(c) for c in v) for v in K5])
print("  Gram of nrd (bilinear form, half of the polar):", [[str(x) for x in r] for r in G], " det =", SM(G).det())
# integral quadratic form coefficients: q(n) = sum G_ij n_i n_j ; scale to integers
gden = 1
for r in G:
    for x in r: gden = gden*x.denominator//math.gcd(gden, x.denominator)
Gi = [[int(x*gden) for x in r] for r in G]
print("  scaled Gram (x%d):" % gden, Gi, " det =", SM(Gi).det())
def q(n): return sum(Gi[i][j]*n[i]*n[j] for i in range(3) for j in range(3))
def has_primitive_zero(p, k):
    mod = p**k
    for n in itertools.product(range(mod), repeat=3):
        if any(x % p for x in n) and q(n) % mod == 0: return True
    return False
res = {}
for p, k in ((5,3),(2,6),(3,3),(7,2),(11,2),(13,2)):
    res[p] = has_primitive_zero(p, k); print("  primitive zero of q mod %d^%d: %s" % (p, k, res[p]))
p1 = (not res[5]) and all(res[p] for p in (2,3,7,11,13))
# units
units = 0
for n in itertools.product(range(-3,4), repeat=4):
    v = tuple(sum(F(n[i])*O[i][c] for i in range(4)) for c in range(4))
    if nrd(v) == 1: units += 1
print("  |O^x| (nrd = 1, box search) =", units)
# <1,1,5> control at 5
def q115(n): return n[0]**2 + n[1]**2 + 5*n[2]**2
z115 = any(any(x%5 for x in n) and q115(n) % 125 == 0 for n in itertools.product(range(125), repeat=3))
print("  <1,1,5> primitive zero mod 5^3:", z115)
print("  P1 K_5 anisotropic exactly at {5, inf} (checked at 2,3,5,7,11,13):", "HIT" if p1 else "MISS")
print("  P2 K_5 not <1,1,5> (which is isotropic at 5):", "HIT" if (z115 and not res[5]) else "MISS")
print("  P3 reduced disc = 5 and |O^x| = 6:", "HIT" if (rd == 5 and units == 6) else "MISS (rd=%d, units=%d)" % (rd, units))
print("  P4 predicted comb spacing 2pi/ln5 = %.4f (not computed here)" % (2*math.pi/math.log(5)))

# ---- SECOND PASS (same run, appended after the first output): LLL-reduce before counting units.
# The first pass's unit count searched a box on an UNREDUCED basis (coordinates ~ 50) and missed even 1;
# that was an instrument fault, not a finding. Reduce with the positive-definite form nrd, then count.
def lll(basis, form, delta=F(3,4)):
    """LLL on rational vectors with a positive-definite bilinear form 'form(u,v)'."""
    B = [list(v) for v in basis]; n = len(B)
    def sub(u, v, k): return tuple(x - k*y for x, y in zip(u, v))
    def gso(B):
        Bs = []; mu = [[F(0)]*n for _ in range(n)]
        for i in range(n):
            v = tuple(B[i])
            for j in range(i):
                mu[i][j] = form(tuple(B[i]), Bs[j]) / form(Bs[j], Bs[j])
                v = sub(v, Bs[j], mu[i][j])
            Bs.append(v)
        return Bs, mu
    k = 1
    while k < n:
        Bs, mu = gso(B)
        for j in range(k-1, -1, -1):
            r = round(mu[k][j])
            if r: B[k] = list(sub(tuple(B[k]), tuple(B[j]), F(r))); Bs, mu = gso(B)
        if form(Bs[k], Bs[k]) >= (delta - mu[k][k-1]**2) * form(Bs[k-1], Bs[k-1]): k += 1
        else: B[k], B[k-1] = B[k-1], B[k]; k = max(k-1, 1)
    return [tuple(v) for v in B]
Ored = lll(O, bil)
print("\nSECOND PASS — LLL-reduced maximal order basis:", [tuple(str(c) for c in v) for v in Ored],
      " nrd of basis:", [str(nrd(v)) for v in Ored])
units = 0; unit_list = []
for n in itertools.product(range(-2,3), repeat=4):
    v = tuple(sum(F(n[i])*Ored[i][c] for i in range(4)) for c in range(4))
    if nrd(v) == 1: units += 1; unit_list.append(tuple(str(c) for c in v))
print("  |O^x| on the reduced basis =", units, " units:", unit_list)
K5red = lll(K5, bil)
Gr = [[bil(u, v) for v in K5red] for u in K5red]
print("  K_5 reduced basis:", [tuple(str(c) for c in v) for v in K5red])
print("  K_5 reduced Gram (bilinear):", [[str(x) for x in r] for r in Gr], " diagonal nrd values:", [str(nrd(v)) for v in K5red], " det =", SM(Gr).det())
print("  P3 (re-scored on the reduced basis): reduced disc = 5 and |O^x| = 6:", "HIT" if (rd == 5 and units == 6) else "MISS (rd=%d, units=%d)" % (rd, units))
