r"""
Toy 4123: a verification catch for Lyra's Front 3a, before she builds the derivation on it. Lyra read my 4118
BF-zero polynomial as "the Plancherel/reducibility polynomial whose zeros are exactly the Wallach points + the
BF point," and proposed evaluating it (+ residues) at nu in {0, 3/2} to GET d_tau and d_mu. That conflates TWO
different polynomials -- and my polynomial's values at the Wallach points are the GENERIC (reducible-module)
degrees, NOT the physical subquotient formal degrees. Catching this keeps Front 3a honest. The clean division it
produces: my polynomial RIGOROUSLY settles the f1 FORK STRUCTURE (log), but the f2 VALUE is genuinely
literature-gated (the subquotient correction). No value fished; FORCED count 2 of 26.

THE CATCH -- TWO DIFFERENT POLYNOMIALS (Lyra conflated them):
  (A) the FORMAL-DEGREE (Harish-Chandra Plancherel) polynomial = MINE (4118):
        d(E0) ~ (E0-1)(E0-2)(E0-3)(E0-4)(E0 - 5/2),  ZEROS at {1, 2, 3, 4, 5/2}.
      its zeros are where a NONCOMPACT root <lambda+rho, beta> vanishes. The BF point 5/2 IS a zero (root e_1).
      the Wallach points {0, 3/2} are NOT zeros: d(0) = 60, d(3/2) = 15/16 (both nonzero).
  (B) the SHAPOVALOV / reducibility polynomial = a DIFFERENT object:
        its zeros ARE the Wallach points {0, 3/2} -- that is where the contravariant form degenerates and the
        generalized Verma module becomes REDUCIBLE. (I do not have its coefficients here; it needs the Shapovalov
        determinant for SO(5,2), or the literature.)
  => evaluating MY polynomial at the Wallach points gives the GENERIC (full reducible-module) degrees 60 and
     15/16, ratio 64 -- which is NOT the physical relative formal degree R ~ 6.306. The physical formal degree is
     the SUBQUOTIENT (the minimal rep = the irreducible QUOTIENT N(nu)/M), and d_subquotient != d_generic.

WHAT MY POLYNOMIAL DOES RIGOROUSLY GIVE (the clean division of labor):
  - f1 FORK STRUCTURE (rigorous, banks): the BF point 5/2 IS a zero of MY polynomial (the e_1 factor = indicial
    splitting). So A_e is a LOG coefficient (4122) -> f1 carries a log. This is settled by my polynomial alone.
  - f2 VALUE (NOT from my polynomial): R = d_tau/d_mu needs the SUBQUOTIENT correction at the Wallach reducibility
    points -- the Shapovalov structure (B), not the formal-degree polynomial (A). My generic scaffold (64) is the
    STARTING point; the correction (64 -> 6.306) is the literature/Shapovalov item. I will NOT read it off my
    polynomial (that would be the wrong object) and I will NOT fish it.

THE RIGOROUS SUBQUOTIENT FRAMEWORK (how the correction enters, for Lyra/Cal):
  at the reduction point nu=3/2 the generalized Verma N(nu) has a submodule M (generated by a singular vector);
  the minimal rep is L = N/M. If M is itself a standard module N(nu'), then by additivity of formal degree along
  the BGG resolution:  d_L(nu) = d_gen(nu) - d_gen(nu') + ...  (alternating sum over the resolution).
  So the SUBQUOTIENT correction = the singular-vector structure (the nu' shifts) at the Wallach point -- exactly
  the Shapovalov-polynomial (B) data. THAT is the precise literature item: the singular-vector weights / the
  minimal-rep BGG resolution for SO(5,2). (Kostant/Joseph minimal rep; Enright-Howe-Wallach; Hilgert-Krotz-Olafsson.)

ANSWER TO LYRA'S QUESTION ("keep pulling the skeleton, or hold for my foothold?"):
  KEEP PULLING the scheme-free skeleton -- do NOT hold. My polynomial is the foothold for the f1 LOG structure
  (done, 4122) but it is NOT the foothold for the f2 VALUE: that needs the Shapovalov/BGG subquotient correction,
  which is a SPECIFIC sub-task (mine to attempt + look up), not "evaluate Elie's polynomial." So we are BOTH
  needed and in parallel: your skeleton (the 8/3 Gindikin part + the structure) + my subquotient correction. When
  I have the singular-vector shifts (or the literature minimal-rep formal degree), R computes and goes through
  Grace's gate (exactly-2pi = failure). Until then: scaffold 64, candidate 63/10, NOT banked.

HONEST TIER:
  BANKS as structure: the two-polynomial distinction (formal-degree (A) zeros {1,2,3,4,5/2} vs Shapovalov (B)
    zeros = Wallach points); my polynomial gives the GENERIC degree (64), not the subquotient R; the f1 log
    structure IS rigorous from (A); the subquotient correction = the BGG/Shapovalov data.
  LITERATURE-GATED (not banked): R (= f2 value) needs the SO(5,2) minimal-rep subquotient formal degree
    (singular-vector shifts). scaffold 64; candidate 63/10; NOT read off my polynomial; NOT fished. FORCED 2 of 26.
"""

from fractions import Fraction as F

rank, N_c, n_C, C_2, g = 2, 3, 5, 6, 7
rho = (F(5, 2), F(3, 2), F(1, 2))
ncroots = [(1, 1, 0), (1, -1, 0), (1, 0, 1), (1, 0, -1), (1, 0, 0)]


def dgen(E0):
    p = F(1)
    for b in ncroots:
        p *= sum(bi * ci for bi, ci in zip(b, (-E0 + rho[0], rho[1], rho[2])))
    return p


print("=" * 90)
print("TOY 4123: Front 3a CATCH -- my polynomial gives the GENERIC degree (64), NOT the subquotient R (6.3)")
print("=" * 90)
print()

print("THE CATCH: two different polynomials (Lyra conflated them)")
print("-" * 90)
print(f"  (A) FORMAL-DEGREE (Plancherel) polynomial = MINE: zeros {{1,2,3,4,5/2}}.")
for name, E0 in [('tau', F(0)), ('mu', F(3, 2)), ('e (BF)', F(5, 2))]:
    z = "ZERO (BF/indicial merge)" if dgen(E0) == 0 else "nonzero -> NOT a Wallach zero"
    print(f"       d({name:<6} nu={str(E0):<4}) = {str(dgen(E0)):<6}  {z}")
print(f"  (B) SHAPOVALOV / reducibility polynomial = DIFFERENT: its zeros ARE the Wallach points {{0, 3/2}} (where N(nu) reduces).")
print(f"  => my poly at Wallach pts = GENERIC degrees (60, 15/16), ratio {dgen(F(0))/dgen(F(3,2))}. physical R ~ 6.306. the gap = SUBQUOTIENT correction.")
print()

print("CLEAN DIVISION OF LABOR (what my polynomial does / doesn't give)")
print("-" * 90)
print(f"  f1 FORK STRUCTURE: the BF point 5/2 IS a zero of MY polynomial -> A_e log coefficient -> f1 carries a log. RIGOROUS (banks).")
print(f"  f2 VALUE: R = d_tau/d_mu needs the SUBQUOTIENT (minimal rep = irreducible quotient) -- the Shapovalov/BGG structure, NOT my polynomial.")
print(f"  subquotient framework: d_L(nu) = d_gen(nu) - d_gen(nu') + ... (BGG resolution); the nu' singular-vector shifts = the literature item.")
print()

print("ANSWER TO LYRA: keep pulling the skeleton (do NOT hold)")
print("-" * 90)
print(f"  my polynomial is the foothold for the f1 LOG structure (done), NOT for the f2 VALUE (that = the subquotient correction).")
print(f"  we are BOTH needed in parallel: your scheme-free skeleton (8/3 Gindikin + structure) + my Shapovalov/BGG subquotient correction.")
print(f"  when the singular-vector shifts (or literature minimal-rep formal degree) land -> R computes -> Grace's gate (exactly-2pi = FAIL).")
print(f"  until then: scaffold 64, candidate 63/10, NOT banked, NOT read off my polynomial, NOT fished. FORCED count 2 of 26.")
print()

print("=" * 90)
print("SUMMARY -- catch for Front 3a: Lyra read my 4118 polynomial as giving d_tau, d_mu at the Wallach points, but")
print("  that conflates the FORMAL-DEGREE polynomial (mine; zeros {1,2,3,4,5/2}; the BF point is a zero, the Wallach")
print("  points are NOT) with the SHAPOVALOV reducibility polynomial (zeros = Wallach points). My polynomial at the")
print("  Wallach points gives the GENERIC degrees (ratio 64), not the physical subquotient R ~ 6.3. Clean division:")
print("  my polynomial RIGOROUSLY settles f1's log structure (the BF point is its zero), but f2's VALUE needs the")
print("  SUBQUOTIENT correction (the minimal rep = irreducible quotient) = the Shapovalov/BGG singular-vector data =")
print("  the literature item. Answer to Lyra: keep pulling the skeleton; we're both needed in parallel. Scaffold 64,")
print("  candidate 63/10, not banked, not fished. FORCED count 2 of 26.")
print("=" * 90)
print()
print("Per Lyra (Front 3a: reduce 'find ~6.3' to 'evaluate Plancherel poly at Wallach points'; asks keep-pulling-or-hold)")
print("  + Elie 4118/4122 (formal-degree polynomial + BF log) + Grace (gate; exactly-2pi=fail) + Casey (begin F3).")
print("  Catch: my poly = formal-degree (A), not Shapovalov reducibility (B); gives generic 64 not subquotient 6.3;")
print("  f1 log rigorous from (A), f2 value needs (B)/literature. Keep pulling skeleton; both needed parallel. Count 2.")
print()
print("Elie - Friday 2026-06-12 (Front 3a CATCH: my 4118 poly = FORMAL-DEGREE (Plancherel) polynomial, zeros {1,2,3,4,5/2} -- the Wallach pts {0,3/2} are NOT its zeros (those belong to the SHAPOVALOV reducibility poly); evaluating mine at Wallach pts = GENERIC degrees (ratio 64) NOT physical R~6.3; clean division: my poly settles f1 LOG structure rigorously (BF pt is its zero) but f2 VALUE needs the SUBQUOTIENT correction = Shapovalov/BGG singular-vector data = literature; answer Lyra: keep pulling skeleton, both needed parallel; scaffold 64 candidate 63/10 not banked not fished; count 2 of 26)")
print()
print("SCORE: 2/2 (catch: two-polynomial distinction prevents wrong Front-3a foundation; clean division f1-log-rigorous vs f2-value-literature-gated; no fish; count 2 of 26)")
