import numpy as np
rng=np.random.default_rng(77)
print("="*80)
print("TASK 1 -- pin the premise. CORPUS FIRST: 'commitment is light' is NOT stated anywhere")
print("="*80)
print("  grep over notes/ for (commitment is light | commit+massless/null/photon | light-absorption+commit)")
print("  returns NOTHING. Like 'observer = position only' (toy 5267), this premise is an ADDITION,")
print("  not a corpus statement. Both candidate premises for Task 1 are un-banked.")
print()
print("="*80)
print("★ AND A CONSISTENCY CHECK THE PREMISE HAS TO PASS -- against the object F989 CONFIRMED")
print("="*80)
print("  The commit order (F989, and what I measured in 5251/5252/5261) is the TIMELIKE order:")
print("        a < b  iff  dt > d_geo(a,b)      -- STRICTLY timelike.")
print("  'Commitment is light' would put commitments on the LIGHT CONE:  dt = d_geo  exactly.")
print()
N=200000
t=rng.uniform(0,2,N); x=rng.normal(size=(N,5)); x/=np.linalg.norm(x,axis=1)[:,None]
i=rng.integers(0,N,N); j=rng.integers(0,N,N)
dt=np.abs(t[j]-t[i]); dg=np.arccos(np.clip(np.sum(x[i]*x[j],axis=1),-1,1))
tl=(dt>dg).mean(); 
for tol in [1e-2,1e-3,1e-6]:
    print("   fraction of pairs NULL to within %.0e : %.6f"%(tol,(np.abs(dt-dg)<tol).mean()))
print("   fraction of pairs strictly TIMELIKE      : %.6f"%tl)
print()
print("  => the null set is MEASURE ZERO. If commitments were literally light-like related,")
print("     the commitment order would be EMPTY -- no relations at all in any sprinkling.")
print("  => so 'commitment is light' CANNOT mean the commitment EVENTS are null-related.")
print()
print("="*80)
print("★★ THE DISTINCTION THAT RESOLVES IT -- and it is the conflation to watch")
print("="*80)
print("  TWO DIFFERENT STRUCTURES are being called 'the commit order':")
print("   (A) the order of commitment EVENTS      -- TIMELIKE (F989's object; what 5251/5252/5261 measured)")
print("   (B) the CHANNEL carrying the record     -- NULL (what 'commitment is light' would constrain)")
print()
print("  These are not the same object. An absorber's worldline is timelike; the photon it absorbs is null.")
print("  => 'commitment is light' constrains (B), the channel -- NOT (A), the event order.")
print("  => so it does NOT contradict F989. But it also does NOT directly force angle-not-depth for (A):")
print("     it forces it for WHAT IS TRANSMITTED, which is a statement about the record, not the order.")
print()
print("  ⟹ FOR @LYRA: the angle-not-depth leg has to run on (B) and then be transferred to (A) EXPLICITLY.")
print("     Assuming it transfers is the conflation. That transfer is the owed step, and it is not free.")
