import numpy as np, sympy as sp
print("="*92)
print("CAL'S DECISIVE CHEAP TEST: does A^2 TRACK RANK, or is it a coincidence at D_IV^5?")
print("="*92)
print("  From my 5305, A^2 is READABLE OFF ANY vector v of length N, with no fitting and no theta:")
print("     |v_par|^2 = (sum v)^2/N,  |v_perp|^2 = sum v^2 - (sum v)^2/N,  A^2 = 2 |v_perp|^2/|v_par|^2")
print("     i.e.  A^2(v) = 2 [ N * sum(v^2) / (sum v)^2  -  1 ]")
def A2(v):
    v=np.asarray(v,dtype=float); N=len(v)
    return 2*(N*(v**2).sum()/v.sum()**2 - 1)
print("\n  sanity: the exact Koide vector should return A^2 = 2 for ANY theta --")
for th in [0.0,0.7,2.1]:
    v=[1+np.sqrt(2)*np.cos(th+2*np.pi*k/3) for k in range(3)]
    print("     theta = %.1f  ->  A^2 = %.10f"%(th,A2(v)))
print("     ✓ theta-independent, and the estimator is exact. No 45-degree angle used anywhere.")
print()
print("="*92)
print("NOW RUN IT ON THE BANKED OBJECT -- T2517's addresses nu = (rho_1, rho_2, 0)")
print("="*92)
print("  corpus: rho(D_IV^5) = (n_C, N_c)/rank = (5/2, 3/2), and T2517 banks nu = {5/2, 3/2, 0}.")
print("  So the address vector generalises within type IV as  v(n) = ( n/2, (n-2)/2, 0 ).")
n=sp.symbols('n', positive=True)
vs=[n/2,(n-2)/2,sp.Integer(0)]
S1=sum(vs); S2=sum(x**2 for x in vs)
A2sym=sp.simplify(2*(3*S2/S1**2-1))
print("\n     A^2(n) = %s"%sp.simplify(A2sym))
print("\n      n     address vector          A^2      = rank(2)?   = 2?")
for nv in [3,4,5,6,7,8,12,50]:
    v=[nv/2,(nv-2)/2,0.0]
    a=A2(v)
    print("     %3d    (%.1f, %.1f, 0)%s   %.4f      %s        %s"%(nv,v[0],v[1]," "*(6-len("%.1f, %.1f"%(v[0],v[1]))),a,"NO","NO" if abs(a-2)>1e-9 else "YES"))
lim=sp.limit(A2sym,n,sp.oo)
print("\n     limit as n -> infinity : A^2 -> %s"%lim)
sol=sp.solve(sp.Eq(A2sym,2),n)
print("     A^2 = 2 would require n = %s  -- NOT an integer, and not 5."%[sp.nsimplify(s) for s in sol if s.is_real and s>0])
print()
print("="*92)
print("★★★ THE VERDICT -- and it is not the binary Cal expected")
print("="*92)
print("  A^2 on the banked address vector is %.4f at D_IV^5, NOT 2."%A2([2.5,1.5,0.0]))
print("  It does not track rank (rank is 2 for EVERY type-IV domain here, while A^2 varies with n),")
print("  and it never reaches 2 for any integer n. It tends to 1 as n grows.")
print("  ⟹ THE TEST RETURNS NEITHER 'STRUCTURAL' NOR 'COINCIDENCE'. It returns: THE QUANTITY IS NOT")
print("     THERE. A^2 = rank cannot be read off the addresses at all -- at D_IV^5 or anywhere.")
print("  ⟹ This CONFIRMS AND SHARPENS my 5305 negative (I reported ratio 0.5938; that IS A^2/2 =")
print("     %.4f/2, the same number seen from the other side)."%A2([2.5,1.5,0.0]))
print()
print("  ★ SO THE DECISIVE TEST IS BLOCKED UNTIL LYRA'S MAP LANDS -- and that is itself the finding:")
print("    NOBODY SHOULD CLAIM A^2 = rank FROM THE ADDRESSES. The claim has no support on the only")
print("    banked object available, and the test Cal designed cannot even be posed until the")
print("    overlap -> sqrt(mass) map exists. When it does, this estimator runs on its image in one")
print("    line, theta-free, and returns a number that either is 2 or is not.")
print()
print("  ★★ AND THE ESTIMATOR IS THE DELIVERABLE: A^2(v) = 2[N sum(v^2)/(sum v)^2 - 1] is")
print("     pre-registered HERE, before the map exists. Whatever Lyra posts, the check is mechanical")
print("     and cannot be tuned after the fact.")
