from fractions import Fraction as F
print("="*104)
print("TOY 5361 -- BLOCK C, CONDITION 5: is C_2/(2 n_C) = (n_C-2)/n_C a FORCING or an IDENTITY?")
print("  Target-innocence first: before matching at n=5, ask what C_2 is AS A FUNCTION OF n.")
print("="*104)

print("\nTABLE 1 -- *** the load-bearing question nobody asked: is C_2 a function of n? ***")
print("   The corpus records TWO readings of C_2 = 6:")
print("     (i)  'n_C + 1 = C_2'            -- recorded as a 'new substrate identity'")
print("     (ii) the Casimir of the K-type (1,1) of so(n)")
print("   These AGREE at n = 5 (both give 6). *** They are different functions of n. ***")

print("\nTABLE 2 -- compute the (1,1) Casimir for so(n) properly")
print("   C(lambda) = <lambda, lambda + 2 rho>.  For so(n), BOTH B and D series give")
print("       rho_1 = (n-2)/2,  rho_2 = (n-4)/2")
print("   so for lambda = (1,1):")
print("       C = 1(1 + 2 rho_1) + 1(1 + 2 rho_2) = (1 + n-2) + (1 + n-4) = *** 2n - 4 ***")
print("\n   n     C_2 = 2n-4   'n+1' reading   agree?   note")
for n in range(3,10):
    c=2*n-4; alt=n+1
    print("   %-5d %-12d %-15d %-8s %s"%(n,c,alt,c==alt,"<-- they agree ONLY here" if c==alt else ""))
print("   ==> *** C_2 = 2n - 4 = 2(n-2) = 2a, where a = n-2 is the FK multiplicity. ***")
print("       'C_2 = n+1' is TRUE ONLY AT n = 5 -- it is a coincidence of the value, not a formula.")

print("\nTABLE 3 -- *** now run Condition 5 with the CORRECT C_2(n) ***")
print("   Condition 5:   C_2/(2n) = (n-2)/n")
print("   substitute C_2 = 2n-4 = 2(n-2):")
print("       LHS = 2(n-2)/(2n) = (n-2)/n")
print("       RHS =              (n-2)/n")
print("   *** LHS = RHS IDENTICALLY, FOR EVERY n. ***")
print("\n   n     LHS = C_2/(2n)   RHS = (n-2)/n   equal?")
for n in range(3,10):
    L=F(2*n-4,2*n); R=F(n-2,n)
    print("   %-5d %-16s %-15s %s"%(n,str(L),str(R),L==R))
print("   ==> *** CONDITION 5 HOLDS AT EVERY n. IT IS AN IDENTITY, NOT A CONDITION. ***")

print("\nTABLE 4 -- and why it LOOKED unique at n=5 (the diagnosis)")
print("   using the 'C_2 = n+1' reading instead:")
print("       (n+1)/(2n) = (n-2)/n  ->  n+1 = 2(n-2)  ->  n = 5, unique.")
print("   *** So the 'uniqueness at n=5' is an artifact of substituting a VALUE-COINCIDENCE")
print("       (C_2 = n+1, true only at n=5) for the actual FORMULA (C_2 = 2n-4). ***")
print("   The equation was solved for the n at which its own input was valid -- so of course it")
print("   returned that n. That is circular, and the circle is only visible once C_2(n) is written out.")

print("\nTABLE 5 -- the same-name-different-object check (@Keeper's Round-14 discipline)")
print("   'C_2' names two things here: the NUMBER 6, and the FUNCTION 2n-4.")
print("   Condition 5 needs the FUNCTION; the corpus supplied the NUMBER via a formula that")
print("   reproduces it only at n = 5. *** Fourth instance this week of one name, two objects. ***")

print("\n"+"="*104)
print("VERDICT -- Block C, Condition 5")
print("="*104)
print(" (1) ***** CONDITION 5 IS AN IDENTITY, NOT A FORCING. ***** With the correct Casimir")
print("     C_2 = 2n - 4 = 2(n-2) = 2a, both sides of C_2/(2n) = (n-2)/n equal (n-2)/n for EVERY n.")
print("     It holds at n = 5 because it holds everywhere. Verified n = 3..9 (Table 3).")
print()
print(" (2) *** THE APPARENT UNIQUENESS IS AN ARTIFACT. *** It comes from substituting 'C_2 = n+1'")
print("     -- which is true ONLY at n = 5 -- for the actual formula. The equation was then solved")
print("     for the n at which its own input was valid. *** Circular, and invisible until C_2(n) is")
print("     written out as a function. ***")
print()
print(" (3) *** SO BLOCK C's ONE CANDIDATE FORCING DOES NOT FORCE. *** @Keeper: of the 22 uniqueness")
print("     conditions you classified, 21 were selections and Condition 5 was the lone candidate.")
print("     Condition 5 is now an identity. *** On this analysis n_C = 5 is NOT forced by the")
print("     uniqueness set -- the honest close is the boundary you pre-registered (type forced,")
print("     dimension an input), and the minimality derivation does NOT get to lean on Condition 5. ***")
print()
print(" (4) THE ONE GENUINELY NICE THING THAT FALLS OUT: *** C_2 = 2a. *** The Casimir is exactly")
print("     twice the FK short-root multiplicity -- cleaner than 'C_2 = n_C + 1', true for all n,")
print("     and it ties C_2 to the same 'a' that gives the Wallach point a/2 (5324) and N_c = a")
print("     (5344). That is a real structural relation and it is NOT dimension-selecting.")
print()
print(" (5) I am NOT claiming this kills n_C = 5 -- only that CONDITION 5 cannot support it. The")
print("     other 21 selections stand as selections, and @Lyra's minimality route is untouched.")
