import numpy as np, mpmath as mp
mp.mp.dps=25
print("MY FIRST MELLIN TEST WAS SLOPPY (ratio 0.9375 at sigma=1/2 -- coarse grid, truncated t-range).")
print("Redone EXACTLY with f(x) = e^{-x}, whose Mellin transform is Gamma(s).\n")
print("="*92)
print("WEIGHTED PARSEVAL:  INT_0^inf |f(x)|^2 x^{2 sigma - 1} dx  =  (1/2pi) INT |F(sigma+it)|^2 dt")
print("For f = e^{-x}:  LHS = Gamma(2 sigma)/2^{2 sigma}.  Check both sides.")
print("="*92)
print("\n      sigma      LHS = Gamma(2s)/4^s      RHS = (1/2pi) INT |Gamma|^2 dt     ratio")
for sig in [0.30,0.50,0.75,1.00]:
    lhs=float(mp.gamma(2*sig)/mp.mpf(2)**(2*sig))
    rhs=float(mp.quad(lambda t: abs(mp.gamma(mp.mpf(sig)+1j*t))**2, [-mp.inf,0,mp.inf])/(2*mp.pi))
    print("      %.2f        %16.8f      %20.8f      %.6f"%(sig,lhs,rhs,rhs/lhs))
print("\n  ⟹ the weighted identity holds at EVERY sigma -- as it must. THE POINT IS THE WEIGHT:")
print("     x^{2 sigma - 1} = 1  <=>  sigma = 1/2, and ONLY THERE.")
print("     So sigma = 1/2 is the UNIQUE line on which the Mellin transform is an isometry onto")
print("     PLAIN L^2(dx), with no weight. That is where Re = 1/2 comes from: the half-density")
print("     normalisation of the multiplicative measure dx/x. Classical, exact, and derivable.")
print("\n  and the closed form that makes it transparent:  |Gamma(1/2 + it)|^2 = pi / cosh(pi t)")
for t in [0.0,0.7,2.0]:
    print("     t=%.1f :  |Gamma(1/2+it)|^2 = %.10f    pi/cosh(pi t) = %.10f"%(
        t,float(abs(mp.gamma(mp.mpf(0.5)+1j*t))**2),float(mp.pi/mp.cosh(mp.pi*t))))
print("\n  ★★ BUT UNITARITY IS NOT RH. Re=1/2 is where the CHARACTERS live. The zeros are RESONANCES.")
print("     'Re=1/2 is the self-dual / descent-invariant axis' is TRUE, derivable, and does NOT")
print("     locate a single zero. Connes' wall sits exactly in that gap.")
print()
print("="*92)
print("THE SHIMURA-LIFT ARITHMETIC -- what the repair actually outputs")
print("="*92)
print("  Shimura's correspondence: weight k + 1/2  -->  weight 2k.")
print("  our half-integral weight is n_C/2 = 5/2  =>  k + 1/2 = 5/2  =>  k = 2  =>  LIFT HAS WEIGHT 4.")
print("  A weight-4 cusp form's L-function has an Euler product and a functional equation")
print("  s <-> 4 - s, with critical line Re s = 2 (classically) = 1/2 after normalisation.")
print("  ★★★ SO EVEN IN THE FAVOURABLE CASE, THE LIFT GIVES RH FOR A WEIGHT-4 MODULAR L-FUNCTION,")
print("      NOT FOR ZETA. zeta is not the L-function of a weight-4 cusp form -- it is degree 1 with")
print("      a pole at s=1; a weight-4 cusp L-function is degree 2 and entire. DIFFERENT OBJECTS.")
print("      Proving RH for the lift would be a real theorem. It would not be the Riemann Hypothesis.")
