import numpy as np
np.set_printoptions(precision=4,suppress=True)
I3=np.eye(3)
lam={1:np.array([[0,1,0],[1,0,0],[0,0,0]],complex),
     2:np.array([[0,-1j,0],[1j,0,0],[0,0,0]]),
     3:np.diag([1,-1,0]).astype(complex),
     5:np.array([[0,0,-1j],[0,0,0],[1j,0,0]]),
     7:np.array([[0,0,0],[0,0,-1j],[0,1j,0]])}
def L(a):                       # spin-1 (vector) generators, (L_a)_{bc} = -eps_{abc}
    M=np.zeros((3,3))
    for b in range(3):
        for c in range(3):
            e=0
            p=[(0,1,2),(1,2,0),(2,0,1)]; n=[(0,2,1),(2,1,0),(1,0,2)]
            if (a,b,c) in p: e=1
            if (a,b,c) in n: e=-1
            M[b,c]=-e
    return M.astype(complex)
Lg=[L(0),L(1),L(2)]
def structure(G):
    """return the 3x3x3 array of structure constants c with [G_a,G_b] = sum_c c_ab^c G_c (least squares)"""
    B=np.array([g.ravel() for g in G]).T
    out=np.zeros((3,3,3))
    for a in range(3):
        for b in range(3):
            com=(G[a]@G[b]-G[b]@G[a]).ravel()
            out[a,b]=np.linalg.lstsq(B,com,rcond=None)[0].real
    return out
def homdim(V,T):
    """dim_C Hom_G(V,T): solve M V_a = T_a M for all a"""
    rows=[]
    for Va,Ta in zip(V,T):
        rows.append(np.kron(Va.T,np.eye(3))-np.kron(np.eye(3),Ta))
    A=np.vstack(rows)
    s=np.linalg.svd(A,compute_uv=False)
    return int((s<1e-9).sum())+ (9-len(s)), s

print("="*90)
print("THE INTERTWINER QUESTION IS DECIDED BY SCHUR *BEFORE* ANY MATRIX ELEMENT IS COMPUTED.")
print("A matrix element IS an element of Hom_G(V_color, T_sky). If that space is 0, NO operator --")
print("Dirac or otherwise -- can be a nonzero intertwiner. If it is 1-dimensional, the map is forced")
print("up to scale by SCHUR, and the operator can at most fix the normalisation.")
print("="*90)

# --- route A: the DOUBLET->SPINOR route (block SU(2) subset SU(3)) -- the one the prompt favours
A=[1j*lam[a]/2 for a in (1,2,3)]
cA=structure(A); cL=structure(Lg)
# match normalisation of the spin-1 generators to the same structure constants
scale=np.linalg.lstsq(cL.reshape(-1,1),cA.reshape(-1),rcond=None)[0][0]
Lm=[scale*g for g in Lg]
print("\nROUTE A -- DOUBLET->SPINOR: G = the BLOCK SU(2) subset SU(3) (the chain's SU(2))")
print("  structure constants match after scaling by %.4f : max resid %.2e"%(scale,np.abs(structure(Lm)-cA).max()))
# how does the colour 3 decompose?
C2=sum(g@g for g in A)
ev=np.linalg.eigvalsh(-C2)
print("  colour triplet restricted to this SU(2): Casimir eigenvalues %s  => 2 (+) 1  (doublet + singlet)"%np.array2string(ev,precision=4))
d,s=homdim(A,Lm)
print("  dim_C Hom_G(V_colour, T_sky) = %d      (smallest singular values %s)"%(d,np.array2string(s[-3:],precision=3)))
print("  ⟹ ZERO. No operator can intertwine 2(+)1 with the irreducible vector 3. SCHUR FORBIDS IT.")

# --- route B: the TRIPLET->VECTOR route (real SO(3) subset SU(3))
B=[1j*lam[a]/2 for a in (7,5,2)]
cB=structure(B)
scaleB=np.linalg.lstsq(cL.reshape(-1,1),cB.reshape(-1),rcond=None)[0][0]
LmB=[scaleB*g for g in Lg]
print("\nROUTE B -- TRIPLET->VECTOR: G = the REAL SO(3) subset SU(3) (generated by lam_2, lam_5, lam_7)")
print("  structure constants match after scaling by %.4f : max resid %.2e"%(scaleB,np.abs(structure(LmB)-cB).max()))
C2B=sum(g@g for g in B); evB=np.linalg.eigvalsh(-C2B)
print("  colour triplet restricted to this SO(3): Casimir eigenvalues %s  => IRREDUCIBLE 3 (vector)"%np.array2string(evB,precision=4))
dB,sB=homdim(B,LmB)
print("  dim_C Hom_G(V_colour, T_sky) = %d      (smallest singular values %s)"%(dB,np.array2string(sB[-3:],precision=3)))
print("  ⟹ EXACTLY ONE. The intertwiner EXISTS and is UNIQUE UP TO SCALE -- forced by SCHUR, not by Dirac.")
