import numpy as np
from math import comb
print("="*80)
print("WHICH DIMENSION DOES THE COMMITMENT PROJECTION DROP? -- exact Weyl counting")
print("="*80)
print("Module (toy 5264):  Lambda*(C^5) (x) C[z_1..z_5],  lam_max ~ 2N^2,  modes = 32*C(N+5,5) ~ N^5")
print("   => N(lam) ~ lam^{5/2}  =>  d = 5.   [EXACT, verified 5264]")
print()
print("IF the commitment projects out ONE holomorphic direction: C[z_1..z_4], modes ~ N^4:")
print()
print("   variables k   modes(N)=32*C(N+k,k)   lam~2N^2   =>  d = k   (exact, from the same counting)")
for k in [3,4,5,6]:
    ds=[]
    prev=None
    for N in [16,64,256,1024]:
        lm=2*N**2+9*N+14; md=32*comb(N+k,k)
        if prev: ds.append(2*np.log(md/prev[1])/np.log(lm/prev[0]))
        prev=(lm,md)
    print("      k = %d        ~N^%d                        d -> %.4f"%(k,k,ds[-1]))
print()
print("  => dropping ONE holomorphic variable takes d from 5 to 4, EXACTLY. The mechanism's")
print("     dimensional prediction is d = 4 on the nose -- not 4.2, not approximately.")
print()
print("="*80)
print("★ BUT WHICH direction?  -- and here it meets my own theorem (toy 5257)")
print("="*80)
print("  By symmetry, dropping ANY one of the five gives d = 4. The dimension is INSENSITIVE")
print("  to the choice.  =>  the dimension count CONFIRMS the mechanism yields 4, but it")
print("      CANNOT SELECT WHICH direction is projected. No information there.")
print()
print("  And toy 5257 (Schur): NO SO(5)-equivariant construction with invariant inputs can")
print("  select a direction in R^5 -- the only SO(5)-fixed vector is 0.")
print("  => a GLOBAL, observer-independent projected direction is FORBIDDEN by that theorem.")
print()
print("  ⟹ THE TWO FACTS FIT, and they force the mechanism's shape:")
print("     the projection must be OBSERVER-RELATIVE -- each observer on S^4 projects out")
print("     ITS OWN radial direction. The FAMILY is SO(5)-covariant; NO single direction is")
print("     selected; my no-go is respected because there is no single equivariant map.")
print("     That is exactly Cal's 'foliation up-to-symmetry' from yesterday, now with a")
print("     mechanism attached -- and it is why the mechanism is NOT rank-capped.")
print()
print("  ⟹ FALSIFIABLE CONSEQUENCE for @Lyra: if the projection is observer-relative, there is")
print("     NO global 4D manifold -- there is a 4D record PER OBSERVER, related by SO(5).")
print("     'The 4D manifold' is then a section/quotient, and THAT is what must be derived.")
