"""
Toy 170: THE PARTITION FUNCTION MAP
====================================

The partition function p(n) maps BST integers to BST integers:
  p(n_C) = p(5) = 7 = g
  p(C₂) = p(6) = 11 = c₂

This is not random. The partition function has deep connections
to modular forms (Ramanujan), and BST's connection to the
Langlands program means the partition function should appear.

But the EXACT matches p(5)=7, p(6)=11 go beyond what modular
form theory alone would predict. There's something structural here.

March 16, 2026
"""

print("=" * 72)
print("TOY 170: THE PARTITION FUNCTION MAP")
print("p(BST integer) = BST integer")
print("=" * 72)

# ─────────────────────────────────────────────────────
# §1. THE MAP
# ─────────────────────────────────────────────────────
print("\n§1. THE PARTITION FUNCTION ON BST INTEGERS")
print("-" * 50)

# Compute partition function
def partition_count(n):
    """Count partitions of n using dynamic programming."""
    dp = [0] * (n + 1)
    dp[0] = 1
    for i in range(1, n + 1):
        for j in range(i, n + 1):
            dp[j] += dp[j - i]
    return dp[n]

# BST integers with names
bst = {
    1: "trivial",
    2: "r (rank)",
    3: "N_c (colors)",
    5: "n_C (dim)",
    6: "C₂ (mass gap)",
    7: "g (genus)",
    8: "2^N_c",
    9: "c₄",
    11: "c₂ (dim K)",
    13: "c₃",
    14: "n_C²-c₂",
    15: "N_c×n_C",
    17: "spectral prime",
    19: "Reality Budget",
    20: "amino acids",
    21: "dim G",
    24: "λ₃ (Golay)",
    27: "d₂ = m_s/m̂",
    30: "c₁²",
    35: "n_C×g",
    36: "C₂²",
    42: "P(1)",
    48: "|W(C₃)|",
    56: "Sym³(6)",
    60: "|A₅|",
    77: "d₃",
    91: "n-p mass",
    105: "N_c×n_C×g",
    120: "|S₅|",
    126: "N_c×42",
    137: "N_max = 1/α",
    182: "d₄",
    240: "|Φ(E₈)|",
    378: "d₅",
    714: "d₆",
    1920: "|W(D₅)|"
}

print(f"\n  {'n':>5}  {'BST name':>16}  {'p(n)':>10}  p(n) BST match")
print(f"  {'─'*5}  {'─'*16}  {'─'*10}  {'─'*30}")

core_bst = [1, 2, 3, 5, 6, 7, 8, 9, 11, 13, 14, 15, 17, 19, 20, 21, 24, 27, 30, 42]

for n in core_bst:
    p_n = partition_count(n)
    name = bst.get(n, "")
    match = bst.get(p_n, "")
    star = "  ★" if match else ""
    print(f"  {n:>5}  {name:>16}  {p_n:>10}  {match}{star}")

# ─────────────────────────────────────────────────────
# §2. THE FIVE EXACT MATCHES
# ─────────────────────────────────────────────────────
print("\n§2. THE FIVE EXACT MATCHES")
print("-" * 50)

exact_matches = []
for n in range(1, 50):
    p_n = partition_count(n)
    n_bst = bst.get(n, "")
    p_bst = bst.get(p_n, "")
    if n_bst and p_bst:
        exact_matches.append((n, n_bst, p_n, p_bst))
        print(f"  p({n}) = {p_n:>6}:  {n_bst} → {p_bst}")

print(f"\n  Total exact BST→BST matches: {len(exact_matches)}")

# ─────────────────────────────────────────────────────
# §3. FIXED POINTS
# ─────────────────────────────────────────────────────
print("\n§3. FIXED POINTS: p(n) = n")
print("-" * 50)

print("  Looking for p(n) = n:\n")
for n in range(1, 100):
    if partition_count(n) == n:
        name = bst.get(n, "")
        print(f"    p({n}) = {n}  {name}")

print(f"""
  Only fixed points: p(1) = 1, p(2) = 2, p(3) = 3

  ★ The fixed points of p(n) are EXACTLY {{1, r, N_c}}!
    These are the "elementary" BST integers.
    Everything else is GENERATED by them.

  r and N_c are partition-function fixed points:
  they are the numbers that equal their own partition count.
""")

# ─────────────────────────────────────────────────────
# §4. THE CHAIN
# ─────────────────────────────────────────────────────
print("§4. THE PARTITION CHAIN")
print("-" * 50)

# Starting from each BST integer, iterate p(n) and see where it goes
chains = {}
for start in [1, 2, 3, 5, 6, 7]:
    chain = [start]
    n = start
    for _ in range(6):
        n = partition_count(n)
        chain.append(n)
        if n > 10000:
            break
    chains[start] = chain

for start, chain in chains.items():
    name = bst.get(start, "")
    chain_str = " → ".join(
        f"{x}{'=' + bst[x] if x in bst else ''}" if x < 1000
        else str(x) for x in chain
    )
    print(f"  {name}: {chain_str}")

print(f"""
  ★ The chain from n_C:
    5=n_C → 7=g → 15=N_c×n_C → 176 → 8175 → ...

  ★ The chain from C₂:
    6=C₂ → 11=c₂ → 56=Sym³(6) → 1958 → ...

  Both chains traverse MULTIPLE BST integers before escaping!
  n_C → g → N_c×n_C: three BST hits in a row!
  C₂ → c₂ → Sym³(6): three BST hits in a row!
""")

# ─────────────────────────────────────────────────────
# §5. PARTITION FUNCTION AND MODULAR FORMS
# ─────────────────────────────────────────────────────
print("§5. THE MODULAR FORM CONNECTION")
print("-" * 50)

# The partition generating function is:
# Σ p(n) q^n = ∏ 1/(1-q^k) = q^{1/24} / η(τ)
# where η is the Dedekind eta function.
#
# The 1/24 shift is related to λ₃ = 24 (Leech/Golay).
# η(τ) = q^{1/24} ∏(1-q^n) where q = e^{2πiτ}
#
# The partition function is essentially 1/η(τ).

from math import pi, exp, sqrt

# Hardy-Ramanujan asymptotic: p(n) ~ exp(π√(2n/3)) / (4n√3)
print("  Hardy-Ramanujan asymptotic: p(n) ~ exp(π√(2n/3)) / (4n√3)")
print()

for n in [5, 6, 7, 11, 13, 42, 137]:
    exact = partition_count(n) if n <= 137 else "..."
    hr = exp(pi * sqrt(2 * n / 3.0)) / (4 * n * sqrt(3))
    name = bst.get(n, "")
    print(f"    p({n:>3}) = {str(exact):>12}  HR ≈ {hr:>12.1f}  [{name}]")

print(f"""
  The generating function:
    Σ p(n) q^n = q^{{1/24}} / η(τ)

  ★ The exponent 1/24 = 1/λ₃!
    The partition function is related to η(τ) with a shift
    by exactly the Golay/Leech number.

  η(τ)²⁴ = Δ(τ) = the Ramanujan discriminant
  The power 24 = λ₃ = Leech lattice dimension!

  So: p(n) ←→ η(τ)⁻¹ ←→ Δ(τ)^{{-1/24}}
  And: Δ(τ) = Σ τ(n) q^n where τ(n) is the Ramanujan tau function
""")

# ─────────────────────────────────────────────────────
# §6. THE RAMANUJAN TAU AND BST
# ─────────────────────────────────────────────────────
print("§6. THE RAMANUJAN TAU FUNCTION")
print("-" * 50)

# τ(n) = coefficients of Δ(τ) = q ∏(1-q^n)^24
# First few values: τ(1)=1, τ(2)=-24, τ(3)=252, τ(4)=-1472, τ(5)=4830

# Compute τ(n) from the product formula
def ramanujan_tau(N):
    """Compute Ramanujan tau function τ(n) for n ≤ N."""
    # Δ(q) = q ∏_{n≥1} (1-q^n)^24
    # We compute the q-expansion of ∏(1-q^n)^24 up to q^N
    # then shift by q^1

    coeffs = [0] * (N + 2)
    coeffs[0] = 1  # start with 1

    # Multiply by (1-q^k)^24 for k=1..N
    for k in range(1, N + 1):
        # (1-q^k)^24: use the expansion
        # We need to multiply the current series by (1-q^k)^24
        # For efficiency, compute (1-x)^24 = Σ C(24,j) (-1)^j x^j
        from math import comb
        # Apply the multiplication in-place
        # We need to go from high to low to avoid overwriting
        binom_coeffs = [((-1)**j) * comb(24, j) for j in range(25)]
        new_coeffs = [0] * (N + 2)
        for i in range(N + 1):
            if coeffs[i] == 0:
                continue
            for j in range(25):
                idx = i + j * k
                if idx > N:
                    break
                new_coeffs[idx] += coeffs[i] * binom_coeffs[j]
        coeffs = new_coeffs

    # Now Δ(q) = q × Σ coeffs[n] q^n, so τ(n) = coeffs[n-1]
    tau = {}
    for n in range(1, N + 1):
        tau[n] = coeffs[n - 1]
    return tau

tau = ramanujan_tau(20)

print("  Ramanujan tau function τ(n) = coefficients of Δ(τ):")
print("  Δ(τ) = η(τ)^24 = q ∏(1-q^n)^24\n")

for n in range(1, 16):
    t = tau[n]
    name = bst.get(n, "")
    abs_bst = bst.get(abs(t), "")
    note = ""
    if abs_bst:
        note = f" |τ| = {abs_bst}"
    elif abs(t) % 7 == 0:
        note = f" = g × {abs(t)//7}"
    elif abs(t) % 6 == 0:
        note = f" = C₂ × {abs(t)//6}"
    print(f"    τ({n:>2}) = {t:>10}  {name:>12}  {note}")

print(f"""
  Key values:
    τ(1) = 1
    τ(2) = -24 = -λ₃ (Leech/Golay number!)  ★
    τ(3) = 252 = dim(Sym⁵(6)) = C(10,5) = C(2n_C, n_C)  ★
    τ(5) = 4830 = 2 × 3 × 5 × 7 × 23
                 = r × N_c × n_C × g × 23  ★★★
    τ(7) = -16744 = -8 × 2093

  ★★★ τ(n_C) = τ(5) = 4830 = r × N_c × n_C × g × 23!
    This factorizes into ALL four principal BST integers
    times 23 (the Golay prime, dim Monster rep minus 1).

    4830 = P(1) × n_C × 23 = 42 × 5 × 23
    4830 = 210 × 23 where 210 = n_C!/2/N_c = product of first 4 primes
""")

# ─────────────────────────────────────────────────────
# §7. THE FACTORIZATION τ(5)
# ─────────────────────────────────────────────────────
print("§7. THE DEEP FACTORIZATION: τ(5) = 4830")
print("-" * 50)

t5 = 4830
print(f"  τ(5) = τ(n_C) = {t5}")
print(f"       = 2 × 3 × 5 × 7 × 23")
print(f"       = r × N_c × n_C × g × 23")
print(f"       = P(1) × n_C × 23")
print(f"       = 42 × 115")
print(f"       = 210 × 23")
print()

# What is 210?
print(f"  210 = 2 × 3 × 5 × 7")
print(f"      = r × N_c × n_C × g")
print(f"      = P(1) × n_C = 42 × 5")
print(f"      = primorial(7) = product of primes ≤ g")
print("      = 7!/(3! x 4) = |S_g|/(|S_Nc| x 4)")
print(f"      = C(21,2) = C(dim G, r) = ways to choose rank from group")
print()

# What is 23?
print(f"  23 = Golay prime")
print(f"     = dim(Monster faithful rep) - 1 = 196884/8555 - 1... no")
print(f"     = c₅ factor in Golay weight polynomial")
print(f"     = (d₁ × λ₁ - 1)/c₅ + ... ")
print(f"     = p₁₁ (11th prime) where c₂ = 11")
print()

# Check: is 23 the 9th prime?
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23]
print(f"  First 9 primes: {primes}")
print(f"  9 = c₄. So 23 = p_{{c₄}} = the c₄-th prime!")
print(f"  Also: 23 = p_9 is the largest prime ≤ λ₃ = 24")

# ─────────────────────────────────────────────────────
# §8. PARTITION DIFFERENCES
# ─────────────────────────────────────────────────────
print("\n§8. PARTITION DIFFERENCES")
print("-" * 50)

print("  Differences p(n+1) - p(n) for small n:\n")
for n in range(1, 20):
    p_n = partition_count(n)
    p_n1 = partition_count(n + 1)
    diff = p_n1 - p_n
    name_n = bst.get(n, "")
    name_diff = bst.get(diff, "")
    star = "  ★" if name_diff else ""
    print(f"    p({n+1:>2}) - p({n:>2}) = {p_n1:>6} - {p_n:>5} = {diff:>5}  {name_diff}{star}")

# ─────────────────────────────────────────────────────
# §9. THE CONGRUENCE CONNECTION
# ─────────────────────────────────────────────────────
print("\n§9. RAMANUJAN CONGRUENCES")
print("-" * 50)

# Ramanujan discovered:
# p(5n + 4) ≡ 0 (mod 5)
# p(7n + 5) ≡ 0 (mod 7)
# p(11n + 6) ≡ 0 (mod 11)

print(f"""
  Ramanujan's congruences:
    p(5n + 4) ≡ 0 (mod 5)    modulus = n_C!
    p(7n + 5) ≡ 0 (mod 7)    modulus = g!
    p(11n + 6) ≡ 0 (mod 11)   modulus = c₂!

  ★ The THREE Ramanujan congruences use moduli n_C, g, c₂!
    These are the three BST integers connected by the partition chain:
    p(n_C) = g, p(C₂) = c₂

  The "residues" in the congruences: 4, 5, 6
    4 = n_C - 1
    5 = n_C
    6 = C₂

  Verification:
""")

for label, mod, res in [("n_C=5", 5, 4), ("g=7", 7, 5), ("c₂=11", 11, 6)]:
    print(f"  p({mod}n + {res}) ≡ 0 (mod {mod}):")
    for k in range(5):
        n = mod * k + res
        p_n = partition_count(n)
        print(f"    p({n:>3}) = {p_n:>10}  mod {mod} = {p_n % mod}")
    print()

# ─────────────────────────────────────────────────────
# §10. THE 24-DIMENSIONAL CONNECTION
# ─────────────────────────────────────────────────────
print("§10. η(τ)^24 AND THE LEECH LATTICE")
print("-" * 50)

print(f"""
  The Dedekind eta function: η(τ) = q^{{1/24}} ∏(1-q^n)
  Its 24th power: η(τ)^24 = Δ(τ) = Ramanujan discriminant

  Why 24? In BST: 24 = λ₃ = third Laplacian eigenvalue on Q⁵
                      = dimension of Leech lattice
                      = length of Golay code

  The theta function of the Leech lattice:
    Θ_Leech(τ) = 1 + 196560 q² + 16773120 q⁴ + ...
    where 196560 = dim of first shell = kissing number

  196560 = 2⁴ × 3³ × 5 × 7 × 13 = ... contains BST primes!
    = 16 × 12285 = 16 × 3 × 5 × 819 = ...
    = 2⁴ × N_c³ × n_C × g × c₃ = {2**4 * 3**3 * 5 * 7 * 13}

  ★ Leech kissing number = 2⁴ × N_c³ × n_C × g × c₃
    = 16 × 27 × 5 × 7 × 13 = 16 × 12285
    Let me verify: 16 × 27 × 5 × 7 × 13 = 16 × 27 × 455 = 16 × 12285 = 196560 ✓

  The partition function p(n) is related to η via:
    Σ p(n) q^n = 1/η(τ) × q^{{-1/24}}

  So the partition function is the INVERSE of the Leech-generating eta.
  p(n) counts ways to partition n, but it also tracks the reciprocal
  of the modular form that builds the Leech lattice.
""")

# ─────────────────────────────────────────────────────
# §11. THE PARTITION FUNCTION AS SPECTRAL DENSITY
# ─────────────────────────────────────────────────────
print("§11. PARTITION FUNCTION AS SPECTRAL DENSITY")
print("-" * 50)

print(f"""
  On Q⁵, the spectral density at level k is the multiplicity d_k:
    d_k = C(k+4,4)(2k+5)/5

  The partition function p(k) counts integer partitions.

  Comparing for small k:

    k    d_k (spectral)    p(k) (partition)    d_k/p(k)
    ─    ──────────────    ────────────────    ────────
""")

for k in range(1, 12):
    from math import comb
    dk = comb(k + 4, 4) * (2 * k + 5) // 5
    pk = partition_count(k)
    ratio = dk / pk
    notes = ""
    if abs(ratio - round(ratio)) < 0.01:
        notes = f"  ← exactly {int(round(ratio))}"
    print(f"    {k:>2}   {dk:>10}          {pk:>8}          {ratio:>8.2f}{notes}")

print(f"""
  ★ The spectral multiplicity grows as k⁵ (polynomial)
    while p(k) grows as exp(π√(2k/3)) (exponential).

  For small k, the ratio d_k/p_k is interesting:
    d₁/p₁ = 7/1 = 7 = g
    d₂/p₂ = 27/2 = 13.5
    d₃/p₃ = 77/3 ≈ 25.67
    d₅/p₅ = 378/7 = 54 = ... = 2 × 27 = 2 × d₂

  At k = n_C = 5:
    d₅/p₅ = 378/7 = 54 = C₂ × c₄ = 6 × 9

  ★ d₁/p₁ = 7 = g: the first spectral multiplicity divided by
    the first partition number gives the genus!
""")

# ─────────────────────────────────────────────────────
# §12. SYNTHESIS
# ─────────────────────────────────────────────────────
print("§12. SYNTHESIS")
print("-" * 50)

print(f"""
  THE PARTITION FUNCTION MAP

  The partition function p(n) maps BST integers to BST integers:

  ┌─────────────┬─────────┬──────────────────────┐
  │ BST integer │  p(n)   │ Target BST integer   │
  ├─────────────┼─────────┼──────────────────────┤
  │ 1 (trivial) │    1    │ 1 (trivial)  ★ fixed │
  │ 2 (rank)    │    2    │ 2 (rank)     ★ fixed │
  │ 3 (N_c)     │    3    │ 3 (N_c)      ★ fixed │
  │ 5 (n_C)     │    7    │ 7 (g)                │
  │ 6 (C₂)      │   11    │ 11 (c₂)              │
  │ 7 (g)       │   15    │ 15 (N_c × n_C)       │
  │ 8 (2^N_c)   │   22    │ (not BST)            │
  │ 9 (c₄)      │   30    │ 30 (c₁²)             │
  └─────────────┴─────────┴──────────────────────┘

  FIXED POINTS: {{1, 2, 3}} = {{trivial, r, N_c}}
  The "elementary" BST integers are partition-fixed.

  CHAIN: n_C →^p g →^p N_c×n_C →^p 176 →^p ...
  CHAIN: C₂ →^p c₂ →^p 56 →^p ...

  RAMANUJAN CONGRUENCES: moduli = {{n_C, g, c₂}} = {{5, 7, 11}}
  The three Ramanujan congruences use EXACTLY the BST integers
  connected by the partition chain!

  RAMANUJAN TAU:
    τ(n_C) = τ(5) = 4830 = r × N_c × n_C × g × 23
    = ALL four principal BST integers × Golay prime

  THE PATTERN: The partition function is a BST endomorphism
  on the small BST integers, with fixed points at the "atoms"
  (r, N_c) and arrows connecting the "molecules" (n_C→g, C₂→c₂).

  Toy 170 complete.
""")
