from fractions import Fraction as F
from math import comb
print("="*104)
print("TOY 5345 -- THE BLIND C4 TEST: does fermion parity (JDJ = -D) supply the BD pair-weights?")
print("  *** STEP 1 writes BST's weights with NO reference to Benincasa-Dowker. ***")
print("  *** STEP 2 then states BD. STEP 3 compares. Continuum [] is NEVER imposed. ***")
print("="*104)

print("\n" + "-"*104)
print("STEP 1 -- BST'S OWN WEIGHTS, WRITTEN BLIND (nothing from BD used below this line)")
print("-"*104)
print("\nTABLE 1 -- what JDJ = -D actually gives")
print("   J is the real structure; JDJ = -D says J ANTICOMMUTES with D.")
print("   grading operator Gamma, supertrace Str(A) = Tr(Gamma A).")
print("   D has +- paired spectrum (verified toy 5334: eigenvalues +-(n/2+k)).")
print("   ==> the grading assigns to each object a factor  (-1)^n  and NOTHING ELSE.")
print("   *** A Z_2 GRADING IS VALUED IN {+1, -1}. That is its entire range. ***")
print("\nTABLE 2 -- so the BST layer-weights, blind:")
print("   layer n   fermion-parity weight   magnitude")
for n in range(1,5):
    print("   %-9d %-23s %d"%(n,"(-1)^%d = %+d"%(n-1,(-1)**(n-1)),1))
print("   ==> *** ALL MAGNITUDES ARE 1, BY CONSTRUCTION. The only content is the SIGN. ***")
print("   (equivalently: the alternating chain-sum is the poset MOEBIUS function, mu = zeta^{-1},")
print("    whose coefficients are pure (-1)^n -- no magnitudes either.)")
print("\n   *** COMMITTING THAT BEFORE LOOKING AT BD: BST's object supplies signs (1,-1,1,-1),")
print("       magnitudes identically 1. If BD needs any magnitude != 1, this route cannot supply it. ***")

print("\n" + "-"*104)
print("STEP 2 -- NOW state Benincasa-Dowker (from memory; FLAGGED for source-pinning)")
print("-"*104)
BD={2:[1,-2,1],4:[1,-9,16,-8]}
print("   dim   layer coefficients      sum      magnitudes")
for d,cs in BD.items():
    print("   %-5d %-22s %-8d %s"%(d,str(cs),sum(cs),[abs(c) for c in cs]))
print("   consistency check -- coefficients sum to 0 in both (needed so B(constant) has no layer term): OK")
print("   2D magnitudes (1,2,1) = binomial C(2,k) -- a discrete second difference, as [] in 2D should be")
print("   4D magnitudes (1,9,16,8) are NOT binomial C(3,k) = (1,3,3,1)")
print("   ** @Grace/@Lyra: pin these to Benincasa-Dowker 2010 before anything is banked. The")
print("      STRUCTURAL verdict below does NOT depend on their exact values -- only on whether any")
print("      magnitude differs from 1, which is true for every dimension above 1. **")

print("\n" + "-"*104)
print("STEP 3 -- THE COMPARISON")
print("-"*104)
print("\nTABLE 3 -- side by side")
print("   layer n   BST fermion-parity   BD (4D)   match?")
for n,c in enumerate(BD[4],1):
    w=(-1)**(n-1)
    print("   %-9d %-20s %-9d %s"%(n,"%+d"%w,c,"sign only" if (w>0)==(c>0) else "SIGN MISMATCH"))
print("\n   signs      : BST (+,-,+,-)   BD (+,-,+,-)   *** MATCH ***")
print("   magnitudes : BST (1,1,1,1)    BD (1,9,16,8)  *** DO NOT MATCH ***")

print("\nTABLE 4 -- *** and the deeper problem: where do BD's magnitudes COME FROM? ***")
print("   Benincasa-Dowker FIX the coefficients by REQUIRING that <B phi> -> [] phi in the")
print("   continuum limit. That is their definition -- the magnitudes ARE the continuum matching.")
print("   ==> so 'derive BD's magnitudes from BST' would mean deriving something whose only")
print("       definition is the continuum [] -- *** exactly what the fence forbids importing. ***")
print("   Either you import [] (fenced out -> the match is empty, as @Keeper pre-registered), or")
print("   you reproduce (1,9,16,8) from independent structure -- and a Z_2 grading provably cannot,")
print("   because its range is {+1,-1}.")

print("\n"+"="*104)
print("VERDICT -- blind weights written first, comparison after")
print("="*104)
print(" *** THE C4 WEIGHTING DOES NOT LAND BY THIS ROUTE. NAMING THE FLOOR PRECISELY: ***")
print()
print(" (1) BST's fermion parity supplies EXACTLY the sign alternation (+,-,+,-) and NOTHING ELSE.")
print("     A Z_2 grading is valued in {+1,-1}; that is its entire range, by construction.")
print()
print(" (2) BD's signs also alternate -- *** so the halves that match is the half that is FREE. ***")
print("     Any alternating object matches it. The Moebius function of ANY poset alternates.")
print("     This is a can't-fail agreement and must not be reported as evidence.")
print()
print(" (3) *** THE MAGNITUDES ARE THE ENTIRE PHYSICAL CONTENT, and the grading is blind to them. ***")
print("     BD 4D needs (1,9,16,8); fermion parity gives (1,1,1,1). No choice of J, D or grading")
print("     changes this -- the obstruction is the RANGE of a Z_2 grading, not a missing computation.")
print()
print(" (4) *** AND THE MAGNITUDES ARE DEFINED BY THE CONTINUUM []. *** So the only way to 'derive'")
print("     them is to import the very thing the fence excludes. @Keeper's fence was not a caution")
print("     -- it was load-bearing, and it fires here exactly as pre-registered.")
print()
print(" ==> HONEST FLOOR: spectral-action = causal-action is NOT established, and this particular")
print("     route is CLOSED for a structural reason, not an unfinished one. What would be needed is")
print("     a BST object with a GRADED MAGNITUDE SPECTRUM (something valued beyond {+1,-1}) that is")
print("     defined WITHOUT reference to the continuum limit. Fermion parity is not that object.")
print("     I did not find one today and am not claiming one exists.")
