#!/usr/bin/env python3
"""
Toy 3551 — GF(32) explicit Frobenius orbit structure

Elie, Wednesday 2026-05-27 ~11:10 EDT
Toy 3541 sub-task 3541b/3541c support. Computes Frobenius x→x² orbits
on F_32^* explicitly, parallel to K59 GF(128) 18-orbit structure.

PURPOSE
-------
The Galois group Gal(GF(32) / GF(2)) ≅ Z/5 is generated by Frobenius
φ(x) = x². Under φ, F_32^* partitions into orbits of size = order of
Frobenius = 5. With 30 non-identity elements, expect 30/5 = 6 orbits.

Compare to K59 GF(128) substrate-mechanism: 18 orbits of size 7 on F_128^*.

Each Frobenius orbit corresponds to:
  - Conjugacy class under Galois action
  - Set of roots of a single irreducible polynomial over GF(2)
  - In K59 substrate-mechanism: candidate substrate-coupling site per orbit

CAL #29 STANDING QUESTION-SHAPE AUDIT (PRE-PASS):
  Question: "What are the Frobenius orbits at GF(32) explicitly?"
  - Forward computation via standard finite-field theory
  - No back-fit; orbit structure is math fact
  - Substrate interpretation is Lyra theoretical work
  CLEAN PASS

INVESTIGATIONS (5 scored)
1. Reconstruct GF(32) from Toy 3550 (same primitive polynomial)
2. Compute all Frobenius orbits in F_32^*
3. Identify orbit representatives + irreducible polynomial per orbit
4. Verify 6 orbits of size 5 (= 30/5)
5. Document parallel structure to K59 GF(128) 18 orbits
"""
import sys

print("=" * 78)
print("Toy 3551 — GF(32) explicit Frobenius orbit structure")
print("Toy 3541b/c sub-task — Frobenius orbits parallel to K59 18-orbit structure")
print("Elie, Wednesday 2026-05-27 11:10 EDT")
print("=" * 78)

# BST primaries
rank, N_c, n_C, C_2, g = 2, 3, 5, 6, 7
# Primitive polynomial from Toy 3550 was x^5 + x^2 + 1 = 0b100101 = 37
PRIM_POLY = 0b100101  # 37


def poly_mul_gf2(a, b):
    result = 0
    while b:
        if b & 1:
            result ^= a
        a <<= 1
        b >>= 1
    return result


def poly_div_gf2(num, den):
    quo = 0
    deg_den = den.bit_length() - 1
    while num.bit_length() - 1 >= deg_den and num != 0:
        shift = num.bit_length() - 1 - deg_den
        quo |= (1 << shift)
        num ^= (den << shift)
    return quo, num


def gf32_mul(a, b):
    prod = poly_mul_gf2(a, b)
    _, rem = poly_div_gf2(prod, PRIM_POLY)
    return rem


def gf32_square(a):
    return gf32_mul(a, a)


# ============================================================
# Test 1: Reconstruct GF(32) from Toy 3550
# ============================================================
print("\n--- Test 1: Reconstruct GF(32) ---")
print(f"  GF(32) = GF(2)[x] / ({bin(PRIM_POLY)[2:]}) = x^5 + x^2 + 1")
# Verify 1 is identity, and that some element has order 31
order_of_2 = 1
val = 2
while val != 1:
    val = gf32_mul(val, 2)
    order_of_2 += 1
print(f"  Order of element '2' in F_32^*: {order_of_2} (expect 31)")
test_1 = order_of_2 == 31
print(f"  Test 1: {'PASS' if test_1 else 'FAIL'}")

# ============================================================
# Test 2: Compute Frobenius orbits
# ============================================================
print("\n--- Test 2: Compute Frobenius orbits ---")
# Frobenius φ(x) = x² acting on F_32^* = {1, 2, ..., 31}
orbits = []
seen = set()
for x in range(1, 32):
    if x in seen:
        continue
    orbit = []
    current = x
    while current not in seen:
        orbit.append(current)
        seen.add(current)
        current = gf32_square(current)
    orbits.append(orbit)

print(f"  Total Frobenius orbits in F_32^*: {len(orbits)}")
print(f"  Expected: 6 orbits of size 5 (for non-identity) + 1 identity = 7 orbits")
print(f"  Or: 1 fixed point ({{1}} = identity) + 6 size-5 orbits")
test_2 = len(orbits) == 7  # 6 size-5 + 1 fixed {1}
print(f"  Test 2: {'PASS' if test_2 else 'FAIL'}")

# ============================================================
# Test 3: Orbit details
# ============================================================
print("\n--- Test 3: Orbit representatives + sizes ---")
print(f"\n  {'Orbit #':<8} {'Size':<6} {'Representative':<14} {'Elements'}")
print(f"  {'-'*8} {'-'*6} {'-'*14} {'-'*40}")
for i, orbit in enumerate(orbits, 1):
    rep = min(orbit)
    elems_str = "{" + ", ".join(str(e) for e in sorted(orbit)) + "}"
    print(f"  {i:<8} {len(orbit):<6} {rep:<14} {elems_str}")

# All non-identity orbits should have size 5
size_5_orbits = [o for o in orbits if len(o) == 5]
size_1_orbits = [o for o in orbits if len(o) == 1]
test_3 = len(size_5_orbits) == 6 and len(size_1_orbits) == 1
print(f"\n  Size-5 orbits: {len(size_5_orbits)} (expect 6)")
print(f"  Size-1 fixed points: {len(size_1_orbits)} (expect 1, the identity {{1}})")
print(f"  Test 3: {'PASS' if test_3 else 'FAIL'}")

# ============================================================
# Test 4: Orbit ↔ irreducible polynomial correspondence
# ============================================================
print("\n--- Test 4: Orbit ↔ irreducible polynomial correspondence ---")
print(f"  Each Frobenius orbit corresponds to one irreducible polynomial over GF(2)")
print(f"  whose roots are the orbit elements (in their algebraic closure).")
print(f"  ")
print(f"  Expected irreducible polynomial count of degree 5 over GF(2):")
print(f"    N(5) = (2^5 − 2)/5 = 30/5 = 6  (number of irreducible polynomials of degree 5)")
print(f"    Matches our 6 size-5 Frobenius orbits ✓")
print(f"  ")
print(f"  Plus 1 fixed-point orbit {{1}} corresponds to factor (x − 1) of degree 1.")
print(f"  Plus the unique degree-1 irreducible factor of x over GF(2) (i.e., x itself)")
print(f"  corresponds to the element {{0}} not in F_32^*.")

test_4 = len(size_5_orbits) == 6
print(f"  Test 4: {'PASS' if test_4 else 'FAIL'}")

# ============================================================
# Test 5: Parallel structure to K59 GF(128)
# ============================================================
print("\n--- Test 5: Parallel structure GF(32) ↔ GF(128) ---")
print(f"""
  {"Property":<40} {"GF(32) = GF(2^n_C)":<22} {"GF(128) = GF(2^g)":<22}
  {"-"*40} {"-"*22} {"-"*22}
  {"Field cardinality":<40} {"32 = 2^5":<22} {"128 = 2^7":<22}
  {"Multiplicative group |F^*|":<40} {"M_5 = 31 (Mersenne)":<22} {"M_7 = 127 (Mersenne)":<22}
  {"Frobenius order":<40} {"n_C = 5":<22} {"g = 7":<22}
  {"Galois group":<40} {"Z/5 cyclic":<22} {"Z/7 cyclic":<22}
  {"Non-identity Frobenius orbits":<40} {"6 orbits of size 5":<22} {"18 orbits of size 7":<22}
  {"Identity orbit":<40} {"{1} fixed":<22} {"{1} fixed":<22}
  {"Degree-N irreducible polys over GF(2)":<40} {"6":<22} {"18":<22}
""")

# K59 number of orbits
N_orbits_K59 = 126 // g  # 18
print(f"  K59 GF(128) substrate-mechanism uses {N_orbits_K59} orbits of size g=7.")
print(f"  Parallel GF(32) candidate substrate-mechanism uses 6 orbits of size n_C=5.")
print(f"  Number of orbits at GF(32): 6 = C_2 (substantive coincidence? Mode 6 caveat).")
print(f"  Number of orbits at GF(128): 18 = N_c² · rank · g / 7 = 3 · 6 = N_c · C_2 (Mode 6 candidate).")

print(f"\n  IMPLICATION for Lyra Track DC v0.12 (K59-analog at X=n_C):")
print(f"  - 6 substrate-coupling sites at GF(32) parallel to 18 at GF(128)")
print(f"  - Galois-orbit structure provides explicit substrate-operator candidates per site")
print(f"  - Cross-CI hand-off: orbit data ready for Lyra theoretical framework")

test_5 = True
print(f"\n  Test 5: PASS (parallel structure documented)")

# ============================================================
# Substantive observation worth surfacing
# ============================================================
print("\n--- Cal Thread 4 observation: orbit count ↔ BST primaries ---")
print(f"  GF(32):  6 orbits = C_2 (BST primary!)")
print(f"  GF(128): 18 orbits = N_c · C_2 = 3 · 6 (BST primary product)")
print(f"")
print(f"  6 and 18 both have BST primary content. Cal #29 question-shape audit:")
print(f"  was this observation pre-selected? NO — I computed orbit counts from")
print(f"  Galois theory (orbit count = |F^*|/order_Frobenius = M_p/p) and noted")
print(f"  the result happened to equal C_2 and N_c·C_2 respectively.")
print(f"")
print(f"  Cal #133 partial-tautology check:")
print(f"  - M_5/5 = 31/5 not integer; actually 30/5 = 6 (excluding identity)")
print(f"  - M_7/7 = 127/7 not integer; 126/7 = 18 (excluding identity)")
print(f"  - 6 = (2^5 - 2)/5 just IS the count of irreducibles deg 5 over GF(2)")
print(f"  - These are formulas not derivations; substrate-mechanism is what")
print(f"    BST identifies, not the orbit-count formula itself")
print(f"")
print(f"  Observation: 6 = C_2 at GF(32) AND 18 = N_c·C_2 at GF(128) both contain")
print(f"  BST primary content. Surfaced for Cal Thread 4; toy does NOT promote.")

# ============================================================
# Summary
# ============================================================
results = [test_1, test_2, test_3, test_4, test_5]
score = sum(results)
total = len(results)

print("\n" + "=" * 78)
print("GF(32) FROBENIUS ORBIT STRUCTURE — RESULT")
print("=" * 78)
print(f"""
GF(32) FROBENIUS ORBIT STRUCTURE (explicit computation):

  Total orbits: 7 (1 identity {{1}} + 6 size-5 orbits)
  Non-identity orbits: 6 size-5 orbits covering all 30 elements of F_32^* \\ {{1}}
  Frobenius φ(x) = x² generates cyclic Galois group Z/5

  ORBIT REPRESENTATIVES:
    Each orbit = {{α, α², α⁴, α⁸, α^16}} for some α ∈ F_32^*
    Each orbit corresponds to one irreducible polynomial of degree 5 over GF(2)
    Total deg-5 irreducible polys = 6 ✓ (matches (2^5−2)/5)

PARALLEL STRUCTURE TO K59 GF(128) 7-STEP:

  GF(32) parallel structure:
    n_C = 5 chain length
    M_5 = 31 cardinality of F^*
    6 Frobenius orbits of size 5
    Galois group Z/5

  K59 RATIFIED structure:
    g = 7 chain length
    M_g = 127 cardinality of F^*
    18 Frobenius orbits of size 7
    Galois group Z/7

OBSERVATION (FLAGGED for Cal Thread 4 typing, NOT PROMOTED):
  - 6 = C_2 at GF(32) orbit count (BST primary)
  - 18 = N_c · C_2 at GF(128) orbit count (BST primary product)
  - Mode 6 candidates per Cal #133; surfaced honestly

WHAT THIS TOY ACHIEVES:
  - Explicit Frobenius orbit computation at GF(32)
  - Confirmed 6-orbit structure parallel to K59 18-orbit at GF(128)
  - Orbit data hand-off for Lyra Track DC v0.12 K59-analog framework
  - Sub-task 3541b/c partial completion (substrate-operator connection per orbit
    is Lyra theoretical work; this toy provides structural data)

CROSS-CI HAND-OFF for Lyra:
  - Explicit orbit representatives (computed above)
  - 6 substrate-coupling-site candidates per orbit (analog of K59's 18 at GF(128))
  - Standard finite-field structure ready for substrate-mechanism interpretation

WHAT THIS TOY DOES NOT DO:
  - Does NOT derive substrate-mechanism at GF(32) (multi-week Lyra work)
  - Does NOT prove substrate operates with 6-orbit structure (Lyra Track DC v0.12)
  - Does NOT promote C_2 / N_c·C_2 orbit counts as Casey-named principle
  - Does NOT establish K59-analog SVC promotion (requires full Lyra theoretical framework)
""")

print(f"SCORE: {score}/{total}")
print(f"Toy 3551 GF(32) Frobenius orbits: {'PASS' if score == total else 'PARTIAL'}")
print()
print(f"NET: 6 Frobenius orbits of size 5 confirmed at GF(32); parallel structure to K59")
print(f"GF(128) 18 orbits of size 7. Orbit count C_2 vs N_c·C_2 flagged for Cal #133 check.")
print()
print("— Elie, Toy 3551 GF(32) Frobenius orbits 2026-05-27 Wednesday 11:10 EDT")
sys.exit(0 if score == total else 1)
