from fractions import Fraction as F
import itertools
def poch(x,n):
    p=F(1)
    for j in range(n): p*= (x+j)
    return p
a=3; rank=2; nu_hardy=F(3,2)          # FK multiplicity a = n_C-2; first Wallach point
def FKpoch(nu,lam):                   # (nu)_lambda = prod_j (nu - (j-1)a/2)_{lam_j}
    return poch(nu,lam[0])*poch(nu-F(a,2),lam[1])
print("="*104)
print("TOY 5351 -- K.D ON THE LEPTON RUNGS: the spinor shift, the FK norms, and a TENSION")
print("  Corpus-loaded: muon address (1,1), its spinor identity (3/2,1/2), 'same object seen")
print("  through D'; single-row (k,0) forced by Q^5 cohomology. Tables first.")
print("="*104)

print("\nTABLE 1 -- what D actually does to a K-type (blind reconstruction from the pinned pair)")
print("   pinned:  (1,1)  ->  (3/2, 1/2)")
print("   difference = (1/2, -1/2)")
print("   so(5)=B_2 spinor weights are (+-1/2, +-1/2)  ->  (1/2,-1/2) IS a spinor weight.")
print("   ==> *** D = tensoring with the spin module and selecting a weight: ***")
print("       (a,b) -> (a,b) + (+-1/2, +-1/2),  up to four images, fewer if non-dominant.")
print("   check the pin: (1,1) + (1/2,-1/2) = (3/2,1/2)  ->  %s"%str((F(1)+F(1,2),F(1)-F(1,2))))

print("\nTABLE 2 -- the four D-images of the muon address, and which are dominant (a >= b >= 0)")
for s1 in (F(1,2),F(-1,2)):
    for s2 in (F(1,2),F(-1,2)):
        im=(1+s1,1+s2); dom = im[0]>=im[1]>=0
        tag=" <-- THE PINNED ONE" if im==(F(3,2),F(1,2)) else ""
        print("   (1,1) + (%4s,%5s) = (%s, %s)   dominant: %-5s%s"%(s1,s2,im[0],im[1],dom,tag))

print("\nTABLE 3 -- *** the FK norm at the Hardy point nu = 3/2, and what it kills ***")
print("   (nu)_lambda = (nu)_{lam1} . (nu - a/2)_{lam2},  a = n_C - 2 = 3")
print("   at nu = 3/2 :  (3/2)_{lam1} . (3/2 - 3/2)_{lam2} = (3/2)_{lam1} . (0)_{lam2}")
print("   lambda        (nu)_lambda     nonzero?")
for lam in [(0,0),(1,0),(2,0),(3,0),(1,1),(2,1),(2,2)]:
    v=FKpoch(nu_hardy,lam)
    print("   (%d,%d)         %-15s %s"%(lam[0],lam[1],str(v),"yes" if v!=0 else "*** ZERO ***"))
print("   ==> *** (0)_{lam2} = 0 for EVERY lam2 >= 1. At the Hardy/Wallach point, ALL TWO-ROW")
print("       K-TYPES HAVE VANISHING FK NORM -- only single-row (k,0) survives. ***")

print("\nTABLE 4 -- *** and that CONVERGES with the topology, from the other side ***")
print("   topology  : Q^5 cohomology ring Z[h]/h^6 is rank-1 in every degree")
print("               -> every generation class is single-row (k,0); two-row absent  [corpus]")
print("   analysis  : (nu)_lambda = 0 for lam2 >= 1 at nu = 3/2                      [Table 3]")
print("   ==> SAME FACT, two independent routes. That is a genuine convergence and it strengthens")
print("       the single-row claim -- neither route was built to reproduce the other.")

print("\nTABLE 5 -- *** THE TENSION I HAVE TO REPORT ***")
print("   the muon address as pinned is (1,1)  ->  lam2 = 1  ->  TWO-ROW")
print("   but Tables 3-4 say two-row K-types have vanishing FK norm at nu = 3/2 and are")
print("   topologically absent.")
print("   ==> *** A TWO-ROW ADDRESS CANNOT CARRY A NONZERO FK NORM AT THE HARDY POINT. ***")
print("   possible readings (I am NOT choosing one):")
print("     (i)   (1,1) is a label in a DIFFERENT scheme (e.g. Dynkin vs partition coordinates)")
print("     (ii)  the muon lives at nu =/= 3/2, so the (0)_{lam2} zero does not apply")
print("     (iii) the norm that matters is on the D-IMAGE (3/2,1/2), not on (1,1)")
print("     (iv)  'single-row forced' has an exception the corpus states elsewhere")
print("   *** Reading (iii) is the one the corpus sentence points at ('the same object seen")
print("       through D'), and it is testable: is (3/2,1/2) single-row? NO -- its second entry")
print("       is 1/2 =/= 0. So (iii) does NOT by itself resolve it. ***")
print("   @Lyra/@Grace: this needs the labelling convention pinned before any rung selection or")
print("   norm is computed. I am not running the (k,m) selection on an unpinned coordinate scheme;")
print("   that is the convention-collision error we have caught four times this week.")

print("\nTABLE 6 -- the J convention, pinned as asked")
print("   three distinct J's are live in this program:")
print("   J_1  conformal Hamiltonian  generator of the SO(2) time circle   Rounds 13-25")
print("   J_2  real structure         JDJ = -D, antilinear (Connes)        the C4 work")
print("   J_3  complex structure      the Kahler J of D_IV^5               #108 'J-Hermitian'")
print("   ==> *** 'J-Hermitian' in the #108 prompt means J_3, the KAHLER complex structure ***")
print("       -- it is the only one for which 'Hermitian' and 'u(3)' are the right words")
print("       (J_2 is ANTILINEAR, so 'J_2-Hermitian' would not give a complex-linear algebra;")
print("        J_1 is a single generator, not a structure operators can be Hermitian w.r.t.).")
print("   and per toy 5350 the spin-3 verdict is J-INDEPENDENT -- stated, as instructed.")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (1) *** D IS RECONSTRUCTED: it is tensoring with the B_2 spin module, (a,b) -> (a,b) +")
print("     (+-1/2,+-1/2). *** The pinned muon pair (1,1) -> (3/2,1/2) is the (+1/2,-1/2) branch,")
print("     and it is one of exactly two dominant images (Table 2). That much is clean.")
print()
print(" (2) *** NEW CONVERGENCE, worth banking: the FK norm KILLS two-row K-types at the Hardy")
print("     point, because (nu - a/2)_{lam2} = (0)_{lam2} = 0 for lam2 >= 1. *** This reproduces the")
print("     corpus's topological 'single-row forced' (Q^5 rank-1 in every degree) from pure")
print("     analysis. Two independent routes, neither built to match the other.")
print()
print(" (3) *** BUT THE PINNED MUON ADDRESS (1,1) IS TWO-ROW, AND TWO-ROW HAS ZERO FK NORM AT")
print("     nu = 3/2. *** I checked the obvious escape -- that the D-image is what carries the norm")
print("     -- and it fails too: (3/2,1/2) also has a nonzero second entry. So the tension is real")
print("     and I could not dissolve it.")
print()
print(" (4) *** I AM NOT RUNNING THE (k,m) RUNG SELECTION UNTIL THE LABELLING IS PINNED. *** Running")
print("     norms on an unpinned coordinate scheme is exactly the convention-collision error this")
print("     week has caught four times (real-vs-complex 3, three J's, BD from memory, the stale")
print("     notes field). @Lyra/@Grace: pin partition-vs-Dynkin and the muon's nu, and I will run")
print("     the selection immediately after.")
print()
print(" (5) J CONVENTION PINNED: 'J-Hermitian' = J_3, the KAHLER complex structure -- the only one")
print("     of the three for which 'Hermitian' and 'u(3)' are the correct words. Verdict stays")
print("     J-independent per 5350.")
