import numpy as np
from fractions import Fraction as F
print("="*92)
print("PART 1 -- THE CORRECTED MIXING SCORECARD (banking Keeper's V_cb correction against my 5320)")
print("="*92)
obs={"V_us":(0.22431,0.00085),"V_cb":(0.04182,0.00085),"V_ub":(0.003820,0.00012)}
vus=1/np.sqrt(20); vcb=1/np.sqrt(42)
o,e=obs["V_us"]
print("\nTABLE 1 -- the numbers")
print("     V_us = 1/sqrt(20) = %.7f  vs %.5f +- %.5f  ->  %.2f%%, %.2f sigma   (BLIND, T2529/30)"%(
    vus,o,e,100*abs(vus-o)/o,abs(vus-o)/e))
o2,e2=obs["V_cb"]
print("     V_cb = 1/sqrt(42) = %.7f  vs %.5f +- %.5f  ->  %+.0f%%, %.0f sigma"%(
    vcb,o2,e2,100*(vcb-o2)/o2,abs(vcb-o2)/e2))
print("       and the RMS route lands ~5%% off -> STRUCTURAL, not Identified.")
print("\nTABLE 2 -- MY 5320 vs THE CORRECTION")
print("     element    my 5320 said        corrected")
print("     V_us       Derived-sharp       Derived-sharp (blind)        unchanged")
print("     V_cb       Identified-coarse   NOT DERIVED                  <- I was too generous")
print("     V_ub       Free                Free                         unchanged")
print("     delta_CP   Free                Free                         unchanged")
print("\nTABLE 3 -- the corrected count, of 4 CKM physical parameters")
print("     derived sharply : 1   (V_us)")
print("     not derived     : 3   (V_cb, V_ub, delta_CP)")
print("     plus            : the SKELETON (parity selection + one-rung), Structure-Derived, 0 params")
print("     Standard Model  : 0 of 4")
print("\n  ⟹ CORRECTION ACCEPTED AND BANKED. My 5320 carried V_cb as Identified-coarse; there is no")
print("     surviving V_cb derivation. The honest line is 'a derived skeleton plus ONE sharp angle',")
print("     which still beats 0-of-4 and needs no help from a fourth tier.")
print()
print("="*92)
print("PART 2 -- JOINING TIME: verifying Cal's parity identity  exp(2 pi i J) = -(-1)^F")
print("="*92)
Di=[F(2)+2*k for k in range(5)]; Rac=[F(3,2)+2*k for k in range(5)]
def ph(T,l): 
    z=np.exp(1j*T*float(l)); return complex(round(z.real,12),round(z.imag,12))
print("\nTABLE 4 -- the identity, tower by tower")
print("     tower   charges          exp(2 pi i J)   F   -(-1)^F   match?")
for nm,tw,Fno in [("Di",Di,1),("Rac",Rac,0)]:
    lhs={ph(2*np.pi,l) for l in tw}
    rhs=-((-1)**Fno)
    ok=(len(lhs)==1 and abs(list(lhs)[0]-rhs)<1e-9)
    print("     %-5s   %-16s %-14s  %d   %+d        %s"%(nm,str([str(x) for x in tw[:3]]),str(list(lhs)[0]),Fno,rhs,ok))
print("\n  ⟹ ★★ CAL'S IDENTITY VERIFIED EXACTLY ON BOTH TOWERS, with Di = fermion (F=1) and")
print("     Rac = boson (F=0). Not approximately -- exactly, on every level of each tower.")
print()
print("TABLE 5 -- the spin-statistics tension, made precise")
print("     ordinary ROTATION : exp(2 pi i J_rot) = (-1)^F   ->  bosons +1, fermions -1")
print("     BST's conformal J : exp(2 pi i J)     = -(-1)^F  ->  bosons -1, fermions +1")
print("     ⟹ the two differ by an overall factor of -1, AND the sign per species is INVERTED.")
print()
print("="*92)
print("VERDICT -- from Tables 4-5 only")
print("="*92)
print("  The identity is exact, and the tension with spin-statistics is exact too: BST's operator")
print("  gives the OPPOSITE sign per species from the rotation operator, plus an overall -1.")
print("  ⟹ THE HONEST RESOLUTION SHAPE (what @Keeper says is owed and unwritten): J is the CONFORMAL")
print("     HAMILTONIAN -- it generates a translation in conformal TIME, not a spatial ROTATION. So")
print("     exp(2 pi i J) is not the 2pi-rotation operator and is under no obligation to reproduce")
print("     (-1)^F. Spin-statistics constrains the ROTATION; it says nothing about a time translation.")
print("  ★ WHAT IS STILL OWED, and I will not paper over it: naming that is not the same as")
print("    EXHIBITING it. The extra -1 needs a derivation -- the natural candidate is that a 2pi")
print("    conformal-time translation is the ANTIPODAL map on the conformal boundary, which acts as")
print("    -1 on the whole spectrum. That is a CANDIDATE mechanism, not a banked one, and the paper")
print("    should say 'the sign is not the rotation's; its origin is an open identification' rather")
print("    than assert the antipodal reading before someone has computed it.")
