from fractions import Fraction as F
d=5   # SO(5,2) = conformal group of 5D Minkowski; Shilov boundary real dim 5
print("="*98)
print("TOY 5326 -- the Mack SHORT-REP question: does the VECTOR appear as a short rep in D_IV^5?")
print("  Tables first, verdict after.  *** This re-examines my OWN 5325 Table 3. ***")
print("="*98)

print("\nTABLE 1 -- Mack's unitarity bounds (1977) for SO(d,2), stated by BRANCH.")
print("  These are three DIFFERENT formulas, not one formula in s:")
print("     scalar   (l=0)     : Delta >= (d-2)/2")
print("     spinor             : Delta >= (d-1)/2")
print("     tensor   (l>=1)    : Delta >= d - 2 + l      <-- DIFFERENT BRANCH")
sc=F(d-2,2); sp=F(d-1,2); vec=F(d-2+1)
print("\n  at d = n_C = %d:"%d)
print("     scalar bound = %-5s   corpus Rac = 3/2   MATCH: %s"%(sc,sc==F(3,2)))
print("     spinor bound = %-5s   corpus Di  = 2     MATCH: %s"%(sp,sp==F(2)))
print("     VECTOR bound = %-5s   <-- NOT 5/2"%vec)
print("  (two independent confirmations that the boundary dimension really is d = n_C = 5)")

print("\nTABLE 2 -- *** MY 5325 TABLE 3 WAS WRONG. *** What I did vs what is true:")
print("   spin s   my 5325 used (d-2)/2 + s   TRUE Mack bound   same?")
for s,lab,mine,true in [(F(0),"scalar",sc+0,sc),(F(1,2),"spinor",sc+F(1,2),sp),(F(1),"VECTOR",sc+1,vec)]:
    print("   %-8s %-24s %-17s %s"%(str(s),lab+"  "+str(mine),str(true),
          "yes" if mine==true else "*** NO ***"))
print("   The scalar and spinor bounds differ by exactly 1/2 in EVERY d ((d-1)/2 - (d-2)/2 = 1/2),")
print("   so two points look like an arithmetic progression '+s'. IT IS NOT ONE. The l>=1 branch")
print("   is a different function. I fit a line through two branches and extrapolated into a third.")

print("\nTABLE 3 -- how bad is 5/2 for a vector?  (not merely 'not short')")
print("   Mack bound for l=1 at d=5 : Delta >= %s"%vec)
print("   proposed photon           : Delta  = 5/2")
print("   5/2 >= 4 ?                  %s"%(F(5,2)>=vec))
print("   ==> 5/2 is BELOW the unitarity bound ==> NEGATIVE-NORM STATES. Not a long rep --")
print("       a NON-UNITARY one. A spin-1 primary at 5/2 in a 5D CFT is a GHOST.")

print("\nTABLE 4 -- so IS there a short vector?  YES -- via Flato-Fronsdal, and it is COMPOSITE.")
print("   Rac (x) Rac  ->  conserved currents of spin l, with Delta = 2*Delta_Rac + l = (d-2) + l")
for l in range(4):
    print("      l = %d :  Delta = %s%s"%(l,F(d-2+l)," <-- THE VECTOR (conserved current)" if l==1 else ""))
print("   saturates the l>=1 branch EXACTLY ==> SHORT (conserved, partially conserved at l=0).")
print("   ==> the vector IS short, at E_0 = d - 1 = %s. It is a TWO-SINGLETON COMPOSITE,"%F(d-1))
print("       not a singleton -- so it was never going to be a third entry in the {Rac, Di} list.")

print("\nTABLE 5 -- *** re-run the Section-10 collision with the CORRECTED value ***")
S={F(3,2)*p+F(2)*q for p in range(40) for q in range(40)}
for cand,lab in [(F(5,2),"5/2  (my 5325 value)"),(F(4),"4    (corrected value)")]:
    print("   is %-22s in the semigroup <3/2, 2>?   %s"%(lab,"*** NO ***" if cand not in S else "YES"))
print("   4 = 2 + 2  and  4 = (d-2) + 1 = 2*(3/2) + 1.  Both land in the semigroup.")

print("\n"+"="*98)
print("VERDICT -- from Tables 1-5 only")
print("="*98)
print(" (1) *** I RETRACT MY OWN 5325 TABLE 3 AND ITS 5/2. *** The 'family' 3/2, 2, 5/2 was a FALSE")
print("     FAMILY: the scalar and spinor bounds are (d-2)/2 and (d-1)/2, which differ by 1/2 in")
print("     EVERY dimension, so any two of them mimic a '+s' progression. The l>=1 branch is a")
print("     different function. I ran a line through two branches into a third. That is exactly the")
print("     family-rule failure I have caught on other people's numbers twice -- my turn.")
print()
print(" (2) THE ANSWER TO THE ASSIGNED QUESTION: *** YES, the vector IS a short rep -- at E_0 = 4,")
print("     NOT 5/2. *** It saturates Mack's l>=1 branch (E_0 = d-2+l = 4) as a CONSERVED CURRENT,")
print("     and it arises in Rac (x) Rac by Flato-Fronsdal. It is a TWO-SINGLETON COMPOSITE, which")
print("     is why it never belonged in the {Rac, Di} singleton list in the first place.")
print()
print(" (3) 5/2 IS NOT MERELY UNSUPPORTED -- IT IS NON-UNITARY. 5/2 < 4 puts a spin-1 primary below")
print("     the unitarity bound: negative-norm states. @Lyra -- the vector row must come OUT of")
print("     Section 9 regardless of how the photon question settles; 5/2 is not a weak candidate,")
print("     it is a ghost.")
print()
print(" (4) *** AND THE COLLISION DISSOLVES -- IN SECTION 10's FAVOUR. *** The corrected value 4 IS")
print("     in the semigroup <3/2, 2> (Table 5). @Lyra: Section 10's generation rule SURVIVES the")
print("     test that 5/2 failed. The falsifier fired correctly -- it was pointing at MY number,")
print("     not at your rule. Section 10 stands as written.")
print("     ** Honest separation (shared-integer rule): '4 = 2+2' is a NUMERICAL fact; the MECHANISM")
print("        is 2*Delta_Rac + l. Both give 4. Do NOT claim the semigroup as the mechanism. **")
