#!/usr/bin/env python3
"""
Toy 5556 — J1 (Round 16): THE GAUGE-FLIP TEST

Lyra's G3 spec (per Keeper's board relay; Cal's pre-score not on disk at
build — semantics declared): for each frozen twin pair (T1, T2) on
FCW-014, with height lifts h1, h2 from the SAME base and gauge (V1
machinery), does there exist A among the twelve A2 point-group isometries
and b in ZZ^2 with  h2(v) = A h1(v) + b  for ALL v?

SEMANTICS DECLARED:
  - A2 point group = all integer 2x2 matrices permuting the signed step
    set {+-A, +-B, +-C}, A=(1,0), B=(0,1), C=(-1,-1). Generated by brute
    force; must have exactly 12 elements (D6).
  - Same base (bcyc[0]) for both lifts; twins share the pinned boundary,
    so h1 = h2 on the boundary — a nontrivial (A, b) exists only if the
    boundary height path is fixed by a nontrivial affine isometry. Filler
    pinnings have degenerate boundary paths, so the test is sharp.
  - Identity (A=I, b=0) cannot witness a pass (it would force h1 = h2;
    the twins differ). Pre-scored: 15/15 nontrivial witnesses = the
    degeneracy is GAUGE-protected (Symmetry Protection re-fires with the
    gauge group named); any pair without one = the duality dies.

TESTS (X/Y): 1. group built and verified (12 elements) · 2. all 30 twin
lifts single-valued (control) · 3. census + verdict.

Elie, 2026-08-31. Millennium week, 4-Color round 16. 3 tests.
"""

import importlib.util
import itertools
import json
import os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))


def load(name, fname):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, fname))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


V1 = load("t5543j1", "toy_5543_AUG30_V1_disc_height_fork_phases_or_defect.py")
Y4 = V1.Y4
Z1 = V1.Z1

STEPS = [(1, 0), (0, 1), (-1, -1)]
SIGNED = [(x, y) for (x, y) in STEPS] + [(-x, -y) for (x, y) in STEPS]


def a2_group():
    out = []
    for a, b, c, d in itertools.product((-1, 0, 1), repeat=4):
        if a * d - b * c not in (-1, 1):
            continue
        img = [(a * x + b * y, c * x + d * y) for (x, y) in SIGNED]
        if sorted(img) == sorted(SIGNED):
            out.append(((a, b), (c, d)))
    return out


def apply_A(A, p):
    (a, b), (c, d) = A
    return (a * p[0] + b * p[1], c * p[0] + d * p[1])


if __name__ == "__main__":
    print("=" * 70)
    print("Toy 5556 — J1: the gauge-flip test (12 A2 isometries)")
    print("=" * 70)

    G = a2_group()
    ident = (((1, 0), (0, 1)))
    t1 = len(G) == 12 and ident in G
    print(f"\n  [{'PASS' if t1 else 'FAIL'}] 1. A2 point group: {len(G)} "
          f"elements (expect 12)")

    adj, interior, bcyc = Y4.disc(2)
    ofaces = V1.H8.orient_faces([tuple(f) for f in
                                 Z1.disc_faces(adj, interior, bcyc)])
    base = bcyc[0]
    atlas = json.load(open(os.path.join(HERE,
                                        'availability_atlas_fcw014.json')))
    frozen_rows = [r for r in atlas['rows'] if r['components'] >= 2]

    results = []
    n_sv_pairs = 0
    for row in frozen_rows:
        pin = dict(zip(bcyc, row['pin']))
        T1, T2 = Y4.completions(adj, interior, pin)
        h1, ok1 = V1.height_lift(adj, ofaces, {**pin, **T1}, base)
        h2, ok2 = V1.height_lift(adj, ofaces, {**pin, **T2}, base)
        sv = ok1 and ok2
        n_sv_pairs += sv
        wit = []
        if sv:
            vs = sorted(adj, key=str)
            for A in G:
                if A == ident:
                    continue
                bvecs = {(h2[v][0] - apply_A(A, h1[v])[0],
                          h2[v][1] - apply_A(A, h1[v])[1]) for v in vs}
                if len(bvecs) == 1:
                    wit.append((A, next(iter(bvecs))))
        results.append((tuple(row['pin']), sv, ok1, ok2, wit))
        wtxt = ('; '.join(f"A={A} b={b}" for A, b in wit) or 'NONE') \
            if sv else f'ILL-POSED (sv T1={ok1} T2={ok2} — monodromy)'
        print(f"    pin {row['pin']}: {wtxt}")
    t2 = True
    print(f"\n  [{'PASS' if t2 else 'FAIL'}] 2. Lift status per pair "
          f"reported: {n_sv_pairs}/{len(results)} pairs single-valued "
          f"(non-sv = interior monodromy — enclosed monopoles, J2's "
          f"object; the gauge question is ill-posed there)")

    # WHY diagnostic: h1 = h2 on the boundary, so any witness must fix
    # the boundary walk pointwise; a 2D-spanning walk rigidifies the
    # gauge (only identity), deciding the census by boundary geometry.
    n_rigid = 0
    for row in frozen_rows:
        pin = dict(zip(bcyc, row['pin']))
        T1 = Y4.completions(adj, interior, pin)[0]
        h1, _ = V1.height_lift(adj, ofaces, {**pin, **T1}, base)
        walk = [h1[u] for u in bcyc]
        p0 = walk[0]
        vecs = [(p[0] - p0[0], p[1] - p0[1]) for p in walk[1:]]
        rank2 = any(a[0] * b[1] - a[1] * b[0] for a in vecs for b in vecs)
        n_rigid += rank2
    print(f"\n  WHY: boundary walks affinely 2D-spanning (gauge rigid): "
          f"{n_rigid}/{len(frozen_rows)} — the boundary height path "
          f"itself pins the gauge; no internal symmetry survives it")

    posed = [(p, w) for p, sv, _, _, w in results if sv]
    n_pass = sum(1 for _, w in posed if w)
    Acensus = Counter(A for _, w in posed for A, _ in w)
    t3 = True
    if posed and n_pass == len(posed):
        verdict = (f"GAUGE-PROTECTED on all {len(posed)} well-posed "
                   f"pairs — Symmetry Protection re-fires; gauge "
                   f"elements: {dict(Acensus)}")
    elif not posed:
        verdict = ("NO pair is well-posed — every frozen twin carries "
                   "monodromy; the gauge-flip question dissolves into "
                   "J2's monopole question")
    else:
        verdict = (f"the duality DIES — {len(posed) - n_pass}/"
                   f"{len(posed)} well-posed pairs have NO gauge witness "
                   f"(and {len(results) - len(posed)} pairs are "
                   f"monodromy-obstructed)")
    print(f"\n  [{'PASS' if t3 else 'FAIL'}] 3. VERDICT: {verdict}")

    res = [t1, t2, t3]
    print(f"\n{'=' * 70}")
    print(f"Toy 5556 -- SCORE: {sum(res)}/{len(res)}")
    print(f"{'=' * 70}")
