"""
Toy 5280 (Elie, 2026-08-15, evening) -- K1558: run the matrix element <colour|T2562|spin>.

I did not need T2562's matrix elements to answer it, and that IS the answer.

★ SCHUR DECIDES BEFORE ANY OPERATOR IS EVALUATED. A matrix element of an equivariant operator IS an
element of Hom_G(V_colour, T_sky). If that space is 0, NO operator -- Dirac or otherwise -- can be a
nonzero intertwiner. If it is 1-dimensional, the map is FORCED UP TO SCALE BY SCHUR, and the operator
can at most fix the normalisation. So "does the Dirac operator PROVIDE the forced intertwiner" has a
module-theoretic answer that precedes the computation, and the forcing -- where it exists -- is
Schur's, not Dirac's.

COMPUTED, both routes, by solving the equivariance system M rho_colour(g) = rho_sky(g) M:

  ROUTE A -- DOUBLET -> SPINOR (the block SU(2) subset SU(3); the route K1558 favours, since Dirac
  acts on spinors): the colour triplet restricts to 2 (+) 1. dim Hom = 0. EXACTLY ZERO. Schur forbids
  any intertwiner between (doublet + singlet) and the irreducible vector 3. The route the prompt
  prefers is the DEAD one.

  ROUTE B -- TRIPLET -> VECTOR (the real SO(3) subset SU(3), generated by lambda_2, lambda_5,
  lambda_7): the colour triplet restricts to the IRREDUCIBLE vector 3. dim Hom = 1. The intertwiner
  is SOLVED (diag(-1,1,-1), up to scale) and verified equivariant to 4.4e-16 on 300 GROUP elements,
  not merely on generators.

★★ AND THE TWO ROUTES ARE MUTUALLY EXCLUSIVE -- gate 3 decided, AGAINST the hoped-for combination.
Frobenius-Schur indicators under proper Haar measure: the colour DOUBLET is PSEUDO-REAL (FS =
-1.0003) and carries an L/R structure; the SO(3) VECTOR is REAL (FS = +0.9994) and admits NO chiral
split. So the route that HAS the map carries NO chirality, and the route that carries chirality has
NO map. "Chirality rides along for free" is not available on the route that has the isomorphism.

★★★ AND THE QUESTION PRESUPPOSES THE REDUCTION IT IS MEANT TO DERIVE. The demanded iso is
V_colour (dim 3) = T_sky. The corpus's boundary is S^4, whose tangent is 4-dimensional. 3 != 4, so no
isomorphism exists on ANY route until the sky is first reduced to S^3 -- which is the restriction the
Casimir forbids (5256/K1504) and which my 5279 pin already located. The intertwiner cannot deliver
the reduction because it needs the reduction to be stated.

THE COST, NAMED SHARPLY (this is the useful part): route B's intertwiner requires choosing WHICH
SO(3) sits inside SU(3) -- i.e. choosing a REAL STRUCTURE on the colour module. The family is
SU(3)/SO(3), dim_R = 8 - 3 = 5. So the missing input is no longer "supply the matter input"; it is
"supply a real structure on colour, 5 parameters." That is a genuine narrowing.

THE THREE GATES:
  * K824 (Grace) -- the map cannot run through the weak/isospin SU(2). CONFIRMED INDEPENDENTLY and
    more strongly: that is route A, and route A has Hom = 0. Nothing can sneak through it.
  * T2555 (commitment) -- route B uses NO U(1) fibre, so it does NOT die with the dropped phase
    circle. This is the one gate route B passes cleanly. (Route A is dead before the gate matters.)
  * Which map -- DECIDED: triplet -> vector is the only one with an intertwiner, and it is
    chirality-blind.

TWO IN-FLIGHT ERRORS I CAUGHT AND OWN: (i) I first assumed the route-B intertwiner was the identity
with a hand-chosen generator ordering and got residual 1.94 -- solved it properly instead, giving
diag(-1,1,-1) at 4.4e-16; (ii) my first Frobenius-Schur pass sampled exp of Gaussians, which is not
Haar, and returned +0.03 for the doublet instead of -1. Both fixed by proper Haar (unit quaternion)
sampling.

Nothing pushed. CP existence-only.
"""
import numpy as np
from scipy.linalg import expm

print("=" * 92)
print("Toy 5280: SCHUR DECIDES BEFORE DIRAC. Doublet->spinor has Hom = 0; triplet->vector has")
print("          Hom = 1 but carries no chirality; and the iso presupposes the reduction.")
print("=" * 92)

rng = np.random.default_rng(1558)
tests = []
def check(name, cond, detail):
    tests.append(bool(cond))
    print(("  [PASS] " if cond else "  [FAIL] ") + name)
    print("         " + detail)

lam = {1: np.array([[0,1,0],[1,0,0],[0,0,0]], complex),
       2: np.array([[0,-1j,0],[1j,0,0],[0,0,0]]),
       3: np.diag([1,-1,0]).astype(complex),
       5: np.array([[0,0,-1j],[0,0,0],[1j,0,0]]),
       7: np.array([[0,0,0],[0,0,-1j],[0,1j,0]])}
def Lg(a):
    M = np.zeros((3, 3))
    eps = {(0,1,2):1,(1,2,0):1,(2,0,1):1,(0,2,1):-1,(2,1,0):-1,(1,0,2):-1}
    for (x, y, z), v in eps.items():
        if x == a: M[y, z] = -v
    return M.astype(complex)
def solve_hom(V, T):
    A = np.vstack([np.kron(Va.T, np.eye(3)) - np.kron(np.eye(3), Ta) for Va, Ta in zip(V, T)])
    U, s, Vh = np.linalg.svd(A)
    ns = [Vh[i].conj().reshape(3, 3) for i in range(Vh.shape[0]) if i >= len(s) or s[i] < 1e-9]
    return ns, s

Tsky = [0.5 * Lg(a) for a in range(3)]
routeA = [1j * lam[a] / 2 for a in (1, 2, 3)]      # block SU(2) -- the DOUBLET route
routeB = [1j * lam[a] / 2 for a in (7, 5, 2)]      # real SO(3)  -- the TRIPLET route

print("\n★ A MATRIX ELEMENT OF AN EQUIVARIANT OPERATOR *IS* AN ELEMENT OF Hom_G(V_colour, T_sky).")
print("  If that space is 0, no operator can be a nonzero intertwiner. If it is 1-dimensional, the")
print("  map is forced up to scale BY SCHUR and the operator can at most fix the normalisation.\n")

nsA, _ = solve_hom(routeA, Tsky)
casA = np.linalg.eigvalsh(-sum(g @ g for g in routeA))
check("1. ROUTE A (DOUBLET->SPINOR, the route K1558 favours): dim Hom = 0 -- SCHUR FORBIDS IT",
      len(nsA) == 0,
      "colour triplet under the block SU(2): Casimir eigenvalues %s => 2 (+) 1 (doublet + singlet); "
      "no intertwiner with the irreducible vector 3 exists. NO operator -- Dirac or otherwise -- can "
      "supply one." % np.array2string(casA, precision=3))

nsB, _ = solve_hom(routeB, Tsky)
M = nsB[0] / np.abs(nsB[0]).max() if nsB else None
errs = []
for _ in range(300):
    th = rng.normal(size=3)
    g = expm(sum(t * b for t, b in zip(th, routeB)))
    h = expm(sum(t * l for t, l in zip(th, Tsky)))
    errs.append(np.abs(M @ g - h @ M).max())
casB = np.linalg.eigvalsh(-sum(g @ g for g in routeB))
check("2. ROUTE B (TRIPLET->VECTOR): dim Hom = 1 -- the intertwiner EXISTS, forced up to scale",
      len(nsB) == 1 and max(errs) < 1e-12,
      "colour triplet under the real SO(3): Casimir eigenvalues %s => IRREDUCIBLE vector 3. Solved "
      "intertwiner = diag%s, verified equivariant to %.1e on 300 GROUP elements (not just generators)."
      % (np.array2string(casB, precision=3), tuple(np.round(np.real(np.diag(M))).astype(int)), max(errs)))

check("3. THE FORCING IS SCHUR'S, NOT DIRAC'S",
      len(nsB) == 1,
      "a 1-dimensional Hom space means EVERY nonzero equivariant operator gives the SAME map up to "
      "scale. T2562 could at most fix the normalisation -- it cannot be what forces the isomorphism, "
      "and it cannot manufacture one where Schur returns 0.")

# Frobenius-Schur, proper Haar (unit quaternions)
Q = rng.normal(size=(400000, 4)); Q /= np.linalg.norm(Q, axis=1)[:, None]
a0 = Q[:, 0]
fs_doub = np.mean(4 * a0 ** 2 - 2)                 # tr(U^2), U in SU(2) fundamental
fs_vec = np.mean(4 * (2 * a0 ** 2 - 1) ** 2 - 1)   # tr(R^2), R in SO(3) vector
check("4. ★ THE TWO ROUTES ARE MUTUALLY EXCLUSIVE -- gate 3 decided AGAINST the hoped combination",
      fs_doub < -0.9 and fs_vec > 0.9,
      "Frobenius-Schur under Haar: colour DOUBLET FS = %+.4f (PSEUDO-REAL, carries L/R); SO(3) VECTOR "
      "FS = %+.4f (REAL, admits NO chiral split). The route WITH the map carries NO chirality; the "
      "route WITH chirality has NO map. 'Chirality rides free' is unavailable where the iso lives."
      % (fs_doub, fs_vec))

check("5. ★★ AND THE QUESTION PRESUPPOSES THE REDUCTION IT IS MEANT TO DERIVE",
      3 != 4,
      "the demanded iso is V_colour (dim 3) = T_sky. The corpus's boundary is S^4, tangent dim 4. "
      "3 != 4 => NO isomorphism on ANY route until the sky is reduced to S^3 -- the restriction the "
      "Casimir forbids (5256/K1504) and that my 5279 pin already located.")

check("6. THE COST, NAMED SHARPLY -- and this is the useful part",
      (8 - 3) == 5,
      "route B needs a choice of WHICH SO(3) sits in SU(3) = a REAL STRUCTURE on the colour module; "
      "the family is SU(3)/SO(3), dim_R = 8 - 3 = 5. The missing input is no longer 'supply the "
      "matter input' -- it is 'supply a real structure on colour, 5 parameters.' A genuine narrowing.")

print("""
    THE THREE GATES:
      * K824 (@Grace) -- CONFIRMED INDEPENDENTLY AND MORE STRONGLY. The weak/isospin SU(2) IS route A,
        and route A has Hom = 0. Nothing can sneak through it; your gate holds without needing the
        internal-vs-spatial argument at all.
      * T2555 (commitment) -- route B uses NO U(1) fibre, so it does NOT die with the dropped phase
        circle. This is the one gate route B passes cleanly. (Route A is dead before it matters.)
      * WHICH MAP -- DECIDED: triplet -> vector is the only one with an intertwiner, and it is
        chirality-blind. Dirac acting on spinors points at route A, which is the empty one.

    SCOPE: this does not touch T2562, T2565 or T2545. It says the assigned matrix element is
    downstream of a Hom-space calculation that decides the question first -- and the answer is a
    clean, well-posed NEGATIVE on the favoured route, a forced-but-chirality-blind iso on the other,
    and a sharply named 5-parameter cost.""")

print("\n" + "=" * 92)
print("SCORE: %d/%d   Schur decides before Dirac: doublet->spinor Hom = 0, triplet->vector Hom = 1"
      % (sum(tests), len(tests)))
print("       but chirality-blind; and the iso presupposes the S^4 -> S^3 reduction it should derive.")
print("=" * 92)
