from fractions import Fraction as F
N_c=3; RAC=F(3,2); DI=F(2); d=5
print("="*104)
print("TOY 5331 -- Casey's time<->EM KILL-CHECK: is the charge-SO(2) the SAME U(1) as the time-SO(2)?")
print("  Corpus loaded first: T2470 (charge = SO(2)-weight, PROVED), K = SO(5) x SO(2).")
print("  Tables first, verdict after.")
print("="*104)

print("\nTABLE 1 -- SPECTRUM TEST. Same operator => same spectrum. Compare the two.")
print("   operator            spectrum                                    bounded?")
print("   charge Q  (T2470)   exactly N_c+1 = %d magnitudes {0,1/3,2/3,1}   YES -- capped at 1"%(N_c+1))
print("   time J    (the flow) towers 3/2, 7/2, 11/2, ... and 2, 4, 6, ...  NO  -- unbounded above")
print("   ==> *** A BOUNDED OPERATOR CANNOT EQUAL AN UNBOUNDED ONE. FIRST KILL. ***")

print("\nTABLE 2 -- FUNCTION TEST. Weaker claim: is charge at least a FUNCTION of Delta, Q = f(J)?")
print("   If so, equal Delta must force equal charge. Find two states with the SAME Delta:")
print("   particle    composite slot        Delta    charge Q")
same=[("muon","Rac (x) Di, l=0",F(7,2),"-1"),("neutrino","Rac (x) Di, l=0",F(7,2)," 0")]
for p,s,D,q in same:
    print("   %-11s %-21s %-8s %s"%(p,s,str(D),q))
print("   SAME Delta = 7/2, DIFFERENT charge (-1 vs 0).")
print("   ==> *** CHARGE IS NOT EVEN A FUNCTION OF Delta. SECOND, INDEPENDENT KILL. ***")

print("\nTABLE 3 -- so WHERE does charge live?  Count the SO(2)'s available in K.")
print("   K = SO(5) x SO(2)")
print("   SO(5) is B_2: RANK 2  ->  maximal torus = SO(2) x SO(2)   (two INTERNAL circles)")
print("   the explicit SO(2) factor                                  (one TIME circle)")
print("   total independent commuting U(1)'s in K: 2 + 1 = 3")
print("   ==> there is NO shortage of SO(2)'s. 'The SO(2)' is ambiguous, and T2470's charge circle")
print("       need not be -- and by Tables 1-2 CANNOT be -- the K-factor time circle.")

print("\nTABLE 4 -- *** the consolation, and it is a real one: why charge is CONSERVED ***")
print("   K = SO(5) x SO(2) is a DIRECT PRODUCT, so every generator of SO(5) commutes with the")
print("   SO(2)-factor generator:  [Q_internal , J] = 0  identically.")
print("   ==> charge is conserved under time evolution BECAUSE the two circles sit in different")
print("       direct factors of K. That is a derivation of charge conservation from the geometry.")

print("\nTABLE 5 -- the Higgs (1,0) map: does an internal 5-vector fit an even-#Rac slot?")
print("   (1,0) of SO(5) = the VECTOR rep, dim 5  (INTERNAL index -- not spacetime spin, per 5330)")
print("   IF the Rac carries the SO(5) spinor 4, then the two-Rac product decomposes as:")
print("       4 (x) 4 = 16 = 1 + 5 + 10   ->  CONTAINS the 5 = (1,0)")
print("   slot check: Rac (x) Rac has #Rac = 2 (EVEN -> boson, passes 5329 parity prong)")
print("               and l = 0 -> spacetime SCALAR (passes the spin prong)")
print("   ==> a (1,0) internal 5-vector that is a spacetime scalar with even #Rac EXISTS in Rac(x)Rac.")
print("   *** CONDITIONAL: this rests on 'Rac carries the SO(5) spinor 4', which I did NOT verify.")
print("       That K-type must be pinned to source. It is the hinge of the whole map. ***")

print("\n"+"="*104)
print("VERDICT -- from Tables 1-5 only")
print("="*104)
print(" (1) ***** CASEY'S TIME<->EM: THE ANSWER IS *DIFFERENT U(1)s*, killed two independent ways.")
print("     (a) SPECTRUM: charge is capped at N_c+1 = 4 magnitudes (T2470, proved); J is unbounded")
print("         above. A bounded operator is not an unbounded one.")
print("     (b) FUNCTION: the muon and the neutrino are BOTH Rac(x)Di at l=0, so they share")
print("         Delta = 7/2, yet carry charges -1 and 0. Charge is not even a FUNCTION of Delta.")
print("     ==> it is a STRUCTURAL ANALOGY, not a unification. Casey's electric<->magnetic intuition")
print("         does not survive as 'one SO(2) read three ways'.")
print()
print(" (2) *** BUT THE CHECK PAYS FOR ITSELF. *** K = SO(5) x SO(2) is a DIRECT PRODUCT, so")
print("     [Q_internal, J] = 0 identically ==> CHARGE CONSERVATION IS DERIVED FROM THE GEOMETRY:")
print("     charge is conserved under time evolution precisely BECAUSE the charge circle and the")
print("     time circle sit in different direct factors. Not the unification asked for; a real")
print("     theorem instead. The separateness IS the content.")
print()
print(" (3) SHARED-INTEGER GUARD: SO(5) has rank 2, and D_IV^5 has rank 2. *** These are two")
print("     different rank-2's *** (a compact group's rank vs a symmetric space's rank). Do not")
print("     merge them -- that is the trap that has fired nine times in this program.")
print()
print(" (4) HIGGS MAP, PARTIAL PROGRESS: Rac(x)Rac at l=0 has even #Rac and is a spacetime scalar,")
print("     and IF the Rac carries the SO(5) spinor 4 then 4(x)4 = 1+5+10 supplies the (1,0)")
print("     internal 5-vector. Both prongs of the 5329 filter would pass. *** The hinge -- the Rac's")
print("     SO(5) K-type -- is NOT verified here and must be pinned to source. @Grace: that single")
print("     K-type is the whole map. ***")
