import numpy as np, sympy as sp
print("="*92)
print("THE KOIDE GATE (#64): what exactly must be derived, and is the advertised identity the")
print("derived one?  Structure first, before any overlap computation.")
print("="*92)
A,th,N,k,r=sp.symbols('A theta N k r', positive=True)
print("  standard Koide parameterisation:  sqrt(m_k) = M (1 + A cos(theta + 2 pi k / N)),  k = 0..N-1")
print("  -- and I will do this symbolically so nothing is fitted.\n")
for Nv in [3,4,5]:
    ks=range(Nv)
    S1=sp.simplify(sum(1+A*sp.cos(th+2*sp.pi*i/Nv) for i in ks))
    S2=sp.simplify(sp.expand_trig(sp.expand(sum((1+A*sp.cos(th+2*sp.pi*i/Nv))**2 for i in ks))))
    Q=sp.simplify(S2/S1**2)
    print("     N = %d :  sum sqrt(m)/M = %-8s   sum m/M^2 = %-22s   Q = %s"%(Nv,S1,sp.simplify(S2),sp.simplify(Q)))
print("\n  ⟹ THE GENERAL RESULT:  Q = (1 + A^2/2) / N,  and it is INDEPENDENT OF theta.")
print("     At N = 3 with A^2 = 2:  Q = (1+1)/3 = 2/3, exactly, for EVERY theta.")
print("  ★ SO THE GATE IS CORRECTLY IDENTIFIED: A^2 = 2 is precisely what forces Q = 2/3.")
print()
print("  verify against the measured leptons (the target is public and already in the corpus --")
print("  this is checking the identity, NOT predicting the masses; the pilot blind is untouched):")
me,mmu,mtau=0.51099895,105.6583755,1776.86
Qobs=(me+mmu+mtau)/(np.sqrt(me)+np.sqrt(mmu)+np.sqrt(mtau))**2
print("     Q_observed = %.9f    2/3 = %.9f    deviation %.2e"%(Qobs,2/3,abs(Qobs-2/3)))
Aimp=np.sqrt(2*(3*Qobs-1))
print("     implied A  = %.6f    sqrt(2) = %.6f   ->  A^2 = %.6f"%(Aimp,np.sqrt(2),Aimp**2))
print()
print("="*92)
print("★★★ BUT THE ADVERTISED IDENTITY IS NOT THE DERIVED ONE.  Q = rank/N_c is a COINCIDENCE.")
print("="*92)
print("  The derived denominator is N_gen -- the number of GENERATIONS -- not N_c, the number of")
print("  COLOURS. Both are 3, and they are different objects (F86: N_gen = rank + 1, which has no")
print("  colour in it at all).")
print()
print("  Substituting the corpus's own structure -- A^2 = rank and N_gen = rank + 1 (F86):")
Qder=(1+r/2)/(r+1)
print("     DERIVED   Q(r) = (1 + r/2)/(r+1) = %s"%sp.simplify(Qder))
print("     ADVERTISED Q    = rank/N_c, and as a rank-formula the natural reading is r/(r+1)")
for rv in [2,3,4]:
    a=sp.nsimplify(Qder.subs(r,rv)); b=sp.Rational(rv,rv+1)
    print("       r = %d :  derived = %-8s   r/(r+1) = %-8s   equal? %s"%(rv,a,b,a==b))
print("\n  ⟹ THEY AGREE AT r = 2 AND NOWHERE ELSE -- the same diagnostic that settled the integer web")
print("     (my 5300) and the null model (my 5301).  Q = rank/N_c is a coincidence AT rank 2.")
print("     THE STRUCTURAL FORM IS  Q = (rank + 2) / (2(rank + 1)),  with NO N_c in it.")
print()
print("  ★ AND THIS ONE IS GOOD NEWS METHODOLOGICALLY: unlike the two-2s problem (my 5300), the")
print("    discriminator IS available here -- the two formulas separate at r = 3 (5/8 vs 3/4).")
print("    So if a rank-3 Jordan analogue is ever constructed, the reading is testable.")
print()
print("="*92)
print("WHAT THE GATE NOW NEEDS, STATED PRECISELY")
print("="*92)
print("  DERIVE:  A^2 = 2 from the Bergman overlap at the F86 strata (bulk dim n_C=5 / Cartan slice")
print("           dim rank=2 / Shilov points dim 0) -- theta-independently.")
print("  DO NOT:  match the integer 2 to the Cartan-slice dimension. That is the eighth 2 of the arc")
print("           (Jordan rank / SO(2) signature / erasure distance / Cartan slice / Koide amplitude),")
print("           and a shared integer is not a shared object.")
print("  AND FIX: the claim line should read Q = (rank+2)/(2(rank+1)), not Q = rank/N_c.")
