#!/usr/bin/env python3
"""
toy 5697 — Grace, 2026-09-06 (Keeper handoff G1; Casey's word).

The cone-zeta of Z^{1,n} (K1862-A):  r*(N) = sum over chamber vectors x with Q(x)=N of 1/|W_x|,
Q = x0^2 - x1^2 - ... - xn^2, chamber = Vinberg simplex of O+(Z^{1,n}) (n <= 9).
Independent instrument (no code shared with Keeper's scratchpad/siegel_check2_final.py, which I have not read):

  Part A  chamber enumeration + stabilizer orders by parabolic Coxeter-type recognition, validated by BFS closure.
  Part B  x^perp Gram matrices for primitive x; isometry classes and |O(L)| by exhaustive short-vector backtracking.
  Part C  Nipp's tables (external): mass identity  r*(N) = 2^{omega_odd(N)} * sum_{L admissible, det N} 1/|O(L)|
          for squarefree N, and class-by-class comparison.  Pre-registered: notes/grace_PREREG_toy_5697_*.md.

Usage:  python3 toy_5697_*.py [Nmax=108] [nipp_dir=scratchpad]
"""
import sys, os, re, math, itertools, json, time
from fractions import Fraction
from math import gcd, isqrt

# ----------------------------------------------------------------------------------------------
# Part A: Vinberg chamber of Z^{1,n}
# ----------------------------------------------------------------------------------------------
def B(x, y):
    """Lorentzian bilinear form x0 y0 - sum xi yi."""
    return x[0]*y[0] - sum(a*b for a, b in zip(x[1:], y[1:]))

def vinberg_roots(n):
    """Simple roots of O+(Z^{1,n}), n>=2, signed so the chamber is {x : B(x,r) >= 0 for all r}.
    r_i = e_{i+1} - e_i (i=1..n-1): B(x,r_i) = x_i - x_{i+1} >= 0
    r_n = -e_n:                      B(x,r_n) = x_n >= 0
    r_{n+1} = e0 + e1 + e2 + e3 (n>=3), e0 + e1 + e2 (n=2): B = x0 - x1 - x2 - x3 >= 0."""
    dim = n + 1
    roots = []
    for i in range(1, n):
        r = [0]*dim; r[i+1] = 1; r[i] = -1; roots.append(tuple(r))
    r = [0]*dim; r[n] = -1; roots.append(tuple(r))
    r = [0]*dim; r[0] = 1
    for i in range(1, min(3, n) + 1):
        r[i] = 1
    roots.append(tuple(r))
    return roots

def coxeter_label(r, s):
    """m_ij from the Gram of two roots (both of negative norm)."""
    b = B(r, s); qr, qs = B(r, r), B(s, s)
    c2 = Fraction(b*b, qr*qs)
    return {Fraction(0): 2, Fraction(1, 4): 3, Fraction(1, 2): 4, Fraction(3, 4): 6}.get(c2, 0)  # 0 = infinite

FINITE_ORDERS = {}
def coxeter_order(roots, subset):
    """Order of the parabolic subgroup generated by the reflections in roots[i], i in subset.
    Recognises the finite type of each connected component (A, B, D, E6-8, F4, G2); returns None if infinite."""
    subset = tuple(sorted(subset))
    key = (tuple(roots), subset)
    if key in FINITE_ORDERS:
        return FINITE_ORDERS[key]
    k = len(subset)
    lab = {}
    for a in range(k):
        for b in range(a+1, k):
            m = coxeter_label(roots[subset[a]], roots[subset[b]])
            if m == 0:
                FINITE_ORDERS[key] = None; return None
            if m > 2:
                lab[(a, b)] = m
    # components
    adj = {a: set() for a in range(k)}
    for (a, b) in lab:
        adj[a].add(b); adj[b].add(a)
    seen = set(); order = 1
    for start in range(k):
        if start in seen: continue
        comp = []; stack = [start]
        while stack:
            v = stack.pop()
            if v in seen: continue
            seen.add(v); comp.append(v); stack.extend(adj[v] - seen)
        order *= component_order(comp, adj, lab)
        if order == 0:
            FINITE_ORDERS[key] = None; return None
    FINITE_ORDERS[key] = order
    return order

def component_order(comp, adj, lab):
    kc = len(comp)
    edges = [(a, b) for (a, b) in lab if a in comp]
    if len(edges) != kc - 1:
        return 0                                   # cycle -> affine/infinite
    labels = sorted(lab[e] for e in edges)
    degs = {v: len(adj[v]) for v in comp}
    maxdeg = max(degs.values()) if comp else 0
    big = [m for m in labels if m > 3]
    if kc == 1: return 2
    if not big:
        if maxdeg <= 2: return math.factorial(kc + 1)                     # A_k
        branch = [v for v in comp if degs[v] == 3]
        if len(branch) != 1 or maxdeg > 3: return 0
        v = branch[0]; arms = []
        for w in adj[v]:
            L = 1; prev, cur = v, w
            while degs[cur] == 2:
                nxt = (adj[cur] - {prev}).pop(); prev, cur = cur, nxt; L += 1
            arms.append(L)
        arms.sort()
        if arms[0] == 1 and arms[1] == 1: return 2**(kc-1) * math.factorial(kc)   # D_k
        if arms == [1, 2, 2]: return 51840
        if arms == [1, 2, 3]: return 2903040
        if arms == [1, 2, 4]: return 696729600
        return 0
    if len(big) == 1 and big[0] == 4:
        if maxdeg > 2: return 0
        e4 = [e for e in edges if lab[e] == 4][0]
        ends = [v for v in comp if degs[v] == 1]
        if kc == 2: return 8
        if e4[0] in ends or e4[1] in ends: return 2**kc * math.factorial(kc)         # B_k
        if kc == 4: return 1152                                                        # F_4
        return 0
    if len(big) == 1 and big[0] == 6 and kc == 2: return 12                            # G_2
    return 0

def reflect(x, r):
    q = B(r, r); b = B(x, r)
    t = Fraction(2*b, q)
    assert t.denominator == 1
    t = int(t)
    return tuple(xi - t*ri for xi, ri in zip(x, r))

def bfs_order(roots, subset, cap=2_000_000):
    """Order of the group generated by the reflections in the given roots, by closure on matrices (columns = images of e_i)."""
    dim = len(roots[0])
    basis = [tuple(1 if j == i else 0 for j in range(dim)) for i in range(dim)]
    gens = [tuple(reflect(e, roots[i]) for e in basis) for i in subset]  # matrix as tuple of column images
    def mul(g, h):  # g∘h : columns of h mapped through g
        return tuple(tuple(sum(g[j][k]*h[i][j] for j in range(dim)) for k in range(dim)) for i in range(dim))
    ident = tuple(basis)
    seen = {ident}; frontier = [ident]
    while frontier:
        new = []
        for g in frontier:
            for s in gens:
                h = mul(s, g)
                if h not in seen:
                    seen.add(h); new.append(h)
                    if len(seen) > cap: return None
        frontier = new
    return len(seen)

def chamber_vectors(n, Nmax):
    """All x = (x0,...,xn) in the closed Vinberg chamber with 1 <= Q(x) <= Nmax.  Returns dict N -> list of x."""
    out = {N: [] for N in range(1, Nmax+1)}
    if n >= 3:
        b3 = isqrt(Nmax // (9 - n)) + 1
        b2 = isqrt(3*Nmax // (9 - n)) + 1
    else:
        b3 = 0; b2 = isqrt(Nmax // 2) + 1
    # x2 >= x3 >= ... >= xn >= 0 with x3.. <= b3, x2 <= b2 ; x1 >= x2 ; x0 >= x1+x2+x3 (or x1+x2)
    def tails(prev, depth):
        if depth == 0:
            yield (); return
        for v in range(0, min(prev, b3) + 1):
            for rest in tails(v, depth - 1):
                yield (v,) + rest
    for x2 in range(0, b2 + 1):
        for tail in tails(x2, max(0, n - 2)):
            x3 = tail[0] if n >= 3 else 0
            S_rest = x2*x2 + sum(t*t for t in tail)
            if x2 >= 1:
                x1max = (Nmax + (n-3 if n >= 3 else 0)*x3*x3) // (2*x2) + 1
            else:
                x1max = Nmax // 2 + 1
            for x1 in range(x2, x1max + 1):
                S = S_rest + x1*x1
                lo = max(x1 + x2 + x3, isqrt(S) + 1)
                hi = isqrt(S + Nmax)
                for x0 in range(lo, hi + 1):
                    N = x0*x0 - S
                    if 1 <= N <= Nmax:
                        x = (x0, x1, x2) + tuple(tail)
                        assert all(B(x, r) >= 0 for r in vinberg_roots(n))
                        out[N].append(x)
    return out

def stabilizer_subset(x, roots):
    return [i for i, r in enumerate(roots) if B(x, r) == 0]

def cone_zeta(n, Nmax, check_bfs=False):
    """Returns dict N -> list of (x, |W_x|, primitive?) and r*(N) as Fractions."""
    roots = vinberg_roots(n)
    ch = chamber_vectors(n, Nmax)
    data = {}; rstar = {}; rprim = {}
    for N in range(1, Nmax+1):
        rows = []
        for x in ch[N]:
            sub = stabilizer_subset(x, roots)
            w = coxeter_order(roots, sub)
            assert w is not None, (x, sub)
            if check_bfs:
                wb = bfs_order(roots, sub)
                assert wb == w, (x, sub, w, wb)
            prim = (math.gcd(*x) == 1)
            rows.append((x, w, prim))
        data[N] = rows
        rstar[N] = sum(Fraction(1, w) for _, w, _ in rows)
        rprim[N] = sum(Fraction(1, w) for _, w, p in rows if p)
    return data, rstar, rprim

# ----------------------------------------------------------------------------------------------
# Part B: x^perp, reduction, short vectors, isometries
# ----------------------------------------------------------------------------------------------
def int_kernel_basis(w):
    """Integer basis of {v in Z^m : w.v = 0} for an integer row vector w (not all zero)."""
    m = len(w)
    w = list(w)
    U = [[1 if i == j else 0 for j in range(m)] for i in range(m)]   # columns of U are basis vectors; w*U tracked in w
    def colop(j, i, q):   # column j -= q * column i
        for k in range(m): U[k][j] -= q*U[k][i]
        w[j] -= q*w[i]
    def swap(i, j):
        for k in range(m): U[k][i], U[k][j] = U[k][j], U[k][i]
        w[i], w[j] = w[j], w[i]
    # Euclid all entries into position 0
    while any(w[j] != 0 for j in range(1, m)):
        # move the smallest nonzero |w| to position 0
        j0 = min((j for j in range(m) if w[j] != 0), key=lambda j: abs(w[j]))
        if j0 != 0: swap(0, j0)
        for j in range(1, m):
            if w[j] != 0:
                q = w[j] // w[0]
                colop(j, 0, q)
    return [[U[k][j] for k in range(m)] for j in range(1, m)]   # list of basis vectors (rows here)

def gram_of_perp(x):
    """Positive-definite integer Gram matrix of x^perp (Lorentzian form negated), for x with Q(x) > 0."""
    w = [x[0]] + [-xi for xi in x[1:]]
    basis = int_kernel_basis(w)
    n = len(basis)
    G = [[-B(basis[i], basis[j]) for j in range(n)] for i in range(n)]
    return G

def det_int(M):
    M = [list(map(Fraction, row)) for row in M]; n = len(M); d = Fraction(1)
    for i in range(n):
        p = next((r for r in range(i, n) if M[r][i] != 0), None)
        if p is None: return 0
        if p != i: M[i], M[p] = M[p], M[i]; d = -d
        d *= M[i][i]
        for r in range(i+1, n):
            f = M[r][i] / M[i][i]
            for c in range(i, n): M[r][c] -= f*M[i][c]
    assert d.denominator == 1
    return int(d)

def pair_reduce(G):
    """Greedy pairwise reduction of a positive-definite Gram matrix (exact, integer)."""
    n = len(G); G = [row[:] for row in G]
    changed = True
    while changed:
        changed = False
        for i in range(n):
            for j in range(n):
                if i == j: continue
                q = round(G[i][j] / G[j][j])
                if q == 0: continue
                newii = G[i][i] - 2*q*G[i][j] + q*q*G[j][j]
                if newii < G[i][i]:
                    # b_i <- b_i - q b_j
                    for k in range(n):
                        if k != i: G[i][k] -= q*G[j][k]; G[k][i] = G[i][k]
                    G[i][i] = newii
                    changed = True
        # sort by diagonal
        order = sorted(range(n), key=lambda i: G[i][i])
        if order != list(range(n)):
            G = [[G[a][b] for b in order] for a in order]; changed = True
    return G

def short_vectors(G, C):
    """All integer v != 0 with v^T G v <= C (Fincke–Pohst with exact rational Cholesky, exact final check)."""
    n = len(G)
    # q_ij as Fractions: Q(v) = sum_i q_ii (v_i + sum_{j>i} q_ij v_j)^2
    q = [[Fraction(0)]*n for _ in range(n)]
    A = [[Fraction(G[i][j]) for j in range(n)] for i in range(n)]
    for i in range(n):
        q[i][i] = A[i][i]
        for j in range(i+1, n):
            q[i][j] = A[i][j] / A[i][i]
        for k in range(i+1, n):
            for l in range(k, n):
                A[k][l] -= q[i][k]*q[i][l]*A[i][i]; A[l][k] = A[k][l]
    out = []
    v = [0]*n
    def rec(i, T):
        # T = remaining budget (Fraction)
        c = -sum(q[i][j]*v[j] for j in range(i+1, n))
        rad = math.sqrt(float(T / q[i][i])) + 1e-9
        lo = math.ceil(float(c) - rad); hi = math.floor(float(c) + rad)
        for vi in range(lo, hi+1):
            v[i] = vi
            T2 = T - q[i][i]*(vi - c)**2
            if T2 < 0: continue
            if i == 0:
                vec = tuple(v)
                if any(vec):
                    val = sum(G[a][b]*vec[a]*vec[b] for a in range(n) for b in range(n))
                    if val <= C: out.append((val, vec))
            else:
                rec(i-1, T2)
        v[i] = 0
    rec(n-1, Fraction(C))
    return out

def theta_invariant(G, C):
    sv = short_vectors(G, C)
    cnt = {}
    for val, _ in sv: cnt[val] = cnt.get(val, 0) + 1
    return tuple(sorted(cnt.items()))

def isometries(G1, G2, limit=None):
    """All integer matrices V (columns v_i) with V^T G2 V = G1, i.e. isometries L1 -> L2; returns the count (and first found)."""
    n = len(G1)
    C = max(G1[i][i] for i in range(n))
    sv = short_vectors(G2, C)
    bynorm = {}
    for val, vec in sv: bynorm.setdefault(val, []).append(vec)
    cands = [bynorm.get(G1[i][i], []) for i in range(n)]
    def ip(u, w): return sum(G2[a][b]*u[a]*w[b] for a in range(n) for b in range(n))
    count = 0; first = None
    chosen = []
    def rec(i):
        nonlocal count, first
        if i == n:
            count += 1
            if first is None: first = [c[:] for c in chosen]
            return
        for vec in cands[i]:
            if all(ip(vec, chosen[j]) == G1[i][j] for j in range(i)):
                chosen.append(list(vec)); rec(i+1); chosen.pop()
                if limit and count >= limit: return
    rec(0)
    return count, first

def classify(grams, C_extra=0):
    """Group Gram matrices into isometry classes. Returns list of classes: dict(rep=G, members=[indices], aut=|O(L)|)."""
    classes = []
    inv_index = {}
    reduced = [pair_reduce(G) for G in grams]
    # one common theta bound for the whole batch: pairwise reduction is not canonical, so a per-Gram bound
    # would put isometric lattices in different invariant buckets (caught 10:12 on N = 21: 4 classes for 3)
    C_common = max((G[i][i] for G in reduced for i in range(len(G))), default=0) + C_extra
    for idx, G in enumerate(reduced):
        C = C_common
        inv = (det_int(G), theta_invariant(G, C))
        placed = False
        for ci in inv_index.get(inv, []):
            cnt, _ = isometries(G, classes[ci]['rep'], limit=1)
            if cnt > 0:
                classes[ci]['members'].append(idx); placed = True; break
        if not placed:
            aut, _ = isometries(G, G)
            classes.append({'rep': G, 'members': [idx], 'aut': aut})
            inv_index.setdefault(inv, []).append(len(classes)-1)
    return classes

# ----------------------------------------------------------------------------------------------
# discriminant-form constant and admissibility
# ----------------------------------------------------------------------------------------------
def adjugate(G):
    n = len(G); d = det_int(G)
    Minv = mat_inv_frac(G)
    adj = [[Minv[i][j]*d for j in range(n)] for i in range(n)]
    assert all(a.denominator == 1 for row in adj for a in row)
    return [[int(a) for a in row] for row in adj]

def mat_inv_frac(G):
    n = len(G)
    M = [[Fraction(G[i][j]) for j in range(n)] + [Fraction(1 if i == j else 0) for j in range(n)] for i in range(n)]
    for i in range(n):
        p = next(r for r in range(i, n) if M[r][i] != 0)
        M[i], M[p] = M[p], M[i]
        piv = M[i][i]
        M[i] = [a/piv for a in M[i]]
        for r in range(n):
            if r != i and M[r][i] != 0:
                f = M[r][i]; M[r] = [a - f*b for a, b in zip(M[r], M[i])]
    return [row[n:] for row in M]

def squarefree_factors(N):
    fs = []; m = N; p = 2
    while p*p <= m:
        if m % p == 0:
            fs.append(p); m //= p
            if m % p == 0: return None
        p += 1
    if m > 1: fs.append(m)
    return fs

def disc_constant(G, N):
    """c_L mod N for squarefree N (D(L) = L*/L cyclic of order N): pick an integer vector u with
    w = adj(G) u / N of order N in L*/L (i.e. gcd(N, adj(G) u) = 1); then N*b(w,w) = u^T adj(G) u mod N."""
    adj = adjugate(G); n = len(G)
    for rng in (2, 4, 8):
        for u in itertools.product(range(-rng, rng+1), repeat=n):
            if not any(u): continue
            au = [sum(adj[i][j]*u[j] for j in range(n)) for i in range(n)]
            g = N
            for a in au: g = gcd(g, a)
            if g == 1:
                return sum(u[i]*adj[i][j]*u[j] for i in range(n) for j in range(n)) % N
    return None

def is_square_mod(c, p):
    if p == 2: return True
    return pow(c % p, (p-1)//2, p) == 1 if c % p else True

def admissible(G, N):
    fs = squarefree_factors(N)
    if N == 1: return True
    c = disc_constant(G, N)
    if c is None: return None
    return all(is_square_mod(c, p) for p in fs)

# ----------------------------------------------------------------------------------------------
# Part C: Nipp
# ----------------------------------------------------------------------------------------------
def parse_nipp(nipp_dir):
    rows = []
    for fn in sorted(os.listdir(nipp_dir)):
        if not (fn.startswith('nipp_d') and fn.endswith('.html')): continue
        txt = open(os.path.join(nipp_dir, fn), encoding='latin-1').read()
        txt = re.sub(r'<[^>]*>', '', txt)
        for line in txt.splitlines():
            t = line.split()
            if len(t) < 16 or not t[0].isdigit(): continue
            try:
                d, g = int(t[0]), int(t[1]); f = list(map(int, t[2:12]))
                Nlev, Gaut, m1, m2 = int(t[-4]), int(t[-3]), int(t[-2]), int(t[-1])
            except ValueError:
                continue
            f11, f22, f33, f44, f12, f13, f23, f14, f24, f34 = f
            F = [[2*f11, f12, f13, f14], [f12, 2*f22, f23, f24], [f13, f23, 2*f33, f34], [f14, f24, f34, 2*f44]]
            if det_int(F) != d:
                raise ValueError(f'parse: det F != d on line {line!r}')
            rows.append(dict(d=d, g=g, f=f, F=F, level=Nlev, G=Gaut, mass=Fraction(m1, m2), src=fn))
    return rows

def nipp_classes_of_gram_det(rows, N):
    """Classes of positive quaternary lattices with INTEGER Gram matrix and det = N, from Nipp:
    odd lattices at d = 16N with all off-diagonal f even (Gram = F/2); even lattices at d = N (Gram = F)."""
    out = []
    for r in rows:
        if r['d'] == 16*N and all(r['F'][i][j] % 2 == 0 for i in range(4) for j in range(i+1, 4)):
            G = [[r['F'][i][j] // 2 for j in range(4)] for i in range(4)]
            assert det_int(G) == N
            out.append(dict(G=G, aut=r['G'], parity='odd', nipp=r))
        elif r['d'] == N:
            G = [row[:] for row in r['F']]
            assert det_int(G) == N
            out.append(dict(G=G, aut=r['G'], parity='even', nipp=r))
    return out

# ----------------------------------------------------------------------------------------------
def main():
    t0 = time.time()
    Nmax = int(sys.argv[1]) if len(sys.argv) > 1 else 108
    nipp_dir = sys.argv[2] if len(sys.argv) > 2 else '/private/tmp/claude-501/-Users-cskoons-projects-github/c276d470-0599-4f22-ac8d-fd48467c9a36/scratchpad'
    n = 4
    print(f'# toy 5697 — Z^{{1,{n}}} cone-zeta vs quaternary lattices, Nmax={Nmax}')
    roots = vinberg_roots(n)
    print('roots:', roots)
    print('labels:', {(i, j): coxeter_label(roots[i], roots[j]) for i in range(n+1) for j in range(i+1, n+1) if coxeter_label(roots[i], roots[j]) != 2})
    # sanity: all n+1 roots together must be infinite (hyperbolic), each n-subset finite except the cusp one
    for k in range(n+1):
        sub = [i for i in range(n+1) if i != k]
        print(f'  parabolic without r{k+1}: order', coxeter_order(roots, sub))
    print('  all roots:', coxeter_order(roots, list(range(n+1))))

    # Part A
    data, rstar, rprim = cone_zeta(n, Nmax, check_bfs=(Nmax <= 60))
    print('\n## Part A: r*(N) (all x) and orbit counts, N=1..12  [P4 vs K1862-A printed values]')
    keeper = [Fraction(1,384), Fraction(1,96), Fraction(1,48), Fraction(3,128), Fraction(7,240), Fraction(1,16), Fraction(1,12), Fraction(5,96), Fraction(25,384), Fraction(7,48), Fraction(7,48), Fraction(5,48)]
    keeper_orb = [1,1,1,2,2,2,2,3,3,2,2,4]
    p4 = True
    for N in range(1, 13):
        ok = (rstar[N] == keeper[N-1] and len(data[N]) == keeper_orb[N-1]); p4 &= ok
        print(f'  N={N:2d}: r*={str(rstar[N]):>8}  orbits={len(data[N])}  keeper={str(keeper[N-1]):>8}/{keeper_orb[N-1]}  {"OK" if ok else "MISMATCH"}')
    print('P4 (reproduction of K1862-A N<=12):', 'HIT' if p4 else 'MISS')
    tot = sum(len(data[N]) for N in range(1, min(40, Nmax)+1))
    print(f'  chamber vectors N<=40: {tot} (K1862-A: 158); stabilizer types: {len(set(tuple(stabilizer_subset(x, roots)) for N in range(1,min(40,Nmax)+1) for x,_,_ in data[N]))} (K1862-A: 25, at N<=40)')

    # Part B + C
    rows = parse_nipp(nipp_dir)
    print(f'\n## Nipp rows parsed: {len(rows)}; d range {min(r["d"] for r in rows)}..{max(r["d"] for r in rows)}')
    # parse validation: genus masses
    from collections import defaultdict
    gsum = defaultdict(Fraction); gmass = {}
    for r in rows:
        gsum[(r['d'], r['g'])] += Fraction(1, r['G']); gmass[(r['d'], r['g'])] = r['mass']
    bad = [k for k in gsum if gsum[k] != gmass[k]]
    print(f'  genus-mass check: {len(gsum)-len(bad)}/{len(gsum)} genera have sum 1/G = m1/m2 (mismatches: {bad[:5]})')

    print('\n## Parts B+C: squarefree N — chamber mass vs Nipp mass identity (P1), per class (P2), |O| pin (P3)')
    print('  N | omega_odd | r*(N) | 2^w * sum_{adm} 1/|O| (Nipp) | P1 | classes: mine / Nipp adm / Nipp non-adm | P2 | P3(|O| mine=Nipp)')
    P1 = P2 = P3 = True; results = []
    for N in range(1, Nmax+1):
        fs = squarefree_factors(N)
        if fs is None: continue
        w = sum(1 for p in fs if p != 2)
        nipp = nipp_classes_of_gram_det(rows, N)
        for c in nipp: c['adm'] = admissible(c['G'], N)
        adm = [c for c in nipp if c['adm']]; nonadm = [c for c in nipp if not c['adm']]
        nipp_mass = 2**w * sum(Fraction(1, c['aut']) for c in adm)
        p1 = (rprim[N] == nipp_mass); P1 &= p1
        # my classes from x^perp
        grams = [gram_of_perp(x) for x, _, p in data[N] if p]
        for G in grams: assert det_int(G) == N
        cls = classify(grams)
        # per-class chamber mass
        p2 = True; p3 = True
        for c in cls:
            mass_c = sum(Fraction(1, data[N][[k for k,(x,_,p) in enumerate(data[N]) if p][m]][1]) for m in c['members'])
            c['chamber_mass'] = mass_c
            # match to a Nipp admissible class
            match = None
            for nc in nipp:
                cnt, _ = isometries(pair_reduce(c['rep']), pair_reduce(nc['G']), limit=1)
                if cnt: match = nc; break
            c['nipp'] = match
            if match is None or not match['adm']:
                p2 = False
            else:
                p3 &= (match['aut'] == c['aut'])
                p2 &= (mass_c == Fraction(2**w, c['aut']))
        # every admissible Nipp class must appear among mine
        if len(cls) != len(adm) or any(c['nipp'] is None for c in cls): p2 = False
        P2 &= p2; P3 &= p3
        print(f'  {N:3d} | {w} | {str(rprim[N]):>9} | {str(nipp_mass):>9} | {"HIT " if p1 else "MISS"} | {len(cls)} / {len(adm)} / {len(nonadm)} | {"HIT " if p2 else "MISS"} | {"HIT " if p3 else "MISS"}')
        results.append(dict(N=N, omega_odd=w, rstar=str(rprim[N]), nipp_mass=str(nipp_mass), P1=p1, P2=p2, P3=p3,
                            my_classes=[dict(rep=c['rep'], aut=c['aut'], chamber_mass=str(c['chamber_mass']), orbits=len(c['members']),
                                             nipp_aut=(c['nipp']['aut'] if c['nipp'] else None), nipp_parity=(c['nipp']['parity'] if c['nipp'] else None)) for c in cls],
                            nipp_nonadmissible=[dict(G=c['G'], aut=c['aut'], parity=c['parity']) for c in nonadm]))
    print(f'\nP1 mass identity (all squarefree N<={Nmax}): {"HIT" if P1 else "MISS"}')
    print(f'P2 per-class identity + admissible<->appears:  {"HIT" if P2 else "MISS"}')
    print(f'P3 |O(L)| mine = Nipp G on every matched class: {"HIT" if P3 else "MISS"}')
    print(f'P4 reproduction of K1862-A:                     {"HIT" if p4 else "MISS"}')
    out = dict(toy=5697, Nmax=Nmax, P1=P1, P2=P2, P3=P3, P4=p4, rstar_all={N: str(rstar[N]) for N in range(1, Nmax+1)},
               orbits_all={N: len(data[N]) for N in range(1, Nmax+1)}, results=results, seconds=round(time.time()-t0, 1))
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '.toy_5697_results.json'), 'w') as f:
        json.dump(out, f, indent=1)
    print(f'elapsed {time.time()-t0:.1f}s; results in play/.toy_5697_results.json')

if __name__ == '__main__':
    main()
