from fractions import Fraction as F
import numpy as np
print("="*104)
print("TOY 5414 -- LANE A: PIN THE KERNEL EXPONENTS (Hua/FK). C6-COMPLIANT: candidates PRE-REGISTERED")
print("  below before any evaluation; ALL are reported, including the ones that do not close.")
print("  ASSIGNED (@Lyra handoff): settle 'genus 7 vs Bergman 6 vs Szegő 5' and pin the ratio.")
print("="*104)

print("\nPRE-REGISTRATION (written before evaluation) — candidate readings of 'the exponent ratio':")
print("   R1  nu_B / nu_S      (Bergman exponent / Hardy exponent)")
print("   R2  (n_C + 1)/n_C    = 6/5 at n=5   [the claimed reading]")
print("   R3  C_2 / n_C        with C_2 = 2n-4 [the corpus's REAL C_2 formula]")
print("   R4  g / n_C          with g = n_C + rank = 7 [BST's g]")
print("   Expected form: a dimensionless ratio of two kernel singularity exponents.")

print("\nTABLE 1 -- *** THE FK/HUA DATA FOR D_IV^n, from multiplicities I ALREADY COMPUTED ***")
print("  Type IV (Lie ball), complex dim d = n, rank r = 2.")
print("  Multiplicity a: my toy 5402 computed the Peirce dims as (1, n-2, 1) -> *** a = n - 2 ***,")
print("  independently, not quoted. b = 0 for type IV.")
print("  GENUS (FK):  p = 2 + a(r-1) + b = 2 + (n-2) + 0 = *** n ***")
print("   n    a=n-2   r   b   genus p = n   Bergman nu_B = p   Hardy nu_S = d/r = n/2")
for n in range(3,10):
    print("   %-4d %-7d %-3d %-3d %-13d %-18d %s"%(n,n-2,2,0,n,n,F(n,2)))
print("   *** AT n_C = 5:  genus p = 5,  nu_B = 5,  nu_S = 5/2. ***")

print("\nTABLE 2 -- ★★★ *** SETTLING '7 vs 6 vs 5' — THEY ARE THREE DIFFERENT OBJECTS ***")
print("   number   what it actually is                              value at n_C=5")
print("   5        the FK GENUS p of D_IV^5 = n  (and nu_B)         *** 5 ***")
print("   5/2      the HARDY/Szegő exponent d/r                     *** 5/2 ***")
print("   7        *** BST's g = n_C + rank = 7 — NOT the FK genus ***  7")
print("   6        C_2 = 2n_C - 4 = 6 — a Casimir, not an exponent   6")
print("   *** THE 'GENUS 7' IN THE FLAG IS BST's g, A DIFFERENT OBJECT FROM THE JORDAN-THEORETIC")
print("       GENUS p = n = 5. Same word, two objects. *** And 6 is C_2, not a kernel exponent at all.")

print("\nTABLE 3 -- *** EVALUATE ALL FOUR PRE-REGISTERED CANDIDATES, ACROSS THE FAMILY (C6) ***")
print("   n    R1 nu_B/nu_S   R2 (n+1)/n   R3 C_2/n = (2n-4)/n   R4 g/n = (n+2)/n")
for n in range(3,10):
    print("   %-4d %-14s %-12s %-22s %s"%(n,F(n,1)/F(n,2),F(n+1,n),F(2*n-4,n),F(n+2,n)))
print("   *** R1 = 2 EXACTLY, AT EVERY n — the Bergman-to-Hardy exponent ratio is DIMENSION-FREE. ***")
print("   *** R2, R3, R4 all VARY with n, and R2 = R3 = 6/5 ONLY at n = 5. ***")

print("\nTABLE 4 -- ★★★★ *** THE CLAIMED READING RE-IMPORTS A TWICE-RETIRED IDENTITY ***")
print("   The handoff states: 'kernel exponent ratio (n_C+1)/n_C = C_2/n_C = 6/5'.")
print("   That equality needs C_2 = n_C + 1. *** The corpus's C_2 is 2n - 4. ***")
print("   n    n+1   2n-4   equal?")
for n in range(3,10):
    print("   %-4d %-5d %-6d %s"%(n,n+1,2*n-4,"*** YES ***" if n+1==2*n-4 else "no"))
print("   *** They coincide ONLY at n = 5. This is the SAME false identity my 5361 retired (it killed")
print("       Condition 5) and my 5393 caught again (t = n_C+1, not C_2). *** THIRD APPEARANCE.")

print("\nTABLE 5 -- *** SO WHICH READING CLOSES? (report the nulls, C6) ***")
print("   candidate                     value at n=5   dimension-generic?   verdict")
print("   R1 nu_B/nu_S                  2              YES (2 at every n)   *** CLOSES — but the")
print("                                                                     value is 2, NOT 6/5 ***")
print("   R2 (n_C+1)/n_C                6/5            no (varies)          DOES NOT CLOSE as an")
print("                                                                     exponent ratio")
print("   R3 C_2/n_C                    6/5            no (varies)          DOES NOT CLOSE; and its")
print("                                                                     equality to R2 is the")
print("                                                                     retired C_2 = n+1")
print("   R4 g/n_C                      7/5            no (varies)          DOES NOT CLOSE")
print("   *** ONE of four closes, and it closes on a DIFFERENT VALUE than the one proposed. ***")

print("\n"+"="*104); print("VERDICT -- Lane A exponent pin"); print("="*104)
print(" (1) ★★★★ *** THE EXPONENTS PIN CLEANLY, AND THE '7 vs 6 vs 5' FLAG IS A THREE-WAY NAME")
print("     COLLISION, NOT AN AMBIGUITY: *** FK genus p = n = 5 (= the Bergman exponent nu_B);")
print("     Hardy exponent nu_S = d/r = 5/2; *** BST's g = 7 is NOT the FK genus ***; C_2 = 6 is a")
print("     Casimir, not an exponent. Four numbers, four different objects.")
print()
print(" (2) *** THE BERGMAN-TO-HARDY EXPONENT RATIO IS 2, EXACTLY, AT EVERY n. *** nu_B/nu_S =")
print("     n/(n/2) = 2 — dimension-free, so it is a property of the CONSTRUCTION, not of n_C = 5.")
print("     *** The transition map is real; the number it induces is 2, not 6/5. ***")
print()
print(" (3) ★★★ *** THE 6/5 READING DOES NOT CLOSE, AND ITS STATED FORM RE-IMPORTS A TWICE-RETIRED")
print("     IDENTITY: '(n_C+1)/n_C = C_2/n_C' requires C_2 = n_C + 1, but C_2 = 2n - 4. *** They")
print("     agree only at n = 5. That identity killed Condition 5 (my 5361) and resurfaced in my 5393.")
print("     *** THIRD APPEARANCE — @Keeper, this one deserves a standing grep, not another catch. ***")
print()
print(" (4) *** C6 REPORT: FOUR candidates pre-registered, ALL evaluated, ONE closes — and it closes")
print("     on a value nobody proposed. *** Three nulls reported alongside the one hit, as the bar asks.")
print()
print(" (5) ★ WHAT I DID **NOT** DO: I have not verified the Hua (1963) closed forms against the")
print("     primary source — I derived the exponents from the FK genus formula with a = n-2, which")
print("     my 5402 computed independently. *** Pinning to Hua's printed kernel is still owed; if his")
print("     normalization differs, the RATIO (2) is unaffected but the individual exponents may shift. ***")
