import numpy as np
from fractions import Fraction as F
print("="*104)
print("TOY 5381 -- (A) SECOND the dimension-rooted label (it corrects MY toys). (B) the deconfinement")
print("            stretch: Polyakov mode at 10 vs the confirmed T_c.")
print("  *** SPACE, LINE ONE: the SHILOV BOUNDARY (S^4 x S^1)/Z_2. ***")
print("="*104)

print("\n--- (A) THE LABEL: my 5379/5380 said '2 N_c'. @Keeper says 2(d_S - 1). Test it. ---")
def lam1(p,d): return (1+p)*(d-p)
print("\nTABLE 1 -- *** the eigenvalue is GROUP-BLIND. Verify by construction. ***")
print("   Delta_Hodge on 1-forms knows only the MANIFOLD. The gauge group enters only as an overall")
print("   tensor factor (the adjoint bundle), which multiplies the DEGENERACY, never the eigenvalue.")
print("   gauge group   dim(adjoint)   eigenvalue at (1,0)   degeneracy")
for g,da in [("U(1)",1),("SU(2)",3),("SU(3)",8),("SU(5)",24)]:
    print("   %-13s %-14d %-21d %d x (form multiplicity)"%(g,da,lam1(1,4),da))
print("   ==> *** ALL GIVE 6. The gauge group cannot touch the eigenvalue. ***")
print("       So calling it '2 N_c' attributes it to colour, which is doing NO work. @Keeper is right.")

print("\nTABLE 2 -- *** and here is the subtle part, which is why the catch was worth making ***")
print("   d_S - 1 = (n_C - 1) - 1 = n_C - 2 = 3")
print("   N_c     =                  n_C - 2 = 3")
print("   ==> *** THESE ARE THE SAME FUNCTION OF n_C, not merely the same number. ***")
print("   so 2(d_S-1) and 2 N_c are numerically identical AT EVERY n -- the labels can never be")
print("   separated by a value. *** They are separated only by MECHANISM, and the U(1) test (Table 1)")
print("   is what separates them: change the group, the number does not move. ***")
print("   ** That is a sharper kind of same-name trap than the ones we have caught: the two readings")
print("      agree as functions, so only a physical variation distinguishes them. **")

print("\nTABLE 3 -- the dimension-rooted form, swept")
print("   lambda_1 = 2(d_S - 1) for the 1-form sector on S^{d_S}")
for d in range(3,8):
    print("   d_S = %-3d -> lambda_1 = %-3d   %s"%(d,lam1(1,d),"<-- our boundary sphere" if d==4 else ""))
print("   ==> the value tracks the SPHERE DIMENSION. Corrected label seconded.")

print("\n--- (B) THE DECONFINEMENT STRETCH ---")
print("\nTABLE 4 -- the structural fact (solid)")
print("   gap mode      A_i (1,0)     lambda = 6    -> mass ~ sqrt(6) = %.4f"%np.sqrt(6))
print("   Polyakov mode A_theta (2,0) lambda = 10   -> mass ~ sqrt(10) = %.4f"%np.sqrt(10))
print("   ==> *** the Polyakov mode sits ABOVE the gap. The confining vacuum is STABLE *** -- the")
print("       order parameter is not the lightest excitation. That much is solid and meaningful.")

print("\nTABLE 5 -- *** now the quantitative test, and I report it whichever way it lands ***")
r=np.sqrt(F(10,6).numerator/F(10,6).denominator)
print("   mass ratio Polyakov/gap = sqrt(10/6) = %.4f"%r)
print("   inverse                             = %.4f"%(1/r))
Tc,Lam=150.05,208.50
print("   from my 5367: T_c = %.2f MeV, Lambda_QCD = %.2f MeV -> T_c/Lambda = %.4f"%(Tc,Lam,Tc/Lam))
dev=100*abs(1/r-Tc/Lam)/(Tc/Lam)
print("   compare sqrt(6/10) = %.4f  vs  T_c/Lambda = %.4f  ->  *** %.1f%% off ***"%(1/r,Tc/Lam,dev))
print("   ==> *** DOES NOT LAND. %.1f%% is not a match by any standard we use. ***"%dev)
print("   ** and 10/6 = 5/3 = n_C/N_c is a SHARED FORM -- flagging, NOT claiming. **")

print("\n"+"="*104)
print("VERDICT")
print("="*104)
print(" (A) *** I SECOND THE DIMENSION-ROOTED LABEL, AND IT CORRECTS MY OWN 5379/5380. *** The")
print("     eigenvalue is group-blind: U(1), SU(2), SU(3), SU(5) all give 6 (Table 1). Calling it")
print("     '2 N_c' credited colour with work it does not do. *** Corrected to 2(d_S - 1). ***")
print()
print(" (B) *** AND THE CATCH IS SHARPER THAN OUR USUAL SAME-NAME CASES: 2(d_S-1) and 2 N_c are the")
print("     SAME FUNCTION OF n_C (both 2(n_C-2)), so no value can ever separate them. *** Only a")
print("     physical variation does -- change the gauge group and the number does not move. Worth")
print("     banking as a method: when two labels agree as functions, vary the physics, not the n.")
print()
print(" (C) DECONFINEMENT, SOLID HALF: *** the Polyakov mode (10) sits ABOVE the gap (6), so the")
print("     confining vacuum is stable *** -- the order parameter is not the lightest excitation.")
print("     That is a real structural statement and it is consistent with confinement.")
print()
print(" (D) *** DECONFINEMENT, QUANTITATIVE HALF: DOES NOT LAND. *** sqrt(6/10) = %.4f against"%(1/r))
print("     T_c/Lambda = %.4f from my 5367 is *** %.1f%% off *** -- not a match. I have no principled"%(Tc/Lam,dev))
print("     formula relating a boundary eigenvalue to T_c, and I am not going to fit one. Reporting")
print("     the miss.")
print()
print(" (E) SHARED-FORM FLAG: 10/6 = 5/3 = n_C/N_c. *** Flagged, not claimed. *** Given (B), a shared")
print("     form is exactly the thing that needs a physical variation to test, not a nicer ratio.")
