import numpy as np, itertools
from fractions import Fraction as F
n_C=5; a=n_C-2
Rac=[F(3,2)+2*m for m in range(6)]; Di=[F(2)+2*m for m in range(6)]
print("="*96)
print("TOY 5325 -- (A) the Z_2 PARITY KILL-CHECK   (B) hunting the vector E_0 primary source")
print("  Tables first, verdict after.")
print("="*96)

print("\n--- PART A: the Z_2 kill-check.  Keeper: 'if Rac is EVEN the story inverts.' ---")
print("\n  The Z_2 of Shilov = (S^4 x S^1)/Z_2 is generated by  g:(x,tau) -> (-x, tau+pi).")
print("  GEOMETRIC FACT: g^2 : (x,tau) -> (x, tau+2pi) = IDENTITY.  So on ANY mode, the")
print("  represented generator MUST square to +1 -- that is what makes it a Z_2 at all.")
print("\nTABLE 1 -- the generator's eigenvalue and ITS SQUARE, per tower")
print("   tower   e^{i pi E0}      square = e^{2 pi i E0}   is it a genuine Z_2 rep?")
for nm,tw in [("Di",Di),("Rac",Rac)]:
    E0=float(tw[0]); z=np.exp(1j*np.pi*E0); z2=z*z
    fmt=lambda w:("%+g"%w.real if abs(w.imag)<1e-9 else "%+gi"%w.imag)
    ok=abs(z2-1)<1e-9
    print("   %-7s %-16s %-24s %s"%(nm,fmt(z),fmt(z2),"YES -- even" if ok else "*** NO -- squares to -1 ***"))

print("\nTABLE 2 -- is the assignment stable under the OTHER l-convention? (the thing I flagged unpinned)")
print("   Z_2 eigenvalue = (-1)^l * e^{i pi E}. Try both readings of the tower's angular momentum:")
print("   convention              Rac eigenvalue    squares to   genuine Z_2?")
for lab,lof in [("l = 2m  (E,l locked)",lambda m:2*m),("l = m   (l steps by 1)",lambda m:m)]:
    vals=set()
    for m in range(6):
        E=float(Rac[m]); l=lof(m)
        v=((-1)**l)*np.exp(1j*np.pi*E); vals.add(complex(round(v.real,9),round(v.imag,9)))
    v=list(vals)[0]; sq=v*v
    fmt=lambda w:("%+g"%w.real if abs(w.imag)<1e-9 else "%+gi"%w.imag)
    print("   %-23s %-17s %-12s %s"%(lab,fmt(v) if len(vals)==1 else "NOT CONSTANT",
          fmt(sq) if len(vals)==1 else "--", "yes" if len(vals)==1 and abs(sq-1)<1e-9 else "NO"))

print("\n  ==> BOTH conventions give a generator squaring to -1 on Rac. The verdict does NOT")
print("      depend on the unpinned l-assignment -- it is CONVENTION-INDEPENDENT.")

print("\n--- PART B: the vector E_0.  Is 5/2 forced, and does it fit the Section-10 falsifier? ---")
print("\nTABLE 3 -- Mack's unitarity bound (1977) at boundary dimension d, saturated:")
print("   E_0(spin s) >= (d-2)/2 + s.   BST: (d-2)/2 = a/2 = %s  <=>  d = n_C = %d."%(F(a,2),n_C))
print("   spin s    bound (d-2)/2 + s   corpus value    match?")
for s,nm,corp in [(F(0),"scalar (Rac)",F(3,2)),(F(1,2),"spinor (Di)",F(2)),(F(1),"vector (photon)",F(5,2))]:
    b=F(a,2)+s
    print("   %-9s %-19s %-15s %s"%(str(s),nm+" "+str(b),str(corp),"YES" if b==corp else "no"))
print("   ==> 5/2 is NOT a two-point interpolation: it is Mack's bound, a THEOREM, at d = n_C.")
print("       *** But SATURATION is the assumption. A long (non-short) vector has E_0 > 5/2. ***")

print("\nTABLE 4 -- *** COLLISION CHECK vs Lyra's Section-10 falsifier ***")
print("   Section 10 states: 'the spectrum is GENERATED from {3/2, 2} BY ADDITION.'")
print("   Additive semigroup  S = { (3/2)p + 2q : p,q >= 0 integers }.  Is 5/2 in S?")
S=sorted({F(3,2)*p+F(2)*q for p in range(8) for q in range(8) if F(3,2)*p+F(2)*q<=6})
print("   S (up to 6) = %s"%", ".join(str(x) for x in S))
hit=any(F(3,2)*p+F(2)*q==F(5,2) for p in range(40) for q in range(40))
print("   is 5/2 generated?  %s"%("YES" if hit else "*** NO ***"))
print("   (check: p must be odd for a half-odd result; p=1 needs 2q=1 -> q=1/2 not an integer;")
print("    p=3 already gives 9/2 > 5/2. So 5/2 is unreachable.)")

print("\n"+"="*96)
print("VERDICT -- from Tables 1-4 only")
print("="*96)
print(" (A) *** THE Z_2 STORY IS DEAD, AND NOT BY THE ROUTE KEEPER NAMED. ***")
print("     The question 'is Rac even or odd?' is a FALSE DICHOTOMY. The answer is NEITHER:")
print("     the Z_2 generator squares to -1 on the Rac tower, so Rac carries a Z_4, NOT a Z_2.")
print("     A mode with no +-1 holonomy has NO Z_2 holonomy for an Aharonov-Bohm story to use.")
print("     ** And it is CONVENTION-INDEPENDENT (Table 2) -- the unpinned l-assignment cannot")
print("        rescue it, so this kills the reading without needing the primary source. **")
print("     Di IS a genuine even Z_2 rep. Only the Rac fails -- the same half-odd E0 as always.")
print("     ==> @Cal: of your three required Z_2 kill-checks, this is one, and it FAILS CLOSED.")
print("         The Aharonov-Bohm story should not go anywhere. I am retracting my own 5324")
print("         twisted-sector CANDIDATE -- 'twisted sector' presumes a Z_2 grading that is absent.")
print()
print(" (B) VECTOR E_0 = 5/2 IS CONDITIONALLY FORCED: it is Mack's unitarity bound at d = n_C = 5,")
print("     saturated. The BOUND is a theorem; the SATURATION (photon is a SHORT rep) is the open")
print("     assumption. @Grace: that is the exact pin to hunt -- not '5/2', but 'does the vector")
print("     appear as a SHORT/singleton rep in the D_IV^5 spectrum?' (Mack 1977; Fernando-Gunaydin).")
print()
print(" (C) *** AND THE TWO HALVES COLLIDE -- @Lyra, before v0.3: ***")
print("     Section 10's falsifier says the spectrum is generated from {3/2, 2} by ADDITION.")
print("     5/2 IS NOT IN THAT SEMIGROUP. So Section 10 and a 5/2 photon CANNOT BOTH BE RIGHT.")
print("     Exactly one of these must give: (i) the photon is not at 5/2; (ii) the generation rule")
print("     is wrong; (iii) the photon is not in the singleton spectrum at all. This is our own")
print("     stated falsifier firing on our own candidate row -- it must be resolved IN v0.3, not")
print("     after. It is also good news: the Section-10 rule is sharp enough to bite.")
