import numpy as np, sys
exec(open('causet.py').read().split('print("STEP 1')[0])
exec(open('commit_order.py').read().split('print("=')[0])
rng=np.random.default_rng(4242)
print("="*78)
print("VERSION CHECK first: does F989's confirmed object match what I computed?")
print("="*78)
print("  F989: Shilov S = S^4 x S^1/Z2, unwrap S^1 -> R  =>  R x S^4;")
print("        a < b iff a in the conformal (Lorentzian) causal past of b on R x S^4.")
print("  MINE (commit_order.py): relations_ESU, dt > geodesic distance on S^4, on R x S^4.")
print("  => IDENTICAL OBJECT. My numbers transfer; not-KR is legitimately unqualified. Good.")
print()
print("="*78)
print("BUT: F989(A) and F989(B) describe DIFFERENT-SIZED systems. Checking the seam.")
print("="*78)
print("  (A) not-KR rests on HEIGHT GROWING -- which needs an UNBOUNDED order (S^1 unwrapped to R).")
print("  (B) SSB-unavailable rests on the committed record being FINITE, capped at N_max = 137.")
print("  A finite capped system has BOUNDED height. So: at the PHYSICAL size, is height still")
print("  distinguishable from KR's flat-3?  Measuring at N ~ 137.")
print()
print("   N      height (R x S^4)   ordering fraction   KR height   distinguishable?")
for N in [137,300,600,1200,2400]:
    hs=[];rs=[]
    for _ in range(5):
        t,x=sprinkle_ESU(N,4,2.0); R=relations_ESU(t,x)
        hs.append(height(R)); rs.append(ordering_fraction(R))
    h=np.mean(hs)
    print("   %5d   %5.1f              %.4f              3           %s"%(
        N,h,np.mean(rs),"YES" if h>4.5 else ("marginal" if h>3.5 else "NO -- same as KR")))
    sys.stdout.flush()
print()
print("  => the height discriminator needs a LARGE order. At the physical cap it weakens.")
print("  => this does NOT overturn not-KR as a statement about the conformal order on R x S^4 (F989 A).")
print("  => it flags that (A) and (B) are statements about DIFFERENT objects: (A) the unbounded")
print("     conformal boundary order; (B) the finite committed record. Both can be true; they are")
print("     not the same causal set, and the not-KR verdict should not be read as a property of the")
print("     finite committed record without re-measuring at its actual size.")
