import numpy as np, sympy as sp
print("="*92)
print("THE KOIDE GATE UNDER THE CIRCULARITY GUARD: derive A^2 = 2 WITHOUT presupposing rank.")
print("="*92)
print("  The guard is right: 'A^2 = rank' cannot be the derivation, because rank goes in by hand.")
print("  So: what IS A^2 = 2, stated with no rank anywhere?\n")
N=sp.symbols('N', positive=True, integer=True)
A,M=sp.symbols('A M', positive=True)
print("  Split the sqrt-mass vector v under the generation-permutation group S_N:")
print("     v = v_par  (+)  v_perp,   v_par along the DEMOCRATIC (1,1,...,1), v_perp traceless.")
print("     |v_par|^2 = (sum v)^2 / N      |v_perp|^2 = |v|^2 - (sum v)^2 / N")
print()
print("  For the Koide form v_k = M(1 + A cos(theta + 2 pi k/N)):")
S1=N*M; S2=N*M**2*(1+A**2/2)
vpar=sp.simplify(S1**2/N); vperp=sp.simplify(S2-S1**2/N)
print("     |v_par|^2  = %s"%sp.simplify(vpar))
print("     |v_perp|^2 = %s"%sp.simplify(vperp))
ratio=sp.simplify(vperp/vpar)
print("     |v_perp|^2 / |v_par|^2 = %s"%ratio)
sol=sp.solve(sp.Eq(ratio,1),A)
print("\n  ★★ SET THEM EQUAL:  |v_perp| = |v_par|  =>  A = %s  =>  A^2 = %s"%(sol,[sp.simplify(s**2) for s in sol]))
print("  ⟹ A^2 = 2 IS EXACTLY THE STATEMENT THAT THE DEMOCRATIC AND TRACELESS COMPONENTS CARRY")
print("     EQUAL NORM. NO RANK APPEARS ANYWHERE IN THAT SENTENCE.")
print()
print("  and the 2 is identified: it is the NUMBER OF PARTS IN THE SPLIT (one democratic + one")
print("  traceless = two pieces, equal share), NOT the Jordan rank. Eighth 2 of the arc, disambiguated.")
print()
print("  NOTE what it is NOT: equipartition PER MODE would give |v_perp|^2 = (N-1)|v_par|^2;")
for Nv in [3]:
    print("     at N=%d that is |v_perp|^2 = %d |v_par|^2  ->  A^2 = %d, i.e. A = %d -- NOT 2."%(Nv,Nv-1,2*(Nv-1),2))
print("     So it is equal TOTAL norm between two isotypic blocks, not equal energy per degree.")
print("     That is a sharp, falsifiable statement about the overlap, and it is what must be derived.")
print()
print("="*92)
print("AND THE PAYOFF: equal-norm gives Q = 2/N_gen, rank-free")
print("="*92)
Q=sp.simplify(S2/S1**2).subs(A,sp.sqrt(2))
print("     Q = (1 + A^2/2)/N  with A^2 = 2  ->  Q = %s"%sp.simplify(Q))
print("     at N_gen = 3 :  Q = 2/3   ✓")
print()
print("  THREE CANDIDATE FORMULAS ALL GIVE 2/3 AT rank 2 -- and they SEPARATE at rank 3:")
r=sp.symbols('r', positive=True)
cands=[("rank/N_c  (advertised)",       r/(r+1),        "presupposes rank AND borrows N_c"),
       ("(r+2)/(2(r+1))  [A^2 = rank]", (r+2)/(2*(r+1)),"presupposes rank -- CIRCULAR"),
       ("2/(r+1)  [equal-norm]",        2/(r+1),        "RANK-FREE: the 2 is the split, N_gen = r+1 is F86")]
print("      formula                        r=2      r=3      r=4     status")
for name,f,st in cands:
    print("      %-30s %-8s %-8s %-7s %s"%(name,sp.nsimplify(f.subs(r,2)),sp.nsimplify(f.subs(r,3)),sp.nsimplify(f.subs(r,4)),st))
print("\n  ⟹ ONLY THE EQUAL-NORM FORM IS RANK-FREE, so it is the ONLY one that passes the guard.")
print("     And the three separate at r = 3 (3/4 vs 5/8 vs 1/2) -- the discriminator is real.")
print()
print("="*92)
print("A CHECK I RAN, AND IT COMES BACK NEGATIVE -- reported, not hunted around")
print("="*92)
print("  T2517 banks the three addresses as rho-vector components nu = {5/2 (e), 3/2 (mu), 0 (tau)}.")
v=np.array([2.5,1.5,0.0])
par=v.sum()**2/3; perp=(v**2).sum()-par
print("     nu-vector = %s :  |v_par|^2 = %.4f   |v_perp|^2 = %.4f   ratio = %.4f  (equal-norm needs 1)"%(v,par,perp,perp/par))
print("  ⟹ THE RAW ADDRESS VECTOR DOES NOT SATISFY EQUAL-NORM. That is not a refutation -- sqrt(m) is")
print("     presumably a FUNCTION of nu, not nu itself. But it means the gate needs TWO things, not one:")
print("       (a) the overlap-to-sqrt(mass) map EXHIBITED, and then")
print("       (b) equal-norm shown to hold for the image.")
print("     I did NOT go looking for a function that makes it work -- that is the fit trap, and")
print("     finding one after seeing the target would prove nothing.")
