import numpy as np
print("="*90)
print("WHAT *DOES* PRODUCE A LOGARITHMIC DENSITY?  Berry-Keating: the DILATION generator H = xp,")
print("regularised by a PHASE-SPACE CELL. Semiclassical count = area / (2 pi hbar).")
print("="*90)
print("  region {x >= lx, p >= lp, xp <= E}:  area = E*log(E/(lx*lp)) - E + lx*lp")
def N_bk(E,cell):
    return (E*np.log(E/cell) - E + cell)/(2*np.pi)
def N_rvm(T): return (T/(2*np.pi))*np.log(T/(2*np.pi)) - T/(2*np.pi) + 7/8
print("\n  Choose the cell = 2*pi*hbar = 2*pi (hbar = 1) -- ONE Planck cell:")
print("      T          Berry-Keating N(T)      Riemann-von Mangoldt      difference")
for T in [100,1000,10000,100000]:
    a=N_bk(T,2*np.pi); b=N_rvm(T)
    print("   %8d          %12.4f          %12.4f          %8.4f"%(T,a,b,a-b))
print("\n  ⟹ IDENTICAL to the constant: N_BK(T) - N_RvM(T) = 1 - 7/8 = 0.125, EXACTLY, at every T.")
print("     ONE phase-space cell of area 2*pi*hbar in a dilation flow reproduces the Riemann counting")
print("     function including its subleading term. The log density comes from the SCALING generator")
print("     plus the CELL -- not from any manifold dimension.")
print()
print("="*90)
print("AND BST HAS BOTH INGREDIENTS -- this is the honest redirect, not a claim.")
print("="*90)
print("  * a DILATION generator, explicit in the corpus's own ladder: K_mu = 2 z_mu (E + nu) - Q d_mu,")
print("    where E is the Euler/degree operator. E generates scaling. That is the xp sector.")
print("  * a phase-space CELL: Casey's own reframe -- 'the Uncertainty Principle is the actual")
print("    resolution of the continuum' -- IS the 2*pi*hbar cell Berry-Keating needs.")
print("  ⟹ if RH lives in BST, it lives in the DILATION sector with an hbar-cell, NOT in the Dirac")
print("     sector. The forced self-adjoint operator we own is the wrong object for this problem.")
print()
print("HONEST TIER, stated so nothing is over-read:")
print("  * matching N(T) is NECESSARY, NOT SUFFICIENT. It is the smooth leading term only; the actual")
print("    zeros are the FLUCTUATIONS about it, and no self-adjoint realisation of xp with the right")
print("    fluctuation spectrum is known -- that is exactly where Berry-Keating has been stuck since")
print("    1999, and BST does not change that.")
print("  * BST's Dirac operator FAILS the necessary condition. Berry-Keating PASSES it. Passing is")
print("    not proving.")
print("  * and the cell size is FIXED BY MATCHING (lx*lp = 2*pi*hbar is chosen to make the constant")
print("    come out). Until the cell is DERIVED from D_IV^5 rather than matched, that step is a FIT.")
