from fractions import Fraction as F
d=5; n_C=5; RAC=F(3,2); DI=F(2)
print("="*104)
print("TOY 5330 -- (A) the induced-gravity / #Rac question   (B) a group-identity check on the Higgs map")
print("  Tables first, verdict after.")
print("="*104)

print("\n--- PART A: where does GRAVITY sit in the #Rac grading? ---")
print("\nTABLE 1 -- the stress tensor's weight is FORCED twice, independently")
print("   route                                              Delta(T_mu_nu)")
print("   CFT theorem: conserved spin-2 => Delta = d-2+l, l=2  ->  %s"%F(d-2+2))
print("   Flato-Fronsdal: Rac (x) Rac at l=2, Delta = (d-2)+l  ->  %s"%F(d-2+2))
print("   agree, and both equal d = n_C = %d"%n_C)
print("   ==> *** Delta(T_mu_nu) = n_C = 5. The graviton slot sits at conformal weight n_C. ***")

print("\nTABLE 2 -- the gravitational sector's #Rac parity")
print("   state              tower           l    Delta   #Rac   exp(2 pi i J)   rides   species")
rows=[("graviton / T_mu_nu","Rac (x) Rac",2,F(d-2+2),2),
      ("photon / J_mu",     "Rac (x) Rac",1,F(d-2+1),2),
      ("gravitino (if any)","Rac (x) Di ",1,RAC+DI+1,1)]
for nm,tw,l,D,nR in rows:
    p=(-1)**nR
    print("   %-18s %-15s %-4d %-7s %-6d %-15s %-7s %s"%(nm,tw,l,str(D),nR,"%+d"%p,
          "4 pi" if p<0 else "2 pi","FERMION" if p<0 else "BOSON"))
print("\n   ==> *** GRAVITY DOES NOT RIDE THE DOUBLE COVER. *** #Rac = 2 is even, so the graviton")
print("       rides 2 pi. The 720-degree structure is a FERMIONIC (odd-#Rac) phenomenon only.")

print("\nTABLE 3 -- what #Rac IS, for induced gravity (Sakharov)")
print("   Induced 1/G comes from a one-loop sum over species, weighted by the boson/fermion sign.")
print("   From toy 5327:  (-1)^{#Rac} = (-1)^F  exactly, on all composites.")
print("   ==> the loop sign IS the #Rac grading: the induced-gravity sum is a SUPERTRACE graded")
print("       by #Rac mod 2. Str(...) = sum_species (-1)^{#Rac} (...).")
print("   ** This is an IDENTIFICATION of the grading, NOT a computation of G. I did not compute")
print("      1/G and am not claiming a value. **")

print("\nTABLE 4 -- the SUSY non-implication (guard for Five-Absence)")
print("   Both an even-#Rac spin-2 (Delta 5) and an odd-#Rac spin-3/2 (Delta 9/2) exist as slots.")
print("   Delta difference = %s -- which is exactly the weight of a supercharge."%(F(d-2+2)-(RAC+DI+1)))
print("   *** THIS DOES NOT IMPLY SUSY. *** Two towers existing does not supply an operator Q")
print("   mapping one to the other; SUSY needs Q to BE a symmetry, which nothing here provides.")
print("   Flagging it because 'graviton and gravitino slots both present' reads as SUSY at a glance")
print("   and would collide with the Five-Absence set. It is a slot, not a superpartner.")

print("\n--- PART B: a group-identity check before anyone builds the Higgs forced map ---")
print("\nTABLE 5 -- *** there are TWO different 'SO(5)-ish' groups in play. They are NOT the same. ***")
print("   object                                    group            dim   what a 'vector' means")
print("   K-factor of D_IV^5 = SO(5) x SO(2)        COMPACT SO(5)    5     internal 5-component index")
print("   boundary spatial rotations, d=5 spacetime SO(4)            4     spacetime spin")
print("   boundary Lorentz group, d=5 spacetime     SO(4,1)          --    spacetime spin")
print("   ==> the 'SO(5)-vector condensate' carries the COMPACT SO(5) index -- an INTERNAL index.")
print("       It is NOT a spacetime vector. So it can be spin-0 in spacetime while being a 5-vector")
print("       internally, and its #Rac is therefore NOT constrained by its spin.")

print("\n"+"="*104)
print("VERDICT -- from Tables 1-5 only")
print("="*104)
print(" (A1) *** Delta(T_mu_nu) = d = n_C = 5, forced twice independently *** (CFT conservation +")
print("      Flato-Fronsdal both give d-2+2). The graviton slot sits at conformal weight n_C.")
print()
print(" (A2) *** GRAVITY IS EVEN-#Rac AND RIDES 2 pi. *** The double cover is a FERMIONIC phenomenon")
print("      only. @Lyra: the time paper should not claim the gravitational sector rides 4 pi --")
print("      nothing in the grading supports it, and Table 2 says the opposite.")
print()
print(" (A3) THE #Rac GRADING IS THE INDUCED-GRAVITY LOOP SIGN: (-1)^{#Rac} = (-1)^F, so Sakharov's")
print("      one-loop sum is a supertrace graded by #Rac mod 2. ** Identification of the grading,")
print("      NOT a computation of G. No value of G is claimed here. **")
print()
print(" (A4) GUARD: graviton-slot + gravitino-slot both existing is NOT SUSY. Nothing here supplies")
print("      a supercharge. Do not let this read as a SUSY signal -- it would collide with Five-Absence.")
print()
print(" (B)  *** BEFORE THE HIGGS MAP IS BUILT: the 'SO(5)-vector' is the COMPACT SO(5) of the")
print("      K-factor -- an INTERNAL index -- while boundary spin lives in SO(4)/SO(4,1). Two")
print("      different groups, both reasonably called 'SO(5)-ish', neither reducible to the other.")
print("      @Grace/@Lyra: the condensate can be an internal 5-vector AND a spacetime scalar at once,")
print("      so 'it is a vector' does NOT by itself decide the spin prong of the 5329 filter, and")
print("      its #Rac must be determined separately. This is the shared-integer trap in group form --")
print("      I am flagging it, not resolving it; the forced map is still owed.")
