import numpy as np, sympy as sp, mpmath as mp
mp.mp.dps=25
def A2(v):
    v=np.asarray([float(x) for x in v]); N=len(v)
    return 2*(N*(v**2).sum()/v.sum()**2-1)
n25=float(mp.gamma(2.5)**2/mp.gamma(5)); n15=float(mp.gamma(1.5)**2/mp.gamma(3))
print("="*92)
print("(1) THE TAU CONTINUATION -- what value would the third entry have to take?")
print("="*92)
print("   e and mu entries are fixed by the corpus: %.6f, %.6f"%(n25,n15))
x=sp.symbols('x', real=True)
eq=sp.Eq(3*(n25**2+n15**2+x**2),2*(n25+n15+x)**2)
sols=[float(s) for s in sp.solve(eq,x) if s.is_real]
print("   solving A^2(v) = 2 for the tau entry x:  x = %s"%[round(s,6) for s in sols])
for s in sols:
    print("      check: v = (%.4f, %.4f, %.4f)  ->  A^2 = %.6f"%(n25,n15,s,A2([n25,n15,s])))
print("\n   ⟹ A finite continuation CAN give A^2 = 2 -- at x = %.4f or x = %.4f."%(sols[0],sols[1]))
print("   ★★ BUT STATING THAT IS NOT PERMISSION TO CHOOSE IT. These are TARGETS. A continuation")
print("      SELECTED to land on them is the fit trap this whole arc has been about. @Lyra: post")
print("      your intended continuation from its DEFINITION; then this is a one-line check against")
print("      a number you never saw while choosing. I am posting the target openly precisely so it")
print("      cannot be quietly reverse-engineered later.")
print("   ⟹ AND THE FAIL IS NOT YET FINAL: it is final for the DIVERGENT continuation (2/nu), which")
print("      pins A^2 = 4. A finite continuation is not excluded by my 5307.")
print()
print("="*92)
print("(2) THE MIDPOINT REFRAME -- verify it, because it is exact and it reinterprets my 5307")
print("="*92)
print("   Q = sum(m)/(sum sqrt m)^2.  Range over positive masses:")
print("      Cauchy-Schwarz: (sum sqrt m)^2 <= 3 sum m  =>  Q >= 1/3, attained at DEMOCRATIC (all equal)")
print("      one mass dominating:                          Q -> 1,   the MAXIMALLY HIERARCHICAL limit")
for v,lab in [([1,1,1],"democratic"),([1,1e-8,1e-8],"one dominates"),([1,0.5,0.25],"generic")]:
    Q=sum(x**2 for x in v)/sum(v)**2
    print("      v = %-18s ->  Q = %.6f   A^2 = %.4f"%(str(v),Q,A2(v)))
print("\n   ★★★ MIDPOINT OF [1/3, 1] = (1/3 + 1)/2 = %s = %.10f  -- KOIDE'S VALUE, EXACTLY."%(sp.Rational(2,3),2/3))
print("   and in the A^2 coordinate: Q = (1+A^2/2)/3, so")
print("      Q = 1/3  <->  A^2 = 0   (democratic, no traceless part)")
print("      Q = 1    <->  A^2 = 4   (one component: A^2 = 2(N-1) = 4)")
print("      Q = 2/3  <->  A^2 = 2   = THE EXACT MIDPOINT OF [0, 4]")
print()
print("   ★★★★ AND THIS REINTERPRETS MY 5307's FAILURE. I found the divergent ladder pins A^2 = 4.")
print("        That is not a random miss -- IT IS THE UPPER ENDPOINT OF THE RANGE. The FK ladder is")
print("        MAXIMALLY HIERARCHICAL; Koide is the exact midpoint. The ladder overshoots to the")
print("        extreme. That is a much more informative failure than 'wrong number'.")
print()
print("="*92)
print("(3) THE Z_3 MATRIX ROUTE -- tested BEFORE anyone builds on it")
print("="*92)
print("   claim to test: does a Z_3-democratic (circulant) mass matrix force the midpoint?")
w=np.exp(2j*np.pi/3)
print("   a real SYMMETRIC circulant has first row (a,b,b); eigenvalues:")
for a,b in [(1.0,0.3),(2.0,-0.5)]:
    M=np.array([[a,b,b],[b,a,b],[b,b,a]])
    ev=np.sort(np.linalg.eigvalsh(M))[::-1]
    print("      (a,b) = (%.1f,%.1f) -> eigenvalues %s   distinct? %s"%(a,b,np.round(ev,6),len(set(np.round(ev,9)))==3))
print("   ⟹ A REAL SYMMETRIC CIRCULANT HAS A DOUBLY-DEGENERATE SPECTRUM (a+2b, a-b, a-b).")
print("      It CANNOT give three distinct lepton masses. Exact Z_3 symmetry must be BROKEN.")
print()
print("   and the general Z_3-COVARIANT form (democratic + one Z_3 mode) is:")
print("      sqrt(m_k) = M (1 + A cos(theta + 2 pi k/3))   -- which IS the Koide parameterisation.")
for th in [0.0,0.9,2.4]:
    for Aamp in [0.6,np.sqrt(2),1.9]:
        v=[1+Aamp*np.cos(th+2*np.pi*k/3) for k in range(3)]
        print("      theta=%.1f A=%.3f -> A^2(v) = %.6f"%(th,Aamp,A2(v)))
print("   ⟹ THE MATRIX ROUTE REPRODUCES THE KOIDE *FORM* AUTOMATICALLY (that is exactly why Q is")
print("      theta-independent) -- BUT IT LEAVES A AS A FREE PARAMETER. A^2 comes out as whatever")
print("      amplitude you put in: 0.36, 2.000, 3.61 above.")
print("   ★★★ SO THE PIVOT DOES NOT, BY ITSELF, SUPPLY THE CONTENT. The whole question is still")
print("       A^2 = 2, and 'Z_3-democratic matrix' gives the form for free and the amplitude not at all.")
print("       Something must force the AMPLITUDE. That is the same open gate, relocated -- not closed.")
