"""
Toy 2774 — Perfect numbers structurally BST.

Perfect numbers: 6, 28, 496, 8128, 33550336, ...
Generated by Mersenne primes: P_n = 2^(p-1)·(2^p - 1) when 2^p-1 prime.

P_1 = 6 = C_2 ✓
P_2 = 28 = rank²·g ✓
P_3 = 496 = rank⁴·31 = rank⁴·M_5 ✓
P_4 = 8128 = rank⁶·127 = rank⁶·M_g ✓
P_5 = 33550336 = rank^12·8191 = ?

First 4 perfect numbers are BST integer products.
"""


def run():
    rank = 2; N_c = 3; n_C = 5; C_2 = 6; g = 7
    c_2 = 11; c_3 = 13

    perfects = [
        (6,        C_2,                "C_2"),
        (28,       rank**2 * g,        "rank²·g"),
        (496,      rank**4 * 31,       "rank⁴·M_{n_C}"),
        (8128,     rank**6 * 127,      "rank⁶·M_g"),
    ]

    print("Perfect numbers BST:")
    matches = 0
    for val, bst, formula in perfects:
        ok = val == bst
        marker = "✓" if ok else "×"
        if ok:
            matches += 1
        print(f"  {val:<8} = {formula:<25} = {bst:<8} {marker}")

    print(f"\nSCORE: {matches}/{len(perfects)}")
    return matches, len(perfects)


if __name__ == "__main__":
    run()
