"""TEST 6b — meiosis, CORRECTED. The quotient is the automorphism group of the PAIRING
structure, not the full symmetric group on homologs.  Lyra for Casey, 2026-09-05.
Bug found by positive control: at j=1 with p>=3, 0 of 41 states moved -- sorting undid the swap.
"""
import math, itertools
from collections import deque

def perms_of(gens, p):
    """Closure of the permutation group generated by `gens` (as tuples of images)."""
    idp = tuple(range(p)); G = {idp}; frontier = [idp]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = tuple(x[g[i]] for i in range(p))
            if y not in G: G.add(y); frontier.append(y)
    return sorted(G)

def canon(rows, G):
    return min(tuple(rows[g[i]] for i in range(len(rows))) for g in G)

def crossover(rows, j, a, b, G):
    r = list(rows); ra, rb = r[a], r[b]
    r[a] = ra[:j] + rb[j:]; r[b] = rb[:j] + ra[j:]
    return canon(tuple(r), G)

def states_of(p, L, ones, G):
    cols = [c for c in itertools.product([0, 1], repeat=p) if sum(c) == ones]
    out = set()
    for ch in itertools.product(cols, repeat=L):
        out.add(canon(tuple("".join(str(ch[j][i]) for j in range(L)) for i in range(p)), G))
    return sorted(out)

def classes(st, J, pairs, G):
    idx = {s: i for i, s in enumerate(st)}; comp = [-1]*len(st); nc = 0
    for s0 in range(len(st)):
        if comp[s0] != -1: continue
        dq = deque([s0]); comp[s0] = nc
        while dq:
            x = dq.popleft()
            for j in J:
                for (a, b) in pairs:
                    t = idx.get(crossover(st[x], j, a, b, G))
                    if t is not None and comp[t] == -1: comp[t] = nc; dq.append(t)
        nc += 1
    return [comp.count(k) for k in range(nc)]

R = lambda sz: -sum((s/sum(sz))*math.log2(s/sum(sz)) for s in sz if s)
Ht = lambda sz: sum((s/sum(sz))*math.log2(s) for s in sz if s)

def sweep(p, L, ones, pairs, gens, label):
    G = perms_of(gens, p); st = states_of(p, L, ones, G)
    print("\n%s\n  p=%d L=%d ones/locus=%d | pairing %s | |Aut|=%d | %d states"
          % (label, p, L, ones, pairs, len(G), len(st)))
    prev = None
    for m in range(0, L):
        J = list(range(1, m+1)); sz = classes(st, J, pairs, G)
        d = "" if prev is None else "  drop %+.4f" % (R(sz)-prev)
        # positive control: how many states does the FIRST crossover actually move?
        ctl = "" if m != 1 else "   [control: %d of %d states moved by j=1]" % (
            sum(1 for s in st if crossover(s,1,pairs[0][0],pairs[0][1],G) != s), len(st))
        print("  |J|=%d  classes=%5d  R=%8.4f  H_th=%8.4f%s%s" % (len(J), len(sz), R(sz), Ht(sz), d, ctl))
        prev = R(sz)

if __name__ == "__main__":
    S2 = [(1,0)]
    sweep(2, 7, 1, [(0,1)], S2, "DIPLOID, one bivalent (primate-like). Aut = swap within the pair.")
    sweep(3, 5, 1, [(0,1)], [(1,0,2)],
          "TRIPLOID, one bivalent + one UNIVALENT. No perfect matching on 3. Aut = swap the pair only.")
    sweep(3, 5, 1, [(0,1),(0,2),(1,2)], [(1,0,2),(1,2,0)],
          "TRIPLOID, TRIVALENT (any pair synapses). Aut = S_3.")
    sweep(4, 4, 2, [(0,1),(2,3)], [(1,0,2,3),(0,1,3,2),(2,3,0,1)],
          "TETRAPLOID, two disjoint bivalents (perfect matching EXISTS). Aut = wreath, order 8.")
    sweep(4, 4, 2, [(0,1),(0,2),(0,3),(1,2),(1,3),(2,3)], [(1,0,2,3),(1,2,3,0)],
          "TETRAPLOID, QUADRIVALENT (all pairs synapse). Aut = S_4.")
